### PR TITLE
Bump jackson and jackson_databind from 2.15.2 to 2.16.0

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Bumps `jackson` and `jackson_databind` from 2.15.2 to 2.16.0

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Two changes that might have an impact (potentially):

### Maximum Output nesting depth

Implementation of [jackson-core#1055](https://github.com/FasterXML/jackson-core/pull/1055) sets upper limit on maximum output nesting (Objects, Arrays) when generating output (writing JSON etc). Default limit is:

    1000 levels

### Maximum Property name length

Implementation of [jackson-core#1047](https://github.com/FasterXML/jackson-core/issues/1047) sets maximum length of allowed Property names when parsing input. Default limit is:

    50,000 units (bytes or chars, depending on input source)

**Comment by cwperks** [comment]
```
> Task :server:internalClusterTest

Tests with failures:
 - org.opensearch.operateAllIndices.DestructiveOperationsIT.testOpenIndexDefaultBehaviour
```

**Comment by cwperks** [comment]
I opened an issue to track the failing test: https://github.com/opensearch-project/OpenSearch/issues/11275

@reta Those new jackson values seem really large and accommodative of any realistic use-case.

**Comment by reta** [comment]
> @reta Those new jackson values seem really large and accommodative of any realistic use-case.

Correct, BUT we have own settings for that, ` index.mapping.depth.limit` and ` index.mapping.field_name_length.limit` (inherited from Elasticsearch [1]), which potentially may be set to exceed those defaults. 

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-settings-limit.html

**Comment by cwperks** [comment]
The defaults in OpenSearch are:

```
public static final Setting<Long> INDEX_MAPPING_DEPTH_LIMIT_SETTING = Setting.longSetting(
    "index.mapping.depth.limit",
    20L,
    1,
    Property.Dynamic,
    Property.IndexScope
);
public static final Setting<Long> INDEX_MAPPING_FIELD_NAME_LENGTH_LIMIT_SETTING = Setting.longSetting(
    "index.mapping.field_name_length.limit",
    Long.MAX_VALUE,
    1L,
    Property.Dynamic,
    Property.IndexScope
);
```

Should I see if we can leverage jackson to enforce these limits instead of relying on implementations within this codebase? I will file an issue to track overriding the jackson maximums in case these configured amounts are over the max.

**Comment by reta** [comment]
> Should I see if we can leverage jackson to enforce these limits instead of relying on implementations within this codebase?

We probably should just make sure those do not conflict

> I will file an issue to track overriding the jackson maximums in case these configured amounts are over the max.

:+1:

**Comment by cwperks** [comment]
@reta Capturing the discussion in an issue [here](https://github.com/opensearch-project/OpenSearch/issues/11278). The jackson maximums look sensible to me and are much larger than then OpenSearch limits. Should OpenSearch allow configuring those values to values that exceed the new jackson maximums?

**Comment by reta** [comment]
> Should OpenSearch allow configuring those values to values that exceed the new jackson maximums?

I will add context / details to the issue, thank you!

**Comment by cwperks** [comment]
@reta Can you add backport labels for 2.x and 1.x/1.3?

**Comment by reta** [comment]
@cwperks for 1.x it could be quite risky, it is still using 2.14.x

**Pull request merged**
