### PR TITLE
add support for s390x architecture

### PR DESCRIPTION
**Pull request by pantovad**
https://github.com/opensearch-project/OpenSearch/issues/4000

### Description
Helps making OpenSearch Server running on s390x
 
### Issues Resolved
Issue #4000
 
### Check List
- add support for s390x architecture in systemcallfilter

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### Linked Issues
Issue #4259
Issue #4358

### CODE REVIEW

**Review by nknize — COMMENTED** [review]
This is interesting. I'm not sure the side effect this has on our build and test requirements. By adding this here to the bootstrap will we need to add official build and test support for this discontinued architecture? Maybe? And then we remove it as soon as a change breaks the build?

/cc @bbarani @peterzhuamazon @peternied

**Comment by peternied** [comment]
Adding @opensearch-project/engineering-effectiveness can you look into @nknize comment above and provide thoughts?

**Comment by dbwiddis** [comment]
>  will we need to add official build and test support

FYI there is a GitHub Action that enables building/testing on  s390x or ppc64le (see #1303) and there's a request for risc-v 64 support (see #2341).  So hopefully the answer to this question is more general and can address those issues.

**Comment by prudhvigodithi** [comment]
Hey right now the build and test is being done on [jenkins agents](https://build.ci.opensearch.org/) configured as per architecture, for `s390x` following are the options which can be considered.

1. Need a direct instance added as jenkins agents with ESA/390 `s390x` architecture, so that the build default logic `uname -m` is `s390x`.
2. Use of package [multiarch/qemu-user-static ](https://github.com/multiarch/qemu-user-static) which supports multi-architecture containers, I have tested this on `x86_64` and after installing `qemu-user-static` and using `docker run --rm -it s390x/ubuntu bash` the architecture is now inferred as `s390x`

@dblock @peterzhuamazon @bbarani

**Comment by peterzhuamazon** [comment]
> Hey right now the build and test is being done on [jenkins agents](https://build.ci.opensearch.org/) configured as per architecture, for `s390x` following are the options which can be considered.
> 
>     1. Need a direct instance added as jenkins agents with ESA/390 `s390x` architecture, so that the build default logic `uname -m` is `s390x`.
> 
>     2. Use of package [multiarch/qemu-user-static ](https://github.com/multiarch/qemu-user-static) which supports multi-architecture containers, I have tested this on `x86_64` and after installing `qemu-user-static` and using `docker run --rm -it s390x/ubuntu bash` the architecture is now inferred as `s390x`.
> 
> 
> @dblock @peterzhuamazon @bbarani

It is better we go with 1 but not sure if EC2 support s390x, probably IBM cloud.

**Comment by dblock** [comment]
@pantovad Let's get this to 🍏 , haven't looked at the failures

**Comment by pantovad** [comment]
> @pantovad Let's get this to green_apple , haven't looked at the failures

Hi @dblock - the 'gradle_check' fails with different reasons apparently unrelated to the changes in this PR (different test failures or heap issue). Can you please have a look at the latest https://build.ci.opensearch.org/job/gradle-check/2234/

**Comment by dblock** [comment]
For flaky tests we usually look at the failure, see if there's an existing issue already open and link to it. Otherwise open a new one. I'll rerun.

**Comment by pantovad** [comment]
[https://github.com/opensearch-project/OpenSearch/issues/4259](url)

**Comment by pantovad** [comment]
> For flaky tests we usually look at the failure, see if there's an existing issue already open and link to it. Otherwise open a new one. I'll rerun.

@dblock finally the gradle check passed after merging the recent commits fixing flaky tests, PR seems ready now, please have a look.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Curious, where do you have an s390x, @pantovad ? And have you tested OpenSearch with these changes on it?

**Comment by pantovad** [comment]
Thx @dblock ! We have IBM LinuxOne (s390x) in our company and we run OpenSearch there (I put more details about it in my issue #4000). I am about to upgrade to v2.2.1.

**Pull request merged**
