### PR TITLE
Set httpcore5 to 5.2 to be compatible with httpclient5 5.2.1

### PR DESCRIPTION
**Pull request by cwperks**
### Description

`org.apache.httpcomponents.client5:httpclient5:5.2.1` is [compatible with httpcore5:5.2](https://github.com/apache/httpcomponents-client/blob/rel/v5.2.1/pom.xml#L65) and the recent upgrade to 5.2.2 is causing problems running an [extension using the SDK](https://github.com/opensearch-project/opensearch-sdk-java/issues/857). I am opening a PR to downgrade the version to 5.2 which is compatible with httpclient:5.2.1

### Issues Resolved

https://github.com/opensearch-project/opensearch-sdk-java/issues/857

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
@reta There were issues in the SDK related to the [httpcore5 update to 5.2.2](https://github.com/opensearch-project/OpenSearch/pull/8434) so I created a PR to set it to 5.2 which is compatible with httpclient:5.2.1.

I created another PR in opensearch-java too: https://github.com/opensearch-project/opensearch-java/pull/566

**Review by owaiskazi19 — APPROVED** [review]
LGTM! Unless @reta has anything for downgrading the version.

**Comment by dblock** [comment]
Isn't the fix to upgrade httpcore to 5.2.2?

**Comment by cwperks** [comment]
@dblock Looking at the source code for HttpClient5:5.2.1, it [references HttpCore5:5.2](https://github.com/apache/httpcomponents-client/blob/rel/v5.2.1/pom.xml#L65) **not** HttpCore5:5.2.2

This isn't the case with HttpClient5:4.5.14 which [references HttpCore5:4.4.16](https://github.com/apache/httpcomponents-client/blob/rel/v4.5.14/pom.xml#L77)

**Comment by reta** [comment]
> Isn't the fix to upgrade httpcore to 5.2.2?

We use 5.2.2 explicitly, the transient 5.2 dependency from HttpClient5 should not be used

**Comment by reta** [comment]
Fix is sent to https://github.com/opensearch-project/opensearch-sdk-java/pull/861

**Comment by cwperks** [comment]
Thank you @reta ! Closing this PR.

**Comment by reta** [comment]
For the record, `rest-high-level` dependencies:

```
> Task :client:rest-high-level:dependencyInsight
org.apache.httpcomponents.core5:httpcore5:5.2.2
  Variant runtime:
    | Attribute Name                 | Provided     | Requested    |
    |--------------------------------|--------------|--------------|
    | org.gradle.status              | release      |              |
    | org.gradle.category            | library      | library      |
    | org.gradle.libraryelements     | jar          | jar          |
    | org.gradle.usage               | java-runtime | java-runtime |
    | org.gradle.dependency.bundling |              | external     |
    | org.gradle.jvm.environment     |              | standard-jvm |
    | org.gradle.jvm.version         |              | 11           |

org.apache.httpcomponents.core5:httpcore5:5.2.2
\--- project :client:rest
     \--- runtimeClasspath

org.apache.httpcomponents.core5:httpcore5-h2:5.2.2
  Variant runtime:
    | Attribute Name                 | Provided     | Requested    |
    |--------------------------------|--------------|--------------|
    | org.gradle.status              | release      |              |
    | org.gradle.category            | library      | library      |
    | org.gradle.libraryelements     | jar          | jar          |
    | org.gradle.usage               | java-runtime | java-runtime |
    | org.gradle.dependency.bundling |              | external     |
    | org.gradle.jvm.environment     |              | standard-jvm |
    | org.gradle.jvm.version         |              | 11           |

org.apache.httpcomponents.core5:httpcore5-h2:5.2.2
\--- project :client:rest
     \--- runtimeClasspath

```

**Pull request closed without merging**
