### PR TITLE
[Backport] [2.x] Upgrade Lucene to 9.8.0

### PR DESCRIPTION
**Pull request by reta**
### Description
Upgrade Lucene to 9.8.0

### Related Issues
See please https://github.com/opensearch-project/OpenSearch/pull/10031, https://github.com/opensearch-project/OpenSearch/pull/8668, https://github.com/opensearch-project/OpenSearch/pull/10276

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] GitHub issue/PR created in [OpenSearch documentation repo](https://github.com/opensearch-project/documentation-website) for the required public documentation changes (#[Issue/PR number])

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock @msfroh @CEHENKLE @heemin32 @andrross @nknize @model-collapse opening up the pull request to bring 9.8.0 to 2.x (and possibly, 2.11 as there are some hesitations).

**Review by CEHENKLE — CHANGES_REQUESTED** [review]
Hey -- given that today to the last day to merge changes for 2.11, I think we should hold this because of the potential impact.

**Comment by reta** [comment]
> Hey -- given that today to the last day to merge changes for 2.11, I think we should hold this because of the potential impact.

Sure, we'll wait till 2.11 cut off, thanks @CEHENKLE !

**Comment by CEHENKLE** [comment]
> > Hey -- given that today to the last day to merge changes for 2.11, I think we should hold this because of the potential impact.
> 
> Sure, we'll wait till 2.11 cut off, thanks @CEHENKLE !

Thanks, @reta!

**Comment by reta** [comment]
> > > Hey -- given that today to the last day to merge changes for 2.11, I think we should hold this because of the potential impact.
> > 
> > 
> > Sure, we'll wait till 2.11 cut off, thanks @CEHENKLE !
> 
> Thanks, @reta!

@CEHENKLE the `2.11` is cut, `2.x` is on `2.12` now, we should be good to merge it, thank you!

**Review by dblock — APPROVED** [review]
Let's get this into 2.x.

**Review by CEHENKLE — APPROVED** [review]
woot woot :)

**Pull request merged**
