### PR TITLE
Removed suspicious call of getClass() on instance of Class, which erased type info

### PR DESCRIPTION
**Pull request by dk2k**
Added unit test.
Previous PR was prematurely closed https://github.com/opensearch-project/OpenSearch/pull/15367 without letting me react upon the comment.

### CODE REVIEW

**Comment by dblock** [comment]
`getName` looks much better, thanks for doing this and for fixing the comment typo.

**Review by sandeshkr419 — APPROVED** [review]
Thanks for adding test-case as well for these changes. LGTM!

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Odd failure

```
* What went wrong:
Execution failed for task ':libs:opensearch-core:licenseHeaders'.
> License header problems were found! Full details: /var/jenkins/workspace/gradle-check/search/libs/core/build/reports/licenseHeaders/rat.log
```

Rebase?

**Comment by dk2k** [comment]
I rebased

**Review by dbwiddis — APPROVED** [review]

**Comment by dbwiddis** [comment]
> Odd failure
> 
> ```
> * What went wrong:
> Execution failed for task ':libs:opensearch-core:licenseHeaders'.
> > License header problems were found! Full details: /var/jenkins/workspace/gradle-check/search/libs/core/build/reports/licenseHeaders/rat.log
> ```
> 
> Rebase?

Checked out the PR, rebased and still failing precommit.

Ran locally to generate that log.  The new test class had no license headers.

**Review by owaiskazi19 — APPROVED** [review]

**Pull request merged**
