### PR TITLE
added config file to git issue template directory to disable blank is…

### PR DESCRIPTION
**Pull request by joshpalis**
…creation
 
### Issues Resolved
remove "blank issue" from options #2070

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CEHENKLE** [comment]
Hey @joshpalis this is great to see.  Have you validated on your fork that it works as expected?

Thanks!

**Comment by saratvemulapalli** [comment]
Curious how you've tested this?

**Comment by joshpalis** [comment]
@CEHENKLE Yes, I have validated on my fork that it works correctly by enabling issues and confirming that the "Open a blank issue" link has been removed.

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
Thanks @joshpalis !

**Comment by saratvemulapalli** [comment]
start gradle check

**Review by CEHENKLE — APPROVED** [review]

**Pull request merged**
