### PR TITLE
[Backport 2.x] Add groupId value propagation tests for ZIP publication task

### PR DESCRIPTION
**Pull request by lukas-vlcek**
### Description

This is back-port of #4772 

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>
(cherry picked from commit eb3301554ec7e1a07866508ffc390b8651dc3394)

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
Please notice that this is back-port of #4772 but I do not refer that PR number in the CHANGELOG.md file, instead I refer this new PR (which is the back-port). Let me know if I need to change this.

**Comment by lukas-vlcek** [comment]
Also I think this PR will need proper labels.
Thanks you. 🙏

**Comment by dblock** [comment]
I believe this has been fixed in a backport of https://github.com/opensearch-project/OpenSearch/pull/4270, rebase?

**Comment by lukas-vlcek** [comment]
@dblock This is a manually created back-port of https://github.com/opensearch-project/OpenSearch/pull/4772 because the automatic back-port failed, see https://github.com/opensearch-project/OpenSearch/pull/4772#issuecomment-1283174487

**Review by reta — APPROVED** [review]

**Pull request merged**
