### PR TITLE
[OSCI][DEV]ingest feature flags from .env file

### LINKED ISSUE #594: [DEV] Allow developers to have a local/modify opensearch.yml or ENV
**Is your feature request related to a problem? Please describe.**

I was trying to figure out how to expose 0.0.0.0 from my EC2 test instance on which I do development. What worked was to run `./gradlew -Dtests.opensearch.http.host=0.0.0.0 run`. 

**Describe the solution you'd like**

I'd like to be able to do any (combination) of these:

a) modify `distribution/src/config/opensearch.yml` or another yml and have it get picked up by `./gradlew run`
b) use an equivalent of dotenv to permanently override settings, e.g. `OPENSEARCH_HTTP_HOST=0.0.0.0 ./gradlew run` which would allow one to create `.env` and run `dotenv ./gradlew run`
c) some other set it and forget it mechanism   

**Describe alternatives you've considered**

Run `./gradlew assemble` to build the ZIP for the distribution. Extract the zip and edit `config/opensearch.yml`. But this is more time consuming.

**Additional context**

### PR DESCRIPTION
**Pull request by kohinoor98**
### Description
Reads the .env file and then applies the necessary flags to the system instead of passing in flags in the commandline.

### Related Issues
Resolves #594 

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
I think you can see that this is no different than editing `opensearch.yml`, just a different file, so likely will cause more confusion. I think we want a way where all the settings can come from the environment, along with a new section in DEVELOPER_GUIDE for how to use that with [dotenv](https://github.com/cdimascio/dotenv-java).

**Comment by kohinoor98** [comment]
Hi @dblock 

Absolutely, will make changes accordingly.

All settings would include ingestion of the flags similar to opensearch.yml(distribution/src/config/opensearch.yml) which contains these under the sections - Cluster, Node, etc using dotenv?

@scrawfor99, I have made the change to the description! Excited to work on this.

Thanks,
KC

**Comment by dblock** [comment]
> All settings would include ingestion of the flags similar to opensearch.yml(distribution/src/config/opensearch.yml) under the sections - Cluster, Node, etc using dotenv?

I _think_ so. I imagine that this is completely dynamic and _any_ setting can be overridden this way.

**Comment by kohinoor98** [comment]
Hi @dblock 

1. Please could you help me understand how I could achieve:
You should iterate to green either way

2. For the command:
```bash
dotenv ./gradlew run
```
[dotenv-cli](https://www.npmjs.com/package/dotenv-cli) would need to be installed on the users system. 

This tool helps manage the environment variables by loading them from a `.env` file into the `ENV` of your script's process. However, in the context of the changes, whether or not `dotenv` is used explicitly to override flags doesn't make a difference. This is because, during the startup script execution, environment variables will be picked up directly, making the commands `dotenv ./gradlew run` and `./gradlew run` effectively identical in behavior. The system inherently reads `env` variables, ensuring no disparity in the execution process resulting from how they were initiated.

Therefore, while dotenv-cli aids in the initial loading of your custom environment variables, the actual running script initiated by `gradlew` remains unaffected by this intermediary.

Thanks,
KC

**Comment by dblock** [comment]
> [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) would need to be installed on the users system.

This is totally normal, typical use of dotenv.

**Review by peternied — COMMENTED** [review]
I am not sure what the value of having a .env file is vs opensearch.yml, but maybe I am not the developer targeted by this effort 🤷

I develop on my less-than-beefy windows laptop by using VSCode's remote plugin to an EC2 instance does the heavy lifting, maybe I am part of the audience but have been worked around these issues addressed with .env?

PS: I rarely use `./gradlew run` opting to use test cases to validate what I'm build most of the time.

**Comment by kohinoor98** [comment]
Hi @dblock 

Gradle Check is failing due to a known `flaky-test` addressed here #7396.

I think rest is good to go. Please let me know if anything else has to be done for this `PR`.

Thanks a lot,
KC

**Comment by dblock** [comment]
@kohinoor98 Please do rebase/force push an update to re-trigger tests until they pass. Appreciate any time you can spend fixing flaky tests while you wait on retries, too.

**Comment by scrawfor99** [comment]
I suggest we close this. @kohinoor98 you are more than welcome to open a new PR for this change in the future.

**Comment by kohinoor98** [comment]
> I suggest we close this. @kohinoor98 you are more than welcome to open a new PR for this change in the future.

I am facing some issues with hitting all green due to some configurations. I will create a new PR for the same.

**Pull request closed without merging**
