### PR TITLE
[Backport] [2.x] replace with getField (#7855)

### PR DESCRIPTION
**Pull request by mingshl**
* replace with getField

Signed-off-by: Shinsuke Sugaya <shinsuke@apache.org>

Signed-off-by: Shinsuke Sugaya <shinsuke@apache.org>
Signed-off-by: Shinsuke Sugaya <shinsuke.sugaya@gmail.com>
Signed-off-by: Mingshi Liu <mingshl@amazon.com>
Co-authored-by: Andriy Redko <drreta@gmail.com>
Co-authored-by: Mingshi Liu <mingshl@amazon.com>
(cherry picked from commit 828730f23377e78dd1df0fa53939ed7f2486800e)

### Description
[Backport] [2.x] replace with getField (#7855)

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/7835

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mingshl** [comment]
Gradle Check  failed not related to this code change. 

same gradle check error happed to the proceeding PRs to 2.x 
https://github.com/opensearch-project/OpenSearch/pull/8587
https://github.com/opensearch-project/OpenSearch/pull/8595
https://github.com/opensearch-project/OpenSearch/pull/8545

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Builds are failing because of https://github.com/opensearch-project/OpenSearch/pull/8591

**Comment by mingshl** [comment]
#8591 get merged, need some help rerunning the gradle check.

**Comment by macohen** [comment]
@dblock, @reta are you able to rerun the check now that #8591 is merged, please?

**Comment by reta** [comment]
> @dblock, @reta are you able to rerun the check now that #8591 is merged, please?

@macohen the pull request needs rebase first :( @mingshl could you please do that?

**Comment by mingshl** [comment]
Thanks @reta ! rebased and ready for merge.

**Pull request merged**
