### PR TITLE
[Backport-1.x] Kept the original constructor for PluginInfo to maintain bwc (#1206)

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha <vachshah@amazon.com>

### Description
Backport #1206 
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tlfeng** [comment]
start gradle check

**Comment by CEHENKLE** [comment]
start gradle check

**Comment by CEHENKLE** [comment]
Curses!  lost the race to your lightening fast fingers, @tlfeng ! ;) ;) ;)

**Comment by tlfeng** [comment]
@CEHENKLE Appreciate your compliment!

**Review by dblock — APPROVED** [review]

**Comment by VachaShah** [comment]
Thank you @dblock !

**Pull request merged**
