### PR TITLE
[Manual Backport 2.11] Add release notes for 2.11 (#10594)

### PR DESCRIPTION
**Pull request by noCharger**
Signed-off-by: Louis Chu <clingzhi@amazon.com>
(cherry picked from commit 382eb301b21bf5c6eda613432b9ddccda1c414b9)

### Description
[Describe what this change achieves]

- Manual backport https://github.com/opensearch-project/OpenSearch/pull/10594

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kotwanikunal — APPROVED** [review]

**Comment by noCharger** [comment]
https://github.com/opensearch-project/OpenSearch/pull/10594

**Comment by noCharger** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/27773/
> * **CommitID:** [333a9e5](https://github.com/opensearch-project/OpenSearch/commit/333a9e5ea0e760c48fb8dbd50d2086d750f172f1)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://build.ci.opensearch.org/job/gradle-check/27773/console

```
> Task :modules:lang-expression:internalClusterTest

Tests with failures:
 - org.opensearch.script.expression.MoreExpressionIT.testSpecialValueVariable {p0={"search.concurrent_segment_search.enabled":"true"}}
```
Flaky test, tracking https://github.com/opensearch-project/OpenSearch/issues/10079

**Comment by noCharger** [comment]
```

* What went wrong:
Execution failed for task ':modules:ingest-geoip:thirdPartyAudit'.
> Audit of third party dependencies failed:
    Jar Hell with the JDK:
    * #
    * # An error report file with more information is saved as:
934 actionable tasks: 933 executed, 1 from cache
    * # D:\a\OpenSearch\OpenSearch\modules\ingest-geoip\hs_err_pid4644.log
    * # Native memory allocation (mmap) failed to map 65536 bytes for Failed to commit area from 0x0000023efc170000 to 0x0000023efc180000 of length 65536.
    * # There is insufficient memory for the Java Runtime Environment to continue.
```
@heemin32  do you have context on this?

**Comment by kotwanikunal** [comment]
No code changes. Pushing this in for the release.

**Pull request merged**
