### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PranBopannaKK**
### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by PranBopannaKK** [comment]
Documentation!
[Open source(21bcaf43).docx](https://github.com/opensearch-project/OpenSearch/files/11058161/Open.source.21bcaf43.docx)

**Comment by PranBopannaKK** [comment]
Documentation Of OpenSearch Project
[Open source(21bcaf43).docx](https://github.com/opensearch-project/OpenSearch/files/11058164/Open.source.21bcaf43.docx)

**Comment by PranBopannaKK** [comment]
Documentation of OpenSearch Project
[Open source(21bcaf43).docx](https://github.com/opensearch-project/OpenSearch/files/11058190/Open.source.21bcaf43.docx)

**Comment by PranBopannaKK** [comment]
Documentation of OpenSearch Project
[Open source(21bcaf43).docx](https://github.com/opensearch-project/OpenSearch/files/11058196/Open.source.21bcaf43.docx)

**Comment by dblock** [comment]
@PranBopannaKK looking at the diff here it's a 1-liner with a title "Documentation". I'm too afraid to click on the .docx files linked to see what's in them :) 

I'm going to close this PR, but please tell us what you're trying to do and we/I can help?

**Pull request closed without merging**
