### PR TITLE
[Backport 2.x] [Segment Replication] Add check to cancel ongoing replication with old primary on onNewCheckpoint on replica

### PR DESCRIPTION
**Pull request by dreamer-89**
Manul backport of https://github.com/opensearch-project/OpenSearch/pull/4363 to 2.x

### CODE REVIEW

**Review by mch2 — APPROVED** [review]

**Comment by dreamer-89** [comment]
503 error during ping on github adoptium binary release
```
> Task :distribution:bwc:maintenance:buildBwcLinuxTar
 [1.3.5] > Task :distribution:archives:buildLinux FAILED
 [1.3.5] build complete, generating: /var/jenkins/workspace/gradle-check/search/distribution/bwc/maintenance/build/bwc/checkout-1.3/build/2589.tar.bz2
 [1.3.5] 
 [1.3.5] 148 actionable tasks: 148 executed
 [1.3.5] FAILURE: Build failed with an exception.
 [1.3.5] 
 [1.3.5] * What went wrong:
 [1.3.5] Execution failed for task ':distribution:archives:buildLinux'.
 [1.3.5] > Could not resolve all files for configuration ':distribution:archives:jdk_bundled_linux_x64'.
 [1.3.5]    > Could not resolve adoptium_11:linux:11.0.16.
 [1.3.5]      Required by:
 [1.3.5]          project :distribution:archives
 [1.3.5]       > Could not resolve adoptium_11:linux:11.0.16.
 [1.3.5]          > Could not get resource 'https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16+8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.16_8.tar.gz'.
 [1.3.5]             > Could not HEAD 'https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16+8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.16_8.tar.gz'. Received status code 503 from server: Backend fetch failed
 [1.3.5] 
 [1.3.5] * Try:
 [1.3.5] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 [1.3.5] 
 [1.3.5] * Get more help at https://help.gradle.org/
 [1.3.5] 
 [1.3.5] BUILD FAILED in 4m 18s
```

**Comment by dreamer-89** [comment]
This test was added as part of PR https://github.com/opensearch-project/OpenSearch/pull/4363. Looking into it. 
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication" -Dtests.seed=6B983CC6B30CF463 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb-NO -Dtests.timezone=Africa/Malabo -Druntime.java=17

org.opensearch.indices.replication.SegmentReplicationTargetServiceTests > testOnNewCheckpointFromNewPrimaryCancelOngoingReplication FAILED
    org.mockito.exceptions.misusing.UnfinishedStubbingException: 
    Unfinished stubbing detected here:
    -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:232)

    E.g. thenReturn() may be missing.
    Examples of correct stubbing:
        when(mock.isOk()).thenReturn(true);
        when(mock.isOk()).thenThrow(exception);
        doThrow(exception).when(mock).someVoidMethod();
    Hints:
     1. missing thenReturn()
     2. you are trying to stub a final method, which is not supported
     3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
        at __randomizedtesting.SeedInfo.seed([6B983CC6B30CF463:B2A5F5E8335F5752]:0)
        at app//org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:232)

```

**Comment by mch2** [comment]
> This test was added as part of PR #4363. Looking into it.
> 
> ```
> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication" -Dtests.seed=6B983CC6B30CF463 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb-NO -Dtests.timezone=Africa/Malabo -Druntime.java=17
> 
> org.opensearch.indices.replication.SegmentReplicationTargetServiceTests > testOnNewCheckpointFromNewPrimaryCancelOngoingReplication FAILED
>     org.mockito.exceptions.misusing.UnfinishedStubbingException: 
>     Unfinished stubbing detected here:
>     -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:232)
> 
>     E.g. thenReturn() may be missing.
>     Examples of correct stubbing:
>         when(mock.isOk()).thenReturn(true);
>         when(mock.isOk()).thenThrow(exception);
>         doThrow(exception).when(mock).someVoidMethod();
>     Hints:
>      1. missing thenReturn()
>      2. you are trying to stub a final method, which is not supported
>      3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
>         at __randomizedtesting.SeedInfo.seed([6B983CC6B30CF463:B2A5F5E8335F5752]:0)
>         at app//org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:232)
> ```

For another seed - https://github.com/opensearch-project/OpenSearch/pull/4366#issuecomment-1236486418

**Comment by dreamer-89** [comment]
> > This test was added as part of PR #4363. Looking into it.
> > ```
> > REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication" -Dtests.seed=6B983CC6B30CF463 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb-NO -Dtests.timezone=Africa/Malabo -Druntime.java=17
> > 
> > org.opensearch.indices.replication.SegmentReplicationTargetServiceTests > testOnNewCheckpointFromNewPrimaryCancelOngoingReplication FAILED
> >     org.mockito.exceptions.misusing.UnfinishedStubbingException: 
> >     Unfinished stubbing detected here:
> >     -> at org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:232)
> > 
> >     E.g. thenReturn() may be missing.
> >     Examples of correct stubbing:
> >         when(mock.isOk()).thenReturn(true);
> >         when(mock.isOk()).thenThrow(exception);
> >         doThrow(exception).when(mock).someVoidMethod();
> >     Hints:
> >      1. missing thenReturn()
> >      2. you are trying to stub a final method, which is not supported
> >      3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
> >         at __randomizedtesting.SeedInfo.seed([6B983CC6B30CF463:B2A5F5E8335F5752]:0)
> >         at app//org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testOnNewCheckpointFromNewPrimaryCancelOngoingReplication(SegmentReplicationTargetServiceTests.java:232)
> > ```
> 
> For another seed - [#4366 (comment)](https://github.com/opensearch-project/OpenSearch/pull/4366#issuecomment-1236486418)

Raised https://github.com/opensearch-project/OpenSearch/pull/4414

**Pull request merged**
