### PR TITLE
[Remove] Legacy 6x BWC Support

### PR DESCRIPTION
**Pull request by nknize**
This PR removes all support for legacy 6x bwc logic that is no longer supported in 2.0.

### CODE REVIEW

**Comment by dblock** [comment]
I'm going to ask the hard question: do we _have_ to? Wouldn't users prefer we tried to maintain bcw support over more major versions and how bad would that be in terms of effort?

**Comment by nknize** [comment]
> do we have to?

Unfortunately, for the deprecated features we inherited (e.g., zen1, deprecated types).. yes.  Unfortunately, because the versioning mechanism we inherited is tied to specific Lucene versions that will no longer be available in the next major lucene releases (e.g., IndexFormat changes, endianess, overall improvements)...yes. 

I know there have been public discussions about supporting bwc indefinitely, but we just don't have the mechanisms or designs in place (e.g., compatibility modules, legacy format support) to support such a capability and that will take some time. Furthermore, we're not actually removing anything that hasn't already been deprecated and/or disabled upstream (outside OpenSearch purview).  So we're safe to remove these pre-selected deprecated features in OpenSearch 2.0. This also gives us some runway to thoughtfully decide how to implement LTS for OpenSearch 1+ in OpenSearch 3+ versions.

**Comment by nknize** [comment]
start gradle check

**Comment by dblock** [comment]
@nknize Want to rebase and finish this?

**Comment by adnapibar** [comment]
@nknize does it make sense to do this in small chunks e.g. remove a specific 6.x version in one PR ?

**Comment by nknize** [comment]
closing in favor of individual commits related to #1674

**Pull request closed without merging**
