### PR TITLE
Upgrade to log4j 2.15.0

### PR DESCRIPTION
**Pull request by andrross**
This commit upgrades to log4j version 2.15.0.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
> The build is failing on task `:plugins:discovery-azure-classic:thirdPartyAudit` at the moment. Have not determined a fix yet.
> 
> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

@andrross you should be able to add `javax.jms.Message` to https://github.com/opensearch-project/OpenSearch/blob/main/plugins/discovery-azure-classic/build.gradle#L125 and it should fix it.

**Comment by andrross** [comment]
Test failure that succeeds on retry:

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.MinimumMasterNodesIT.testTwoNodesNoMasterBlock" -Dtests.seed=8C423154E3EBD680 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=el-GR -Dtests.timezone=Asia/Aden -Druntime.java=17
```

Will start another gradle check

**Comment by andrross** [comment]
start gradle check

**Review by dblock — APPROVED** [review]
LGTM assuming it can be green

**Review by saratvemulapalli — APPROVED** [review]

**Review by nknize — APPROVED** [review]
gce build.gradle thirdPartyAudit looks correct to me.  Interesting that was updated even on old 2.11 versions. If gradle check doesn't succeed it'll either be from a missing class or some unrelated PR.

**Comment by andrross** [comment]
Another test failure that succeeds on retry:

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.gateway.RecoveryFromGatewayIT.testReuseInFileBasedPeerRecovery" -Dtests.seed=D48F3A89DF7F2A1F -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-SG -Dtests.timezone=Africa/Asmera -Druntime.java=17
```

**Comment by andrross** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
@andrross could you rebase your PR. 
Bwc for 1.2.1 is now ported to `main`
https://github.com/opensearch-project/OpenSearch/pull/1701

**Comment by andrross** [comment]
Another test failure that succeeds on retry:

```
./gradlew ':qa:remote-clusters:integTest' --tests "org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks" -Dtests.seed=403F055E1F14E391 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-TN -Dtests.timezone=Africa/Conakry -Druntime.java=17
```

**Comment by dblock** [comment]
start gradle check

**Comment by nknize** [comment]
Not the first time HAProxy has failed. This is unrelated to the PR but I'm not sure it's a "flake". Wondering if this is a CI config issue.  /cc @peternied  @peterzhuamazon 

It's tiresome chasing these red herring failures.

```
2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([403F055E1F14E391:4749D095249295CC]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks(RemoteClustersIT.java:125)
  1> [2021-12-10T20:14:09,766][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] before test
  1> [2021-12-10T20:14:10,385][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] Configuring remote cluster [opensearch-2:9300]
  1> [2021-12-10T20:14:10,487][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] Connection info: org.opensearch.client.cluster.RemoteConnectionInfo@688b190
  1> [2021-12-10T20:14:10,693][INFO ][o.o.c.r.t.RemoteClustersIT] [testProxyModeConnectionWorks] after test
  1> [2021-12-10T20:14:10,737][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] before test
  1> [2021-12-10T20:14:11,294][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] Configuring remote cluster [opensearch-2:9300]
  1> [2021-12-10T20:14:11,363][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] Connection info: org.opensearch.client.cluster.RemoteConnectionInfo@5aef8603
  1> [2021-12-10T20:14:11,500][INFO ][o.o.c.r.t.RemoteClustersIT] [testSniffModeConnectionFails] after test
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/qa/remote-clusters/build/testrun/integTest/temp/org.opensearch.cluster.remote.test.RemoteClustersIT_403F055E1F14E391-001
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ar-TN, timezone=Africa/Conakry
  2> NOTE: Linux 5.4.0-1045-aws amd64/Eclipse Adoptium 17.0.1 (64-bit)/cpus=72,threads=1,free=451487832,total=536870912
  2> NOTE: All tests run in this JVM: [RemoteClustersIT]
```

**Comment by dblock** [comment]
> Not the first time HAProxy has failed. This is unrelated to the PR but I'm not sure it's a "flake". Wondering if this is a CI config issue. /cc @peternied @peterzhuamazon
> 
> It's tiresome chasing these red herring failures.

Do we have an issue on this yet?

**Comment by nknize** [comment]
> (will open and move to separate issue

**Comment by peternied** [comment]
> Not the first time HAProxy has failed. This is unrelated to the PR but I'm not sure it's a "flake". Wondering if this is a CI config issue. /cc @peternied @peterzhuamazon
> 
> It's tiresome chasing these red herring failures.

Just checked in, I don't see any blips in the system.  Looking forward to the day when everyone can see it on demand.

**Pull request merged**
