### PR TITLE
Adding a pre-commit task that runs git-secrets.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Adds a pre-commit task that runs `git-secrets`. 

**I don't think this is a good idea, but I want to put it up here for feedback. I think I'd prefer that the developer guide instructs developers to install git-secrets manually, and configure it globally, as good hygiene. I can PR that instead under separate cover.**

As this PR stands, 

Pros:

* Helps avoid accidentally committing secrets into the repo because developers run `./gradlew precommit`.

Cons:

* Requires installing of git-secrets from  https://github.com/awslabs/git-secrets. Would require updating CI bot.
* Requires adding this task into every single plugin if we want this to be adopted generally.
* Redundant with a global installation of git-secrets which can be done as follows (on a mac), just once:

  ```
  brew install git-secrets
  git secrets --register-aws --global
  git secrets --install ~/.git-templates/git-secrets
  git config --global init.templateDir ~/.git-templates/git-secrets
  ```

### Why not check in PRs?

Because GitHub [secret scanning is automatically enabled on public repositories](https://docs.github.com/en/code-security/secret-security/about-secret-scanning), so by the time a PR is created the compromized account owner has been notified and the account disabled.

### Why not a server-side pre-commit hook?

It's [available in GitHub Enterprise Server](https://docs.github.com/en/enterprise-server@2.21/admin/policies/about-pre-receive-hooks), but [isn't available on github.com](https://stackoverflow.com/a/36896396).

### Issues Resolved

N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
start dco check
start wrapper validation
start gradle precommit

**Comment by peterzhuamazon** [comment]
start gradle precommit

**Comment by dblock** [comment]
I propose we close this without moving forward/merging, @CEHENKLE?

**Comment by CEHENKLE** [comment]
Hey @dblock!  Here's where I am on this:

I hate relying on good intentions for something like this.  If we're talking personal preference in set up, then yeah, absolutely put a note in the guide and TMTOWTDI!  But keeping secrets out of the repo seems like something we should make a best effort to help people from making mistakes.  

But that being said, I hear what you're saying -- we haven't found a good way to do it.  How do other repos handle this situation?   If the answer comes back "they call it out in their developer guide, but that's it", well, then c'est la guerre. 

Thanks,
/C

**Comment by dblock** [comment]
I don't think other repos do much different. If you push a secret to Github it gets flagged immediately and account is rotated by the providers, such as AWS. Having done it once or twice I now setup git-secrets globally :) i'm going to close this.

**Pull request closed without merging**
