### PR TITLE
[Backport] Adding spotless support for subprojects under :test

### PR DESCRIPTION
**Pull request by saratvemulapalli**
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>

### Description
Backport PR #1464 to 1.x
 
### Issues Resolved
Part of #974 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by owaiskazi19** [comment]
Do we have an extra file on `1.x`?

**Comment by saratvemulapalli** [comment]
> Do we have an extra file on `1.x` @saratvemulapalli ?

Good question. Seems like it. I did separately run spotless on 1.x to avoid un-merged code conflicts of main and 1.x code. 
Let me see if I can find the culprit.

**Comment by saratvemulapalli** [comment]
Looks like it is 
`test/framework/src/main/java/org/opensearch/upgrades/AbstractFullClusterRestartTestCase.java`

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by owaiskazi19** [comment]
> Looks like it is `test/framework/src/main/java/org/opensearch/upgrades/AbstractFullClusterRestartTestCase.java`
> 
> This code is removed in `main` as it was upgraded to 2.0 but `1.x` will still live with this code till end of life. We should be good! Ref: [4b31e1b#diff-0cf7c88541665319eb6782204233e1dc7db953f1d7749f07e886076ab26373a8L55](https://github.com/opensearch-project/OpenSearch/commit/4b31e1ba04c44005de33fb5bb3f1564d34c6ee8a#diff-0cf7c88541665319eb6782204233e1dc7db953f1d7749f07e886076ab26373a8L55)

Thanks for digging more into it. Changes looks good to me.

**Review by owaiskazi19 — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Precommit failure [82dcf76](https://github.com/opensearch-project/OpenSearch/commit/82dcf766bd37882330fc3b1deed185a15878aa9e) [Log 1488](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Precommit/gradle_precommit_1488.log)

This bot is fun, it says there is a failure but no logs.  And locally it passes.
@peterzhuamazon any insights on this?

**Comment by saratvemulapalli** [comment]
start gradle check

**Review by setiah — APPROVED** [review]

**Pull request merged**
