### PR TITLE
Fixed copyright to OpenSearch

### LINKED ISSUE #1056: Correct copyright notices to reflect Copyright OpenSearch Contributors
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

### PR DESCRIPTION
**Pull request by minalsha**
Signed-off-by: Minal Shah <minalsha@amazon.com>

### Description
Fixed copyright to OpenSearch
 
### Issues Resolved
Closes #1056 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by dblock** [comment]
Check notice needs to be fixed:

```


* What went wrong:
Execution failed for task ':distribution:archives:integ-test-zip:checkNotice'.
> expected line [2] in [/var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/archives/integ-test-zip/build/zip-extracted/opensearch-1.1.0-SNAPSHOT/NOTICE.txt] to be [Copyright 2021 OpenSearch Contributors] but was [Copyright OpenSearch Contributors]

```

**Comment by minalsha** [comment]
@dblock if i update Notice.txt to "Copyright 2021 OpenSearch Contributors" than Readme.md and Notice.txt would not match since Readme.md has "Copyright OpenSearch Contributors. See [NOTICE](NOTICE.txt) for details." So should I change Readme.md as well to be as "Copyright 2021 OpenSearch Contributors. See [NOTICE](NOTICE.txt) for details."

**Comment by dblock** [comment]
The issue is that there's test code that expects `2021` all over the place. It needs to be modified as well.

**Comment by saratvemulapalli** [comment]
start gradle check

**Review by dblock — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Comment by dblock** [comment]
Thanks @minalsha! Please backport this to 1.x branch.

**Pull request merged**
