### PR TITLE
Update `github.actor` with `github.event.pull_request.user.login` for `dependabot[bot]` CI's

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Coming from https://github.com/orgs/community/discussions/25502 and the issue pointed by @cwperks that Pull Request Checks is being run on this PR: https://github.com/opensearch-project/OpenSearch/pull/13643 raised by `dependabot[bot]`.

But actually for the above PR looks to me like the trigger is coming from different bot https://github.com/opensearch-project/OpenSearch/actions/runs/9063816615 which is `opensearch-trigger-bot[bot]`.

Adding `github.event.pull_request.user.login` to get the author who opened this PR and exclude the check for `dependabot[bot]`.

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
Thank you @prudhvigodithi!

Its interesting, because I tested this on my fork and the GHA runs as dependabot (`github.actor = dependabot[bot]`). Example: https://github.com/cwperks/OpenSearch/actions/runs/9056524038?pr=163

In the main repo, the GHA is not run as dependabot for dependabot PRs. Its running as opensearch-trigger-bot instead. Example: https://github.com/opensearch-project/OpenSearch/actions/runs/9063816615?pr=13643

This change looks good to me! Approved. (Verbally approving because my approval counts towards merge, but I'm not a maintainer of this repo)

**Comment by prudhvigodithi** [comment]
Thanks @cwperks here is the quick test run that prints the PR author with `github.event.pull_request.user.login` and skips the run based on `github.event.pull_request.user.login`, please check
https://github.com/prudhvigodithi/opensearch-build/actions/runs/9100626642/job/25015897504?pr=104

**Comment by cwperks** [comment]
```
Run echo "This pull request was created by prudhvigodithi"
This pull request was created by prudhvigodithi
```

Thank you @prudhvigodithi. The output is what I expect, the github username of the submitter of the pull request. 

Can you also update this [instance](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/dependabot_pr.yml#L10) as well?

**Comment by cwperks** [comment]
Both of these actions are only run on PRs, so I expect `github.event.pull_request.user.login` will always be populated, but for actions that run on `push` would this value be empty?

**Comment by prudhvigodithi** [comment]
> but for actions that run on `push` would this value be empty?

From what I understood the `github.event.pull_request.user.login` just looks for PR author. Here is the sample run https://github.com/prudhvigodithi/opensearch-build/actions/runs/9100626642 that was triggered for a push in open PR https://github.com/prudhvigodithi/opensearch-build/pull/104, still the `github.event.pull_request.user.login` was identified as   author of the PR.
@bbarani @peterzhuamazon

**Comment by prudhvigodithi** [comment]
> Can you also update this [instance](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/dependabot_pr.yml#L10) as well?

Updated the `Dependabot PR actions` as well.

**Comment by prudhvigodithi** [comment]
> @prudhvigodithi Is this ready for review/merge or still in draft?
Ya its ready for review @deshsidd

**Comment by cwperks** [comment]
> Tests with failures:
 - org.opensearch.rest.action.admin.cluster.RestNodesStatsActionTests.testIndexMetricsRequestWithoutIndicesMetric

**Comment by prudhvigodithi** [comment]
The test `org.opensearch.rest.action.admin.cluster.RestNodesStatsActionTests.testIndexMetricsRequestWithoutIndicesMetric` Iis coming from class `RestNodesStatsActionTests`, check the [metrics dashboards](https://metrics.opensearch.org/_dashboards/app/dashboards?security_tenant=global#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2e729590-eb26-11ee-b008-6583d3dd450c',key:test_name,negate:!f,params:(query:org.opensearch.rest.action.admin.cluster.RestNodesStatsActionTests.testIndexMetricsRequestWithoutIndicesMetric),type:phrase),query:(match_phrase:(test_name:org.opensearch.rest.action.admin.cluster.RestNodesStatsActionTests.testIndexMetricsRequestWithoutIndicesMetric)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'Gradle%20check%20report',viewMode:view)) and I can see this as flaky.

**Comment by prudhvigodithi** [comment]
The failed error is 

```
BUILD FAILED in 26m 48s
3008 actionable tasks: 3000 executed, 2 from cache, 6 up-to-date
WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
- The deprecated "gradle.enterprise.testretry.enabled" system property has been replaced by "develocity.testretry.enabled"
- The "com.gradle.enterprise" plugin has been replaced by "com.gradle.develocity"
Gradle Check Failed!
```

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peternied** [comment]
@prudhvigodithi Please follow up on the past 2 failed checks as indicated by the checklist:
> Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))


- Note; that buildBwcLinuxTar requires a merge/rebase in order to resolve. https://github.com/opensearch-project/OpenSearch/issues/7396

**Comment by prudhvigodithi** [comment]
> @prudhvigodithi Please follow up on the past 2 failed checks as indicated by the checklist:

Thanks @peternied but while creating PR initially I did that, however I did it again and force pushed. I will and watch the gradle check.

**Review by peternied — APPROVED** [review]

**Pull request merged**
