### PR TITLE
Adds status badge for showing code coverage in README

### LINKED ISSUE #1323: Add status badge for showing code coverage in README
**Is your feature request related to a problem? Please describe.**
A part of issue: #850
Depends on issue: #1320
We need a quick insight for code coverage of the repository, as a result of code coverage reporting.

**Describe the solution you'd like**
Add a [Codecov status badge](https://about.codecov.io/product/feature/badges/) to reflect the percentage of code coverage of the repository in [README.md](https://github.com/opensearch-project/OpenSearch/blob/d46c206f29c760cbe911d1ee8b51ed501a84d14e/README.md).
It has been in the [plan](https://github.com/opensearch-project/opensearch-plugins/blob/511f8d2f104787515fb7a73337a2fb7acebc7531/TESTING.md#code-coverage-reporting) for OpenSearch/Dashboards plugins, and we can expend it to OpenSearch.

Steps for adding the badge into README.md: [the guide in opensearch-plugins repo](https://github.com/opensearch-project/opensearch-plugins/blob/511f8d2f104787515fb7a73337a2fb7acebc7531/TESTING.md#a-status-badge-in-readme-file-to-show-the-code-coverage)

**Describe alternatives you've considered**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by sampathbalivada**
Signed-off-by: Sai Sampath Kumar Balivada <balivadask2000@gmail.com>

### Description
Adds a Codecov status badge as a part of issue #850
Merge after #1320 is implemented.
 
### Issues Resolved
Fixes #1323
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sampathbalivada** [comment]
Pulled into the main branch unintentionally. Should have created a feature branch in the first place. Working to remove the latest merge commit from the source tree.

**Comment by dblock** [comment]
- You'll need to get DCO check sorted out, amend your commit with `-s`.
- I am not seeing any code coverage results in codecov, is someone working on getting those there? a badge is not useful until we publish code coverage results

**Comment by sampathbalivada** [comment]
- That should fix DCO. It was a name mismatch.
- Just worked on this issue as it was mentioned as a "good first issue". The code coverage issue seems to be #1320. I don't see any assignee there. I can work on it with some guidance but will need some time to study the existing information mentioned in the issue description. I will add a comment on that issue once done.

**Comment by nknize** [comment]
Interesting localhost `ConnectException`. Maybe a gradle task crashed? 

```
> Task :plugins:analysis-icu:test
...
...
..
org.gradle.internal.remote.internal.ConnectException: Could not connect to server [a535bd77-cc25-4c26-97b1-b50b3d75ebfa port:38833, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:123)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1141)
	at java.base/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1183)
	at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:98)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)
	... 5 more
```

Internets are trolling again... :trollface:  Re-firing gradle check

**Comment by nknize** [comment]
start gradle check

**Review by nknize — APPROVED** [review]
LGTM! Hopefully codecov.io has a healthy uptime and low outage rate.

**Review by dblock — CHANGES_REQUESTED** [review]
Will block this PR until we publish coverage results, thanks!

**Review by CEHENKLE — APPROVED** [review]

**Review by dreamer-89 — APPROVED** [review]
Thanks @sampathbalivada for this change.

**Review by dblock — APPROVED** [review]

**Pull request merged**
