### PR TITLE
Adding access to noSubMatches and noOverlappingMatches

### LINKED ISSUE #8796: Provide access to new settings for HyphenationCompoundWordTokenFilter
**Is your feature request related to a problem? Please describe.**
In Lucene two additional settings for HyphenationCompoundWordTokenFilter are added. They should be available in opensearch

**Describe the solution you'd like**
The new parameters should be supported.

**Describe alternatives you've considered**

**Additional context**
See https://github.com/apache/lucene/issues/9231 which adds the settings.

### PR DESCRIPTION
**Pull request by evankielley**
…CompoundWordTokenFilter

### Description
This change adds support for / exposes two new settings (noSubMatches and noOverlappingMatches) that were added to Lucene's HyphenationCompoundWordTokenFilter class.

### Related Issues
Resolves #8796 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by evankielley** [comment]
@msfroh I closed my previous pull request #9836 (albeit not intentionally). This PR has the same content, I just need to update the CHANGELOG as well.

**Comment by msfroh** [comment]
> @msfroh I closed my previous pull request #9836 (albeit not intentionally). This PR has the same content, I just need to update the CHANGELOG as well.

Thanks @evankielley!

Can you please also click the link in the PR checklist to create a documentation issue? It looks like we have a list of analyzers with links to the Lucene 8.7 JavaDocs: https://opensearch.org/docs/latest/analyzers/token-filters/index/. We should probably update those links to point to whatever version of Lucene was used for a given release.

**Comment by evankielley** [comment]
> > @msfroh I closed my previous pull request #9836 (albeit not intentionally). This PR has the same content, I just need to update the CHANGELOG as well.
> 
> Thanks @evankielley!
> 
> Can you please also click the link in the PR checklist to create a documentation issue? It looks like we have a list of analyzers with links to the Lucene 8.7 JavaDocs: https://opensearch.org/docs/latest/analyzers/token-filters/index/. We should probably update those links to point to whatever version of Lucene was used for a given release.

No problem! Issue created here: https://github.com/opensearch-project/documentation-website/issues/5389

**Comment by noCharger** [comment]
Let's add some test coverage for this change.

**Comment by evankielley** [comment]
> Let's add some test coverage for this change.

It looks like there's no existing unit tests for this class. Should I create a new file for unit tests in modules/analysis-common/src/test/java/org/opensearch/analysis/ or is there some reason why unit tests were skipped for this class in the first place?

**Comment by noCharger** [comment]
> > Let's add some test coverage for this change.
> 
> It looks like there's no existing unit tests for this class. Should I create a new file for unit tests in modules/analysis-common/src/test/java/org/opensearch/analysis/ or is there some reason why unit tests were skipped for this class in the first place?

One likely reason is that unit testing around the lucene library itself does not add much value, hence it is non-blocking for this PR.

Let's rebase to fix the gradle check failure https://build.ci.opensearch.org/job/gradle-check/28931/console
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qa:mixed-cluster:v2.12.0#mixedClusterTest'.
> There were failing tests. See the report at: file:///var/jenkins/workspace/gradle-check/search/qa/mixed-cluster/build/reports/tests/v2.12.0%23mixedClusterTest/index.html
```

**Comment by ticheng-aws** [comment]
Hi @evankielley, Is this being worked upon? Feel free to reach out to maintainers for further reviews.

**Comment by jed326** [comment]
Closing stalled PR due to inactivity for over 6 months. Please re-open a new PR if you would still like to submit this change. Thanks!

**Pull request closed without merging**
