### PR TITLE
[Backport 2.14] Fix negative requestStats memory_size issue (#13553)

### PR DESCRIPTION
**Pull request by sgup432**
### Description
Backports https://github.com/opensearch-project/OpenSearch/pull/13553

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sgup432** [comment]
Seems like all the changelog entries were removed recently. Maybe add a skip changelog tag in that case?

**Comment by msfroh** [comment]
> Seems like all the changelog entries were removed recently. Maybe add a skip changelog tag in that case?

The change log for a release branch is the release notes. You should add this to the 2.14 release notes instead. (Actually, it should be removed from the `Unreleased 2.x` sections in the 2.x and main branches, since it will be released in 2.14.)

**Comment by sgup432** [comment]
@msfroh Added in the release notes. I thought it was already picked, my bad.

**Review by andrross — APPROVED** [review]

**Review by sohami — APPROVED** [review]

**Comment by andrross** [comment]
@sgup432 Can you fix up the changelog and release notes on the 2.x and main branches for this change now?

**Pull request merged**
