### PR TITLE
Fix weighted routing stats version

### PR DESCRIPTION
**Pull request by anshu1106**
Signed-off-by: Anshu Agarwal <anshukag@amazon.com>

### Description
This PR fixes weighted routing stats version. Currently, the version is set to `CURRENT` but should be `2_6`

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@Bukhtawar how come we are merging pull request with failing checks? the `main` is broken now :(

**Comment by Bukhtawar** [comment]
The main was broken due to BWC(know reason) which is due to the sequence of backports and main branch commit which was addressed in backport PR

**Comment by reta** [comment]
> The main was broken due to BWC(know reason) which is due to the sequence of backports and main branch commit which was addressed in backport PR

I think we should never merge pull requests with failing check, the process would still require 2 pull requests (2.x goes first, `main` goes second) but smoother for other people (IMHO)

**Comment by dblock** [comment]
100%

**Pull request merged**
