### PR TITLE
Renaming "slave" terminology to replica.

### LINKED ISSUE #1556: Replace or remove the "slave" terminology used in a test data
**Is your feature request related to a problem? Please describe.**
Replace or remove the non-inclusive terminology from the code base.

**Describe the solution you'd like**
There is only 1 usage in the code base that can be replaced or removed, which is a test data:
https://github.com/opensearch-project/OpenSearch/blob/15e9f137622d878b79103df8f82d78d782b686a1/modules/mapper-extras/src/test/resources/org/opensearch/index/mapper/metricbeat-6.0.template.json#L4601

Document from Elatic that explains the fields in the template: https://www.elastic.co/guide/en/beats/metricbeat/7.10/exported-fields-redis.html

**Describe alternatives you've considered**
None.

**Additional context**
Related issue #472

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-off-by: Rishikesh Pasham <rishireddy1159@gmail.com>

### Description
Renaming slave to replica in filebeat-6.0.template.json file
 
### Issues Resolved
#1556 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by tlfeng — APPROVED** [review]
Thanks for making the change!

**Comment by dblock** [comment]
Isn't this an API change? What are the consequences for the users?

**Comment by andrross** [comment]
> Isn't this an API change? What are the consequences for the users?

The file changed here is used by a BWC test to validate that a Metricbeat template can be used to create an index. The exact name of the field in the template is unimportant to the test so this change should have no impact on the test. This is only a test artifact and there is no API change.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Let's backport to 1.x branch too, please.

**Pull request merged**
