### PR TITLE
[Refactor] CircuitBreaker foundation classes to core library

### PR DESCRIPTION
**Pull request by nknize**
This PR refactors the following `CircuitBreaker` foundation classes from the `server` module to the core library:

* o.o.common.breaker.CircuitBreaker
* o.o.common.breaker.CircuitBreakingException
* o.o.common.breaker.NoopCircuitBreaker
* o.o.indices.breaker.AllCircuitBreakerStats
* o.o.indices.breaker.CircuitBreakerService
* o.o.indices.breaker.CircuitBreakerStats
* o.o.indices.breaker.NoneCircuitBreakerService

The following base support classes are also refactored from the server to appropriate common or core libraries as a net positive side effect:

* o.o.common.component.AbstractLifecycleComponent
* o.o.common.component.Lifecycle
* o.o.common.component.LifecycleComponent
* o.o.common.component.LifecycleListener
* o.o.common.unit.ByteSizeUnit
* o.o.common.unit.ByteSizeValue

Tests and documentation are updated.

This refactor continues the unwinding of foundation classes from the server monolith to separable libraries in support of JPMS and serverless and cloud native implementations. 

relates #5910
relates #8110

### CODE REVIEW

**Comment by nknize** [comment]
Opened bug fix #9011

**Comment by nknize** [comment]
Blocked by 9011

**Comment by nknize** [comment]
Strange. The build passed.. But the GHA failed.. cool. refiring.

**Review by kotwanikunal — APPROVED** [review]

**Comment by Yury-Fridlyand** [comment]
More breaking changes for god of breaking changes! ©

**Comment by cwperks** [comment]
Will this PR be backported to 2.x?

**Comment by nknize** [comment]
Opening the backport now.

**Comment by peternied** [comment]
This PR changes the namespace on large number of classes.  Could we have move these classes to different parts of core into a new library without the namespace change, then at a later date roll out the list of `sed /this/that/` all at once?

**Comment by nknize** [comment]
The divergence with 2.x won't last long. This backport is next in the queue after #9050 merges

**Pull request merged**
