### PR TITLE
Make IndicesRequestCacheCleanupIT more robust

### PR DESCRIPTION
**Pull request by kiranprakash154**
### Description
This is a followup to https://github.com/opensearch-project/OpenSearch/pull/14369
and has 3 changes
- use setup_index in the test `testCacheWithInvalidation` to keep it consistent with other tests. 
- Increase refresh interval to rule out flakiness by keeping it way high - `TimeValue.timeValueDays(1)`
- Increase max wait time to 5 iteration cycles of cache cleanup cycles to consider for events like GC stop the world that is out of control and runs long. This would not increase the test run time since the backoff in assertBusy is logarithmic and should return after all the asserts passes. 

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kiranprakash154** [comment]
@andrross can you review this ?

**Review by andrross — APPROVED** [review]

**Comment by kiranprakash154** [comment]
@andrross I will create a manual backport, thanks for merging.

**Comment by andrross** [comment]
@kiranprakash154 The backport shouldn't fail unless we've missed a previous one. I don't think there's any reason this code should be different across the main and 2.x branches.

**Comment by kiranprakash154** [comment]
> @kiranprakash154 The backport shouldn't fail unless we've missed a previous one. I don't think there's any reason this code should be different across the main and 2.x branches.

It failed because the previous backport was not merged yet, Jay merged it yesterday - https://github.com/opensearch-project/OpenSearch/pull/14482

I retried and looks like the auto backport worked

**Pull request merged**
