### PR TITLE
Renamed to "flaky" test.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>

### Description
After a bit of googling, I believe the correct definition is "flaky". Will rename labels as well.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
Ha! I did the same googling and came to the conclusion that "flakey" was an accepted, albeit less common spelling. I wanted to comment on your last PR but decided I wouldn't be an annoying pedant. [The numbers don't lie though...](https://books.google.com/ngrams/graph?content=flakey%2C+flaky&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cflakey%3B%2Cc0%3B.t1%3B%2Cflaky%3B%2Cc0)

**Review by andrross — APPROVED** [review]

**Comment by dblock** [comment]
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT.testDecommissionStatusUpdatePublishedToAllNodes" -Dtests.seed=89E5053F9731D0F1 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pt -Dtests.timezone=America/Recife -Druntime.java=17

org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT > testDecommissionStatusUpdatePublishedToAllNodes FAILED
    java.lang.AssertionError: expected:<SUCCESSFUL> but was:<DRAINING>
        at __randomizedtesting.SeedInfo.seed([89E5053F9731D0F1:5708DEFD71320B65]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT.testDecommissionStatusUpdatePublishedToAllNodes(AwarenessAttributeDecommissionIT.java:144)
```

https://github.com/opensearch-project/OpenSearch/issues/4824

**Review by dreamer-89 — APPROVED** [review]
Thanks @dblock for the change. 

How are you planning to change existing `flakey` label. I did not find option of renaming existing labels.
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by dblock** [comment]
@dreamer-89 you can edit labels

Screen Shot 2022-10-26 at 8 23 51 AM

**Pull request merged**
