### PR TITLE
Update links to documentation in rest-api-spec

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Removes references to elastic documentation in rest-api-spec where documentation exists. I ran into issues updating all links because there are many undocumented APIs. Some of the undocumented APIs are not useful and there are comments in the specs mentioning that they are deprecated.

Missing Documentation:

- Delete Component Template
- Cluster Delete Voting Config Exclusions
- Exists Component Template
- Cluster Pending Tasks
- Cluster Post Voting Config Exclusions
- Cluster Reroute
- Cluster State
- Field Capabilities
- Index Add Block
- Index Flush
- Index Get Mapping
- Index Get Field Mapping
- Index Recovery
- Index Refresh
- Resolve Index API
- Index Rollover
- Index Segments
- Index Shard Stores
- Simulate Index Template
- Index Validate Query
- Ingest Processor Grok
- Multi-Get (MGET)
- M Term Vector
- Ping
- Search Shards
- Cleanup Snapshot Repository
- Snapshot Clone
- Term Vectors

Documentation exists, but not for specific API:

- Clear Scroll
- Delete Alias

Documentation for PITs exists at https://opensearch.org/docs/latest/search-plugins/searching-data/point-in-time-api/, but could be organized in the broader API docs

Index Template APIs are under a route including im-plugin: https://opensearch.org/docs/latest/im-plugin/index-templates. Are these native APIs or are they provided by the ISM plugin?

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/1339

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Thanks a lot @cwperks !

**Comment by reta** [comment]
@cwperks may I ask you please to backport this great change to `1.x` and `1.3` ? thank you

**Comment by cwperks** [comment]
@reta Sure, no problem!

FYI @hdhalter, see the PR description of this PR. I went through the rest-api-spec tests yesterday and found gaps in documentation. I will check the documentation-website issue list to see if some of these are existing issues or file a new issue if one doesn't exist.

**Comment by cwperks** [comment]
@reta Here's the backport to 1.x: https://github.com/opensearch-project/OpenSearch/pull/13059

**Pull request merged**
