### PR TITLE
Fixing the --release flag usage for javac

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Manifested in https://github.com/opensearch-project/job-scheduler/pull/130
 
### Issues Resolved
Part of https://github.com/opensearch-project/job-scheduler/pull/130
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock please take a look, should fix the `--release` flag issue

**Comment by dblock** [comment]
ZOMG is that it?! ❤️

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
> ZOMG is that it?! heart

```
/job-scheduler$ ./gradlew compileJava
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 6.6.1
  OS Info               : Linux 5.13.0-30-generic (amd64)
  JDK Version           : 1.8 (JDK)
  JAVA_HOME             : /usr/lib/jvm/java-8-openjdk-amd64
  Random Testing Seed   : 36D3E1D6F07DB747
  In FIPS 140 mode      : false
=======================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.                         
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
5 actionable tasks: 5 executed

```

**Comment by dblock** [comment]
Will you please also PR this into `main`? No reason why it should be broken for Java 8 and I wanted to have a working main on that for the long run.

**Comment by reta** [comment]
> Will you please also PR this into `main`? No reason why it should be broken for Java 8 and I wanted to have a working main on JDK8 for the long run before we drop support for it in 2.0.

Absolutely, sorry but discovered failure further in the build with `javadoc` and `html5` flag iusage, pushed the fix. I will bring all changes back to `main`, unblocking you first on `1.x`

**Comment by reta** [comment]
> x   Gradle Check failure [7ded6b1](https://github.com/opensearch-project/OpenSearch/commit/7ded6b1749af8c4c994bfa23d7a7927918ad06f0) [Log 3038](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3038.log)
> 
> [Reports 3038](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_3038_reports.zip)

Looks like new one:

```
Tests with failures:
 - org.opensearch.snapshots.ConcurrentSnapshotsIT.testQueuedOperationsOnMasterRestart
```

Opened https://github.com/opensearch-project/OpenSearch/issues/2347

**Comment by dblock** [comment]
start gradle check

**Pull request merged**
