### PR TITLE
SSL Module Design Document outline draft

### LINKED ISSUE #1418: Tracking Design for Inbuilt Security SSL module
**Is your feature request related to a problem? Please describe.**
This issue is to track the design for Inbuilt Security SSL module that adds encryption support to OpenSearch

**Describe the solution you'd like**
A design document that covers all aspects of SSL Module

**Additional context**
Related to #1029

### PR DESCRIPTION
**Pull request by setiah**
Signed-off-by: Himanshu Setia <setiah@amazon.com>

### Description
This document talks about the SSL module to provide encryption support at REST and transport layers in OpenSearch ensuring all communication is encrypted. 

**PS: this document is still work in progress and does not represent the final design yet.**  
 
### Issues Resolved
#1418 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cliu123 — APPROVED** [review]

**Comment by dblock** [comment]
@setiah What shall we do with this?

**Comment by dreamer-89** [comment]
@setiah : Are you still working on this ?

**Comment by CEHENKLE** [comment]
Joining the folks poking @setiah :)   Poke Poke Poke!

**Comment by kartg** [comment]
Looks like this draft has stalled for about 4 months. @setiah are you still working on this or should we close this?

**Pull request closed without merging**
