### PR TITLE
[Upgrade] Lucene-9.2-snapshot

### PR DESCRIPTION
**Pull request by nknize**
Upgrades to latest snapshot of pre-released lucene 9.2

### CODE REVIEW

**Comment by nknize** [comment]
Fixing failures caused by [9.2 scoring optimization change](https://issues.apache.org/jira/browse/LUCENE-10418)

**Comment by nknize** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
@nknize trying to understand how this works. How do we choose versions of lucene to run with OpenSearch?

- For bleeding edge `main` (3.0) it is always going to be the latest snapshot?
- For current release (2.x line), do we consume a stable release version?

**Comment by nknize** [comment]
We use snapshots until the next release is available. This enables us to stay on top of deprecations and removals without having to wait until the release and make a lot of changes.

**Comment by nknize** [comment]
I'd like to get this merged in main and 2.x so I can start working towards bumping main to Lucene 10 snapshot

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@saratvemulapalli LMK if you have any concerns with merging this to main

**Review by saratvemulapalli — APPROVED** [review]

**Comment by dblock** [comment]
Seems like this may have caused https://github.com/opensearch-project/OpenSearch/pull/3039#issuecomment-1106123595.

**Pull request merged**
