### PR TITLE
Add a whitesource unified agent file and update the config

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
The WhiteSource config was set to default and doesn't seem to work properly for OpenSearch repo. We change the mode to `LOCAL` and provide the `unified agent` config file we used before. 
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by bbarani — APPROVED** [review]

**Comment by VachaShah** [comment]
start gradle check

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [a22680c](https://github.com/opensearch-project/OpenSearch/commit/a22680c1632e719ab9318fe977404832b7c844ea) [Log 1056](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1056.log)
> 
> [Reports 1056](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1056_reports.zip)

```
* What went wrong:
Execution failed for task ':qa:translog-policy:v1.3.0#Step2OldClusterTest'.
> `node{:qa:translog-policy:v1.3.0-0}` failed to wait for ports files after 120000 MILLISECONDS
```

**Review by dblock — APPROVED** [review]
I would not include all this commented out settings in whitesource.config and only include things that are required/set. But NBD.

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [a22680c](https://github.com/opensearch-project/OpenSearch/commit/a22680c1632e719ab9318fe977404832b7c844ea) [Log 1063](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1063.log)
> 
> [Reports 1063](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1063_reports.zip)

```
org.opensearch.cluster.MinimumMasterNodesIT > testTwoNodesNoMasterBlock FAILED
    java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([3971F3035D6294C4:F524D805F8CA81A9]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:1019)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:958)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:947)
        at org.opensearch.cluster.MinimumMasterNodesIT.testTwoNodesNoMasterBlock(MinimumMasterNodesIT.java:223)
```

**Comment by VachaShah** [comment]
start gradle check

**Comment by zelinh** [comment]
> ❌   Gradle Check failure [a22680c](https://github.com/opensearch-project/OpenSearch/commit/a22680c1632e719ab9318fe977404832b7c844ea) [Log 1088](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1088.log)
> 
> [Reports 1088](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1088_reports.zip)

Could you help me handle this check? @VachaShah 

```
* What went wrong:
Execution failed for task ':server:internalClusterTest'.
> There were failing tests. See the report at: file:///var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/server/build/reports/tests/internalClusterTest/index.html

**Comment by zelinh** [comment]
start gradle check

**Pull request merged**
