### PR TITLE
add remark field to NodeData and TaskInfo

### PR DESCRIPTION
**Pull request by XiaochenNan**
### Description
add remark field to NodeData and TaskInfo

### Issues Resolved
[#6552]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by saratvemulapalli — COMMENTED** [review]
Thanks @XiaochenNan for contributing a change. 

Trying to understand, what do intend to use this field for which `attributes` is unable to serve? 
Also it would be great if you could add tests.

**Comment by XiaochenNan** [comment]
> 

just want to get the remark info in first level of data, then user can get it without analyze the key in attributes

**Comment by saratvemulapalli** [comment]
> > 
> 
> @saratvemulapalli just want to get the remark info in first level of data, then user can get it without analyze the key in attributes

Thanks @XiaochenNan. I am not really seeing value of adding a new field but I would like to hear from other maintainers @anasalkouz @reta @andrross @dblock @nknize

**Comment by andrross** [comment]
@XiaochenNan Can you explain the problem this solution is trying to solve? "user may need set more additional infomation in NodeData and TaskInfo data" from the linked issue isn't nearly detailed enough. What is the problem that leads to a user needing addition information in NodeData and TaskInfo? Once the problem is clear we can start evaluating solutions.

**Comment by kotwanikunal** [comment]
Apologies. This PR was auto closed without reaching a resolution from the maintainers.
Re-opening to move it forward.
Thanks for your contributions to OpenSearch!

**Comment by ashking94** [comment]
@XiaochenNan - Is this being worked upon? Please reach out to the maintainers and other active members to reach conclusion or reviews.

**Comment by ticheng-aws** [comment]
Hi @XiaochenNan, do we have any updates on this PR?

**Comment by andrross** [comment]
I'm closing this due to no response to the questions above. @XiaochenNan feel free to respond to the feedback and reopen if appropriate. Thanks!

**Pull request closed without merging**
