### PR TITLE
power changes for building with and without jdk

### PR DESCRIPTION
**Pull request by SonalMahambrey1**
Signed-off-by: Sonal Mahambrey [Sonal Mahambrey1 <Sonal.Mahambrey1@ibm.com>)
### Description
Added changes to build snapshot for power with and without JDK

### Issues Resolved
./gradlew :distribution:archives:linux-ppc64le-tar:assemble
The command used to create the snapshot without JDK and there was no support for creating snapshot with JDK

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@SonalMahambrey1 could you please fix DCO check and update CHANGELOG? Please check https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin

**Comment by andrross** [comment]
> ...and update CHANGELOG?

@reta I'm fine with skipping the CHANGELOG entry for a build-related change like this. What do you think?

**Comment by SonalMahambrey1** [comment]
Added DCO

**Comment by dblock** [comment]
> Added DCO

Looks like it's incorrect. Make sure you have a valid e-mail in your git config:

```
$ git config --global user.name "John Doe" 
$ git config --global user.email johndoe@example.com
```

Then `git commit --amend -s`, then `git push origin sonal-powerchanges -f`.

**Comment by SonalMahambrey1** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/10019/
> * **CommitID:** [df25f63](https://github.com/opensearch-project/OpenSearch/commit/df25f6380bf5611c91916d54a20bb21488ccec5c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?


Tests with failures:
 - org.opensearch.grok.GrokTests.testExponentialExpressions
 - org.opensearch.grok.GrokTests.classMethod
Looks like both are failed due to timeout

org.opensearch.grok.GrokTests > testExponentialExpressions FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([64E6DC875A56E2FC]:0)

org.opensearch.grok.GrokTests > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
        at __randomizedtesting.SeedInfo.seed([64E6DC875A56E2FC]:0)

**Comment by SonalMahambrey1** [comment]
@dblock , @dbwiddis , kindly provide your comments and suggestions

**Comment by reta** [comment]
> @dblock , @dbwiddis , kindly provide your comments and suggestions

LGTM, thanks @SonalMahambrey1 !

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@SonalMahambrey1 could you please rebase?

**Comment by SonalMahambrey1** [comment]
Done

**Comment by reta** [comment]
@SonalMahambrey1 would you take care of backports please?

**Comment by reta** [comment]
@andrross very likely :( I will take care of that, thanks a lot @andrross !

**Pull request merged**
