### PR TITLE
[Remove] Type query

### PR DESCRIPTION
**Pull request by dreamer-89**
Signed-off-by: Suraj Singh <surajrider@gmail.com>

### Description
Remove type query support
 
Related to #1940 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.2.5#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does}" -Dtests.seed=EAFBA6432BCFF6A6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-PE -Dtests.timezone=Pacific/Samoa -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does} FAILED
    java.lang.AssertionError: Failure at [indices.get_field_mapping/20_missing_field:13]: expected [2xx] status code but api [indices.get_field_mapping] returned [404 Not Found] [{}]
        at __randomizedtesting.SeedInfo.seed([EAFBA6432BCFF6A6:62AF999985339B5E]:0)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:442)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.test(OpenSearchClientYamlSuiteTestCase.java:415)

```

**Comment by dreamer-89** [comment]
start gradle check

**Comment by tlfeng** [comment]
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.gateway.RecoveryFromGatewayIT.testReuseInFileBasedPeerRecovery" -Dtests.seed=34FAB6E7849EED38 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CR -Dtests.timezone=America/Costa_Rica -Druntime.java=17

org.opensearch.gateway.RecoveryFromGatewayIT > testReuseInFileBasedPeerRecovery FAILED
    java.lang.AssertionError: shard [test][0] on node [node_t1] has pending operations:
     --> RetentionLeaseBackgroundSyncAction.Request{retentionLeases=RetentionLeases{primaryTerm=1, version=1564, leases={peer_recovery/tf3kx95JRHC7BpxrI_g5Kg=RetentionLease{id='peer_recovery/tf3kx95JRHC7BpxrI_g5Kg', retainingSequenceNumber=1626, timestamp=1647145782774, source='peer recovery'}, peer_recovery/ptxLJ_yKT322o8tdVaf5ng=RetentionLease{id='peer_recovery/ptxLJ_yKT322o8tdVaf5ng', retainingSequenceNumber=1626, timestamp=1647145782774, source='peer recovery'}}}, shardId=[test][0], timeout=1m, index='test', waitForActiveShards=0}
    	at org.opensearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:248)
    	at org.opensearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:3130)
    	at org.opensearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:1116)
    	at org.opensearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:433)
    	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
    	at org.opensearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:377)
...
```
Reported in issue https://github.com/opensearch-project/OpenSearch/issues/1746

**Review by reta — APPROVED** [review]

**Review by CEHENKLE — APPROVED** [review]

**Comment by dreamer-89** [comment]
Another repeated failure of https://github.com/opensearch-project/OpenSearch/issues/2440; need to deep dive to fix it. 
```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.2.5#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does}" -Dtests.seed=A371D302979732E0 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr -Dtests.timezone=US/East-Indiana -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does} FAILED
    java.lang.AssertionError: Failure at [indices.get_field_mapping/20_missing_field:20]: field [test_index.mappings] is null
        at __randomizedtesting.SeedInfo.seed([A371D302979732E0:2B25ECD8396B5F18]:0)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:442)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.test(OpenSearchClientYamlSuiteTestCase.java:415)
        at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by dreamer-89** [comment]
start gradle check

**Comment by tlfeng** [comment]
In log 3375:
```
> Task :test:fixtures:gcs-fixture:composeDown FAILED
Stopping 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-other_1                 ... done
Stopping 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-repositories-metering_1 ... done
Stopping 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-third-party_1           ... done
Stopping 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture_1                       ... done
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-repositories-metering_1 ... 
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture_1                       ... 
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-third-party_1           ... 
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-other_1                 ... 
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-third-party_1           ... done
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture_1                       ... done
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-other_1                 ... done
Removing 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__gcs-fixture-repositories-metering_1 ... done
Removing network 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__default
error while removing network: network 1746e03edff13bc4cdc044d95fc27292_gcs-fixture__default id a25e2bbd9c53ab46b1a84635c2425dcb4e2fbdab7738eb7c08253b288bf49d0c has active endpoints

* What went wrong:
Execution failed for task ':test:fixtures:gcs-fixture:composeDown'.
> Exit-code 1 when calling /usr/bin/docker-compose, stdout: N/A
```

**Comment by tlfeng** [comment]
In log 3378:
```
> Task :qa:mixed-cluster:v1.3.0#mixedClusterTest

REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.3.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does}" -Dtests.seed=45B7C88FC5724FFB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-UY -Dtests.timezone=Europe/Kaliningrad -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=indices.get_field_mapping/20_missing_field/Return empty object if field doesn't exist, but index does} FAILED
    java.lang.AssertionError: Failure at [indices.get_field_mapping/20_missing_field:20]: field [test_index.mappings] is null
        at __randomizedtesting.SeedInfo.seed([45B7C88FC5724FFB:CDE3F7556B8E2203]:0)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:442)
org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.test(OpenSearchClientYamlSuiteTestCase.java:415)
...
```
Failure of issue #2440. re-trigger the gradle task: start gradle check

**Pull request merged**
