### PR TITLE
[Manual] Revert Add bwcVersion 2.5.0 (#5003)

### PR DESCRIPTION
**Pull request by peternied**
### Description
In the middle of getting ready for the 2.4.0 release our backward compatibility tests for security started failing, which looks to be related to this change.

- https://github.com/opensearch-project/OpenSearch/pull/5003

Reverting this commit to unblock pull request checks in to main.

How we can stage changes like this before the 2.5.0 build is ready, or do we need to careful make these changes when main branches won't be impacted?

Signed-off-by: Peter Nied <petern@amazon.com>

### Issues Resolved
- Related https://github.com/opensearch-project/OpenSearch/issues/5076
- Resolves https://github.com/opensearch-project/security/issues/2221

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
@kotwanikunal @VachaShah would you be able to take a look?

**Comment by andrross** [comment]
My understanding is that this version has to match the version that is built by the OpenSearch/2.x branch, or else the backward compatibility tests in OpenSearch will fail. @VachaShah Can you weigh in here?

**Comment by kotwanikunal** [comment]
> My understanding is that this version has to match the version that is built by the OpenSearch/2.x branch, or else the backward compatibility tests in OpenSearch will fail. @VachaShah Can you weigh in here?

+1 on this. It has to stay consistent AFAIK.

**Comment by dblock** [comment]
This doesn't feel right. @peternied says that security repo is running 2.4.0 -> 3.0.0 BWC tests, when 3.0.0 was updated to 2.5.0 security repro broke with: `java.lang.IllegalStateException: Received message from unsupported version: [2.4.0] minimal compatible version is: [2.5.0]`. I think this is expected, the idea is that only latest 2.x will be upgradable to 3.0 when that ships, and this is what we're seeing now since 2.5 is a new thing that will exist. 

@nknize Is this something we still want? Should we relax it? How do we deal with this in plugins?

**Comment by peternied** [comment]
Happy to abandon this change if there are other fixes to unblock the security.

**Comment by peternied** [comment]
```
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 2.4.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-tar/build/distributions/opensearch-min-2.4.0-SNAPSHOT-linux-x64.tar.gz
```

Looks like other dependent changes are already in, I'm guessing a revert is no longer possible without involving many branches.

**Comment by peternied** [comment]
I'm closing out this pull request since it will not be merged, it looks like the root cause has been found and is being worked on.  Moving forward seems like like the correct path.

- https://github.com/opensearch-project/opensearch-build/issues/2854

**Comment by peternied** [comment]
FYI I've captured @dblock question into a new OpenSearch issue for further consideration

- https://github.com/opensearch-project/OpenSearch/issues/5091

**Pull request closed without merging**
