### PR TITLE
Revert "[Backport][Remote Store] Permit backed futures to prevent timeouts during uploa…"

### PR DESCRIPTION
**Pull request by reta**
Reverts opensearch-project/OpenSearch#13645

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
> Please lets take a minute to see what caused a failure. I am still checking but one the face of it looks like an issue with the workflow

@Bukhtawar it is failing breaking changes check, you could clearly see it

**Comment by Bukhtawar** [comment]
> > Please lets take a minute to see what caused a failure. I am still checking but one the face of it looks like an issue with the workflow
> 
> @Bukhtawar it is failing breaking changes check, you could clearly see it: https://github.com/opensearch-project/OpenSearch/actions/runs/9074757318/job/24934080382. All other pull requests are failing because of that

Thanke @reta I am not fully sure its a problem with the BWC workflow or the its a breaking change. Verifying the same

**Review by Bukhtawar — APPROVED** [review]
LGTM

**Review by mch2 — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Comment by dblock** [comment]
> ❌ Gradle check result for [5aeee1c](https://github.com/opensearch-project/OpenSearch/commit/5aeee1c77c0a310b8dab5c6c0091d81f1b81867e): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38683/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.remotemigration.RemoteReplicaRecoveryIT.testReplicaRecovery](https://build.ci.opensearch.org/job/gradle-check/38683/testReport/junit/org.opensearch.remotemigration/RemoteReplicaRecoveryIT/testReplicaRecovery/)

https://github.com/opensearch-project/OpenSearch/issues/13473

**Review by owaiskazi19 — APPROVED** [review]

**Pull request merged**
