### PR TITLE
Bump mockito & bytebuddy dependencies

### PR DESCRIPTION
**Pull request by reta**
### Description
Bump mockito & bytebuddy dependencies (skipping changelog since those are test dependencies)

### Related Issues
N/A

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Review by kkmr — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [85d9373](https://github.com/opensearch-project/OpenSearch/commit/85d9373edcb0f7fa2d6e22cc0b133731a1e6b4b0): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35154/)

https://github.com/opensearch-project/OpenSearch/issues/5426

**Review by DarshitChanpura — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [85d9373](https://github.com/opensearch-project/OpenSearch/commit/85d9373edcb0f7fa2d6e22cc0b133731a1e6b4b0): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35185/)

https://github.com/opensearch-project/OpenSearch/issues/12338
https://github.com/opensearch-project/OpenSearch/issues/12717

**Comment by reta** [comment]
> ❌ Gradle check result for [961b63b](https://github.com/opensearch-project/OpenSearch/commit/961b63b431fbc5cac22d6c137e313f85e4413be3): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35194/)

https://github.com/opensearch-project/OpenSearch/issues/12338
https://github.com/opensearch-project/OpenSearch/issues/12717

**Comment by reta** [comment]
https://github.com/opensearch-project/OpenSearch/issues/12338

**Review by peternied — APPROVED** [review]

**Comment by reta** [comment]
https://github.com/opensearch-project/OpenSearch/issues/12717

**Comment by reta** [comment]
> ❌ Gradle check result for [ac396bf](https://github.com/opensearch-project/OpenSearch/commit/ac396bf44e7b1ff6fb6907eab141b4829523ac68): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35240/)

https://github.com/opensearch-project/OpenSearch/issues/12717

**Comment by reta** [comment]
> ❌ Gradle check result for [ac396bf](https://github.com/opensearch-project/OpenSearch/commit/ac396bf44e7b1ff6fb6907eab141b4829523ac68): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35256/)

https://github.com/opensearch-project/OpenSearch/issues/10006
https://github.com/opensearch-project/OpenSearch/issues/5257

**Review by cwperks — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [ac396bf](https://github.com/opensearch-project/OpenSearch/commit/ac396bf44e7b1ff6fb6907eab141b4829523ac68): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35254/)

https://github.com/opensearch-project/OpenSearch/issues/12758

**Pull request merged**
