### PR TITLE
Create separate transport action for render search template action

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Companion PR in security: https://github.com/opensearch-project/security/pull/3689

Separates the transport action that handles `POST /_render/template` into a separate transport action from `GET /_search/template` to resolve an issue with permission the render template endpoint.

The transport action that handles both of these requests is overloaded and it makes permissioning these endpoints a challenge in the security plugin.

1. `GET /_search/template` or `GET /<list_of_indices>/_search_template` is a form of a search request and should consider whether the user has permission to search on the list of indices provided in the request when evaluating whether the user has permission to perform the search template request.

2. In contrast, `POST /_render/template` is a simulation and never actually queries data. See the linked issue for an example of a search template request. From the security plugin POV, this type of request does not need indices when evaluating whether the user has permission to perform the request and can be treated as a cluster permission.

This PR separates the transport action that handles both so that permissions can handle both of these types of requests. There is no functionality change on this PR, the testing for this is added in the companion PR. 

### Related Issues
Resolves https://github.com/opensearch-project/security/issues/3672

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — COMMENTED** [review]
@cwperks Thanks for making this change - Can you fix the conflict on the change log and I'll approve?

**Comment by cwperks** [comment]
@peternied I synchronized and resolved the conflict.

**Comment by cwperks** [comment]
Gradle check failed with flaky test: https://github.com/opensearch-project/OpenSearch/issues/10704

**Comment by peternied** [comment]
@cwperks Can you please create an issue on the GitHub action failures reported in https://github.com/opensearch-project/OpenSearch/pull/11170#issuecomment-1850701128
```
Jenkins Workflow Url: https://build.ci.opensearch.org/job/gradle-check/31127/
time pass: 2790
parse error: Invalid numeric literal at line 1, column 10
Complete the run, checking results now......
Please check jenkins url for logs: https://build.ci.opensearch.org/job/gradle-check/31127/
Result: null
```

**Comment by cwperks** [comment]
@peternied Opened an issue: https://github.com/opensearch-project/OpenSearch/issues/11574

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
@cwperks Mind doing the backport when you get a chance?

**Pull request merged**
