### PR TITLE
Fix DerivedFieldQuery to support concurrent search.

### LINKED ISSUE #15007: [Feature Request] Concurrent search support with Derived Fields
### Is your feature request related to a problem? Please describe

Today it is [documented](https://opensearch.org/docs/latest/field-types/supported-field-types/derived/#:~:text=Derived%20fields%20allow%20you%20to,from%20a%20field's%20doc%20values.) that Derived Fields are not supported with concurrent segment search.  While documented there is nothing preventing a user executing concurrent search code paths while using derived field queries or aggs.

### Describe the solution you'd like

Add compatibility, silently ignore concurrent search paths, or at a minimum throw an error.

### Related component

Search:Query Capabilities

### Describe alternatives you've considered

Do nothing...

### Additional context

From - https://github.com/opensearch-project/OpenSearch/pull/14618#issuecomment-2256603381

### PR DESCRIPTION
**Pull request by mch2**
### Description
This change updates DerivedFieldQuery to create a separate ValueFetcher instance per thread. The DerivedFieldValueFetcher is not thread safe in that it holds a ref to a compiled DerivedFieldScript that is created per thread.  Each script also holds a SourceLookup object that is not thread safe.

Note there are no changes here specific to aggs with derived fields, that test already passes because we create a new ValueFetcher per leaf [here](https://github.com/opensearch-project/OpenSearch/blob/e26608b1492a8c1dcc61b8f3965564a40b3c0401/server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java#L559).

Without this change these ITs fail with:
```
WARNING: Uncaught exception in thread: Thread[#170,opensearch[node_s1][search][T#1],5,TGRP-SimplePainlessIT]
java.lang.AssertionError: StoredFieldsReader are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[#171,opensearch[node_s1][index_searcher][T#1],5,TGRP-SimplePainlessIT] and consumed in Thread[#172,opensearch[node_s1][index_searcher][T#2],5,TGRP-SimplePainlessIT].
	at __randomizedtesting.SeedInfo.seed([77FDD1CE9C5EAC30]:0)
	at org.apache.lucene.tests.codecs.asserting.AssertingCodec.assertThread(AssertingCodec.java:44)
	at org.apache.lucene.tests.codecs.asserting.AssertingStoredFieldsFormat$AssertingStoredFieldsReader.document(AssertingStoredFieldsFormat.java:75)
	at org.opensearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:104)
	at org.opensearch.script.DerivedFieldScript.lambda$static$1(DerivedFieldScript.java:42)
	at org.opensearch.script.DynamicMap.get(DynamicMap.java:84)
	at org.opensearch.painless.PainlessScript$Script.execute(emit(params._source["field"]):12)
	at org.opensearch.index.mapper.DerivedFieldValueFetcher.fetchValuesInternal(DerivedFieldValueFetcher.java:54)
	at org.opensearch.index.mapper.DerivedFieldValueFetcher.getIndexableField(DerivedFieldValueFetcher.java:59)
	at org.opensearch.index.query.DerivedFieldQuery$1$1.matches(DerivedFieldQuery.java:99)
```

### Related Issues
Resolves #15007 

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
@mch2 looks like the yaml tests did not like your change ☹️

**Comment by mch2** [comment]
> @mch2 looks like the yaml tests did not like your change ☹️

yep, I forgot to make changes to support `ObjectDerivedFieldType`, should be fixed now!

**Review by rishabhmaurya — APPROVED** [review]

**Comment by rishabhmaurya** [comment]
LGTM, thanks @mch2

**Review by jed326 — APPROVED** [review]

**Comment by reta** [comment]
Thanks @mch2 , could you please add changelog entry? thank you

**Comment by mch2** [comment]
Coverage fails here because there are some query types without unit tests in DerivedFieldType, will see if i can bump that up as well

**Review by rishabhmaurya — APPROVED** [review]

**Review by jed326 — APPROVED** [review]

**Pull request merged**
