### PR TITLE
Update to Apache Lucene 9.4.0

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update to Apache Lucene 9.4.0

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nknize — APPROVED** [review]
Thx for taking this @reta

**Review by andrross — APPROVED** [review]

**Comment by reta** [comment]
@nknize do we want it in `2.x` ?

**Comment by dblock** [comment]
> @nknize do we want it in `2.x` ?

If this is non-breaking/backwards compatible then yes.

**Comment by nknize** [comment]
Yes. Target 2.x

**Comment by dblock** [comment]
@reta will need a manual backport :( thx

**Pull request merged**
