### PR TITLE
[Backport] [2.x] Update Gradle to 7.6

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update Gradle to 7.6

### Issues Resolved
Backport of https://github.com/opensearch-project/OpenSearch/pull/5381 to `2.x`

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> 
>     * **RESULT:** FAILURE x
> 
>     * **URL:** https://build.ci.opensearch.org/job/gradle-check/7351/
> 
>     * **CommitID:** [58bfa0b](https://github.com/opensearch-project/OpenSearch/commit/58bfa0bab46259f555457ca1944efea4f0c1e6c9)
>       Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>       Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

It seem like Gradle Retry plugin is not compatible with Gradle 7.6? :D :`(

```
> Receiver class org.gradle.testretry.internal.executer.RetryTestResultProcessor does not define or inherit an implementation of the resolved method 'abstract void failure(java.lang.Object, org.gradle.api.tasks.testing.TestFailure)' of interface org.gradle.api.internal.tasks.testing.TestResultProcessor.
```

**Comment by andrross** [comment]
I just opened #5383 to update test-retry on the 2.x branch to be in line with main. Gradle 7.6 support was added in test-retry 1.4.0.

**Comment by reta** [comment]
> I just opened #5383 to update test-retry on the 2.x branch to be in line with main. Gradle 7.6 support was added in test-retry 1.4.0.

I did it here as well, do you want to spit it in several commits?

**Comment by andrross** [comment]
> > I just opened #5383 to update test-retry on the 2.x branch to be in line with main. Gradle 7.6 support was added in test-retry 1.4.0.
> 
> I did it here as well, do you want to spit it in several commits? This guy seems to be green and ready to merge :)

I don't see the test-retry upgrade in this PR? Am I missing it?

**Comment by reta** [comment]
> > > I just opened #5383 to update test-retry on the 2.x branch to be in line with main. Gradle 7.6 support was added in test-retry 1.4.0.
> > 
> > 
> > I did it here as well, do you want to spit it in several commits? This guy seems to be green and ready to merge :)
> 
> I don't see the test-retry upgrade in this PR? Am I missing it?

Oops, sorry about it, I did the change but forgot to push, apologies

**Comment by reta** [comment]
> I just opened #5383 to update test-retry on the 2.x branch to be in line with main. Gradle 7.6 support was added in test-retry 1.4.0.

Approved, thank you!

**Review by andrross — APPROVED** [review]

**Pull request merged**
