### PR TITLE
Update instructions on how to start OpenSearch in debug mode

### PR DESCRIPTION
**Pull request by adnapibar**
### Description

Updated instructions on how to start OpenSearch in debug mode in IntelliJ IDEA.

Also, fixed some minor typos and added line breaks.
 
### Check List
- [x] All tests pass
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Rabi Panda <adnapibar@gmail.com>

### CODE REVIEW

**Review by abbashus — APPROVED** [review]

**Comment by adnapibar** [comment]
> We removed line breaks in a previous commit. Why are we re-adding those for .md files?
> 
> With line breaks it's just very hard to read multiline sentence diffs when someone goes and adds words, everything gets re-formated across many lines and we don't know what changed anymore. And markdown doesn't use line breaks.

Is that the best practice? I think it's better to wrap the long lines than doing horizontal scrolling while editing (I know I can soft-wrap it in my editor). What do you mean by "markdown doesn't use line breaks" ? For instance, here is a [best practice guide](https://google.github.io/styleguide/docguide/style.html#character-line-limit) from Google.

**Comment by dblock** [comment]
> > We removed line breaks in a previous commit. Why are we re-adding those for .md files?
> > With line breaks it's just very hard to read multiline sentence diffs when someone goes and adds words, everything gets re-formated across many lines and we don't know what changed anymore. And markdown doesn't use line breaks.
> 
> Is that the best practice? I think it's better to wrap the long lines than doing horizontal scrolling while editing (I know I can soft-wrap it in my editor). What do you mean by "markdown doesn't use line breaks" ? For instance, here is a [style guide](https://google.github.io/styleguide/docguide/style.html#character-line-limit) from Google.

I can't speak for Google or the best practice. I think this one is YMMV. Hear me out then decide whether you want me to merge as is or not.

Example old text

```
A quick brown fox jumps 
over the lazy dog.
```

replaced with

```
The quick brown fox 
jumps over a lazy dog.
```

2-line change, but `jumps` moved to the next line, but it didn't really change! My head hurts ;)

Instead

```
>A quick brown fox jumps over the lazy dog.
<The quick brown fox jumps over a lazy dog.
```

So much easier to grok.

**Comment by dblock** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

**Review by dblock — APPROVED** [review]

**Pull request merged**
