### PR TITLE
Explicitly set the include discovery nodes flag for reload secure set…

### PR DESCRIPTION
**Pull request by SwethaGuptha**
…ting request

### Description
Explicitly setting the include discovery nodes flag for reload secure setting request, so that the behavior of the action remains same when the default value is changed.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by shwetathareja — APPROVED** [review]

**Comment by SwethaGuptha** [comment]
> ❌ Gradle check result for [079940c](https://github.com/opensearch-project/OpenSearch/commit/079940c2e96335be98491c372cae35cbea1cc717): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47952/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test https://github.com/opensearch-project/OpenSearch/issues/15812

**Comment by SwethaGuptha** [comment]
> ❌ Gradle check result for [3e70fc2](https://github.com/opensearch-project/OpenSearch/commit/3e70fc269a48c157dc477014a743a6f7ef50c04f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47960/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test https://github.com/opensearch-project/OpenSearch/issues/14311

**Review by dbwiddis — APPROVED** [review]
Code LGTM but I'm missing the context of this.  Is there a bug/issue documenting why it is needed?

**Comment by SwethaGuptha** [comment]
> Code LGTM but I'm missing the context of this. Is there a bug/issue documenting why it is needed?

This is in continuation to the PR https://github.com/opensearch-project/OpenSearch/pull/15131.

**Comment by SwethaGuptha** [comment]
> ❕ Gradle check result for [a931a05](https://github.com/opensearch-project/OpenSearch/commit/a931a0544998d35c17ed2cfe53bb0b0e36f05fc6): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/48059/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Flaky test https://github.com/opensearch-project/OpenSearch/issues/14289

**Review by shwetathareja — APPROVED** [review]

**Pull request merged**
