### PR TITLE
Version bump for 1.1 release

### PR DESCRIPTION
**Pull request by nknize**
Bumps the minor to 1.1 for the 1.0 release.

### CODE REVIEW

**Comment by adnapibar** [comment]
start gradle check

**Comment by nknize** [comment]
VersionUtil test failures as a result of adding the new version number. I'll resolve.

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Comment by adnapibar** [comment]
> Bumps the minor to 1.1 for the 1.0 release.

What's the version bump process? My understanding is,

- main is always the next major version, so it's bumped to e.g. `2.0.0`
- the `1.x` branch is bumped to `1.1.0`
- the `1.0` branch is bumped to `1.0.1`

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
> > Bumps the minor to 1.1 for the 1.0 release.
> 
> What's the version bump process? My understanding is,
> 
> * main is always the next major version, so it's bumped to e.g. `2.0.0`
> * the `1.x` branch is bumped to `1.1.0`
> * the `1.0` branch is bumped to `1.0.1`

That's correct. The mechanics are as follows:

1. Version bump 1.x to 1.1 w/ a PR on main (so main is aware of the 1.1 unreleased version)
2. Open Backport PR to 1.x
3. Version bump main to 2.0.0

After GA:

1. Version bump 1.0 to 1.0.1 w/ a PR on main
2. Open backport PR to 1.x (to CI w/ the 1.x line)
3. Cherry pick to 1.0 branch

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
le sigh. The main failure here was caused by https://github.com/opensearch-project/OpenSearch/pull/656/ not being backported to 1.0.

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
Reproducible failure in IndexingIT#testSeqNoCheckpoints:

```
./gradlew ':qa:mixed-cluster:v1.0.0#mixedClusterTest' --tests "org.opensearch.backwards.IndexingIT.testSeqNoCheckpoints" -Dtests.seed=2A7EC1C9BACC5713 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=sr -Dtests.timezone=America/Martinique -Druntime.java=15
  2> java.lang.AssertionError: max_seq no on Node{id='u92yXF39R0WAl32A7EEXDg', nodeName='v1.0.0-3', version=1.0.0} is wrong
    Expected: <-1L>
         but: was <0L>
```

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
I opened #884 to separate the version fixes from the version bump.

**Comment by nknize** [comment]
start gradle check

**Review by adnapibar — APPROVED** [review]
LGTM

**Pull request merged**
