### PR TITLE
Fixing the regression in inner hits aggregation

### PR DESCRIPTION
**Pull request by jainankitk**
This commit fixing the regression introduced by https://github.com/opensearch-project/OpenSearch/commit/da5b2053864f24dcb3b8c555a9fd19e0d91a14e6.

Description

Reverts https://github.com/opensearch-project/OpenSearch/pull/12503 that introduced regression in 2.13.0. Thanks a lot @martijnbolhuis for spotting it and supplying the tests, @dblock for working with the contributor.
Related Issues

Closes https://github.com/opensearch-project/OpenSearch/issues/13467

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jainankitk** [comment]
Related to https://github.com/opensearch-project/OpenSearch/pull/13486

**Comment by reta** [comment]
> Related to #13486

I am not comfortable with this change as is - we need to add more tests, not just one, to cover all uncovered flows and catch the regressions.

**Comment by jainankitk** [comment]
> I am not comfortable with this change as is - we need to add more tests, not just one, to cover all uncovered flows and catch the regressions.

@dblock @reta - Ideally the original commit should have been 2 separate PRs one for ScriptFields and InnerHits. My suggestion is to not press panic button and revert everything. Instead make more cognitive choice.

> to cover all uncovered flows and catch the regressions.

`all` is very hard in my opinion, but I am open to suggestions

**Comment by reta** [comment]
> `all` is very hard in my opinion, but I am open to suggestions

hence we have such regressions

**Comment by jainankitk** [comment]
> > `all` is very hard in my opinion, but I am open to suggestions
> 
> hence we have such regressions, I prefer taking more time to understand were we have misses instead of patching in a rush

As previously mentioned, those 2 changes should have gone as part of separate commits, and makes sense to revert only one of those. But, I am okay if you really prefer that.

**Comment by msfroh** [comment]
> @dblock @msfroh wdyt folks? I would go with full revert #13486 and reintroducing those in 2.15.0 once we have sufficient test coverage for both.

Yeah... I think that makes sense. Let's get back to the known-okay behavior -- as far as I know, we don't have any evidence that initializing the `FetchSubPhaseProcessor` was causing any noticeable pain(*). We should treat this regression as a helpful sign that we didn't have enough test coverage for these kinds of requests. Once we have the test coverage, we can move forward with the change to avoid unnecessary object creation.

(*) Taking a look at the `FetchSubPhaseProcessor` implementation in `InnerHitsPhase`, it looks like it only captures references to `searchContext` and `innerHits`, so those would be the fields of the anonymous class. Combined with standard object overhead, I'm guessing a useless `FetchPhaseSubProcessor` probably wastes less than 20 bytes (assuming 32-bit object references).

**Comment by dblock** [comment]
@msfroh @reta decide in https://github.com/opensearch-project/OpenSearch/pull/13486#issuecomment-2088954077?

**Comment by jainankitk** [comment]
Closing this PR in favor of #13486

**Pull request closed without merging**
