### PR TITLE
[Backport 2.x] Adding WithFieldName interface for QueryBuilders with fieldName

### PR DESCRIPTION
**Pull request by dzane17**
### Description
Backport 2.x https://github.com/opensearch-project/OpenSearch/pull/15705

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jainankitk** [comment]
Skipping changelog as the change is already part of 2.17

**Comment by dzane17** [comment]
@jainankitk I removed CHANGELOG entry

**Comment by jainankitk** [comment]
Flaky test:

```
[Test Result](https://build.ci.opensearch.org/job/gradle-check/47513/testReport/) (1 failure / +1)

    [org.opensearch.indices.settings.SearchOnlyReplicaIT.testFailoverWithSearchReplica_WithoutWriterReplicas](https://build.ci.opensearch.org/job/gradle-check/47513/testReport/junit/org.opensearch.indices.settings/SearchOnlyReplicaIT/testFailoverWithSearchReplica_WithoutWriterReplicas/)
```

**Comment by jainankitk** [comment]
Due to https://github.com/opensearch-project/OpenSearch/issues/15812

**Comment by jainankitk** [comment]
> ❌ Gradle check result for [a844b6f](https://github.com/opensearch-project/OpenSearch/commit/a844b6f30eb385ecb90a735593c74d1ea09a3cb5): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47545/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Failed due to flaky test:

```
[Test Result](https://build.ci.opensearch.org/job/gradle-check/47545/testReport/) (1 failure / +1)

    [org.opensearch.search.pit.PitMultiNodeIT.testCreatePitWhileNodeDropWithAllowPartialCreationFalse {p0={"search.concurrent_segment_search.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/47545/testReport/junit/org.opensearch.search.pit/PitMultiNodeIT/testCreatePitWhileNodeDropWithAllowPartialCreationFalse__p0___search_concurrent_segment_search_enabled___true___/)
```

**Review by jainankitk — APPROVED** [review]

**Pull request merged**
