### PR TITLE
increment version to 1.2.5

### PR DESCRIPTION
**Pull request by abhinavGupta16**
### Description
Incrementing version to `1.2.5` 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
Can you provide more details for this PR and link if any issue is present? Thanks.

**Comment by dblock** [comment]
@owaiskazi19 This is part of the 1.2.4 release process preparing for next development iteration for an eventual patch.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@abhinavGupta16 Good. Now you need a bcw update on 1.x and main.

**Comment by abhinavGupta16** [comment]
> @abhinavGupta16 Good. Now you need a bcw update on 1.x and main.

@dblock - 1.2.4 already exists in `1.x` and `main` branch

**Comment by dblock** [comment]
> > @abhinavGupta16 Good. Now you need a bcw update on 1.x and main.
> 
> @dblock - 1.2.4 already exists in `1.x` and `main` branch

I *think* we need to add 1.2.5, but if no bwc tests fail then maybe we don't need to until/if we decide that 1.2.5 is a thing.

**Comment by nknize** [comment]
Heads up for the future; when doing these bumps you have to make sure to add the bumped bugfix version to .ci/bwcVersions on the main branch, otherwise you'll get these bwc build errors on main:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:bwc:bugfix:buildBwcLinuxTar'.
> Building 1.2.4 didn't generate expected file /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/bwc/bugfix/build/bwc/checkout-1.2/distribution/archives/linux-tar/build/distributions/opensearch-min-1.2.4-SNAPSHOT-linux-x64.tar.gz
```

**Comment by abhinavGupta16** [comment]
I was not aware that we need to add the unreleased version (`1.2.5`) to 1.x and main. I'll keep that in mind for future.

I have raised the PRs for the same - 
https://github.com/opensearch-project/OpenSearch/pull/2057
https://github.com/opensearch-project/OpenSearch/pull/2058

**Pull request merged**
