### PR TITLE
Update gradle config for develocity rebranding

### PR DESCRIPTION
**Pull request by andrross**
The Gradle Enterprise plugin has been rebranded as the Develocity Plugin, resulting in a number of settings being deprecated. This commit updates the settings per [this migration guide][1] and removes all warnings from the build.

The following warnings are no longer present after this change:

```
WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
- The deprecated "gradle.enterprise.testretry.enabled" system property has been replaced by "develocity.testretry.enabled"
- The "com.gradle.enterprise" plugin has been replaced by "com.gradle.develocity"
```

[1]: https://docs.gradle.com/develocity/gradle-plugin/legacy/#develocity_migration

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by andrross** [comment]
> ❌ Gradle check result for [939cab8](https://github.com/opensearch-project/OpenSearch/commit/939cab8bf55c835d589468a78eff0bf6e99b2d89): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/39644/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

#13600

**Review by reta — APPROVED** [review]

**Review by kotwanikunal — APPROVED** [review]

**Comment by reta** [comment]
@peterzhuamazon  @gaiksaya @prudhvigodithi its seems like some checks are in "stuck" mode, nothing could be merged, could you help folks by checking the repo settings? Thank you.

**Comment by prudhvigodithi** [comment]
> @peterzhuamazon @gaiksaya @prudhvigodithi its seems like some checks are in "stuck" mode, nothing could be merged, could you help folks by checking the repo settings? Thank you.

@reta let me check

**Comment by gaiksaya** [comment]
> @peterzhuamazon @gaiksaya @prudhvigodithi its seems like some checks are in "stuck" mode, nothing could be merged, could you help folks by checking the repo settings? Thank you.

@reta Authors need to rebase. The new workflow was added a week back so anything that was raised before that would need rebase and re-run

**Comment by reta** [comment]
> @reta Authors need to rebase. The new workflow was added a week back so anything that was raised before that would need rebase and re-run

@gaiksaya those are brand new pull requests created a few hours ago

**Comment by prudhvigodithi** [comment]
Looks like this PR is blocked for DCO Expected — Waiting for status to be reported.

**Comment by reta** [comment]
> Looks like this PR is blocked for DCO Expected — Waiting for status to be reported.

Correct, and there are a number of pull requests "stuck" there, afaik DCO is an app, not workflow ...

**Comment by prudhvigodithi** [comment]
> Correct, and there are a number of pull requests "stuck" there, afaik DCO is an app, not workflow ...

True but in past the app used to take care of running as a workflow for every PR, looks to me like something changed with it.

**Comment by prudhvigodithi** [comment]
Same is the case for other repos I dont see DCO running for new PR's https://github.com/opensearch-project/opensearch-build-libraries/pull/434, but in past it used to https://github.com/opensearch-project/opensearch-build-libraries/pull/427/checks. 
To unblock I will remove the DCO as PR requirement for OpenSearch repo until its resolved.

**Comment by reta** [comment]
> To unblock I will remove the DCO as PR requirement for OpenSearch repo until its resolved.

Thank you @prudhvigodithi

**Comment by reta** [comment]
@andrross could you please backport to `2.x`? Thank you.

**Comment by prudhvigodithi** [comment]
There was a new issue created in `dcoapp/app` with the same issue as we got [above](https://github.com/opensearch-project/OpenSearch/pull/13942#issuecomment-2146252713) https://github.com/dcoapp/app/issues/211.

**Pull request merged**
