### PR TITLE
Update Apache Lucene to 9.6.0

### PR DESCRIPTION
**Pull request by reta**
### Description
Update Apache Lucene to 9.6.0

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mch2** [comment]
Taking a look here at [org.opensearch.indices.replication.SegmentReplicationIT.testReplicaHasDiffFilesThanPrimary](https://build.ci.opensearch.org/job/gradle-check/15187/testReport/junit/org.opensearch.indices.replication/SegmentReplicationIT/testReplicaHasDiffFilesThanPrimary_4/), I believe this is flaky but will mute if its blocking this bump

**Review by kotwanikunal — APPROVED** [review]

**Comment by mch2** [comment]
@kotwanikunal yeah I queued it to re-try https://github.com/opensearch-project/OpenSearch/actions/runs/4938705305 but its not appearing here

**Review by kotwanikunal — DISMISSED** [review]
Pending on the `gradle check`

**Comment by reta** [comment]
> Pending on the `gradle check`

Github has issues ... again ...

**Comment by reta** [comment]
> Taking a look here at [org.opensearch.indices.replication.SegmentReplicationIT.testReplicaHasDiffFilesThanPrimary](https://build.ci.opensearch.org/job/gradle-check/15187/testReport/junit/org.opensearch.indices.replication/SegmentReplicationIT/testReplicaHasDiffFilesThanPrimary_4/), I believe this is flaky but will mute if its blocking this bump

Yes, it is: https://github.com/opensearch-project/OpenSearch/issues/6885

**Comment by reta** [comment]
@kotwanikunal could you please unlock the merge? thank you

**Review by nknize — APPROVED** [review]
Thx for doing this!

**Pull request merged**
