### PR TITLE
Update protobuf from 3.22.3 to 3.25.4

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Updates version of protobuf in buildSrc/version.properties from 3.22.3 to 3.25.4

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by mch2 — APPROVED** [review]

**Comment by cwperks** [comment]
Resolved conflicts in CHANGELOG.md

**Review by devvratsaini — APPROVED** [review]

**Comment by reta** [comment]
Thanks a lot @cwperks !

**Comment by reta** [comment]
@cwperks could you please backport to 2.x? thank you!

**Comment by cwperks** [comment]
Opened a backport here: https://github.com/opensearch-project/OpenSearch/pull/15864

**Pull request merged**
