### PR TITLE
Added empty build.gradle files for arm64 and s390x because the gradle assemble task fails without them

### LINKED ISSUE #8903: [BUG] Gradle assemble task fails due to missing build.gradle files in docker subprojects
**Describe the bug**
This is a follow-up to PR #4723 which removed build.gradle files from docker subprojects which, in turn, causes the gradle assemble task to fail.

**To Reproduce**
1. Ensure your local repo matches the remote -- `./gradlew clean`
2. Run gradle assemble task -- `./gradlew assemble`

**Expected behavior**
The gradle assemble task should succeed.

**Plugins**
None.

**Screenshots**
image

**Host/Environment (please complete the following information):**
 - OS: Mac OS X
 - Version 13.3.1 (aarch64)

**Additional context**
None.

### PR DESCRIPTION
**Pull request by evankielley**
### Description
This change fixes the gradle assemble task which is failing due to missing build.gradle files in the docker subprojects for arm64 and s390x. These files were removed in PR #4723. I created issue #8903 to discuss this particular bug and created this PR for a quick fix. In addition, issue #8112 was created to further investigate why removing those files causes the build to fail.

### Related Issues
Resolves #8903
Related #8112

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@evankielley could you please rebase against latest `main` (to fix build issues)? Also, thanks to you finding, I will suggest to add distribution checks for pull requests (https://github.com/opensearch-project/OpenSearch/pull/8924), that would have caught the issue  ... thank you

**Comment by evankielley** [comment]
> @evankielley could you please rebase against latest `main` (to fix build issues)? Also, thanks to you finding, I will suggest to add distribution checks for pull requests (#8924), that would have caught the issue ... thank you

@reta I just rebased but as for adding a distro check to gradle assemble, it looks like you have that covered now in PR #8924 ?

**Comment by reta** [comment]
> @reta I just rebased but as for adding a distro check to gradle assemble, it looks like you have that covered now in PR #8924 ?

Thanks @evankielley , I temporarily applied your fix (to prove that all checks pass) but it is removed. I will rebase the my change after we get this one in, thank you.

**Review by reta — APPROVED** [review]

**Comment by evankielley** [comment]
> > @reta I just rebased but as for adding a distro check to gradle assemble, it looks like you have that covered now in PR #8924 ?
> 
> Thanks @evankielley , I temporarily applied your fix (to prove that all checks pass) but it is removed. I will rebase the my change after we get this one in, thank you.

Perfect, thank you

**Pull request merged**
