### PR TITLE
[Remove] various builder and mapping deprecations

### PR DESCRIPTION
**Pull request by nknize**
This PR removes the following deprecations and invalid tests:

* LegacyUpdateMappingIntegrationIT
* ShapeBuilder new z axis checks
* MatchPhrase new zeroTermsQuery checks
* TypeQuery utf8
* CompositeValuesSource format checks
* LegacyESVersionTests bumped to 6.8.15
* LegacyDynamicMapping, LegacySimilarity, LegacyMapperService tests (no longer supported)

### CODE REVIEW

**Comment by nknize** [comment]
Digging... this is a legit failure but unrelated to this PR!!!  Looks like a possible rounding error. Will open an issue and address in a separate PR.

```
./gradlew ':server:test' --tests "org.opensearch.search.aggregations.metrics.TDigestStateTests.testMoreThan4BValues" -Dtests.seed=5630AE9543646685 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m -Djava.security.manager=allow" -Dtests.locale=el-GR -Dtests.timezone=Indian/Chagos -Druntime.java=17
```

```
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([5630AE9543646685:54203DC5B4948AA7]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.opensearch.search.aggregations.metrics.TDigestStateTests.testMoreThan4BValues(TDigestStateTests.java:60)
  2> NOTE: leaving temporary files on disk at: /opt/dev/opensearch-project/opensearch/server/build/testrun/test/temp/org.opensearch.search.aggregations.metrics.TDigestStateTests_5630AE9543646685-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=1147, maxMBSortInHeap=5.679778913474905, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=el-GR, timezone=Indian/Chagos
  2> NOTE: Linux 4.15.0-163-generic amd64/Oracle Corporation 17.0.1 (64-bit)/cpus=8,threads=1,free=522861872,total=536870912
  2> NOTE: All tests run in this JVM: [TDigestStateTests]
```

`assertTrue(v >= prev);`  fails w/ following values:
`v=3.1138788538165313E-4`
`prev=3.113878853816532E-4`

**Comment by nknize** [comment]
opened #1756

**Comment by nknize** [comment]
start gradle check

**Review by adnapibar — APPROVED** [review]
👍

**Pull request merged**
