### PR TITLE
[Upgrade] Lucene 9.1 release

### PR DESCRIPTION
**Pull request by nknize**
Upgrades from Lucne 9.1 snapshot to the official 9.1 release.

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Review by Rishikesh1159 — APPROVED** [review]

**Comment by nknize** [comment]
Repeat of #2311 

Refiring

**Comment by nknize** [comment]
start gradle check

**Comment by owaiskazi19** [comment]
https://github.com/opensearch-project/OpenSearch/issues/1703

**Comment by nknize** [comment]
start gradle check

**Review by reta — APPROVED** [review]

**Review by mch2 — APPROVED** [review]

**Comment by nknize** [comment]
> The backport to `2.x` failed:

/cc @VachaShah

**Comment by nknize** [comment]
/cc @VachaShah Ignore :point_up:   

The failure for 2.x was due to gradle looking for a 1.4 branch that doesn't exist. Since 1.4 is not released (hence 1.4 branch not cut) the next major's minor (e.g., 2.1) does not test against the 1.x branch since there would be no more 1.x releases once 2.0 is GA.

**Pull request merged**
