### PR TITLE
Drop mocksocket & securemock dependencies from sniffer and rest client (no need) (#1174)

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Cherry-pick https://github.com/opensearch-project/OpenSearch/pull/1174 to `1.x`
 
### Issues Resolved
Part of: #114
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock  cherrypick to 1.x, thank you!

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
The linter check is failing, `http://site.icu-project.org/` is not available (and it really is not), referenced from:
 - plugins/ingest-attachment/licenses/tika-parsers-LICENSE.txt
 - plugins/ingest-attachment/licenses/tika-core-LICENSE.txt

Sadly, I could not find the live ICU project site. :(

**Comment by reta** [comment]
start gradle check

**Comment by dblock** [comment]
> start gradle check

This will only do something if you're a maintainer on the project, and is there to avoid runaway hardware costs. This spawns some massive cluster to run integ tests. 

You can rebase main, link checker is fixed.

**Comment by dblock** [comment]
start gradle check

**Comment by reta** [comment]
@dblock Thank you very much, seems like all checks are green now 🥳

**Comment by dblock** [comment]
Thanks @reta

**Pull request merged**
