### PR TITLE
[Refactor] OpenSearchException streamables to a registry

### PR DESCRIPTION
**Pull request by nknize**
OpenSearchException uses an enumerator to create a handler for each serializable Exception implementation. The enumerator is to make it easy to store in an immutable map. The problem with this Hack is that it makes it difficult to unwind the tight coupling of StreamInput with the OpenSearchException class. This commit switches from using an enumerator to a registry in the opensearch-core library in order to support serverless and cloud native implementations outside of the server module.

This commit also refactors base primitive serialization readers and writers from StreamInput and StreamOutput to BaseStreamInput and BaseStreamOutput, respectively.

relates #5910

### CODE REVIEW

**Comment by nknize** [comment]
Not reproducible, rebasing and refiring

```
./gradlew ':server:test' --tests "org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex" -Dtests.seed=4212AD3BAE883BE9 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-BH -Dtests.timezone=CST6CDT -Druntime.java=19
```

**Comment by nknize** [comment]
Oye!! Another unrelated failure? Looks like PRs are becoming awfully volatile due to test failures not being regularly fixed.

This one was not reproducible but has already been [documented as a "flaky test"](https://github.com/opensearch-project/OpenSearch/issues/1715#issuecomment-1339971108) and caught on [multiple PRs](https://github.com/opensearch-project/OpenSearch/issues/6761#issuecomment-1500493498).

```
./gradlew ':qa:smoke-test-http:integTest' --tests "org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationMultiSearchDuringQueryPhase" -Dtests.seed=82B60F546F2663DE -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ru-RU -Dtests.timezone=Asia/Hebron -Druntime.java=19
```

**Comment by nknize** [comment]
Unreal.. two more (https://github.com/opensearch-project/OpenSearch/issues/3590)

Neither are reproducible locally.

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards" -Dtests.seed=86C4F0E32ABC37F8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=cs -Dtests.timezone=Atlantic/Jan_Mayen -Druntime.java=19
```

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchWeightedRoutingIT.testSearchAggregationWithNetworkDisruption_FailOpenEnabled" -Dtests.seed=86C4F0E32ABC37F8 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CR -Dtests.timezone=Pacific/Pitcairn -Druntime.java=19
```

**Comment by RS146BIJAY** [comment]
> testDelayWithALargeAmountOfShards

Sure will mute this test.

**Comment by nknize** [comment]
> > testDelayWithALargeAmountOfShards
> 
> Sure will mute this test.

That works.. let's try to resolve soon, though so `@AwaitsFix` doesn't turn into an alias of `/dev/null` :)

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Do you want this in 2.x?

**Pull request merged**
