### PR TITLE
Fix Flaky SimpleQueryStringIT Tests

### LINKED ISSUE #12574: [BUG] org.opensearch.search.query.SimpleQueryStringIT. testDocWithAllTypes  is flaky
### Describe the bug
org.opensearch.search.query.SimpleQueryStringIT.testDocWithAllTypes  is flaky.

The following code can create too much TermQuery
```
resp = client().prepareSearch("test").setQuery(simpleQueryStringQuery("foo Bar 19 127.0.0.1").defaultOperator(Operator.AND)).get();
```
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java#L591

### To Reproduce

./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.query.SimpleQueryStringIT" -Dtests.method="testDocWithAllTypes {p0={"search.concurrent_segment_search.enabled":"false"}}" -Dtests.seed=15CDBEEC78B94AB3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms -Dtests.timezone=Europe/Zurich -Druntime.java=21

### Expected behavior

Test should pass

### Additional context
Jenkins build failure link - https://build.ci.opensearch.org/job/gradle-check/34541/

### PR DESCRIPTION
**Pull request by kkewwei**
Signed-off-by: kkewwei [kkewwei@163.com](mailto:kkewwei@163.com)

### Description
org.opensearch.search.query.SimpleQueryStringIT.testDocWithAllTypes is flaky.

### Related Issues
Resolves #12574

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kkmr — APPROVED** [review]

**Comment by kkewwei** [comment]
@kkmr please see it again, it's still blocked.

**Comment by kotwanikunal** [comment]
@kkewwei Can you please describe how the new values solve flakiness?

**Comment by kkewwei** [comment]
@kotwanikunal simpleQueryStringQuery("foo Bar 19 127.0.0.1")
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java#L591
will be rewritted to BooleanQuery(TermQuery...), which the count of TermQuery will be bigger than CLUSTER_MAX_CLAUSE_COUNT,  here the CLUSTER_MAX_CLAUSE_COUNT= randomIntBetween(60, 100),
and throw the exception.
```
Caused by: NotSerializableExceptionWrapper[too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 60]
	at org.apache.lucene.search.IndexSearcher$1.visitLeaf(IndexSearcher.java:806)
	at org.apache.lucene.document.SortedNumericDocValuesRangeQuery.visit(SortedNumericDocValuesRangeQuery.java:67)
	at org.apache.lucene.search.IndexOrDocValuesQuery.visit(IndexOrDocValuesQuery.java:130)
	at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:616)
	at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:611)
	at org.apache.lucene.search.BooleanQuery.visit(BooleanQuery.java:611)
	at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:774)
	at org.opensearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:197)
	at org.opensearch.search.DefaultSearchContext.preProcess(DefaultSearchContext.java:358)
	at org.opensearch.search.query.QueryPhase.preProcess(QueryPhase.java:127)
	at org.opensearch.search.SearchService.createContext(SearchService.java:1010)
	at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:606)
	at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:579)
```

when CLUSTER_MAX_CLAUSE_COUNT=80, it work will.

**Comment by reta** [comment]
> @kotwanikunal simpleQueryStringQuery("foo Bar 19 127.0.0.1")

@kkewwei could you please add the comment to the test (where random value is assigned) to explain lower bound selection? thank you

**Comment by kkewwei** [comment]
@reta @kotwanikunal TBR.

**Comment by reta** [comment]
> ❌ Gradle check result for [bb9d3d6](https://github.com/opensearch-project/OpenSearch/commit/bb9d3d68af9a90107139692426cd46e48f8d6450): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35549/)

```
Execution failed for task ':server:generateProto'.
> java.io.IOException: Cannot run program "/home/ubuntu/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.22.3/c262904eec72a197364a85569a4c8ab602a94ef5/protoc-3.22.3-linux-x86_64.exe": error=26, Text file busy

```

**Pull request merged**
