### PR TITLE
Adds ToC to Readme for section update

### PR DESCRIPTION
**Pull request by stockholmux**
### Description
Adds a entry to the ToC on readme
 
### Issues Resolved
As per feedback on #2473
 
### Check List

- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
You should rebase this against an up-to-date main.

**Comment by tlfeng** [comment]
Log 3411 shows a flaky test failure reported in #2440.
Although we could retry the Gradle`check` task, it's recommended to rebase/merge the current upstream main branch to your feature branch.

**Comment by dblock** [comment]
@stockholmux please rebase

**Comment by stockholmux** [comment]
closed in leu of #2546

**Pull request closed without merging**
