### PR TITLE
Added release notes for 1.2.3.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Added release notes for 1.2.3.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Review by bbarani — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
I'm collecting failed gradle checks here ...

**Comment by dblock** [comment]
start gradle check

**Review by VachaShah — APPROVED** [review]

**Pull request merged**
