### PR TITLE
Fail fast when BytesRestResponse ctor throws exception

### PR DESCRIPTION
**Pull request by vrozov**
### Description
When BytesRestResponse ctor throws exception construct new response based on the exception and send it instead of not sending response at all
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle precommit

**Comment by AmiStrn** [comment]
Is there an issue that this codreferenc

When a fix is created without referencing an issue then there is no discussion around it.
 Without context it looks like this is between the author and the maintainers to decide for the community.

For transparency, please reference an issue so others may gain context.

**Comment by dblock** [comment]
When does this (`BytesRestResponse` ctor throws) happen? Maybe turn the answer into a unit test?

**Comment by vrozov** [comment]
Please see https://github.com/opensearch-project/OpenSearch/issues/897.

**Comment by dblock** [comment]
> Please see #897.

OK, I understand. Code looks good to me. I think this needs a unit test expressing what this change fixes (which exception is thrown), and we're good to go.

**Comment by vrozov** [comment]
@dblock I don't see an easy way to unit test the change as exception will be thrown only when there is a protocol mismatch between OS and ES and it is already fixed in #905.  If you have a concrete suggestion, please post it here.

**Comment by dblock** [comment]
> @dblock I don't see an easy way to unit test the change as exception will be thrown only when there is a protocol mismatch between OS and ES and it is already fixed in #905. If you have a concrete suggestion, please post it here.

At the lowest level you could mock `BytesRestResponse` and cause it to raise an error? It would better to have a higher level test, but I just at least want _something_ to exercise this code path. I'll approve if you don't think it's worth it, LMK what you think.

**Comment by vrozov** [comment]
@dblock I don't see any mocking framework available for mocking `BytesRestResponse`. If it is available, I can possibly take a look, but adding Mockito or any other mocking framework is beyond this PR.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
> Can one of admins restart gradle check. None of the failures seems to be related to the PR changes.

I did. If this fails again, could you please help open an issue with details since you're watching this PR? thx

**Comment by dblock** [comment]
Unit test added in https://github.com/opensearch-project/OpenSearch/pull/1024

**Pull request merged**
