### PR TITLE
[Remove] Type mappings from GeoShapeQueryBuilder

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
Remove type mappings from GeoShapeQueryBuilder
 
Relates #1940

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
`TranslogPolicyIT.testRecoverReplica` test failure. 

```
REPRODUCE WITH: ./gradlew ':qa:translog-policy:v1.3.0#Step1OldClusterTest' --tests "org.opensearch.upgrades.TranslogPolicyIT.testRecoverReplica" -Dtests.seed=5FF3A725E3281996 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=is -Dtests.timezone=Etc/GMT+9 -Druntime.java=17

org.opensearch.upgrades.TranslogPolicyIT > testRecoverReplica FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:40069], URI [/testrecoverreplica], status line [HTTP/1.1 200 OK]
    {"acknowledged":true,"shards_acknowledged":true,"index":"testrecoverreplica"}
        at __randomizedtesting.SeedInfo.seed([5FF3A725E3281996:A56A688116F1D89B]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
        at app//org.opensearch.upgrades.TranslogPolicyIT.testRecoverReplica(TranslogPolicyIT.java:129)
```

**Comment by dreamer-89** [comment]
start gradle check

**Comment by dreamer-89** [comment]
Two failures, not reproducible locally on mac & ubuntu machines

```
> Task :qa:full-cluster-restart:v1.3.0#oldClusterTest

REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testEnableSoftDeletesOnRestore" -Dtests.seed=97CDDED86585B7F3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-ZA -Dtests.timezone=Europe/Guernsey -Druntime.java=17

org.opensearch.upgrades.FullClusterRestartIT > testEnableSoftDeletesOnRestore FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:41905], URI [/testenablesoftdeletesonrestore], status line [HTTP/1.1 200 OK]
    {"acknowledged":true,"shards_acknowledged":true,"index":"testenablesoftdeletesonrestore"}
        at __randomizedtesting.SeedInfo.seed([97CDDED86585B7F3:A3921A71B91609C8]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
        at app//org.opensearch.upgrades.FullClusterRestartIT.testEnableSoftDeletesOnRestore(FullClusterRestartIT.java:1551)

REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testResize" -Dtests.seed=97CDDED86585B7F3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-ZA -Dtests.timezone=Europe/Guernsey -Druntime.java=17

org.opensearch.upgrades.FullClusterRestartIT > testResize FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:39333], URI [/testresize], status line [HTTP/1.1 200 OK]
    {"acknowledged":true,"shards_acknowledged":true,"index":"testresize"}
        at __randomizedtesting.SeedInfo.seed([97CDDED86585B7F3:20B2C42C7AC32DC8]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.upgrades.FullClusterRestartIT.testResize(FullClusterRestartIT.java:1387)
```

**Comment by dreamer-89** [comment]
start gradle check

**Comment by dreamer-89** [comment]
The latest job fails `testThatUpdatingMappingShouldNotRemoveSizeMappingConfiguration` test due to assertion error. 
```
REPRODUCE WITH: ./gradlew ':plugins:mapper-size:internalClusterTest' --tests "org.opensearch.index.mapper.size.SizeMappingIT.testThatUpdatingMappingShouldNotRemoveSizeMappingConfiguration" -Dtests.seed=4F62945A913A057D -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pt -Dtests.timezone=Australia/Currie -Druntime.java=17

org.opensearch.index.mapper.size.SizeMappingIT > testThatUpdatingMappingShouldNotRemoveSizeMappingConfiguration FAILED
    java.lang.AssertionError: Expected size field mapping to be enabled for foo
    Expected: map containing ["_size"->ANYTHING]
         but: map was [<properties={otherField={type=text}}>]
        at __randomizedtesting.SeedInfo.seed([4F62945A913A057D:D988F27324556493]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.opensearch.index.mapper.size.SizeMappingIT.assertSizeMappingEnabled(SizeMappingIT.java:119)
        at org.opensearch.index.mapper.size.SizeMappingIT.testThatUpdatingMappingShouldNotRemoveSizeMappingConfiguration(SizeMappingIT.java:85)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/home/ubuntu/.gradle/wrapper/dists/gradle-7.3.3-all/4295vidhdd9hd3gbjyw1xqxpo/gradle-7.3.3/lib/plugins/gradle-testing-base-7.3.3.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release
```

**Comment by dreamer-89** [comment]
start gradle check

**Review by reta — APPROVED** [review]

**Review by nknize — APPROVED** [review]
My old stomping grounds.. :)  This will also need rebase w/ #2225; otherwise LGTM

**Comment by dreamer-89** [comment]
testMSearchChildRequestCancellationWithClusterLevelTimeout assertion failure
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchCancellationIT.testMSearchChildRequestCancellationWithClusterLevelTimeout" -Dtests.seed=2CA7B9342266CC41 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ru -Dtests.timezone=Poland -Druntime.java=17

org.opensearch.search.SearchCancellationIT > testMSearchChildRequestCancellationWithClusterLevelTimeout FAILED
    java.lang.AssertionError: Actual child request with cancellation failure is different that expected expected:<[0, 1]> but was:<[]>
        at __randomizedtesting.SeedInfo.seed([2CA7B9342266CC41:921A72D1B3702C36]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.opensearch.search.SearchCancellationIT.ensureMSearchWasCancelled(SearchCancellationIT.java:194)
        at org.opensearch.search.SearchCancellationIT.testMSearchChildRequestCancellationWithClusterLevelTimeout(SearchCancellationIT.java:537)
```

**Comment by dreamer-89** [comment]
start gradle check

**Pull request merged**
