### PR TITLE
Bump version to 1.0.1 revision

### PR DESCRIPTION
**Pull request by nknize**
This commit stages the branch to the next 1.0.1 patch release. BWC testing needs this even if the next revision is never actually released.

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
Random unreproducible failure unrelated to this PR:

```
./gradlew ':server:test' --tests "org.opensearch.cluster.routing.allocation.decider.ConcurrentRecoveriesAllocationDeciderTests.testClusterConcurrentRecoveries" -Dtests.seed=2899DF02679A673E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=ro-RO -Dtests.timezone=Africa/Mogadishu -Druntime.java=15
```

**Review by saratvemulapalli — APPROVED** [review]
Changes look good to me, thanks @nknize !

**Pull request merged**
