### PR TITLE
[Backport] [1.x] Update Jackson to 2.12.5

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Backport of https://github.com/opensearch-project/OpenSearch/pull/1247
 
### Issues Resolved
None
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
start gradle check

**Comment by reta** [comment]
> x   Gradle Check failure [6b586d4](https://github.com/opensearch-project/OpenSearch/commit/6b586d461074e1598c07b8095e57706d3f03c2b1)
> [Log 554](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_554.log)
> 
> [Reports 554](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_554_reports.zip)

Looks like nom-related failure, flaky test?

image


```
[2021-09-22T09:13:38,503][WARN ][o.o.s.SnapshotShardsService] [node_t1] [[index-one][0]][test-repo:snapshot-one/6L1qrTmwT_qzq9z29tpC_g] failed to snapshot shard
org.opensearch.common.util.concurrent.UncategorizedExecutionException: Failed execution
	at org.opensearch.common.util.concurrent.FutureUtils.rethrowExecutionException(FutureUtils.java:104) ~[main/:?]
	at org.opensearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:96) ~[main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:124) ~[main/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [main/:?]
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:239) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:119) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:111) [main/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:111) [main/:?]
	at org.opensearch.common.util.concurrent.BaseFuture.setException(BaseFuture.java:175) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.onFailure(ListenableFuture.java:148) [main/:?]
	at org.opensearch.action.StepListener.innerOnFailure(StepListener.java:80) [main/:?]
	at org.opensearch.action.NotifyOnceListener.onFailure(NotifyOnceListener.java:60) [main/:?]
	at org.opensearch.action.support.GroupedActionListener.onFailure(GroupedActionListener.java:96) [main/:?]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.lambda$fileQueueListener$69(BlobStoreRepository.java:2279) [main/:?]
	at org.opensearch.action.ActionListener$2.onFailure(ActionListener.java:107) [main/:?]
	at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:101) [main/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:744) [main/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: already closed
	at org.opensearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:286) ~[main/:?]
	at org.opensearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:259) ~[main/:?]
	at org.opensearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:78) ~[main/:?]
	at org.opensearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:89) ~[main/:?]
	... 20 more
Caused by: java.io.IOException: already closed
	at org.opensearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.blockExecutionAndMaybeWait(MockRepository.java:375) ~[framework-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.opensearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.maybeIOExceptionOrBlock(MockRepository.java:357) ~[framework-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.opensearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.writeBlob(MockRepository.java:485) ~[framework-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.snapshotFile(BlobStoreRepository.java:2513) ~[main/:?]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.lambda$executeOneFileSnapshot$66(BlobStoreRepository.java:2136) ~[main/:?]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86) ~[main/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:756) ~[main/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) ~[main/:?]
	... 3 more
	Suppressed: java.io.IOException: already closed
		at org.opensearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.blockExecutionAndMaybeWait(MockRepository.java:375) ~[framework-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
		at org.opensearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.maybeIOExceptionOrBlock(MockRepository.java:357) ~[framework-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
		at org.opensearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.writeBlob(MockRepository.java:485) ~[framework-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
		at org.opensearch.repositories.blobstore.BlobStoreRepository.snapshotFile(BlobStoreRepository.java:2513) ~[main/:?]
		at org.opensearch.repositories.blobstore.BlobStoreRepository.lambda$executeOneFileSnapshot$66(BlobStoreRepository.java:2136) ~[main/:?]
		at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86) ~[main/:?]
		at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:756) [main/:?]
		at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50) [main/:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-09-22T09:13:38,506][INFO ][o.o.n.Node               ] [testAssertMultipleSnapshotsAndPrimaryFailOver] closed
[2021-09-22T09:13:38,506][WARN ][o.o.s.SnapshotShardsService] [node_t1] [test-repo:snapshot-one/6L1qrTmwT_qzq9z29tpC_g] [ShardSnapshotStatus[state=FAILED, nodeId=f1Pby08PS1KKHg8TPxKBTg, reason=UncategorizedExecutionException[Failed execution]; nested: ExecutionException[java.io.IOException: already closed]; nested: IOException[already closed], generation=null]] failed to update snapshot state
org.opensearch.transport.SendRequestTransportException: [node_t1][127.0.0.1:46289][internal:cluster/snapshot/update_snapshot_status]
	at org.opensearch.transport.TransportService.sendRequestInternal(TransportService.java:796) [main/:?]
	at org.opensearch.transport.TransportService.sendRequest(TransportService.java:685) [main/:?]
	at org.opensearch.transport.TransportService.sendRequest(TransportService.java:617) [main/:?]
	at org.opensearch.snapshots.SnapshotShardsService.lambda$sendSnapshotShardUpdate$2(SnapshotShardsService.java:466) [main/:?]
	at org.opensearch.transport.TransportRequestDeduplicator.executeOnce(TransportRequestDeduplicator.java:65) [main/:?]
	at org.opensearch.snapshots.SnapshotShardsService.sendSnapshotShardUpdate(SnapshotShardsService.java:452) [main/:?]
	at org.opensearch.snapshots.SnapshotShardsService.notifyFailedSnapshotShard(SnapshotShardsService.java:446) [main/:?]
	at org.opensearch.snapshots.SnapshotShardsService.access$300(SnapshotShardsService.java:90) [main/:?]
	at org.opensearch.snapshots.SnapshotShardsService$1.onFailure(SnapshotShardsService.java:298) [main/:?]
	at org.opensearch.action.ActionListener$6.onFailure(ActionListener.java:305) [main/:?]
	at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:84) [main/:?]
	at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:101) [main/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [main/:?]
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:239) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:119) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:111) [main/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:111) [main/:?]
	at org.opensearch.common.util.concurrent.BaseFuture.setException(BaseFuture.java:175) [main/:?]
	at org.opensearch.common.util.concurrent.ListenableFuture.onFailure(ListenableFuture.java:148) [main/:?]
	at org.opensearch.action.StepListener.innerOnFailure(StepListener.java:80) [main/:?]
	at org.opensearch.action.NotifyOnceListener.onFailure(NotifyOnceListener.java:60) [main/:?]
	at org.opensearch.action.support.GroupedActionListener.onFailure(GroupedActionListener.java:96) [main/:?]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.lambda$fileQueueListener$69(BlobStoreRepository.java:2279) [main/:?]
	at org.opensearch.action.ActionListener$2.onFailure(ActionListener.java:107) [main/:?]
	at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:101) [main/:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:744) [main/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.opensearch.node.NodeClosedException: node closed {node_t1}{f1Pby08PS1KKHg8TPxKBTg}{-qk8KDReSH6-LlZOXIk6lg}{127.0.0.1}{127.0.0.1:46289}{d}
	at org.opensearch.transport.TransportService.sendRequestInternal(TransportService.java:777) ~[main/:?]
	... 30 more
```

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
Likely a bug. I opened https://github.com/opensearch-project/OpenSearch/issues/1272

**Review by dblock — APPROVED** [review]

**Pull request merged**
