### PR TITLE
Update/maintainers.md

### PR DESCRIPTION
**Pull request by CEHENKLE**
### Description
Adding in 4 maintainers who have worked on OpenSearch.  
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CEHENKLE** [comment]
start gradle check

**Review by abbashus — APPROVED** [review]
LGTM!

**Comment by CEHENKLE** [comment]
start gradle check

**Review by setiah — APPROVED** [review]
LGTM!

**Comment by setiah** [comment]
start gradle check

**Pull request merged**
