### PR TITLE
Bumps com.avast.gradle:gradle-docker-compose-plugin from 0.16.2 to 0.17.5

### PR DESCRIPTION
**Pull request by Poojita-Raj**
Bumps [com.avast.gradle:gradle-docker-compose-plugin](https://github.com/avast/gradle-docker-compose-plugin) from 0.16.12 to 0.17.5.
- [Release notes](https://github.com/avast/gradle-docker-compose-plugin/releases)
- [Commits](https://github.com/avast/gradle-docker-compose-plugin/compare/0.16.12...0.17.5)

---
updated-dependencies:
- dependency-name: com.avast.gradle:gradle-docker-compose-plugin dependency-type: direct:production update-type: version-update:semver-minor ...

### Description
[Describe what this change achieves]

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dependabot recreate please

**Comment by reta** [comment]
FYI, we already updated https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/build.gradle#L118

**Comment by ticheng-aws** [comment]
Hi @Poojita-Raj, looks like we have already updated. Could we close this PR?

**Comment by sohami** [comment]
Closing this PR as dependency is already upgraded as part of https://github.com/opensearch-project/OpenSearch/pull/11692

**Pull request closed without merging**
