### PR TITLE
[Backport 2.x] Remove deprecated constant META_FIELDS_BEFORE_7DOT8 (#13860)

### PR DESCRIPTION
**Pull request by cwperks**
Backport #13860 to 2.x

### CODE REVIEW

**Comment by reta** [comment]
> ```
> WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
> - The deprecated "gradle.enterprise.testretry.enabled" system property has been replaced by "develocity.testretry.enabled"
> - The "com.gradle.enterprise" plugin has been replaced by "com.gradle.develocity"
> FAILURE: Build failed with an exception.
> ```

I will fix that in https://github.com/opensearch-project/OpenSearch/pull/13584 , thanks for noticing

**Comment by reta** [comment]
@cwperks seems like 2.x is still using this property

**Comment by cwperks** [comment]
I see, it was removed from main in https://github.com/opensearch-project/OpenSearch/commit/db418fb8acc18aef95af7c4c4253d87660fb9e93#diff-1512f075b54901bdac674bdae377e3c0ea1d9f984b8f3a832663e1a8e9b7d77b.

I will close this backport and target this change only on main. I'll open a separate PR to move the CHANGELOG entry from the 2.x CHANGELOG -> CHANGELOG 3.0.

**Comment by reta** [comment]
> I see, it was removed from main in [db418fb#diff-1512f075b54901bdac674bdae377e3c0ea1d9f984b8f3a832663e1a8e9b7d77b](https://github.com/opensearch-project/OpenSearch/commit/db418fb8acc18aef95af7c4c4253d87660fb9e93#diff-1512f075b54901bdac674bdae377e3c0ea1d9f984b8f3a832663e1a8e9b7d77b).

Sorry about that, thank you

**Pull request closed without merging**
