### PR TITLE
Add timeout on cat/stats API

### LINKED ISSUE #494: Timeout on cat/stats APIs
### **Is your feature request related to a problem? Please describe.**
On few Stats/Cat API, master undefinetly waits for response from data nodes. If cluster have bad node and is not able to respond to master calls, then such API calls stays in master memory. Frequent calls of such API will cause **memory pile up on master**. 
We should make master resilient to such API calls when there is bad node in cluster.

Few APIs for which master gathers information from data nodes:
* /_cat/nodes
* /_cat/nodeattrs
* /_cat/thread_pool
* /_cat/allocation
* /_cat/recovery
* /_cat/plugins
* /_nodes
* /_stats

###  **Describe the solution you'd like**
We can add **timeout in communication between master and data nodes**. If timeout occurs and master don't get response from data nodes then it will just return the whatever response collected as API response and clear the memory in master.

###  **Describe alternatives you've considered**
None.

###  **Additional context**
As a next step of improvement, we should make the transport call as cancelable, so once master timeouts on data nodes then it will cancel the transport request so bad data node will also clear memory from their side. Otherwise it might worsen the situation on bad node.

Here our motive is to first make the master resilient, as memory pile up on master affects the availability/performance of whole cluster.

### PR DESCRIPTION
**Pull request by dhwanilpatel**
Signed-off-by: Dhwanil Patel <dhwanip@amazon.com>

### Description
Add timeouts in few of APIs which requires information gathering from data nodes on master node. Timeout has been introduced on this master-data transport calls. Master wont be waiting indefinite for data node response. Default timeout is kept at 30s.
APIs where it has been introduced:
* /_cat/nodes
* /_cat/nodeattrs
* /_cat/thread_pool
* /_cat/allocation
* /_cat/recovery
* /_cat/plugins
* /_nodes
* /_stats
 
### Issues Relates
relates #494
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
  - [x] New tests are passing.
- [ ] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Review by itiyamas — APPROVED** [review]
Thanks Dhwanil for making these changes.  Let us ensure that we update the documentation once it is available.

**Comment by peterzhuamazon** [comment]
start dco check
start wrapper validation
start gradle precommit

**Review by Bukhtawar — APPROVED** [review]

**Comment by dhwanilpatel** [comment]
Can maintainers please help me merge this PR? Approver don’t have write access, so merging is blocked.

**Comment by dblock** [comment]
start gradle check

**Comment by dhwanilpatel** [comment]
@dblock Thanks for kicking off CI. That has passed. 

Can we please merge it? Let me know if anything is required from my side.

**Comment by shwetathareja** [comment]
@dhwanilpatel check if you want to raise a backport PR for 1.x

**Pull request merged**
