### PR TITLE
[Backport 2.x] Add fieldType to AbstractQueryBuilder and SortBuilder (#15328)

### PR DESCRIPTION
**Pull request by dzane17**
(cherry picked from commit 839ba0bca05f8a9aefdbabd023dc75741265bd6c)
Signed-off-by: David Zane <davizane@amazon.com>

### Description
[Describe what this change achieves]

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by msfroh** [comment]
This is a breaking change on the 2.x line.

There are many plugins that implement custom QueryBuilders. We can't go and add a new abstract method to `AbstractQueryBuilder` without breaking all of those plugins.

**Review by msfroh — CHANGES_REQUESTED** [review]
Adding "Request changes" to block this from getting backported to 2.x, so that we don't break all the plugins.

**Comment by jainankitk** [comment]
> This is a breaking change on the 2.x line.
> 
> There are many plugins that implement custom QueryBuilders. We can't go and add a new abstract method to `AbstractQueryBuilder` without breaking all of those plugins.

That's a good point @msfroh. The reason for making it abstract is to ensure future implementations automatically provide fieldName.

Any idea as to how many plugins we are talking about? And, what is the right channel for communicating this change?

**Comment by jainankitk** [comment]
While did not see anything in SQL plugin, saw 1 usage in k-NN - https://github.com/opensearch-project/k-NN/blob/2b303d90d7e47169f5bb1a216c4b9d7207794fba/src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java#L69

**Comment by msfroh** [comment]
> Any idea as to how many plugins we are talking about?

Within opensearch-project, there are these 66 files: https://github.com/search?q=org%3Aopensearch-project+%22extends+AbstractQueryBuilder%22+NOT+repo%3Aopensearch-project%2FOpenSearch&type=code

Outside of opensearch-project, who knows? I tried searching all of GitHub and found a few hits (e.g. Querqy) that aren't forks from opensearch-project: https://github.com/search?q=org.opensearch.index.query.AbstractQueryBuilder+NOT+repo%3Aopensearch-project%2FOpenSearch+NOT+path%3A%2F%5Eserver%5C%2Fsrc%5C%2Fmain%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2F%2F+NOT+owner%3Aopensearch-project++NOT+path%3A%2F%5Emodules%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Fmain%5C%2Fkotlin%5C%2Forg%5C%2Fopensearch%5C%2Findexmanagement%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Fmain%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2Fknn%5C%2Findex%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Fmain%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2Fsecurity%5C%2F%2F+NOT+path%3A%2F%5Eserver%5C%2Fsrc%5C%2FinternalClusterTest%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2Fsearch%5C%2Ffetch%5C%2Fsubphase%5C%2Fhighlight%5C%2F%2F&type=code

See also my comment on https://github.com/opensearch-project/OpenSearch/pull/15328, though. Adding a field name to all `QueryBuilder`s doesn't make sense and is a bad idea. There are many query types that act on multiple fields. The assumption that a QueryBuilder's in general "have" a field name is a fundamental misunderstanding of OpenSearch queries.

**Comment by jainankitk** [comment]
> > Any idea as to how many plugins we are talking about?
> 
> Within opensearch-project, there are these 66 files: https://github.com/search?q=org%3Aopensearch-project+%22extends+AbstractQueryBuilder%22+NOT+repo%3Aopensearch-project%2FOpenSearch&type=code
> 
> Outside of opensearch-project, who knows? I tried searching all of GitHub and found a few hits (e.g. Querqy) that aren't forks from opensearch-project: https://github.com/search?q=org.opensearch.index.query.AbstractQueryBuilder+NOT+repo%3Aopensearch-project%2FOpenSearch+NOT+path%3A%2F%5Eserver%5C%2Fsrc%5C%2Fmain%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2F%2F+NOT+owner%3Aopensearch-project++NOT+path%3A%2F%5Emodules%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Fmain%5C%2Fkotlin%5C%2Forg%5C%2Fopensearch%5C%2Findexmanagement%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Fmain%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2Fknn%5C%2Findex%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Fmain%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2Fsecurity%5C%2F%2F+NOT+path%3A%2F%5Eserver%5C%2Fsrc%5C%2FinternalClusterTest%5C%2Fjava%5C%2Forg%5C%2Fopensearch%5C%2Fsearch%5C%2Ffetch%5C%2Fsubphase%5C%2Fhighlight%5C%2F%2F&type=code
> 
> See also my comment on #15328, though. Adding a field name to all `QueryBuilder`s doesn't make sense and is a bad idea. There are many query types that act on multiple fields. The assumption that a QueryBuilders in general "have" a field name is a fundamental misunderstanding of OpenSearch queries.

I think most of these references are coming from documentation, which should auto update from the code. Excluding that we have about:

* 1 - k-NN
* 1 - alerting
* 1 - security-analytics
* 3 - neural-search
* 5 - opensearch-learning-to-rank-base

TBH, updating these plugins doesn't look too bad to me. But, I am open to suggestions on improving the original code change itself. Some of the discussion on different options is captured over here - https://github.com/opensearch-project/query-insights/issues/69

**Comment by jainankitk** [comment]
Closing PR while we are working on different approach for solving this - https://github.com/opensearch-project/query-insights/issues/69

**Pull request closed without merging**
