### PR TITLE
Remove reference to an EC2 instance type.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Let's remove calling out an EC2 instance type, avoid AWS-specific things.

### Check List

- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by tmarkley — APPROVED** [review]
LGTM!

**Comment by dblock** [comment]
start gradle check

**Comment by CEHENKLE** [comment]
Would it makes sense to add another data point for comparison instead of removing it?

**Comment by dblock** [comment]
> Would it makes sense to add another data point for comparison instead of removing it?

I had added this when I was revamping the developer guide, and it's not even correct as it takes <5m on that hardware. The actual time varies so dramatically setup by setup, and doesn't add anything useful to the developer IMHO. It's also a moving target as we will want to improve the time it takes to run these checks and will inevitably become out of date.

**Comment by CEHENKLE** [comment]
> > Would it makes sense to add another data point for comparison instead of removing it?
> 
> I've considered it and would rather not. I had added this when I was revamping the developer guide, and it's not even correct as it takes <5m on that hardware. The actual time varies so dramatically setup by setup, and doesn't add anything useful to the developer IMHO. It's also a moving target as we will want to improve the time it takes to run these checks and will inevitably become out of date.

Makes sense. I assume the original intent of that number being in there was so that folks didn't start doubting themselves when it took a long time.  So it might be worthwhile to put in a note to that effect (this can take some time, so don't panic).  But if you think folks have more patience/less self-doubt than me, feel free just to strike it ;)

**Comment by dblock** [comment]
> > > Would it makes sense to add another data point for comparison instead of removing it?
> > 
> > 
> > I've considered it and would rather not. I had added this when I was revamping the developer guide, and it's not even correct as it takes <5m on that hardware. The actual time varies so dramatically setup by setup, and doesn't add anything useful to the developer IMHO. It's also a moving target as we will want to improve the time it takes to run these checks and will inevitably become out of date.
> 
> Makes sense. I assume the original intent of that number being in there was so that folks didn't start doubting themselves when it took a long time. So it might be worthwhile to put in a note to that effect (this can take some time, so don't panic). But if you think folks have more patience/less self-doubt than me, feel free just to strike it ;)

I'll strike it. You can clearly see that progress is being made as the workers are showing movement and logs, it's not like it's hanging with a spinner.

**Review by CEHENKLE — APPROVED** [review]
Ship it!

**Pull request merged**
