### PR TITLE
Adding a "meta issue" template

### PR DESCRIPTION
**Pull request by CEHENKLE**
### Description
During the 3/31 OpenSearch triage, we noticed that we had several meta issues that didn't have enough details for someone who wasn't working on the project to understand what was trying to be accomplished.

This template attempts to capture the conversation around "goodness" of a meta ticket here:  https://opensearch.slack.com/archives/C05L60S4UBT/p1706720978192339

### Related Issues
No related issue

### Check List
- [ ] ~New functionality includes testing.~
- [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
- [ ] ~New functionality has javadoc added~
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]
@CEHENKLE Thanks for building this up - give us a baseline quality on our meta issues that will be easy for the community to engage with and if we do see meta issues that can be improved, this is a straight forward way to improve an existing issue by recreating it with this template.

**Review by andrross — APPROVED** [review]

**Comment by peternied** [comment]
@CEHENKLE Looks like you had some changes that [aren't signed off with the DCO](https://github.com/opensearch-project/OpenSearch/pull/12148/checks?check_run_id=21166102508), can you updated these?

**Review by reta — APPROVED** [review]

**Comment by CEHENKLE** [comment]
> @CEHENKLE Looks like you had some changes that [aren't signed off with the DCO](https://github.com/opensearch-project/OpenSearch/pull/12148/checks?check_run_id=21166102508), can you updated these?

D'oh!  I'll fix it Monday, thanks :)

**Comment by kartg** [comment]
Gradle check failure is from known flaky test https://github.com/opensearch-project/OpenSearch/issues/9191

```
> Task :server:internalClusterTest

Tests with failures:
 - org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing

4576 tests completed, 1 failed, 44 skipped
...
```

**Review by peternied — APPROVED** [review]

**Pull request merged**
