### PR TITLE
Cleanup CHANGELOG-3.0

### PR DESCRIPTION
**Pull request by cwperks**
### Description

This PR removes items from CHANGELOG-3.0 that have been backported to 2.x

### Related Issues

Related to recent PR that created CHANGELOG-3.0: https://github.com/opensearch-project/OpenSearch/pull/13040

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
Any idea why the gradle check failed? The last line is `Finished: SUCCESS`.

**Comment by dblock** [comment]
> Any idea why the gradle check failed? The last line is `Finished: SUCCESS`.

Looks like extracting from the log didn't work.

```
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
parse error: Invalid numeric literal at line 4, column 14
Workflow running status :Attempt 1/10 failed. The jq processing failed with exit code: 4. Retrying...
```

Let's see if this reproduced itself or was a fluke. It could be that we got a broken log from Jenkins.

**Comment by dblock** [comment]
> ❌ Gradle check result for [50e1e74](https://github.com/opensearch-project/OpenSearch/commit/50e1e74c967f28a81e2bd2d1f0900fc485b33245): [null](https://build.ci.opensearch.org/job/gradle-check/37109/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT.testConcurrentDecommissionAction](https://build.ci.opensearch.org/job/gradle-check/37109/testReport/junit/org.opensearch.cluster.coordination/AwarenessAttributeDecommissionIT/testConcurrentDecommissionAction/)

https://github.com/opensearch-project/OpenSearch/issues/12197

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Thanks a lot @cwperks !

**Comment by kotwanikunal** [comment]
Thanks @cwperks! Should we also add these entries into `CHANGELOG.md`?

**Pull request merged**
