### PR TITLE
Removed java11 source folders since JDK-11 is the baseline now

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Removed java11 source folders since JDK-11 is the baseline now (also unblocks unnecessary Jacoco customizations to workaround  https://github.com/jacoco/jacoco/issues/407).  
 
### Issues Resolved
Part of https://github.com/opensearch-project/OpenSearch/pull/2821/files
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock please when you have time, thanks!

**Review by nknize — APPROVED** [review]
LGTM. Thx!

**Comment by reta** [comment]
@dblock apologies, I could not add labels to backport it to 2.0, may I ask you please to add those?

**Comment by reta** [comment]
@saratvemulapalli you are very right, the labels (and other settings) are available to me now (but were not available before), thanks for highlighting that!

**Pull request merged**
