### PR TITLE
Adds this PR to CHANGELOG

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Description
Updates changelog for dependabot PR

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kotwanikunal** [comment]
I tried looking into #7068 . This needs more than just the changelog entry
`./gradlew updateSHAs` was failing as well.

**Comment by owaiskazi19** [comment]
Can we add the changelog in https://github.com/opensearch-project/OpenSearch/pull/7068 itself and close this PR?

**Comment by kotwanikunal** [comment]
@owaiskazi19 I am not sure if @DarshitChanpura will be able to directly update the branch because he is not a maintainer for the OpenSearch repo.

**Comment by DarshitChanpura** [comment]
> > @owaiskazi19 I am not sure if @DarshitChanpura will be able to directly update the branch because he is not a maintainer for the OpenSearch repo.
> 
> Ah, missed that. @DarshitChanpura are you fine if I push the change to the changelog on your behalf to #7068?

Yes, sounds good. I was not able to do it directly because I'm not a maintainer.

**Comment by owaiskazi19** [comment]
@DarshitChanpura @kotwanikunal I have added the changelog entry in #7068 and there's a build failure. Closing this PR.

**Pull request closed without merging**
