### PR TITLE
Reduce memory copy in zstd compression

### PR DESCRIPTION
**Pull request by luyuncheng**
As i see #3577 there is a zstd compression mode. 
i think in some scenarios, like init compress buffer, we can save memory copy in `ArrayUtil.grow` instead of using ArrayUtil.growNoCopy

### CODE REVIEW

**Comment by reta** [comment]
@luyuncheng could you please fix DCO check https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@dblock looks like a legit fix (of not doing unneeded array copy), wdyt?

**Review by andrross — APPROVED** [review]

**Comment by Bukhtawar** [comment]
While this one looks straight forward but its always a good practise to understand the optimisation and check if there are regressions if any with performance

**Comment by luyuncheng** [comment]
> @luyuncheng do you have any numbers?

@dblock  We do some mini benchmark with rally:
Track: http_logs , jvm 1G, 8core, 16G Mem, codec:zstd

| Metric |  Task  | Baseline | Contender | Diff | Unit | Diff% |
| ------ | ------ | --------- | ---------- | ---- | ---- | ------ |
| Cumulative indexing time of primary shards |              |   260.726       |    253.455       |   -7.271   |    min |   -2.79% |
| Total Young Gen GC time |              |   263.871       |    256.28        |   -7.591   |      s |   -2.88% |
| Total Young Gen GC count |              | 16495           |  16437           |  -58       |        |   -0.35% |
| Total Old Gen GC time |              |    52.601       |     47.93        |   -4.671   |      s |   -8.88% |
| Total Old Gen GC count |              |   606           |    591           |  -15       |        |   -2.48% |
| Min Throughput | index-append | 89497.2         |  94867.8         | 5370.6     | docs/s |   +6.00% |
| Mean Throughput | index-append | 96260.5         |  97990.2         | 1729.73    | docs/s |   +1.80% |
| Median Throughput | index-append | 96184.2         |  97639.2         | 1455.02    | docs/s |   +1.51% |
|99th percentile latency | index-append |  1271.33        |   1250.93        |  -20.4042  |     ms |   -1.60% |
|99.9th percentile latency | index-append |  1861           |   1860.47        |   -0.52277 |     ms |   -0.03% |
|99.99th percentile latency | index-append |  2799.13        |   2337.49        | -461.639   |     ms |  -16.49% |
|99th percentile service time | index-append |  1271.33        |   1250.93        |  -20.4042  |     ms |   -1.60% |
|99.9th percentile service time | index-append |  1861           |   1860.47        |   -0.52277 |     ms |   -0.03% |
|99.99th percentile service time | index-append |  2799.13        |   2337.49        | -461.639   |     ms |  -16.49% |

**Comment by dblock** [comment]
Looks innocent enough. I merged it.

**Comment by reta** [comment]
> @luyuncheng mind please creating a manual backport to `2.x`? thank you

Backported

**Comment by luyuncheng** [comment]
> > @luyuncheng mind please creating a manual backport to `2.x`? thank you
> 
> Backported

Thanks !!!

**Pull request merged**
