### PR TITLE
[Remove] Type mapping parameter from document update API

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
With types deprecation, this change removes type mapping API end-points provided for document update API end-point.

relates [1940](https://github.com/opensearch-project/OpenSearch/issues/1940)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
distribution:docker:buildDockerImage failure. 
```
> Task :distribution:docker:buildDockerImage FAILED
Exec output and error:
| Output for docker:Sending build context to Docker daemon  223.8MB

| Step 1/27 : FROM centos:8 AS builder
|  ---> 5d0da3dc9764
| Step 2/27 : RUN set -eux ;     tini_bin="" ;     case "$(arch)" in         aarch64) tini_bin='tini-arm64' ;;         x86_64)  tini_bin='tini-amd64' ;;         *) echo >&2 ; echo >&2 "Unsupported architecture $(arch)" ; echo >&2 ; exit 1 ;;     esac ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin} ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin}.sha256sum ;     sha256sum -c ${tini_bin}.sha256sum ;     rm ${tini_bin}.sha256sum ;     mv ${tini_bin} /tini ;     chmod +x /tini
|  ---> Running in 9835ec6dddae
| [91m+ tini_bin=
| + case "$(arch)" in
| [0m[91m++ arch
| [0m[91m+ tini_bin=tini-amd64
| + curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64
| [0m[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|    [0m[91m                              Dload  Upload   Total   S[0m[91mpent    Left  Speed
```

**Comment by dreamer-89** [comment]
start gradle check

**Comment by dreamer-89** [comment]
Another flaky test failure
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.MinimumMasterNodesIT.testTwoNodesNoMasterBlock" -Dtests.seed=7364F0CAD67E19B5 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=el-CY -Dtests.timezone=Asia/Katmandu -Druntime.java=17

org.opensearch.cluster.MinimumMasterNodesIT > testTwoNodesNoMasterBlock FAILED
    java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([7364F0CAD67E19B5:BF31DBCC73D60CD8]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:985)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:924)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:913)
        at org.opensearch.cluster.MinimumMasterNodesIT.testTwoNodesNoMasterBlock(MinimumMasterNodesIT.java:223)

```

**Comment by dreamer-89** [comment]
start gradle check

**Comment by dreamer-89** [comment]
Again failed due to build docker image test

```
**> Task :distribution:docker:buildDockerImage FAILED
Exec output and error:
| Output for docker:Sending build context to Docker daemon  223.9MB

| Step 1/27 : FROM centos:8 AS builder
|  ---> 5d0da3dc9764
| Step 2/27 : RUN set -eux ;     tini_bin="" ;     case "$(arch)" in         aarch64) tini_bin='tini-arm64' ;;         x86_64)  tini_bin='tini-amd64' ;;         *) echo >&2 ; echo >&2 "Unsupported architecture $(arch)" ; echo >&2 ; exit 1 ;;     esac ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin} ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin}.sha256sum ;     sha256sum -c ${tini_bin}.sha256sum ;     rm ${tini_bin}.sha256sum ;     mv ${tini_bin} /tini ;     chmod +x /tini
|  ---> Running in ffd70daea2e5
| [91m+ tini_bin=
| + case "$(arch)" in
| [0m[91m++ arch
| [0m[91m+ tini_bin=tini-amd64
| + curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64
**
```

**Comment by dreamer-89** [comment]
start gradle check

**Review by nknize — APPROVED** [review]
LGTM. Thx!

**Pull request merged**
