### PR TITLE
[Forwardport] Move 2.x version to 2.13.0 (#12227)

### PR DESCRIPTION
**Pull request by reta**
### Description
Move 2.x version to 2.13.0

### Related Issues
Part of 2.12.0 release process

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kotwanikunal** [comment]
Ahh. Thanks @reta!

**Comment by dblock** [comment]
Without looking, we have (had?) version increment automation, what happened there?

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [b6353a4](https://github.com/opensearch-project/OpenSearch/commit/b6353a4d730bd3fc8988cd8516f0d289164bef57): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/33516/)

Awaiting backport of https://github.com/opensearch-project/OpenSearch/pull/11626

**Comment by reta** [comment]
Merging with the failed check while awaiting for awaiting backport of https://github.com/opensearch-project/OpenSearch/pull/11626

**Comment by reta** [comment]
> ❌ Gradle check result for [b6353a4](https://github.com/opensearch-project/OpenSearch/commit/b6353a4d730bd3fc8988cd8516f0d289164bef57): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/33518/)

Awaiting backport of https://github.com/opensearch-project/OpenSearch/pull/11626

**Pull request merged**
