### PR TITLE
[Backport][1.x] Add version 1.2.1

### PR DESCRIPTION
**Pull request by dblock**
### Description

Backport of https://github.com/opensearch-project/OpenSearch/pull/1700

 ### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nknize — COMMENTED** [review]
What about upgrading [precommit.yml](https://github.com/opensearch-project/OpenSearch/blob/1.x/.github/workflows/precommit.yml) from java 11 to 14 for consistency?

**Comment by dblock** [comment]
> What about upgrading [precommit.yml](https://github.com/opensearch-project/OpenSearch/blob/1.x/.github/workflows/precommit.yml) from java 11 to 14 for consistency?

we have upgraded to use Java 11 on 1.x

**Comment by nknize** [comment]
> The precommit check was disabled in Jenkins CI, so I backported it to 1.2 in order to get it back instead of re-enabling it in Jenkins.

:+1: that makes sense. I didn't realize it was disabled in jenkins.

**Review by nknize — APPROVED** [review]
LGTM

**Pull request merged**
