### PR TITLE
Downgrade to JDK 11.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@dblock.org>

### Description

We have 4 issues with attempting to upgrade JDK to 17 in 1.3.0 as part of https://github.com/opensearch-project/opensearch-plugins/issues/64.

- https://github.com/opensearch-project/security/issues/1653
- https://github.com/opensearch-project/OpenSearch/issues/2298
- https://github.com/opensearch-project/OpenSearch/issues/2299
- https://github.com/opensearch-project/performance-analyzer/issues/144

This downgrades 1.x to JDK 11.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock I will take a look why version is not accepted

**Comment by dblock** [comment]
> @dblock I will take a look why version is not accepted (I think it is expected as x.y.z+n, but there are 4 components now)

For now I dropped .1 in the PR.

**Comment by reta** [comment]
> > @dblock I will take a look why version is not accepted (I think it is expected as x.y.z+n, but there are 4 components now)
> 
> For now I dropped .1 in the PR.

Opened https://github.com/opensearch-project/OpenSearch/pull/2301 to your branch

**Comment by dblock** [comment]
start gradle check

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
> 

```
[91mErrors during downloading metadata for repository 'appstream':
|   - Curl error (28): Timeout was reached for http://vault.centos.org/centos/8/AppStream/x86_64/os/repodata/repomd.xml [Connection timed out after 30000 milliseconds]
|   - Curl error (28): Timeout was reached for http://vault.centos.org/centos/8/AppStream/x86_64/os/repodata/repomd.xml [Connection timed out after 30001 millisecond
```
:(

**Comment by dblock** [comment]
start gradle check

**Review by andrross — APPROVED** [review]

**Pull request merged**
