### PR TITLE
Bump JNA from 5.5 to 5.13

### PR DESCRIPTION
**Pull request by austintlee**
### Description
JNA version of 5.5 is still used causing some issues running integTest on Mac M1/2.  JNA 5.7 introduced support for Mac aarch64.  I see that we are already using JNA 5.13 in 'server'.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@austintlee could you please fix DCO check? thank you

**Comment by austintlee** [comment]
@reta it's a Github settings issue.  I think it's because my primary email does not match what's in my signature.

``
Commit sha: [1b6d88d](https://github.com/opensearch-project/OpenSearch/pull/9963/commits/1b6d88df30968a65be09eafe16c62670bf02ec3d), Author: Austin Lee, Committer: GitHub; Can not find "Austin Lee [austin.t.lee@gmail.com](mailto:austin.t.lee@gmail.com)", in ["Austin Lee [austin@aryn.ai](mailto:austin@aryn.ai)", "Austin Lee [austin@aryn.ai](mailto:austin@aryn.ai)", "Austin Lee [austin@aryn.ai](mailto:austin@aryn.ai)", "Austin Lee [austin@aryn.ai](mailto:austin@aryn.ai)"].
``

I switched my primary email, but I think we can override this check since I do have a proper DCO in every commit?  Or can you force it to re-run the check?  I don't know for certain exactly how Github is picking up that old email (I did use it for my first few contributions).

**Comment by reta** [comment]
> I switched my primary email, but I think we can override this check since I do have a proper DCO in every commit? Or can you force it to re-run the check?

We could override DCO check when the only option, but you could amend the last commit and do force push to fix the issue.

**Comment by austintlee** [comment]
The problem is that that would require me to use an email that I don't want to put in the DCO.  Since I corrected my email in my Github settings, do you think we can rerun the DCO check?

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@austintlee sadly needs manual backport to `2.x`

**Comment by austintlee** [comment]
I'm on it!

**Pull request merged**
