### PR TITLE
Update to Gradle 8.6

### PR DESCRIPTION
**Pull request by reta**
### Description
Update to Gradle 8.6 (https://github.com/gradle/gradle/releases/tag/v8.6.0)

### Related Issues
N/A

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
> ❌ Gradle check result for [510583d](https://github.com/opensearch-project/OpenSearch/commit/510583d5efa4ad0057c3e8abc252bd3af368badc): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/31742/)

Needs https://github.com/opensearch-project/OpenSearch/pull/11678 to be backported

**Comment by reta** [comment]
> ❌ Gradle check result for [ddad529](https://github.com/opensearch-project/OpenSearch/commit/ddad529b1607a6511e23df6770666ffafd5262c9): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/31769/)

https://github.com/opensearch-project/OpenSearch/issues/11770

**Review by deshsidd — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [d69b0ef](https://github.com/opensearch-project/OpenSearch/commit/d69b0ef538accda9f1c0ed2cd10fba1327a9da72): [null](https://build.ci.opensearch.org/job/gradle-check/32512/)

https://github.com/opensearch-project/OpenSearch/issues/9191

**Comment by reta** [comment]
> ❌ Gradle check result for [e9dce0e](https://github.com/opensearch-project/OpenSearch/commit/e9dce0e037318428355910ec1556dc7dc1119277): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/32987/)

https://github.com/opensearch-project/OpenSearch/issues/10006

**Comment by reta** [comment]
> ❌ Gradle check result for [e9dce0e](https://github.com/opensearch-project/OpenSearch/commit/e9dce0e037318428355910ec1556dc7dc1119277): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/32987/)

https://github.com/opensearch-project/OpenSearch/issues/12046

**Review by kotwanikunal — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [5fc3243](https://github.com/opensearch-project/OpenSearch/commit/5fc3243e6151ba83f0de0b53f6dc4cbc0a76e56e): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/33159/)

https://github.com/opensearch-project/OpenSearch/issues/9191

**Pull request merged**
