### PR TITLE
Add 1.3.0 release notes in main

### PR DESCRIPTION
**Pull request by dreamer-89**
Signed-off-by: Suraj Singh <surajrider@gmail.com>

### Description
Adds 1.3 release notes starting from [1.x version bump to 1.3](https://github.com/opensearch-project/OpenSearch/commit/ce7b091da6ae50bbc3c015a78b7611923475386c). 

### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/2257
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I understand these were generated with a tool, but they are unreadable because of the garbage in the commit messages. Should we do a human pass on those first? @stockholmux @elfisher ?

**Comment by stockholmux** [comment]
Yeah, @dblock, these don't look right and are a major departure from our previous format.

**Comment by dreamer-89** [comment]
>Yeah, @dblock, these don't look right and are a major departure from our previous format.

Thanks @stockholmux for the review. Can you please share previous format you are referring here ? I will try to follow the same.

**Comment by dreamer-89** [comment]
> > > Yeah, @dblock, these don't look right and are a major departure from our previous format.
> > 
> > 
> > Thanks @stockholmux for the review. Can you please share previous format you are referring here ? I will try to follow the same.
> 
> Here are the release notes @dreamer-89 : https://github.com/opensearch-project/OpenSearch/tree/main/release-notes

Thank you @owaiskazi19 for sharing the sample. 
The [1.3.0 generated release notes](https://github.com/dreamer-89/OpenSearch/blob/1.3_release_notes/release-notes/opensearch.release-notes-1.3.0.md), look similar to one you shared. I notice there is a solid line something like below from dependabot commits.

---


I can remove this line from dependabot commits. @stockholmux : Can you please share your inputs around it ?

**Comment by stockholmux** [comment]
So when I compare the [release notes of 1.2.0](https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-1.2.0.md) to these, I'm seeing a lot more that looks like it's generated by a machine - for example, a lot of 'bump' generated by dependabot and the autogenerated email accounts (e.g. 49699333+dependabot[bot]@users.noreply.github.com)

**Comment by dreamer-89** [comment]
> So when I compare the [release notes of 1.2.0](https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-1.2.0.md) to these, I'm seeing a lot more that looks like it's generated by a machine - for example, a lot of 'bump' generated by dependabot and the autogenerated email accounts (e.g. 49699333+dependabot[bot]@users.noreply.github.com)

Thanks @stockholmux for the promot response. 

There was a recent change (Feb 17th) where we added dependabot to update the new version of dependencies and currently runs on weekly basis. If you feel these commits, doesn't add value in release notes, I can remove these.

**Comment by stockholmux** [comment]
@dreamer-89 I think that would go a long way. @dblock Thoguhts?

**Comment by dblock** [comment]
> @dreamer-89 I think that would go a long way. @dblock Thoughts?

Definitely. I would hand-edit the notes the be useful to humans as much as needed.

I also have https://github.com/opensearch-project/OpenSearch/issues/1868 opened that could be a solution to this problem moving forward.

**Comment by dreamer-89** [comment]
@stockholmux @dblock : I updated the release notes. Kindly review

https://github.com/dreamer-89/OpenSearch/blob/1.3_release_notes/release-notes/opensearch.release-notes-1.3.0.md

**Comment by dreamer-89** [comment]
```
REPRODUCE WITH: ./gradlew ':qa:remote-clusters:integTest' --tests "org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks" -Dtests.seed=1C3D54BD19E7BE49 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sv-SE -Dtests.timezone=America/Indiana/Marengo -Druntime.java=17

org.opensearch.cluster.remote.test.RemoteClustersIT > testHAProxyModeConnectionWorks FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([1C3D54BD19E7BE49:1B4B81762261C814]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks(RemoteClustersIT.java:125)
```

**Comment by dreamer-89** [comment]
start gradle check

**Review by mch2 — APPROVED** [review]

**Pull request merged**
