### PR TITLE
Removing changelog entry for the released fix

### PR DESCRIPTION
**Pull request by sgup432**
### Description
Removing the change log entry as this fix is being released in 2.14.
See https://github.com/opensearch-project/OpenSearch/pull/13591

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sgup432** [comment]
@andrross Can you check this one?

**Comment by andrross** [comment]
@sgup432 The release notes file should be the same across branches as well. I think this entry needs to be added there.

**Comment by andrross** [comment]
@sgup432 Friendly ping :) Let's get this fixed before the next release.

**Comment by sgup432** [comment]
@andrross Looking into this. Somehow missed this.

**Comment by sgup432** [comment]
Ok I so need to do below:
1. Need to remove [this](https://github.com/opensearch-project/OpenSearch/blob/2.x/CHANGELOG.md?plain=1#L34) from 2.x branch CHANGELOG as well.
2. Update release note for 2.x
3. Update release note for main branch as well here.

**Comment by sgup432** [comment]
@andrross I have updated main branch changelog and release notes in this PR.
And fixed for 2.x here - https://github.com/opensearch-project/OpenSearch/pull/13863

**Comment by dblock** [comment]
> And fixed for 2.x here - #13863

We can automatically backport from main, FYI after this is merged.

**Review by andrross — APPROVED** [review]

**Pull request merged**
