### PR TITLE
Guice resection

### PR DESCRIPTION
**Pull request by nknize**
Surgically removes malignant Guice code.

o.o.common.inject is a fork of Guice 2.0 from many moons ago. It is used to create type safe instances at runtime w/o the need for Factories. Most of the functionality has been removed prior to forking OpenSearch. This housecleaning commit removes stale code that is either not called or unnecessarily called through the Injector logic path.

relates #5910 
relates #8110

### CODE REVIEW

**Comment by nknize** [comment]
Ah, Jenkins servung up another healthy bowl. 
35465_ldementhon_d42d7885-0b48-4e0c-b3b4-4a048f989c3e

**Comment by reta** [comment]
@nknize nice cleanup, we need changelog for it please, please notice this change is breaking (I've added label to the pull request): the `Binder` leaks through `Plugin::createGuiceModules`, we should acknowledge that.

**Comment by nknize** [comment]
> the `Binder` leaks through `Plugin::createGuiceModules`.

hideous... that was removed from Elasticsearch a long long time ago. I forgot that it was only merged into 8.0 and we didn't inherit when we forked 7.10.2.

>  ...we should acknowledge that.

+1. I'm going to acknowledge it a step further by removing that trappy method from `Plugin` altogether. Bless any plugin that customized this guice injection framework since it's been walking the green mile for years.

**Comment by dblock** [comment]
> Also, please notice this change is breaking (I've added label to the pull request): the `Binder` leaks through `Plugin::createGuiceModules`, we should acknowledge that.

Given conversations such as https://github.com/opensearch-project/OpenSearch/pull/5902#issuecomment-1769325330, what do you think about introducing an UPGRADING.md for developers? e.g. https://github.com/opensearch-project/opensearch-py/blob/main/UPGRADING.md.

**Comment by nknize** [comment]
> ...what do you think about introducing an UPGRADING.md that would include both dev and end-user breaking changes?

No objection so long as it doesn't add "one more thing" to maintainers todo list. The learning curve to contribute is already quite high.

**Comment by ticheng-aws** [comment]
Hi @nknize, the PR is stalled. Do we have any updates?

**Comment by scrawfor99** [comment]
@opensearch-project/opensearch-core do we have plans to continue this work? It does not seem like this PR is going to be moved forward by Nick at the moment, so if we want to move forward someone else may need to pick up where this was left off. Otherwise we should close this. 

What is the path forward?

**Comment by reta** [comment]
> What is the path forward?

I would give the author the time to finish it (or let it be closed and reopened later). Nick seems to have much better context why the things have been done this way and what the right way is.

**Comment by scrawfor99** [comment]
Hi @reta, thanks for following up. Is there a timeframe OpenSearch's maintainers have decided is reasonable for closing stalled PRs? I know there is the auto comment bot, but I think that was turned off; is it 6 months of inactivity like maintainership or just up to discretion?

**Comment by reta** [comment]
> I know there is the auto comment bot, but I think that was turned off;

I think it is on actually

**Comment by nknize** [comment]
won't be actively working unless needed... too much divergence and code fragmentation at this point. Let me know if anyone is interested in burning this fat in the future.

**Pull request closed without merging**
