### PR TITLE
Sample PR to verifying test coverage report generation

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-off-by: Rishikesh Pasham <rishireddy1159@gmail.com>

### Description
Verify Test Coverage Report Generation
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Rishikesh1159** [comment]
start gradle check

**Comment by Rishikesh1159** [comment]
start gradle check

**Comment by peternied** [comment]
@Rishikesh1159 Checkout `Reports 1037` - https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1037_reports.zip it has a codeCoverageReport.xml inside it

**Comment by dblock** [comment]
@Rishikesh1159 you need to commit/amend with `-s` for DCO check, please

**Pull request closed without merging**
