### PR TITLE
Updates jackson and snakeyml dependencies

### PR DESCRIPTION
**Pull request by owaiskazi19**
Signed-off-by: Owais Kazi <owaiskazi19@gmail.com>

### Description
Updated jackson to `2.13.4` from `2.13.3`
Updated snakeyml to `1.32` from `1.31`

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by owaiskazi19** [comment]
Raised backport PR: https://github.com/opensearch-project/OpenSearch/pull/4563.

**Comment by lezzago** [comment]
@owaiskazi19 Can we backport it to 1.3 (as it it still supported) and the older 2.x versions? This helps plugins to not have to update the dependencies for those older versions

**Comment by owaiskazi19** [comment]
> @owaiskazi19 Can we backport it to 1.3 (as it it still supported) and the older 2.x versions? This helps plugins to not have to update the dependencies for those older versions

@reta @dblock WDYT?

**Comment by reta** [comment]
@owaiskazi19 `snakeyml` definitely would be OK, Jackson might need some considerations (fe we would need to update `opensearch-java` and other plugins since versions could go out of sync).

**Comment by lezzago** [comment]
@reta @dblock Do you think it would be better to create a separate PR just for snakeyml for OS 2.3, 2.2, 2.1, 2.0, and 1.3?

**Comment by reta** [comment]
@lezzago I would suggest to update Jackson + snakeyml across 2.3 / 2.2 / 2.1 / 2.0 lines but only snakeyaml for `1.3`, @dblock wdyt?

**Comment by lezzago** [comment]
@reta @dblock @owaiskazi19 Can we get this resolved before the 1.3.6 patch release?

**Comment by dblock** [comment]
+1 what @reta says

**Comment by owaiskazi19** [comment]
> @lezzago I would suggest to update Jackson + snakeyml across 2.3 / 2.2 / 2.1 / 2.0 lines but only snakeyaml for `1.3`, @dblock wdyt?

@lezzago @reta I will raise the backport PRs for the above.

**Comment by kotwanikunal** [comment]
@reta / @dblock / @owaiskazi19 We have already merged in the changes for 1.x and 1.3.x - #4600 #4599

**Comment by owaiskazi19** [comment]
> @reta / @dblock / @owaiskazi19 We have already merged in the changes for 1.x and 1.3.x - #4600 #4599

Thanks @kotwanikunal! I will take care of 2.3/2.2/2.1 and 2.0 then.

**Comment by owaiskazi19** [comment]
@lezzago backport PRs are up.

**Comment by reta** [comment]
@owaiskazi19 thanks for the update, I think we should align `opensearch-java` client [1] and possibly the plugins

[1] https://github.com/opensearch-project/opensearch-java/blob/main/java-client/build.gradle.kts#L135

**Comment by harshavamsi** [comment]
> @owaiskazi19 thanks for the update, I think we should align `opensearch-java` client [1] and possibly the plugins
> 
> [1] https://github.com/opensearch-project/opensearch-java/blob/main/java-client/build.gradle.kts#L135

Opened https://github.com/opensearch-project/opensearch-java/issues/227. cc @VachaShah

**Comment by owaiskazi19** [comment]
@reta started a campaign for plugin and clients repo [here](https://github.com/opensearch-project/opensearch-plugins/issues/168). Let me know if I missed any repo. Thanks.

**Comment by owaiskazi19** [comment]
> @owaiskazi19 thanks for the update, I think we should align `opensearch-java` client [1] and possibly the plugins
> 
> [1] https://github.com/opensearch-project/opensearch-java/blob/main/java-client/build.gradle.kts#L135

@reta started a campaign for plugin and clients repo [here](https://github.com/opensearch-project/opensearch-plugins/issues/168). Let me know if I missed any repo. Thanks.

**Pull request merged**
