### PR TITLE
Fixing various javadocs

### PR DESCRIPTION
**Pull request by ker2x**
Greetings !
I'm in the process of completing javadoc of OpenSearch.
I have other javadoc fix in progress but not yet ready.

I tried my best following the contributing rule. i hope it's ok.
I didn't create a new issue as there is this one already https://github.com/opensearch-project/OpenSearch/issues/221

Should i make one large pull request or many small one ?

Thank you,

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ker2x** [comment]
The failure doesn't appear to be related to my commit. (unless i'm misunderstanding the error)

**Comment by kotwanikunal** [comment]
> * https://build.ci.opensearch.org/job/gradle-check/24643/

#9191

**Comment by kotwanikunal** [comment]
> I fixed the previous error (my bad) But this new failure doesn't appear to be related to my commit. (unless i'm misunderstanding the error) Any tips appreciated.

@ker2x Thanks for contributing :) 
You are right - the error is unrelated to your change. It is a flaky test and I have linked the issue.
Restarting the workflows.

**Comment by kotwanikunal** [comment]
#9776 

> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/24709/
> * **CommitID:** [c79edc8](https://github.com/opensearch-project/OpenSearch/commit/c79edc88497cc6e47af80225358e518147181a2c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

**Review by reta — APPROVED** [review]

**Comment by ker2x** [comment]
i have much more javadoc to commit, should i wait ?

**Comment by msfroh** [comment]
> i have much more javadoc to commit, should i wait ?

Let's merge this one first.

Gradle checks are failing due to flaky tests. I've restarted the check run (see https://github.com/opensearch-project/OpenSearch/actions/runs/6113402537/job/16644851983?pr=9817), but I suspect that you may need to merge from main again to pick up the fixes for those tests. Sorry about that :(

Thank you so much for these fixes, @ker2x! These new Javadocs are so much better.

**Comment by ker2x** [comment]
> Thank you so much for these fixes, @ker2x! These new Javadocs are so much better.

Merged. i didn't make the mistake to commit on my main this time so i didn't mistakenly push more unrefined javadoc this time :) Let's see how it goes.

there are some javadoc with some "todo fix before commit" in this PR. I'll fix it in next PR (i shouldn't have disabled the "check for TODO" in inteliJ ^^)

thanks for the kind words. i'm having fun doing this. (i'm an Elastic database administrator switching to opensearch. i'm doing this for learning purpose)

**Pull request merged**
