### PR TITLE
[1.x] Fix snapshot deletion task getting stuck in the event of exceptions (#629)

### PR DESCRIPTION
**Pull request by AmiStrn**
backport of #629 

Changes the behavior of the recursive deletion function `executeOneStaleIndexDelete()` stop
condition to be when the queue of `staleIndicesToDelete` is empty -- also in the error flow.
Otherwise the GroupedActionListener never responds and in the event of a few exceptions the
deletion task gets stuck.
Alters the test case to fail to delete in bulk many snapshots at the first attempt, and then
the next successful deletion also takes care of the previously failed attempt as the test
originally intended.
SNAPSHOT threadpool is at most 5. So in the event we get more than 5 exceptions there are no
more threads to handle the deletion task and there is still one more snapshot to delete in the
queue. Thus, in the test I made the number of extra snapshots be one more than the max in the
SNAPSHOT threadpool.

### CODE REVIEW

**Comment by AmiStrn** [comment]
@nknize backport to 1.0 ☝️  :))))

**Comment by AmiStrn** [comment]
start gradle check

**Review by nknize — APPROVED** [review]
LGTM

**Comment by AmiStrn** [comment]
@nknize is it possible to merge this yet? or do we want to give it some more time?

**Comment by nknize** [comment]
Merged. Sorry for the delay on that @AmiStrn. It didn't need to stall that long.

**Comment by AmiStrn** [comment]
All good @nknize :) thanks for the merge!

**Pull request merged**
