### PR TITLE
[Upgrade] Lucene-9.3.0-snapshot-b7231bb

### PR DESCRIPTION
**Pull request by nknize**
Upgrades to latest snapshot of lucene 9.3

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by kotwanikunal** [comment]
```
uite: Test class org.opensearch.cluster.remote.test.RemoteClustersIT
  1> [2022-06-08T12:07:48,067][INFO ][o.o.c.r.t.RemoteClustersIT] [testHAProxyModeConnectionWorks] before test
  1> [2022-06-08T12:07:48,176][INFO ][o.o.c.r.t.RemoteClustersIT] [testHAProxyModeConnectionWorks] initializing REST clients against [http://localhost:49186]
  1> [2022-06-08T12:07:53,126][INFO ][o.o.c.r.t.RemoteClustersIT] [testHAProxyModeConnectionWorks] Configuring remote cluster [haproxy:9600]
  1> [2022-06-08T12:07:53,534][INFO ][o.o.c.r.t.RemoteClustersIT] [testHAProxyModeConnectionWorks] Connection info: RemoteConnectionInfo{modeInfo=ProxyModeInfo{address='haproxy:9600', serverName='', maxSocketConnections=18, numSocketsConnected=0}, initialConnectionTimeoutString='30s', clusterAlias='haproxynosn', skipUnavailable=false}
  1> [2022-06-08T12:07:54,680][INFO ][o.o.c.r.t.RemoteClustersIT] [testHAProxyModeConnectionWorks] after test
  2> REPRODUCE WITH: ./gradlew ':qa:remote-clusters:integTest' --tests "org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks" -Dtests.seed=AB129368B6E3EBA0 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-LB -Dtests.timezone=America/Louisville -Druntime.java=17
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([AB129368B6E3EBA0:AC6446A38D659DFD]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks(RemoteClustersIT.java:125)
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/qa/remote-clusters/build/testrun/integTest/temp/org.opensearch.cluster.remote.test.RemoteClustersIT_AB129368B6E3EBA0-004
  2> NOTE: test params are: codec=Asserting(Lucene92): {}, docValues:{}, maxPointsInLeafNode=1279, maxMBSortInHeap=6.958492600428087, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ar-LB, timezone=America/Louisville
  2> NOTE: Linux 5.13.0-1014-aws amd64/Eclipse Adoptium 17.0.3 (64-bit)/cpus=72,threads=1,free=451428520,total=536870912
  2> NOTE: All tests run in this JVM: [RemoteClustersIT]
```

#1703

**Comment by kotwanikunal** [comment]
start gradle check

**Review by nknize — COMMENTED** [review]
The new Merge on Refresh as default is causing an issue w/ TieredMergePolicy in `LuceneTests.testWrapLiveDocsNotExposeAbortedDocuments`.  Will get back and add a threshold to prevent merges for this test case.

**Comment by reta** [comment]
> The new Merge on Refresh as default is causing an issue w/ TieredMergePolicy in `LuceneTests.testWrapLiveDocsNotExposeAbortedDocuments`. Will get back and add a threshold to prevent merges for this test case.

@nknize  I was about to create an issue about that, was checking https://github.com/apache/lucene/pull/921/files, let me take care of this change.

**Comment by reta** [comment]
Should be fixed https://github.com/nknize/OpenSearch/pull/4/files

**Pull request merged**
