### PR TITLE
Remove the oss string from OpenSearch distributions

### LINKED ISSUE #567: Remove the OSS string from OpenSearch distributions
**Description**
 
Current distributions of OpenSearch contains the string `oss` which is a remnant of the distribution flavors from Elasticsearch. Previously, we have removed the flavor support (#104) along with the `default` flavor.

We should remove the `oss` tag from all the distributions to avoid any ambiguity.

### PR DESCRIPTION
**Pull request by adnapibar**
### Description
This commit removes the **oss** string which is a remnant of the predecessor distribution flavors. As OpenSearch has no flavors for distributions, we are removing this tag from all the distribution names.

For example, currently the Linux tar artifact has name `opensearch-oss-1.0.0-SNAPSHOT-linux-x86_64.tar.gz`. With this PR, the artifact will be named `opensearch-1.0.0-SNAPSHOT-linux-x86_64.tar.gz`
 
### Issues Resolved
Resolves #567 
 
### Check List
- [x] All tests pass
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Rabi Panda <adnapibar@gmail.com>

### CODE REVIEW

**Review by dblock — COMMENTED** [review]
I think we can also get rid of whatever supports `run.distribution` as well, specifically https://github.com/opensearch-project/OpenSearch/blob/main/gradle/run.gradle#L36 and its dependencies.

**Review by dblock — APPROVED** [review]

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
> I think we can also get rid of whatever supports `run.distribution` as well, to make things simpler, specifically https://github.com/opensearch-project/OpenSearch/blob/main/gradle/run.gradle#L36 and everything that depends on it.

Yes I agree - the [TestDistribution.java ](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestDistribution.java) is used for running test clusters using the integ-test-zip or the default archive distribution. We can clean that up in a separate PR.

**Review by dblock — APPROVED** [review]
Good work.

**Pull request merged**
