### PR TITLE
[Version] Add 1.2 for BWC testing

### PR DESCRIPTION
**Pull request by nknize**
Add version 1.2 to .ci/bwcVersions and Version.java

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Review by adnapibar — APPROVED** [review]
Thanks 👍

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
Random test is reproducible 
`./gradlew ':server:test' --tests "org.opensearch.index.translog.TranslogDeletionPolicyTests.testWithRetentionLease" -Dtests.seed=EE4F002486BE0031 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=fr-FR -Dtests.timezone=Europe/Oslo -Druntime.java=15`

**Comment by adnapibar** [comment]
start gradle check

**Pull request merged**
