### PR TITLE
Adding release notes for 1.0.0

### LINKED ISSUE #789: Add release notes drafter for OpenSearch
**Is your feature request related to a problem? Please describe.**
Add release notes drafter for OpenSearch which compiles all the commits made into a release.

**Describe the solution you'd like**
Github actions support this via https://github.com/release-drafter/release-drafter.

### PR DESCRIPTION
**Pull request by abbashus**
Signed-off-by: Abbas Hussain <abbas_10690@yahoo.com>

### Description
Adding release notes for OpenSearch 1.0.0 (GA)
This is generated using the tool: https://github.com/ariatemplates/git-release-notes
 
### Issues Resolved
#789 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
For release versions I believe we do not need to have a qualifier, i would prefer to have 1.0.0 instead of 1.0.0-ga.
And as you brought up we can wait for other PRs to be merged into 1.0...

**Comment by CEHENKLE** [comment]
start gradle check

**Comment by abbashus** [comment]
start gradle check

**Comment by tlfeng** [comment]
The test failure in "Log 266":
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.ClusterHealthIT.testHealthOnMasterFailover" -Dtests.seed=5C28067404DD84A9 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=lt-LT -Dtests.timezone=Asia/Almaty -Druntime.java=15

org.opensearch.cluster.ClusterHealthIT > testHealthOnMasterFailover FAILED
    java.util.concurrent.ExecutionException: MasterNotDiscoveredException[NodeClosedException[node closed {node_s0}{ZMcSsUfoSCqq3rrVnWv1XA}{iyf5QSZjRZSqp6_EtnYkqA}{127.0.0.1}{127.0.0.1:45327}{imr}]]; nested: NodeClosedException[node closed {node_s0}{ZMcSsUfoSCqq3rrVnWv1XA}{iyf5QSZjRZSqp6_EtnYkqA}{127.0.0.1}{127.0.0.1:45327}{imr}];
```

The test failure in "Log 275":
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.DateMathIndexExpressionsIntegrationIT.testCreateIndexWithDateMathExpression" -Dtests.seed=E872F82509438444 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=nn-NO -Dtests.timezone=Asia/Bishkek -Druntime.java=15

org.opensearch.indices.DateMathIndexExpressionsIntegrationIT > testCreateIndexWithDateMathExpression FAILED
    [.marvel-2021.06.30/Z2eGPS5kQ0-KTI1u2Myptw] ResourceAlreadyExistsException[index [.marvel-2021.06.30/Z2eGPS5kQ0-KTI1u2Myptw] already exists]
```

Neither can be reproduced in `main` branch. 🤔

**Comment by abbashus** [comment]
@tlfeng Its strange that a text file with no related tests is causing other test failures 🤔

**Comment by tlfeng** [comment]
> @tlfeng Its strange that a text file with no related tests is causing other test failures 🤔

Exactly! 😂 😂 However, since it can't be reproduced by me, it's harder to debug ...

**Comment by abbashus** [comment]
start gradle check

**Comment by abbashus** [comment]
start gradle check

**Review by tlfeng — APPROVED** [review]
Thanks for adding the massive changes in the release note!

**Pull request merged**
