### PR TITLE
Add support for groovy file exclusion from jacoco

### PR DESCRIPTION
**Pull request by kotwanikunal**
### Description
- Adds support for groovy file exclusion from jacoco
- Stems from https://github.com/opensearch-project/OpenSearch/pull/7068#issuecomment-1584893112

### Related Issues
- https://github.com/opensearch-project/OpenSearch/pull/7068#issuecomment-1584893112

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kotwanikunal** [comment]
I am not sure if this is the appropriate solution but feedback is appreciated. 
@reta / @peterzhuamazon / @prudhvigodithi

**Comment by kotwanikunal** [comment]
Looks like it isn't correct after all :) 

```
Could not determine the dependencies of task ':check'.
> Could not create task ':testCodeCoverageReport'.
   > Project#afterEvaluate(Closure) on root project 'OpenSearch' cannot be executed in the current context.
```

**Comment by owaiskazi19** [comment]
@kotwanikunal I think we should not exclude groovy file from code coverage. We should add tests for groovy file similar to [opensearch-build ](https://github.com/opensearch-project/opensearch-build/tree/main/tests/jenkins) does it.

**Comment by reta** [comment]
> @kotwanikunal I think we should not exclude groovy file from code coverage. We should add tests for groovy files similar to [opensearch-build ](https://github.com/opensearch-project/opensearch-build/tree/main/tests/jenkins) does it.

That's also a fair point, let me add one for the `OptionalDependenciesPlugin`

**Comment by kotwanikunal** [comment]
Closing the PR out based on comments above.

**Pull request closed without merging**
