### PR TITLE
Removed unneeded calls of String.format()

### PR DESCRIPTION
**Pull request by dk2k**
Removed unneeded calls of String.format()

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
Looks like a legit failure.

```

* What went wrong:
Execution failed for task ':server:spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/opensearch/index/compositeindex/CompositeIndexValidator.java
          @@ -13,8 +13,6 @@
           import·org.opensearch.index.compositeindex.datacube.startree.StarTreeValidator;
           import·org.opensearch.index.mapper.MapperService;
           
          -import·java.util.Locale;
          -
           /**
           ·*·Validation·for·composite·indices·as·part·of·mappings
           ·*
  Run './gradlew :server:spotlessApply' to fix these violations.
```

**Review by dbwiddis — APPROVED** [review]
Approved pending running spotlessApply to fix what is probably whitespace

**Comment by sandeshkr419** [comment]
```
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 2.17.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-tar/build/distributions/opensearch-min-2.17.0-SNAPSHOT-linux-x64.tar.gz

```

@dk2k I think you probably just need to do a rebase from main and do a force push then, should succeed.

**Comment by dk2k** [comment]
Guys, sorry, rebase didn't go smoothly. I will close this PR and create a new one.
I really think you need to adjust the processes in this repo and make it contributor-friendly. Currently it's a pain in the neck.

**Comment by sandeshkr419** [comment]
@dk2k Yeah, rebasing has been a major pain. Do you have any suggestions that we can look into?

Also, here is the usual process I do to rebasing smoothly:
1. git remote set-url origin   https://github.com/opensearch-project/Opensearch.git
2. git checkout main
3. git pull
4. git checkout <your-dev-branch>
5. git rebase main
6. git remote set-url origin <your-private-repo>
7. git push origin <your-dev-branch>


Probably I can include these steps in development guide itself.

**Comment by dbwiddis** [comment]
> @dk2k Yeah, rebasing has been a major pain. Do you have any suggestions that we can look into?

I'm not dk2k, but on other repos I maintain there is a GitHub setting that enables rebasing from the PR itself. 
Screenshot 2024-10-16 at 4 45 14 PM

It creates this dialog:
Screenshot 2024-10-16 at 4 47 02 PM

**Comment by dbwiddis** [comment]
@dk2k i messed up my first GitHub PR and had to close and resubmit. You're in good company. :)

**Pull request closed without merging**
