### PR TITLE
[Backport 2.0] [Remove] Type from nested fields using new metadata field mapper

### PR DESCRIPTION
**Pull request by nknize**
Backport https://github.com/opensearch-project/OpenSearch/commit/6b641d2fd29b9542b94f419fc083847fa5bdf55b from https://github.com/opensearch-project/OpenSearch/pull/3004

### CODE REVIEW

**Comment by nknize** [comment]
Note: let's not merge until 2.0 RC is built.

**Comment by dreamer-89** [comment]
This is failing on spotless java check task due to one unused import. 
```
Execution failed for task ':server:spotlessJavaCheck'.
> The following files had format violations:
      src/test/java/org/opensearch/indices/IndicesModuleTests.java
          @@ -41,7 +41,6 @@
           import·org.opensearch.index.mapper.Mapper;
           import·org.opensearch.index.mapper.MapperParsingException;
           import·org.opensearch.index.mapper.MetadataFieldMapper;
          -import·org.opensearch.index.mapper.NestedPathFieldMapper;
           import·org.opensearch.index.mapper.RoutingFieldMapper;
           import·org.opensearch.index.mapper.SeqNoFieldMapper;
           import·org.opensearch.index.mapper.SourceFieldMapper;
  Run './gradlew :server:spotlessApply' to fix these violations.
```

**Comment by dreamer-89** [comment]
start gradle check

**Comment by nknize** [comment]
Related to merge conflict:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.indices.IndicesModuleTests.testBuiltinMappers" -Dtests.seed=9AE7B29E887AF323 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-BO -Dtests.timezone=Asia/Hong_Kong -Druntime.java=17

org.opensearch.indices.IndicesModuleTests > testBuiltinMappers FAILED
    java.lang.AssertionError: expected:<10> but was:<11>
        at __randomizedtesting.SeedInfo.seed([9AE7B29E887AF323:287AF3F9128E5A44]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.indices.IndicesModuleTests.testBuiltinMappers(IndicesModuleTests.java:111)
```

I'll fix shortly.

**Review by dblock — APPROVED** [review]

**Pull request merged**
