### PR TITLE
Add test case for OptionalDependenciesPlugin (com.netflix.nebula:gradle-extra-configurations-plugin plugin migration)

### PR DESCRIPTION
**Pull request by reta**
### Description
Add test case for OptionalDependenciesPlugin (com.netflix.nebula:gradle-extra-configurations-plugin plugin migration)

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kotwanikunal — APPROVED** [review]

**Comment by kotwanikunal** [comment]
Thanks @reta!

**Comment by gaiksaya** [comment]
Hi @reta ,

Just curious, Any particular reason why we added the test cases for 
`buildSrc/src/main/groovy/org/opensearch/gradle/plugin/OptionalDependenciesPlugin.groovy` under 
`buildSrc/src/test/java/org/opensearch/gradle/plugin/OptionalDependenciesPluginTests.java`?

Also for my understanding does the codecoverage tool recognize what we are testing? (from [this](https://github.com/opensearch-project/OpenSearch/pull/7995#issuecomment-1585093686) comment looks like it showed codecov as decreased)
Thanks!

**Comment by reta** [comment]
Thanks @gaiksaya !

> Just curious, Any particular reason why we added the test cases for
buildSrc/src/main/groovy/org/opensearch/gradle/plugin/OptionalDependenciesPlugin.groovy under
buildSrc/src/test/java/org/opensearch/gradle/plugin/OptionalDependenciesPluginTests.java?

Yes, so the plugin is written in Groovy (OptionalDependenciesPlugin.groovy) so it is under `src/main/groovy` by convention, the `OptionalDependenciesPluginTests` is written in Java,  so it is under `src/test/java` by convention, does it help or you were asking about different thing? 

> Gradle has some examples here https://docs.gradle.org/current/userguide/test_kit.html that uses spockframework (bot fancy and easy to use). Wondering if can explore that in future?

I think in general there is no constraints on test framework to use, as far as it brings tangible benefits. Our tests for this module are currently written in Java, as all other tests for OpenSearch core.

> Also for my understanding does the codecoverage tool recognize what we are testing? (from https://github.com/opensearch-project/OpenSearch/pull/7995#issuecomment-1585093686 comment looks like it showed codecov as decreased)

That is a good question, it believe it does not recognize what we are testing in this particular case.

**Comment by gaiksaya** [comment]
Thanks! 
>does it help or you were asking about different thing?

It helps. Was just curious why we didn't add groovy tests under `buildSrc/src/test/groovy` for those components. Looks like anything works and there are no constraints?

**Comment by reta** [comment]
> It helps. Was just curious why we didn't add groovy tests under `buildSrc/src/test/groovy` for those components. Looks like anything works and there are no constraints?

What are the benefits? And what is the cost to maintain the new framework? How is familiar with it? Groovy is on severe decline, the only reason I've added the Groovy plugin is to preserve the original license and source code.

**Comment by gaiksaya** [comment]
Looks like the above framework is already being used in OpenSearch https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/AbstractGradleFuncTest.groovy
https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch%20AbstractGradleFuncTest&type=code

**Comment by reta** [comment]
Indeed, thanks! Wanna give it a try by refactoring the `OptionalDependenciesPluginTests` to use Spock? No objections from my side, if you are curious to do that :)

**Comment by prudhvigodithi** [comment]
Here is the gradle [functional unit tests](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java) example from `opensearch.pluginzip` plugin. 

Also for CodeCov coverage the [buildSrc](https://app.codecov.io/gh/opensearch-project/OpenSearch/tree/main/buildSrc%2Fsrc%2Fmain) folder is included, assume its coming from [code-coverage.gradle](https://github.com/opensearch-project/OpenSearch/blob/main/gradle/code-coverage.gradle), @reta am I right here?
@bbarani @peterzhuamazon

**Comment by reta** [comment]
> Also for CodeCov coverage the [buildSrc](https://app.codecov.io/gh/opensearch-project/OpenSearch/tree/main/buildSrc%2Fsrc%2Fmain) folder is included, assume its coming from [code-coverage.gradle](https://github.com/opensearch-project/OpenSearch/blob/main/gradle/code-coverage.gradle), @reta am I right here?

The `pluginzip/Publish` is Java, not Groovy, right?

**Pull request merged**
