### PR TITLE
Expand SearchPlugin javadocs.

### LINKED ISSUE #1905: Improve javadoc on SortSpec to inform use of preferredName as a unique key
PR #1856 enhanced the [SearchPlugin](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/SearchPlugin.java) to enable pluggable SortBuilders. The mechanism uses a new `SortSpec` to define the specification of the builder and parser and exposes through the named registry. This named registry keys the sort specification off the `preferredName` which is required to be unique. Contributors may not be aware of other sort builders that share the same name. 

This issue is to improve the javadocs to provide better documentation of this requirement.

relates #221

### PR DESCRIPTION
**Pull request by mattweber**
### Description
Add and clarify some search plugin point documentation.
 
### Issues Resolved
#1905 
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nknize — APPROVED** [review]
Nice! Thx @mattweber

**Review by dblock — APPROVED** [review]

**Comment by nknize** [comment]
Let's backport this as well.

**Comment by mattweber** [comment]
@nknize backport PR #1923

**Pull request merged**
