### PR TITLE
Update Developers guide

### PR DESCRIPTION
**Pull request by ace03uec**
### Description
- Fixes git clone link
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CEHENKLE** [comment]
Hey Manivannan!

Thank you -- good catch!  Can you sign your commit so it passes DCO, and we'll merge?

Thanks again.

**Comment by ace03uec** [comment]
@CEHENKLE : Ah, Seem to have missed it. Will fix it and push again.

**Comment by CEHENKLE** [comment]
start gradle check

**Review by CEHENKLE — APPROVED** [review]
Ship it!

**Pull request merged**
