### PR TITLE
Upgrade lucene version

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
Upgrades the lucene snapshot to `9.5.0-snapshot-d5cef1c`. Post 2.4.1 release, the next patch version 2.4.2 needed 9.4.2 lucene version which is not present in existing lucene snapshot. 

Related: https://github.com/opensearch-project/OpenSearch/pull/5560

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dreamer-89 thanks for the update,  could you please update Lucene versions as well [1] for 2.4.1 and 2.5.0 (from custom ones), thank you
 
[1] https://github.com/opensearch-project/OpenSearch/pull/5560/files#diff-5fe8bce6f41cbba30ab4dad09445194a255d5dc8a8fecb94e0152351b84b1588

**Comment by dreamer-89** [comment]
> @dreamer-89 thanks for the update, could you please update Lucene versions as well [1] for 2.4.1 and 2.5.0 (from custom ones), thank you
> 
> [1] https://github.com/opensearch-project/OpenSearch/pull/5560/files#diff-5fe8bce6f41cbba30ab4dad09445194a255d5dc8a8fecb94e0152351b84b1588

Thank you @reta for the quick update. Is this needed for gradle check to pass ? I see lot of java compilation errors in precommit.

**Comment by reta** [comment]
> Thank you @reta for the quick update. Is this needed for gradle check to pass ? I see lot of java compilation errors in precommit.

No, it is not needed to check to pass but it was one of the reasons to update. Also, the compilation issues are "normal" due to changes in Apache Lucene.

**Comment by mch2** [comment]
@dreamer-89 From what I can tell most of these changes are around a new [codec](https://github.com/apache/lucene/blob/branch_9x/lucene/core/src/java/org/apache/lucene/codecs/lucene95/Lucene95Codec.java) used with 9.5, which 9.4 moved to bwc codecs.

**Review by reta — APPROVED** [review]

**Review by mch2 — APPROVED** [review]

**Pull request merged**
