### PR TITLE
[Backport 2.x] [Tiered Caching] Expose a dynamic setting to disable/enable disk cache

### PR DESCRIPTION
**Pull request by sgup432**
### Description
Backport https://github.com/opensearch-project/OpenSearch/pull/13373

### Related Issues
N/A

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sgup432** [comment]
@sohami ^^

**Comment by sohami** [comment]
> ❌ Gradle check result for [93bfc5f](https://github.com/opensearch-project/OpenSearch/commit/93bfc5fadfcc0d6d820b8b15d97c5e94006052c6): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/37784/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Known Flaky Test: https://github.com/opensearch-project/OpenSearch/issues/13045

**Comment by sohami** [comment]
> ❌ Gradle check result for [93bfc5f](https://github.com/opensearch-project/OpenSearch/commit/93bfc5fadfcc0d6d820b8b15d97c5e94006052c6): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/37791/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Known Flaky Test: https://github.com/opensearch-project/OpenSearch/issues/13106

**Comment by sohami** [comment]
> ❌ Gradle check result for [93bfc5f](https://github.com/opensearch-project/OpenSearch/commit/93bfc5fadfcc0d6d820b8b15d97c5e94006052c6): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/37812/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Known Flaky Test:
https://github.com/opensearch-project/OpenSearch/issues/12639
https://github.com/opensearch-project/OpenSearch/issues/2440

**Review by sohami — APPROVED** [review]

**Pull request merged**
