### PR TITLE
[Backport 1.2] Upgrade to log4j 2.15.0

### PR DESCRIPTION
**Pull request by andrross**
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Comment by andrross** [comment]
Overall test timeout was reached:

```
org.opensearch.plugins.InstallPluginCommandTests > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
        at __randomizedtesting.SeedInfo.seed([D1E872A9E86A5199]:0)
```

Individual failed test succeeds on retry.

**Comment by andrross** [comment]
start gradle check

**Comment by andrross** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
@dblock looks like DCO check is not backported to 1.2

**Comment by dblock** [comment]
> @dblock looks like DCO check is not backported to 1.2

Did something slip through?

**Pull request merged**
