### PR TITLE
Upgrade Lucene to 9.8.0

### PR DESCRIPTION
**Pull request by msfroh**
### Description
9.8.0 was officially released this morning:
https://lucene.apache.org/core/9_8_0/changes/Changes.html

### Related Issues
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by zhichao-aws** [comment]
Hi, want to have a double check. This won't be backport to 2.x before 2.11 release, right?

**Comment by msfroh** [comment]
> This won't be backport to 2.x before 2.11 release, right?

I don't know. For now, I'm just focused on applying the change to main.

We can theoretically backport to 2.x before the start of the release window.

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@CEHENKLE please let us know if you are OK making 2.11 release with Apache Lucene 9.8.0, AFAIK there are no regressions we are aware of, the changes we know about were integrated (https://github.com/opensearch-project/OpenSearch/pull/8668, https://github.com/opensearch-project/OpenSearch/pull/10031)

**Comment by heemin32** [comment]
+1 with backporting to 2.11. 
With Lucene 9.8.0, https://github.com/opensearch-project/OpenSearch/pull/10246, and https://github.com/opensearch-project/k-NN/pull/1181 together, a user can have parent join feature in nested query for vector search in OpenSearch 2.11.

**Comment by dblock** [comment]
It’s cutting it a little short for 2.11 but it looks like the performance improvements are compelling.

**Comment by dblock** [comment]
> @CEHENKLE please let us know if you are OK making 2.11 release with Apache Lucene 9.8.0, AFAIK there are no regressions we are aware of, the changes we know about were integrated (#8668, #10031)

Is there a backport PR ready? What are the reasons other than “it’s a little short before a code freeze” not to take it?

**Comment by reta** [comment]
> Is there a backport PR ready? What are the reasons other than “it’s a little short before a code freeze” not to take it?

I could make one tomorrow morning (essentially bundling 2 PRs).

**Comment by msfroh** [comment]
I've had some folks approach me around the office about this with similar concerns to those voiced by @model-collapse in https://github.com/opensearch-project/OpenSearch/pull/8668:

> 1. Before OpenSearch 2.11, the main branch of ml-commons is behind 2.x on some commits. Although this has fixed at the moment, we still suspect that some other repos may have the same kind of problems. The main branch should catch up with 2.x with the latest features & implementations before we back-port Lucene 9.8 to 2.x, otherwise, there will be endless conflicts to deal with.
>2. We believe that all repos have done their functional tests as well as some benchmarkings to their main branch with Lucene 9.8 snapshot and so far there was no negative feedback. But as a rigorous procedure, we suggest all the repo to reproduce their tests with the formal release artifacts of Luence 9.8 (not snapshot version) so as to validate whether there's some negative impact from the Lucene upgrade to OpenSearch. The neural search plugin is absorbing the performance improvement, we also want to see others' feedback.
>3. We'd like to see whether the change of [APIs](https://lucene.apache.org/core/9_8_0/changes/Changes.html#v9.8.0.api_changes) or [runtime behavior](https://lucene.apache.org/core/9_8_0/changes/Changes.html#v9.8.0.changes_in_runtime_behavior) will have impact to AWS hosted search service which will subscribe this upgrade in the feature. That is another topic. We shall be aware but not discuss it on github.

Based on our "release window" model where we have two weeks to produce a working distribution build from tomorrow's code freeze and the fact that we nearly missed it for 2.10, I'm starting to appreciate the risk that we could end up "just not releasing" 2.11. (Frankly, it is a time of year when people at AWS are particularly concerned about missing releases.)

**Comment by macohen** [comment]
Would it make sense to do a fast-follow 2.12 release with only Lucene 9.8?

**Comment by LiuCao0614** [comment]
Hi @msfroh , do we have any plan on releasing a new version with this fix any time soon?

**Comment by reta** [comment]
> Hi @msfroh , do we have any plan on releasing a new version with this fix any time soon?

@LiuCao0614 `2.12` as per https://github.com/orgs/opensearch-project/projects/1

**Comment by LiuCao0614** [comment]
Cool thanks @reta .

**Pull request merged**
