### PR TITLE
Remove compatibility checker

### LINKED ISSUE #12913: [RFC] How helpful is the compatibility checker
### Is your feature request related to a problem? Please describe

Few months back we added a compatibility checker workflow to this repository in order to see if a change in OpenSearch could potentially break the downstream components (plugins in this case).
Associated PR: https://github.com/opensearch-project/OpenSearch/pull/8486
Associated GH issue: https://github.com/opensearch-project/opensearch-devops/issues/114

We observed that the comments about compatibility status are usually ignored. [Example](https://github.com/opensearch-project/OpenSearch/pull/12872#issuecomment-2015678527) and many more

Before approaching to next steps which was creating issues with all associated incompatible components giving a heads-up that there is an incoming change that could break your build, we wanted to get the feedback from the community members.

### Describe the solution you'd like

This was the approach taken to solve the issue: https://github.com/opensearch-project/opensearch-devops/issues/114#issuecomment-1548868449

### Related component

Build

### Describe alternatives you've considered

If the compatibility checker is not providing any value, we would like to remove it and save resources as well as reduce noise on the PR

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peternied**
### Description
I do not see much value in continuing to run the compatibility checker.  The workflow adds additional comments and test results that are ignored even when they detect downstream failures.

### Related Issues
- Resolves #12913

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
It doesn't look like there are any comments one way or another on the RFC. Can we please solicit at least some input? I'll add mine.

**Comment by peternied** [comment]
@dblock Isn't this PR a way to solicit additional feedback on the topic? 😉

**Comment by peternied** [comment]
@dblock Since we've added the Java API compatibility check [1], I think this workflow's purpose has been replaced with a more reliable process.  What do you think about removing this less reliable and often ignored check?


- [1] https://github.com/opensearch-project/OpenSearch/pull/12974

**Comment by kotwanikunal** [comment]
+1. I was going [through another PR today](https://github.com/opensearch-project/OpenSearch/pull/13181#issuecomment-2057177872) and I think the new mechanism serves its purpose well

**Review by gaiksaya — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Pull request merged**
