### PR TITLE
[Backport 2.x] Refactor Compressors from CompressorFactory to CompressorRegistry for extensibility (#9262)

### PR DESCRIPTION
**Pull request by nknize**
Backport c6b67e1b938b5e34806216af5efef32954554bf3 from #9262.

### CODE REVIEW

**Comment by nknize** [comment]
> ...how can we give impacted teams time to stabilize before this change is merged?

Stabilize what? Main? Or 2.x? The [original change](https://github.com/opensearch-project/OpenSearch/pull/9082) was merged to main five days ago. Backport PRs usually come quicker than that.

**Comment by nknize** [comment]
> @[peternied](https://github.com/peternied) peternied added the [>breaking](https://github.com/opensearch-project/OpenSearch/labels/%3Ebreaking) label [7 minutes ago](https://github.com/opensearch-project/OpenSearch/pull/9367#event-10101149753)

Out of curiosity, why did you label this breaking?

**Comment by peternied** [comment]
> Stabilize what? Main? Or 2.x? The https://github.com/opensearch-project/OpenSearch/pull/9082 was merged to main five days ago. Backport PRs usually come quicker than that.

If there was 15 PRs need to handle the previous breaking change, then I would expect there would also be ~15 PRs to handle the backport.  It would be really great if that was happening in a guided way instead of scrambling against broken builds?

The current process is 'OpenSearch chooses to break you' and it does.  This is communicated by CI breaking - unpredictable and uncommunicated.  I think we can do better, what do you think?  Maybe there is a way to run campaigns [1] or something better?

- [1] https://github.com/opensearch-project/opensearch-plugins/issues?q=is%3Aissue+is%3Aopen+label%3Acampaign

**Comment by nknize** [comment]
> This is communicated by CI breaking - unpredictable and uncommunicated. I think we can do better,...

How about a meta issue to track what specifically is breaking on a case by case basis? 

Happy to discuss this PR in particular. What does this break in security? I can't really grok the security git log because of dependabots HTML spam but it looks like y'all were able to get main back in sync? Are you wanting to hold this backport until the security repo backports fixes to 2.x?

**Comment by nknize** [comment]
Actually, it doesn't look like this PR breaks anything in security repo?

It looks like `compileOnly "org.opensearch:opensearch:${opensearch_version}"` in the [build.gradle](https://github.com/opensearch-project/security/blob/5e8f12ce5afe95f2f510cddf2a5b2cf50c076a66/build.gradle#L627C3-L627C66) properly pulls all of the opensearch artifacts which includes things like the new compress library. 

image

Then I don't see security directly calling `CompressorType` or `CompressorFactory` (which is now replaced by `CompressorRegistry`). So compile time shouldn't be impacted. The only possible impact I can see by quickly looking would be at test runtime if `XContentHelper` (e.g., `XContentHelper.createParser(...)`) is ever called (looks like it's called in a few places like [AbstractAuditLog](https://github.com/opensearch-project/security/blob/5e8f12ce5afe95f2f510cddf2a5b2cf50c076a66/src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java#L589)? This will now use the `CompressorRegistry`. But even this is handled by the `Gradle: org.opensearch:opensearch:3.0.0-SNAPSHOT` dependency. 

So what's breaking?

**Comment by peternied** [comment]
Thanks for looking into the security repo - doing that by hand seems painful.  Seems like the compatibility check was broken, how would you feel about waiting till that is operational before we merge changes like this?  Maybe we could invest a little their to build confidence in changes like this rather than starting at zero (such as I am).

- [1] https://github.com/opensearch-project/OpenSearch/issues/9371

**Comment by nknize** [comment]
The 2.x incompatibility is unrelated to this change. It reported incompatible because the Action class changes [were only just merged](https://github.com/opensearch-project/security/commit/ee81de789655945b28c8cfc564f60074ee5a575a) after compatibility checker was run on this PR.

**Comment by nknize** [comment]
I'm refiring check compatibility just in case.

**Comment by peternied** [comment]
> Are you wanting to hold this backport until the security repo backports fixes to 2.x?

I don't have the data, so let not hold off because I say so.  What do you think about coming up with a prediction the downstream impact of this change, then so long as we [1] are ok with that impact, then lets move forward [2]?

- [1] who is we? I think that decision making process should be bigger than 1 contributor and 1 approver in OpenSearch, but it shouldn't bog this all down 🤷 
- [2] Move forward might change very little, e.g. merge and downstream's handle if there are breaking changes, maybe there is breaking change days for predictability 

How does apache foundation handle cases like this?

**Comment by nknize** [comment]
> How does apache foundation handle cases like this?

It's varies by project. I can only speak for Lucene and Solr. Solr absorbs upstream changes "on demand" the same way we do it here with Lucene. This is what I have been suggesting for a while. 

Instead of upstream core OpenSearch repo force feeding per-merge `SNAPSHOT` artifacts to all downstreams, the downstreams should manually (or on some automated, e.g., weekly, cron period) trigger a snapshot build and update their `${opensearch_version}` in `build.gradle` to their own created sha (e.g., `2.10.0-SNAPSHOT-4373c3b`). This would keep downstream builds stable. The unpleasant side affect would depend on how often those snapshots are updated, but that would be under the control of the downstream repo community. It's not perfect (breaking changes never are) but least then the downstream controls their own pain. This happens a lot on Solr, OpenSearch, Elasticsearch when large changes are made to lucene (e.g., JPMS, gradle change from ant, Endianness changes)

**Comment by peternied** [comment]
@nknize Thanks - can you speak to this during our next operations review for discussion and next steps?

While I prefer the structure we currently have in place to prevent 'debt build up' and point in time alignment, the approach you called out to addresses stability that might be the change the project needs.

**Comment by nknize** [comment]
> While I prefer the structure we currently have in place to prevent 'debt build up' and point in time alignment, the approach you called out to addresses stability that might be the change the project needs.

I wonder if we could invent a "toggle" mechanism to have each downstream switch between the two approaches?  Maybe there's a GHA to enable/disable "force fed" snapshots? This could prove useful during large scale refactors to clot the bleeding? Downstreams cut over to the manual snapshot consumption model, and switch back when the change storm has passed?

**Comment by nknize** [comment]
With the need to [cut a 2.9.1 patch release](https://github.com/opensearch-project/OpenSearch/issues/9422) we should get this backport merged so we can easily and quickly backport changes needed to the BlobStoreRepository Zstd compression logic.

**Comment by reta** [comment]
@peternied are you OK with that?

**Comment by peternied** [comment]
@reta Thanks for checking in - speaking for the security plugin team, looks fine for us

**Review by reta — APPROVED** [review]

**Comment by nknize** [comment]
These CI/CD are not at all reliable. It's crazy how much time is wasted re-firing all of these checks... It only seems to be getting worse. Can we simplify all of this? 

```
315.00 MiB / 315.00 MiB (100.00%) ? p/stime="2023-08-21T14:22:21Z" level=info msg="Downloaded the image from \"[https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.5/alpine-lima-clm-3.18.0-x86_64.iso\](https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.5/alpine-lima-clm-3.18.0-x86_64.iso/)""
time="2023-08-21T14:22:25Z" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/runner/.lima/colima/serial*.log\")"
time="2023-08-21T14:22:25Z" level=info msg="SSH Local Port: 49356"
time="2023-08-21T14:22:25Z" level=info msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
time="2023-08-21T14:22:26Z" level=info msg="[hostagent] Driver stopped due to error: \"exit status 255\""
time="2023-08-21T14:22:26Z" level=info msg="[hostagent] Shutting down the host agent"
time="2023-08-21T14:22:26Z" level=warning msg="[hostagent] failed to exit SSH master"
time="2023-08-21T14:22:26Z" level=info msg="[hostagent] Shutting down QEMU with ACPI"
time="2023-08-21T14:22:26Z" level=warning msg="[hostagent] failed to open the QMP socket \"/Users/runner/.lima/colima/qmp.sock\", forcibly killing QEMU"
time="2023-08-21T14:22:26Z" level=info msg="[hostagent] QEMU has already exited"
time="2023-08-21T14:22:26Z" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/Users/runner/.lima/colima/ha.stderr.log\")"
time="2023-08-21T14:22:26Z" level=fatal msg="error starting vm: error at 'creating and starting': exit status 1"
```

**Pull request merged**
