### PR TITLE
Fix Flaky Test

### LINKED ISSUE #13638: [BUG] Test org.opensearch.indices.IndicesRequestCacheIT.testInvalidStalenessThresholdUpdateThrowsException {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}} is flaky
### Describe the bug

The test case `org.opensearch.indices.IndicesRequestCacheIT.testInvalidStalenessThresholdUpdateThrowsException {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}` is flaky

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([98CBE513F9761EBB:CA3D83A51E556CFF]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.opensearch.indices.IndicesRequestCacheIT.testInvalidStalenessThresholdUpdateThrowsException(IndicesRequestCacheIT.java:1096)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.opensearch.test.OpenSearchTestClusterRule$1.evaluate(OpenSearchTestClusterRule.java:369)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Related component

Search

### To Reproduce

```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.IndicesRequestCacheIT" -Dtests.method="testInvalidStalenessThresholdUpdateThrowsException {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}" -Dtests.seed=98CBE513F9761EBB -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=cs-CZ -Dtests.timezone=Brazil/West -Druntime.java=21
```

### Expected behavior

Test should always pass

### Additional Details
https://build.ci.opensearch.org/job/gradle-check/38595/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testInvalidStalenessThresholdUpdateThrowsException__p0___opensearch_experimental_feature_pluggable_caching_enabled___true___/

### PR DESCRIPTION
**Pull request by kiranprakash154**
### Description
Fix Flaky Test - `org.opensearch.indices.IndicesRequestCacheIT.testInvalidStalenessThresholdUpdateThrowsException`
The test is intended to test an exception being thrown on invalid parameter being passed. We don't have to test the working of the cache in this test since it has been covered very extensive in other tests.

The flakiness is due to relying on cache cleanup intervals which are being removed from this test without changing the main objective of the test. 

### Related Issues
Resolves #13638 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
@kiranprakash154 Care to explain what the change is? Looks like a bunch of code that was removed from the test, so I assume it tests less ;)

**Comment by kiranprakash154** [comment]
> @kiranprakash154 Care to explain what the change is? Looks like a bunch of code that was removed from the test, so I assume it tests less ;)

Will update the description soon, that's why I kept this in draft.

**Comment by kiranprakash154** [comment]
The test is supposed to only test throwing of an exception on illegal argument, I was also testing if the cache would behave as expected which I think is unnecessary and that cache interval setup is what causing flakiness.

**Comment by kiranprakash154** [comment]
> ❌ Gradle check result for [07c31a5](https://github.com/opensearch-project/OpenSearch/commit/07c31a5df15be196405c88d4b9364eb53c3df7f2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38824/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md?rgh-link-date=2024-05-16T18%3A42%3A49Z#flaky-tests) unrelated to your change?

Failed because of https://github.com/opensearch-project/OpenSearch/issues/5329

**Comment by kiranprakash154** [comment]
> ❌ Gradle check result for [07c31a5](https://github.com/opensearch-project/OpenSearch/commit/07c31a5df15be196405c88d4b9364eb53c3df7f2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38833/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md?rgh-link-date=2024-05-16T20%3A22%3A24Z#flaky-tests) unrelated to your change?

Failing due to - `:distribution:bwc:staged:buildBwcLinuxTar` - https://github.com/opensearch-project/OpenSearch/issues/7396

**Comment by dblock** [comment]
> The test is supposed to only test throwing of an exception on illegal argument, I was also testing if the cache would behave as expected which I think is unnecessary and that cache interval setup is what causing flakiness.

I assume you double checked that those scenarios are covered in another test?

**Comment by kiranprakash154** [comment]
> > The test is supposed to only test throwing of an exception on illegal argument, I was also testing if the cache would behave as expected which I think is unnecessary and that cache interval setup is what causing flakiness.
> 
> I assume you double checked that those scenarios are covered in another test?

Yep, like [these 3 tests for example](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java#L761-L894)
Some of the tests below them cover too

**Comment by kiranprakash154** [comment]
> ❌ Gradle check result for [a5c83ae](https://github.com/opensearch-project/OpenSearch/commit/a5c83aeac88afc24e31041707fcff730a0f8309f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38870/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md?rgh-link-date=2024-05-17T15%3A35%3A37Z#flaky-tests) unrelated to your change?

This is IndicesRequestCacheIT suite timing out. I have created an issue to track this - https://github.com/opensearch-project/OpenSearch/issues/13734

**Comment by dblock** [comment]
> ❌ Gradle check result for [a5c83ae](https://github.com/opensearch-project/OpenSearch/commit/a5c83aeac88afc24e31041707fcff730a0f8309f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38877/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.cluster.MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock](https://build.ci.opensearch.org/job/gradle-check/38877/testReport/junit/org.opensearch.cluster/MinimumClusterManagerNodesIT/testThreeNodesNoClusterManagerBlock/)
[org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"search.concurrent_segment_search.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/38877/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testDeleteAndCreateSameIndexShardOnSameNode__p0___search_concurrent_segment_search_enabled___true___/)
[org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/38877/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testDeleteAndCreateSameIndexShardOnSameNode__p0___opensearch_experimental_feature_pluggable_caching_enabled___true___/)
[org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"false"}}](https://build.ci.opensearch.org/job/gradle-check/38877/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testDeleteAndCreateSameIndexShardOnSameNode__p0___opensearch_experimental_feature_pluggable_caching_enabled___false___/)
[org.opensearch.indices.IndicesRequestCacheIT.testDeleteAndCreateSameIndexShardOnSameNode {p0={"search.concurrent_segment_search.enabled":"false"}}](https://build.ci.opensearch.org/job/gradle-check/38877/testReport/junit/org.opensearch.indices/IndicesRequestCacheIT/testDeleteAndCreateSameIndexShardOnSameNode__p0___search_concurrent_segment_search_enabled___false___/)

https://github.com/opensearch-project/OpenSearch/issues/10006
https://github.com/opensearch-project/OpenSearch/issues/13600

**Comment by kiranprakash154** [comment]
> ❌ Gradle check result for [a5c83ae](https://github.com/opensearch-project/OpenSearch/commit/a5c83aeac88afc24e31041707fcff730a0f8309f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38925/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md?rgh-link-date=2024-05-20T15%3A42%3A35Z#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/13695

**Review by dblock — APPROVED** [review]

**Pull request merged**
