### PR TITLE
Fix bwcVersions after bumping version 1.3.1 (#2532)

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Nicholas Walter Knize <nknize@apache.org>
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Fix bwc tests
 
### Issues Resolved
Backport of https://github.com/opensearch-project/OpenSearch/pull/2532
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock @nknize please

**Review by nknize — APPROVED** [review]
LGTM! Thx!

**Comment by dblock** [comment]
```
org.opensearch.upgrade.DetectEsInstallationTaskTests > testTaskExecution FAILED
    java.lang.AssertionError: 
    Expected: a collection with size <0>
         but: collection size was <5>
        at __randomizedtesting.SeedInfo.seed([D13BB0340B7301E1:9B2194BFDF244E64]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution(DetectEsInstallationTaskTests.java:53)
REPRODUCE WITH: ./gradlew ':distribution:tools:upgrade-cli:test' --tests "org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution" -Dtests.seed=D13BB0340B7301E1 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sl -Dtests.timezone=Asia/Kolkata -Druntime.java=11

Suite: Test class org.opensearch.upgrade.DetectEsInstallationTaskTests
  1> [2022-03-22T02:33:20,997][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveDefaultUrlFromConfig] before test
  1> [2022-03-22T02:33:21,287][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveDefaultUrlFromConfig] after test
  1> [2022-03-22T02:33:21,336][INFO ][o.o.u.DetectEsInstallationTaskTests] [testTaskExecution] before test
  1> [2022-03-22T02:33:21,978][INFO ][o.o.u.DetectEsInstallationTaskTests] [testTaskExecution] after test
  2> REPRODUCE WITH: ./gradlew ':distribution:tools:upgrade-cli:test' --tests "org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution" -Dtests.seed=D13BB0340B7301E1 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sl -Dtests.timezone=Asia/Kolkata -Druntime.java=11
  2> java.lang.AssertionError: 
    Expected: a collection with size <0>
         but: collection size was <5>
        at __randomizedtesting.SeedInfo.seed([D13BB0340B7301E1:9B2194BFDF244E64]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution(DetectEsInstallationTaskTests.java:53)
  1> [2022-03-22T02:33:21,994][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveUrlFromSettings] before test
  1> [2022-03-22T02:33:21,996][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveUrlFromSettings] after test
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/tools/upgrade-cli/build/testrun/test/temp/org.opensearch.upgrade.DetectEsInstallationTaskTests_D13BB0340B7301E1-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=1578, maxMBSortInHeap=6.043260160779465, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=sl, timezone=Asia/Kolkata
  2> NOTE: Linux 5.13.0-1014-aws amd64/Eclipse Adoptium 11.0.14.1 (64-bit)/cpus=72,threads=1,free=416662832,total=536870912
  2> NOTE: All tests run in this JVM: [DetectEsInstallationTaskTests]

Tests with failures:
 - org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution
```

**Comment by dblock** [comment]
start gradle check

**Pull request merged**
