### PR TITLE
Remove support for legacy es test clusters

### PR DESCRIPTION
**Pull request by adnapibar**
### Description
This commit removes the support we added for running test clusters for legacy ES versions for bwc tests.

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Rabi Panda <adnapibar@gmail.com>

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Are you removing ODFE along the way?

**Comment by adnapibar** [comment]
> Are you removing ODFE along the way?

@dblock not sure which ones you're referring to?

**Comment by dblock** [comment]
> > Are you removing ODFE along the way?
> 
> @dblock not sure which ones you're referring to?

I had noticed things like `DISTRO_EXTRACTED_CONFIG_PREFIX`

**Comment by adnapibar** [comment]
> > > Are you removing ODFE along the way?
> > 
> > 
> > @dblock not sure which ones you're referring to?
> 
> I had noticed things like `DISTRO_EXTRACTED_CONFIG_PREFIX="opensearch_distro_extracted_ "`, is that not ODFE-related and I just see "distro" everywhere? if so ignore me.

Yeah, for a second I got confused :) no that's just a short for distribution, no relation to ODFE.

**Pull request merged**
