### PR TITLE
File name correction to follow existing convention

### PR DESCRIPTION
**Pull request by tylermcvaney**
Updated the name of the file to follow existing naming conventions. I discovered this due to the 1.2.3 hyperlink on "/docs/1.2/version-history/" being broken.

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
@tylermcvaney You'll need to amend your commit with `-s` for the DCO check.

**Comment by tylermcvaney** [comment]
> @tylermcvaney You'll need to amend your commit with `-s` for the DCO check.

Apologies for messing this up, @dblock . I read over the _Contributing to OpenSearch_ page and managed to miss the DCO portion. I used the GitHub web interface to make the pull request and do not appear to have the ability to amend the commit. I see now that I could have manually added the DCO string in my commit description.

I am new to this process, so I want to avoid making anything worse. If someone could provide me some direction on how to resolve this current problem (having issues amending the commit), I will make sure to not make the same mistake in the future. I want to become a more active member in the OS community.

**Comment by dblock** [comment]
> > @tylermcvaney You'll need to amend your commit with `-s` for the DCO check.
> 
> Apologies for messing this up, @dblock . I read over the _Contributing to OpenSearch_ page and managed to miss the DCO portion. I used the GitHub web interface to make the pull request and do not appear to have the ability to amend the commit. I see now that I could have manually added the DCO string in my commit description.
> 
> I am new to this process, so I want to avoid making anything worse. If someone could provide me some direction on how to resolve this current problem (having issues amending the commit), I will make sure to not make the same mistake in the future. I want to become a more active member in the OS community.

No worries! Let me try to help. Try this:

1. Clone the code locally, e.g. `git clone git@github.com:tylermcvaney/OpenSearch-1.git` (might need to be `https://github.com/tylermcvaney/OpenSearch-1.git`)
2. `cd  OpenSearch-1`
3. `git checkout patch-1`
4. `git commit --amend -s`, save
5. `git push origin patch-1 -f`

**Comment by tylermcvaney** [comment]
> > > @tylermcvaney You'll need to amend your commit with `-s` for the DCO check.
> > 
> > 
> > Apologies for messing this up, @dblock . I read over the _Contributing to OpenSearch_ page and managed to miss the DCO portion. I used the GitHub web interface to make the pull request and do not appear to have the ability to amend the commit. I see now that I could have manually added the DCO string in my commit description.
> > I am new to this process, so I want to avoid making anything worse. If someone could provide me some direction on how to resolve this current problem (having issues amending the commit), I will make sure to not make the same mistake in the future. I want to become a more active member in the OS community.
> 
> No worries! Let me try to help. Try this:
> 
> 1. Clone the code locally, e.g. `git clone git@github.com:tylermcvaney/OpenSearch-1.git` (might need to be `https://github.com/tylermcvaney/OpenSearch-1.git`)
> 2. `cd  OpenSearch-1`
> 3. `git checkout patch-1`
> 4. `git commit --amend -s`, save
> 5. `git push origin patch-1 -f`

@dblock that appears to have worked. Many thanks for helping me learn something new!

**Pull request merged**
