### PR TITLE
Fix noop_update_total metric in indexing stats cannot be updated by bulk API

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description
Same to the [update API](https://github.com/opensearch-project/OpenSearch/blob/c20458512ff4e68f359de32bfad91a6a7487f8a1/server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java#L339), we should update the `noop_update_total` metric in indexing stats when there's a noop update operation happened in bulk.

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/9857

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by r1walz — APPROVED** [review]
Thanks for working on this. LGTM. Can you check why gradle-check if failing?

**Comment by gaobinlong** [comment]
`org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing` is flaky, there's an [issue](org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing) tracking it.

**Review by ankitkala — APPROVED** [review]

**Comment by gaobinlong** [comment]
Can this PR be merged now? Thanks!

**Comment by deshsidd** [comment]
Thanks, LGTM

**Review by deshsidd — APPROVED** [review]

**Comment by deshsidd** [comment]
Looks like builds are passing now. Will require one maintainers approval @dblock @reta @msfroh @peternied @andrross

**Review by peternied — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
