### PR TITLE
Fix class_cast_exception when passing int to _version and other metadata fields in ingest simulate API

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description
When we add `_version`, `_if_seq_no` or `_if_primary_term` to each doc in the request body of the ingest simulate API, the API throws `class_cast_excetpion` with 500 status code. The reason is that the API cannot accept those fields as  int, only `long` type is accepted. This PR aims to make that API can accept both int and long for those metadata fields, which is user-friendly.

The main changes of this PR are:
1. Fix the class_cast_exception
2. Add some yml test and unit test code.

### Related Issues

https://github.com/opensearch-project/OpenSearch/issues/10097

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Thanks @gaobinlong, care to check gradle check please?
Maybe @mch2 can CR this?

**Review by dblock — COMMENTED** [review]
I think you should add a test that passes an invalid value for each one of these changed fields, and returns a 400 (hits the failed to parse error) instead of a 500.

**Review by dblock — APPROVED** [review]
Looks great! Let's get CI to pass.

**Comment by dblock** [comment]
@gaobinlong Can you please do a manual backport of this to 2.x?

**Comment by gaobinlong** [comment]
@dblock here are the backport PRs:  https://github.com/opensearch-project/OpenSearch/pull/10478, https://github.com/opensearch-project/OpenSearch/pull/10479, please help to approve, thanks!

**Pull request merged**
