### PR TITLE
Some dependency updates

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Routine dependency updates

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by saratvemulapalli — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Why isn't dependabot doing @reta's work?

**Comment by reta** [comment]
Always forgetting about proper labels, thanks a lot @saratvemulapalli !

**Comment by reta** [comment]
> Why isn't dependabot doing @reta's work?

Cuz it inspect `build.gradle` but we have not found the way yet to tell depandabot to look into `version.properties`, we track it under https://github.com/opensearch-project/OpenSearch/issues/3782

**Comment by reta** [comment]
@dblock do you see risks backporting to `2.x`?

**Comment by saratvemulapalli** [comment]
@reta unless it breaks things in 2.x, from the look it seems fine.

**Pull request merged**
