### PR TITLE
Fix remote shards balance

### LINKED ISSUE #15302: [BUG] RemoteShardsBalancer cannot rebalance shards as expected
### Describe the bug

When rebalancing searchable snapshot indices, we first calculate the average number of primary shards that each node should has. In current implementation, the formula is as follows.
```
(totalNumberOfRemotePrimaryShards + totalNumberOfUnassignedShards)/totalNumberOfRoutingNodes
```
https://github.com/opensearch-project/OpenSearch/blob/e8ee6db87e55f66e28b46fac90bf2a4b33755160/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java#L247-L251

If a cluster has both search nodes and dedicated data nodes, this average number of shards calculated using the current formula may be lower than the actual number.. I think that the formula needs to be adjusted as follows:
```
(totalNumberOfRemotePrimaryShards + totalNumberOfUnassignedRemoteShards)/totalNumberOfSearchNodes
```

### Related component

Search:Searchable Snapshots

### Expected behavior

RemoteShardsBalancer should rebalance shards as expected

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
see #15302

### Related Issues
Resolves #15302

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by andrross — APPROVED** [review]

**Review by sohami — APPROVED** [review]

**Comment by sohami** [comment]
@bugmakerrrrrr Can you please fix the change log conflict

**Comment by bugmakerrrrrr** [comment]
> @bugmakerrrrrr Can you please fix the change log conflict

@sohami done

**Comment by bugmakerrrrrr** [comment]
hi @andrross , can we merge this? or is there anything else that I need to do for this PR?

**Review by andrross — APPROVED** [review]

**Comment by msfroh** [comment]
@bugmakerrrrrr  -- Can you please open a manual backport PR? Looks like the auto-backport operation failed.

**Comment by bugmakerrrrrr** [comment]
@msfroh Done #16972

**Pull request merged**
