### PR TITLE
Update issue template for multiple labels

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
This PR intends to add multiple labels for the issue template to better categorize the issues.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
start gradle check

**Review by CEHENKLE — COMMENTED** [review]
Hey Vacha!  Thanks for this!

Can you keep "bug" in there (so bug, untriaged and beta)?  And I don't care if we capitalize or not, but let's pick one :)

Thanks again...

**Comment by VachaShah** [comment]
> Hey Vacha! Thanks for this!
> 
> Can you keep "bug" in there (so bug, untriaged and beta)? And I don't care if we capitalize or not, but let's pick one :)
> 
> Thanks again...

Sure no problem! I have updated the template to keep "bug" as well.

**Comment by CEHENKLE** [comment]
start gradle check

**Pull request merged**
