### PR TITLE
[Backport] [1.2] [FEATURE] Add OPENSEARCH_JAVA_HOME env to override JAVA_HOME (#2040)

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Backport of https://github.com/opensearch-project/OpenSearch/pull/2040 to 1.2
 
### Issues Resolved
Closes https://github.com/opensearch-project/OpenSearch/issues/1872
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock @andrross no objections from your side guys to bring it into 1.2? thanks!

**Comment by andrross** [comment]
I would think this change doesn't meet the definition of "hotfix" defined in the [release policy](https://github.com/opensearch-project/.github/blob/main/RELEASING.md?plain=1#L28). Do you have a particular reason for wanting to backport this to the 1.2 branch?

**Comment by reta** [comment]
> I would think this change doesn't meet the definition of "hotfix" defined in the [release policy](https://github.com/opensearch-project/.github/blob/main/RELEASING.md?plain=1#L28). Do you have a particular reason for wanting to backport this to the 1.2 branch?

Thanks @andrross  I don't have the compelling  reasons for 1.2 (besides matching the original documentation section), no objections to close this backport, @dblock sounds good to you?

**Comment by dblock** [comment]
Agreed, let's close. Shipping this in 1.3.0 (1.x branch) is good.

**Pull request closed without merging**
