### PR TITLE
Override Default Distribution Download Url with Custom Distribution Url when it is passed from Plugin

### LINKED ISSUE #1240: Override Distribution Downloader to download opensearch-min artifact from a custom url
The opensearch-plugin-cli works well for getting the last released and release candidate builds, but lacks pull artifacts from any location for scenarios like local development and testing.

This is needed for build and release process to validate components _before_ they are released.

### PR DESCRIPTION
**Pull request by Rishikesh1159**
### Description
This PR overrides default distribution url with custom distribution url passes by user from plugin. This fixes the error caused by this PR: #2086 and reverted by PR #2256 
 
### Issues Resolved
#1240 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
How does this fix the issue that caused the revert?

**Comment by Rishikesh1159** [comment]
I was able to root cause failure in Alerting plugin. In order to fix this issue https://github.com/opensearch-project/OpenSearch/issues/1240, in my previous PR I moved call to setupDownloadServiceRepo() in DistributionDownloadPlugin.java from apply() method to setupDistributions() method, which is called in afterEvaluate(). Here is previous PR: https://github.com/opensearch-project/OpenSearch/pull/2086 which is reverted.

-> This change made to setup repo at the end of configuration phase [One of gradle life cycle process] after entire root and sub projects are configured.

-> Internally in subprojects of Alerting plugin in configuration phase call to the repo is being made before it was actually setup. But the setup will happen after configuration phase ends. So, this was the reason Alerting plugin was failing.

-> Temporarily we moved back call to setupDownloadServiceRepo() in DistributionDownloadPlugin.java to apply() method as it was before. Here the repo is setup before evaluation happens. But, it does not fix this issue.

Fix:

-> The fix I found was to use Project properties to set the custom url from plugin instead of system properties. Before, I was trying to use system properties to set custom url from plugin.

-> These system properties are not available for us to use them in configuration phase, we had to wait until configuration phase ends and afterEvaluate() happens to use these system properties.

->But Project properties are different and are available in configuration phase.

-> So, the fix would be using Project properties to set custom url from plugin side.

-> So no moving of seupDownloadServiceRepo() call out of apply() in DistributionDownloadPlugin.java is necessary and just adding conditions and logic of cutom Url is enough to fix this issue.

Test case for handling Alerting plugin failure:

-> I haven't thought of a way writing test case for this failure. As, it is happening because of moving method call in gradle life cycle phase, I find it a bit complex to write a test case for this scenario. https://github.com/opensearch-project/alerting/issues/312

**Comment by Rishikesh1159** [comment]
Here is the [exact line](https://github.com/opensearch-project/alerting/blob/5f18a5cef6047358d4ea38c79fe3b13968f72bd2/build-tools/opensearchplugin-coverage.gradle#L50) where Alerting plugin fail with my previous reverted PR https://github.com/opensearch-project/OpenSearch/pull/2086. There are other plugins using similar piece of [code](https://github.com/opensearch-project/k-NN/blob/bb283932b5834172142d18188668db8fa31676d6/build-tools/knnplugin-coverage.gradle#L67) but for those this piece of code is wrapped inside an after evaluate block, which is making it not fail. So, test case mentioned in my above comment will be related to this. This was the error on Alerting plugin side: https://github.com/opensearch-project/alerting/issues/312

**Comment by Rishikesh1159** [comment]
This PR fixes the issue, but I am planning to keep it open until we write a test case for above mentioned failure. If someone in future tries to do same mistake as I did then a test case should catch that. So, I am planning on keeping this open until I do that. @dblock please let me know your opinion on this, should we keep this PR open until write a test case or should that be a new issue?

**Comment by dblock** [comment]
> This PR fixes the issue, but I am planning to keep it open until we write a test case for above mentioned failure. If someone in future tries to do same mistake as I did then a test case should catch that. So, I am planning on keeping this open until I do that. @dblock please let me know your opinion on this, should we keep this PR open until we write a test case or should that be a new issue?

Because this is an issue in the tooling and not the engine, I would timebox writiung the test for this, and move on if it takes too long.

**Review by saratvemulapalli — APPROVED** [review]
Thanks for this @Rishikesh1159 !

I think we do lack the infrastructure to test these kinds of cases. 
Lets start with opening an issue and as we discussed see how other opensource gradle plugins are being tested. We should bring in a similar framework to test these cases.

**Comment by Rishikesh1159** [comment]
> > This PR fixes the issue, but I am planning to keep it open until we write a test case for above mentioned failure. If someone in future tries to do same mistake as I did then a test case should catch that. So, I am planning on keeping this open until I do that. @dblock please let me know your opinion on this, should we keep this PR open until we write a test case or should that be a new issue?
> 
> Because this is an issue in the tooling and not the engine, I would timebox writing the test for this, and move on if it takes too long.

Sure. Thank you!

**Comment by Rishikesh1159** [comment]
> Thanks for this @Rishikesh1159 !
> 
> I think we do lack the infrastructure to test these kinds of cases. Lets start with opening an issue and as we discussed see how other opensource gradle plugins are being tested. We should bring in a similar framework to test these cases.

Sure I will look for other opensource gradle plugins, and see if their framework fits for our use case. Thank you!

**Comment by dblock** [comment]
Can we merge this?

**Pull request merged**
