### PR TITLE
[Remove] Deprecated Synced Flush API

### PR DESCRIPTION
**Pull request by nknize**
This PR removes the deprecated synced flush API which was replaced by sequence number and retention lease mechanisms and no longer used in 2.0.0.

NOTE: this is not a blocker for Lucene 9 or 6.x deprecation removal

relates: #1674

### CODE REVIEW

**Comment by andrross** [comment]
I went looking for any documentation for this API, and the only reference I found was [in the security plugin](https://github.com/opensearch-project/documentation-website/blob/main/_security-plugin/access-control/permissions.md?plain=1#L217). Will we need a follow up task to clean that up?

**Comment by nknize** [comment]
> I went looking for any documentation for this API, and the only reference I found was [in the security plugin](https://github.com/opensearch-project/documentation-website/blob/main/_security-plugin/access-control/permissions.md?plain=1#L217). Will we need a follow up task to clean that up?

Looks like it's just an access permission for the `_flush/synced` endpoint? I think the security plugin should retain this so the endpoint can still be accessed and users receive the helpful endpoint removal warning (which we can fully remove in 3.0.0):

```
Synced flush was removed and a normal flush was performed instead. This transition will be removed in a future version.
```

**Comment by nknize** [comment]
This is ready for review.

**Review by adnapibar — APPROVED** [review]
LGTM

**Pull request merged**
