### PR TITLE
Add release-notes for 2.13.0

### PR DESCRIPTION
**Pull request by linuxpi**
### Description
Add release nodes for 2.13.0 release

### Related Issues
NA

### Check List
- ~[ ] New functionality includes testing.~
  - ~[ ] All tests pass~
- ~[ ] New functionality has been documented.~
  - ~[ ] New functionality has javadoc added~
- ~[ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [x] Commits are signed per the DCO using --signoff
- ~[ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by linuxpi** [comment]
Thanks for approving @reta

**Review by kotwanikunal — APPROVED** [review]

**Comment by gaiksaya** [comment]
Hi @reta Can you add right backport labels to this PR?
I believe we need both 2.x and 2.13?

**Comment by bbarani** [comment]
Gradle check failures on release notes ??

**Comment by kotwanikunal** [comment]
#10006

**Comment by gaiksaya** [comment]
Looks like it failed again :(

**Comment by reta** [comment]
@gaiksaya @linuxpi could you please rebase it against `main` ? thank you

**Comment by gaiksaya** [comment]
> @gaiksaya @linuxpi could you please rebase it against `main` ? thank you

Done!

**Review by mch2 — APPROVED** [review]

**Pull request merged**
