### PR TITLE
Modernize and consolidate JDKs usage across all stages of the build. Use JDK-17 as bundled JDK distribution to run tests

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Use JDK-17 as bundled JDK distribution to run tests. Tested on Windows / Linux / MacOS (x64), using Adoptium JDK distribution (https://adoptium.net/releases.html)
 
### Issues Resolved
Part of https://github.com/opensearch-project/OpenSearch/issues/1351
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
start gradle check

**Comment by reta** [comment]
@dblock thank you, already working on the next step.

**Comment by dblock** [comment]
> ❌   Gradle Check failure [95b28db](https://github.com/opensearch-project/OpenSearch/commit/95b28dba5e96f8e9d14c2aa1de2b91b33733a82e) [Log 677](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_677.log)
> 
> [Reports 677](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_677_reports.zip)

Doesn't look like a fluke, care to take a look?

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
> > x   Gradle Check failure [5fab558](https://github.com/opensearch-project/OpenSearch/commit/5fab558433022e604ba1aea553067801f0ccf985) [Log 680](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_680.log)
> > [Reports 680](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_680_reports.zip)
> 
> Hm ... this is a new one,
> 
> ```
> Caused by: java.lang.IllegalArgumentException: duration cannot be negative, was given [-3002]
>   1> 	at org.opensearch.common.unit.TimeValue.<init>(TimeValue.java:65) ~[opensearch-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
>   1> 	at org.opensearch.common.unit.TimeValue.<init>(TimeValue.java:60) ~[opensearch-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
>   1> 	at org.opensearch.test.transport.MockTransportService.lambda$addUnresponsiveRule$6(MockTransportService.java:350) ~[framework-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
>   1> 	at org.opensearch.test.transport.MockTransportService$3.sendRequest(MockTransportService.java:392) ~[framework-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
> ```

I kicked it again to see if it reproducible or whether we have solved time travel.

**Comment by saratvemulapalli** [comment]
Coming from #1910 
@dblock / @reta curious why this was not backported to 1.x line?

**Comment by reta** [comment]
> Coming from #1910 @dblock / @reta curious why this was not backported to 1.x line?

@saratvemulapalli I think the https://github.com/opensearch-project/OpenSearch/pull/1358#issuecomment-942300957 was a concern from @dblock

**Pull request merged**
