### PR TITLE
Bump snakeyaml from 2.0 to 2.1

### PR DESCRIPTION
**Pull request by reta**
### Description
Bump snakeyaml from 2.0 to 2.1

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kotwanikunal** [comment]
Sorry @reta!

**Review by kotwanikunal — APPROVED** [review]

**Comment by kotwanikunal** [comment]
Please wait on #9271 before adding the backport label.

**Comment by reta** [comment]
> Sorry @reta!

Np at all!

**Review by Poojita-Raj — APPROVED** [review]

**Comment by kotwanikunal** [comment]
I am not sure if the backport workflow is broken. #9270 was weird.
Let's give it a try again here.

**Comment by reta** [comment]
> I am not sure if the backport workflow is broken. #9270 was weird. Let's give it a try again here.

Still waiting for https://github.com/opensearch-project/OpenSearch/pull/9271

**Comment by kotwanikunal** [comment]
I was wrong on the sus :)

**Pull request merged**
