### PR TITLE
Add Jay Deng as a maintainer

### PR DESCRIPTION
**Pull request by sohami**
### Description
Jay has accepted the invitation to become a maintainer. Welcome Jay!

Jay is an active contributor of OpenSearch project and has extensively contributed in the concurrent segment search feature to make it GA for the users. Aside from this he proactively contributed to improve the documentations for different aggregations like term, sampler, diversified sampler, etc based on his learnings and is pretty active in the triage meetings and reviewing issues/PRs. Jay has contributed 56 pull requests to the project and reviewed close to 53 PRs. Some of his main contributions are:
 
**PRs:**
* Enabling parallel buildAggregation with concurrent search to further improve on agg performance https://github.com/opensearch-project/OpenSearch/issues/11673
* Doc count error computation at slice level: https://github.com/opensearch-project/OpenSearch/issues/11680
* New index_searcher threadpool and integrate it with Resource tracking framework. https://github.com/opensearch-project/OpenSearch/issues/7425
* New metrics related to concurrent search and wait time for search related threadpools.
** https://github.com/opensearch-project/OpenSearch/pull/9622
** https://github.com/opensearch-project/OpenSearch/pull/9681

* Dynamic way to enable/disable concurrent search. Followed by mechanism in the AggregationFactory to separate aggregations which supports concurrent search and determine at runtime if requests needs to be executed using concurrent vs non-concurrent path
** https://github.com/opensearch-project/OpenSearch/pull/7956
** https://github.com/opensearch-project/OpenSearch/pull/9469

**Issues:**
* Proactively followed up on a bug and facilitated the fix for that in 2.14 https://github.com/opensearch-project/OpenSearch/issues/13411

**Deep Dives:**
Evaluation to support force termination with terminate_after in concurrent search path https://github.com/opensearch-project/OpenSearch/issues/8371
Evaluation for Parent Join agg and Diversified Sampler for concurrent search support: https://github.com/opensearch-project/OpenSearch/issues/9316, https://github.com/opensearch-project/OpenSearch/issues/11075

The maintainers have voted and agreed to this nomination, following [the process here](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#nomination).

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- [ ] ~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [X] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sohami** [comment]
> ❕ Gradle check result for [40d45fe](https://github.com/opensearch-project/OpenSearch/commit/40d45fe5a3ce54fb905639d7928d6f6c632fbfc5): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/39038/)
> 
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.remotestore.RemoteStoreStatsIT.testNonZeroPrimaryStatsOnNewlyCreatedIndexWithZeroDocs
> ```
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

Known issue: https://github.com/opensearch-project/OpenSearch/issues/10983

**Comment by owaiskazi19** [comment]
> Tagging @dblock to help with the PR and permissions as mentioned [here](https://github.com/opensearch-project/.github/blob/main/ADMINS.md#addremove-maintainers)

@opensearch-project/admin

**Review by owaiskazi19 — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Review by peternied — APPROVED** [review]
Well deserved @jed326 !

**Comment by sohami** [comment]
> > Tagging @dblock to help with the PR and permissions as mentioned [here](https://github.com/opensearch-project/.github/blob/main/ADMINS.md#addremove-maintainers)
> 
> @opensearch-project/admin

Will wait for the @opensearch-project/admin team confirmation about permissions before merging this PR.

**Comment by rishabh6788** [comment]
Added @jed326 as maintainer.

**Pull request merged**
