### PR TITLE
Skip geojson test for version below 2.4

### PR DESCRIPTION
**Pull request by heemin32**
Signed-off-by: Heemin Kim <heemin@amazon.com>

### Description
Skip geojson test for version below 2.4

### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/4852

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by heemin32** [comment]
This PR need to be merged to make the test pass. https://github.com/opensearch-project/OpenSearch/pull/4842

**Comment by heemin32** [comment]
> The general best practice here, I think, is that on main you should put the skip to " - 2.99.99" since this feature only exists in 3.0 and newer for the moment. Then you can backport that commit, and in the backport PR you can change the skip value to " - 2.3.99" (or whatever is just below the next minor version on the backport branch). Then after the backport is committed, you can submit a new change to main to change the skip value to " - 2.3.99". I think that's the only way to do it without breaking things along the way.

Is it allowed to raise PR for 2.x first and another for main later? This will reduce the number of code changes and PR.

**Comment by andrross** [comment]
> Is it allowed to raise PR for 2.x first and another for main later?

Per our defined [branching strategy](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching), all merges should happen on main and be backported to the other branches.

**Comment by andrross** [comment]
@heemin32 #4842 has been merged, can you rebase this one to fix the changelog conflicts?

**Comment by andrross** [comment]
Created issue for previous test failure: #4881

**Review by andrross — APPROVED** [review]

**Comment by heemin32** [comment]
@andrross Thanks for the quick response!

**Pull request merged**
