### PR TITLE
Remove SEARCH_PIPELINE feature flag

### PR DESCRIPTION
**Pull request by noCharger**
### Description
Remove Search Pipeline SEARCH_PIPELINE feature flag.

Instead of flip the flag, remove the gating logic with some considerations:
1. We should be quite certain that having this feature enabled doesn’t negatively impact unrelated operations
2. We can always reset this PR for rollback
3. It's confusing to users by fliping the flag `opensearch.experimental.feature.search_pipeline.enabled`, from its naming the feature is still in experimental
4. We can also update the flag name and then set default to True, but it seems not a common practice. Open to feedbacks

Will have a follow up PR to remove the flag on bwc test once the this PR is backported

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/8489

### Check List
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by noCharger** [comment]
BWC test failed https://build.ci.opensearch.org/job/gradle-check/19371/testReport/

```
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test basic pipeline crud}	0.26 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Get All Pipelines}	0.22 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test invalid config}	0.23 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Put Versioned Pipeline}	0.22 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test basic pipeline crud}	1.2 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Get All Pipelines}	0.68 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test invalid config}	0.37 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Put Versioned Pipeline}	0.23 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test basic pipeline crud}	1.2 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Get All Pipelines}	0.68 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test invalid config}	0.36 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Put Versioned Pipeline}	0.22 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test basic pipeline crud}	1.2 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Get All Pipelines}	0.68 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test invalid config}	0.36 sec	1
 org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search_pipeline/10_basic/Test Put Versioned Pipeline}	0.22 sec	1
```

While same test case passed test.rest [suite](https://build.ci.opensearch.org/job/gradle-check/19371/testReport/org.opensearch.test.rest/ClientYamlTestSuiteIT/)

```
test {p0=search_pipeline/10_basic/Test Get All Pipelines} | 0.3 sec | Passed
test {p0=search_pipeline/10_basic/Test Put Versioned Pipeline} | 0.66 sec | Passed
test {p0=search_pipeline/10_basic/Test basic pipeline crud} | 0.6 sec | Passed
test {p0=search_pipeline/10_basic/Test invalid config} | 0.21 sec | Passed
```

**Comment by andrross** [comment]
Maybe you need to keep the `setting 'opensearch.experimental.feature.search_pipeline.enabled', 'true'` setting for the mixed cluster so that setting gets applied against the 2.x version which still requires the feature flag? (at least until after this change is backported)

**Comment by noCharger** [comment]
> Maybe you need to keep the `setting 'opensearch.experimental.feature.search_pipeline.enabled', 'true'` setting for the mixed cluster so that setting gets applied against the 2.x version which still requires the feature flag? (at least until after this change is backported)

This works. Thanks for the great suggestion!

```
./gradlew ':qa:mixed-cluster:v2.9.0#mixedClusterTest'

 [2.9.0] BUILD SUCCESSFUL in 6m 38s
 [2.9.0] 170 actionable tasks: 170 executed

BUILD SUCCESSFUL in 8m 12s
```

**Comment by noCharger** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/19476/
> * **CommitID:** [6861c1d](https://github.com/opensearch-project/OpenSearch/commit/6861c1d017b756c3c207a94e6d009a863a78819d)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

This is the bug involved in by https://github.com/opensearch-project/OpenSearch/pull/7253. The`this.state` is not initialized when search pipeline service being invoked implictly. See example below:

```
  2> java.lang.AssertionError: java.lang.NullPointerException: Cannot invoke "org.opensearch.cluster.ClusterState.metadata()" because "this.state" is null
        at __randomizedtesting.SeedInfo.seed([393175DBBB04872C:506F44A03D8F838C]:0)
        at org.opensearch.snapshots.SnapshotResiliencyTests.lambda$continueOrDie$88(SnapshotResiliencyTests.java:1435)
        at org.opensearch.action.ActionListener$1.onFailure(ActionListener.java:88)
        at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54)
        at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
        at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120)
        at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112)
        at java.****/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112)
        at org.opensearch.common.util.concurrent.BaseFuture.setException(BaseFuture.java:178)
        at org.opensearch.common.util.concurrent.ListenableFuture.onFailure(ListenableFuture.java:149)
        at org.opensearch.action.StepListener.innerOnFailure(StepListener.java:82)
        at org.opensearch.action.NotifyOnceListener.onFailure(NotifyOnceListener.java:62)
        at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122)
        at org.opensearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:402)
        at org.opensearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:289)
        at org.opensearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:127)
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218)
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188)
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107)
        at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110)
        at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97)
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:476)
        at org.opensearch.client.support.AbstractClient.search(AbstractClient.java:607)
        at org.opensearch.snapshots.SnapshotResiliencyTests.lambda$testSuccessfulSnapshotWithConcurrentDynamicMappingUpdates$65(SnapshotResiliencyTests.java:1172)
        at org.opensearch.action.ActionListener$1.onResponse(ActionListener.java:80)
        at org.opensearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:126)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341)
        at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120)
        at org.opensearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:112)
        at java.****/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.opensearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:112)
        at org.opensearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:160)
        at org.opensearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:141)
        at org.opensearch.action.StepListener.innerOnResponse(StepListener.java:77)
        at org.opensearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:55)
        at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:113)
        at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:107)
        at org.opensearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:181)
        at org.opensearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:69)
        at org.opensearch.transport.TransportService$6.handleResponse(TransportService.java:867)
        at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1471)
        at org.opensearch.test.transport.MockTransport.handleResponse(MockTransport.java:122)
        at org.opensearch.test.disruption.DisruptableMockTransport$4$1.run(DisruptableMockTransport.java:227)
        at org.opensearch.cluster.coordination.AbstractCoordinatorTestCase$1.run(AbstractCoordinatorTestCase.java:1468)
        at org.opensearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:146)
        at org.opensearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:140)
        at org.opensearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:90)
        at org.opensearch.snapshots.SnapshotResiliencyTests.runUntil(SnapshotResiliencyTests.java:1407)
        at org.opensearch.snapshots.SnapshotResiliencyTests.testSuccessfulSnapshotWithConcurrentDynamicMappingUpdates(SnapshotResiliencyTests.java:1197)

        Caused by:
        java.lang.NullPointerException: Cannot invoke "org.opensearch.cluster.ClusterState.metadata()" because "this.state" is null
            at org.opensearch.search.pipeline.SearchPipelineService.resolvePipeline(SearchPipelineService.java:395)
            at org.opensearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:396)
            ... 36 more
```

The [quick fix](https://github.com/opensearch-project/OpenSearch/pull/8513/commits/8f5000b86ead237ee4e897c8803d11280fc87a17) doesn't fully address the issue. Need further investigation.

**Comment by msfroh** [comment]
> The [quick fix](https://github.com/opensearch-project/OpenSearch/pull/8513/commits/8f5000b86ead237ee4e897c8803d11280fc87a17) doesn't fully address the issue. Need further investigation.

If the cluster state hasn't been applied to the `SearchPipelineService`, then I don't think we should use an index default pipeline.

That is, I think you can modify line 393 to be

```
} else if (state != null && searchRequest.indices() != null && searchRequest.indices().length == 1 ) {
```

That said, I don't understand why `SearchPipelineService` would not have had a cluster state applied, since I'm not familiar with the cluster state application lifecycle. Maybe this test involves a node that is not fully initialized yet?

**Comment by msfroh** [comment]
```
 »  SettingsException[unknown setting [opensearch.experimental.feature.search_pipeline.enabled] did you mean any of [opensearch.experimental.feature.remote_store.enabled, opensearch.experimental.feature.extensions.enabled, opensearch.experimental.feature.identity.enabled, opensearch.experimental.feature.telemetry.enabled]?]
```

If I recall correctly, we're able to conditionally set the flag from Gradle for nodes with specific versions. I had to do something like that on the 2.x branch to avoid setting the flag on mixed cluster tests with 1.3: https://github.com/opensearch-project/OpenSearch/blob/2.x/qa/mixed-cluster/build.gradle#L67

```
      if (bwcVersion.onOrAfter("2.7.0")) {
        setting 'opensearch.experimental.feature.search_pipeline.enabled', 'true'
      }
```

**Comment by noCharger** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/19758/
> * **CommitID:** [65c6ee8](https://github.com/opensearch-project/OpenSearch/commit/65c6ee8e407b39d0f547e9f7ddcb18a3539b8b20)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test
```
 % ./gradlew ':server:test' --tests "org.opensearch.action.admin.cluster.node.tasks.ResourceAwareTasksTests.*"                    

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.2
  OS Info               : Mac OS X 13.3.1 (x86_64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
  Random Testing Seed   : 44DE34F7F3D7B59D
  In FIPS 140 mode      : false
=======================================

> Task :server:test
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/Volumes/workplace/OS-louis-dev/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/Users/clingzhi/.gradle/wrapper/dists/gradle-8.2-all/6mxqtxovn2faat1idb7p6lxsa/gradle-8.2/lib/plugins/gradle-testing-base-8.2.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 16s
47 actionable tasks: 1 executed, 46 up-to-date

```

**Comment by tlfeng** [comment]
The above flaky test failure occurred in https://build.ci.opensearch.org/job/gradle-check/19758/ is reported in issue https://github.com/opensearch-project/OpenSearch/issues/8213

**Comment by noCharger** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/19760/
> * **CommitID:** [65c6ee8](https://github.com/opensearch-project/OpenSearch/commit/65c6ee8e407b39d0f547e9f7ddcb18a3539b8b20)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Another flaky test
```
OpenSearch % ./gradlew ':server:test' --tests "org.opensearch.index.shard.RemoteStoreRefreshListenerTests.*"                                

> Configure project :
========================= WARNING =========================
         Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.2
  OS Info               : Mac OS X 13.3.1 (x86_64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
  Random Testing Seed   : 277D10DB372BCC05
  In FIPS 140 mode      : false
=======================================

> Task :server:test
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/Volumes/workplace/OS-louis-dev/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/Users/clingzhi/.gradle/wrapper/dists/gradle-8.2-all/6mxqtxovn2faat1idb7p6lxsa/gradle-8.2/lib/plugins/gradle-testing-base-8.2.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 29s
47 actionable tasks: 1 executed, 46 up-to-date
```

**Comment by noCharger** [comment]
> ```
>  »  SettingsException[unknown setting [opensearch.experimental.feature.search_pipeline.enabled] did you mean any of [opensearch.experimental.feature.remote_store.enabled, opensearch.experimental.feature.extensions.enabled, opensearch.experimental.feature.identity.enabled, opensearch.experimental.feature.telemetry.enabled]?]
> ```
> 
> If I recall correctly, we're able to conditionally set the flag from Gradle for nodes with specific versions. I had to do something like that on the 2.x branch to avoid setting the flag on mixed cluster tests with 1.3: https://github.com/opensearch-project/OpenSearch/blob/2.x/qa/mixed-cluster/build.gradle#L67
> 
> ```
>       if (bwcVersion.onOrAfter("2.7.0")) {
>         setting 'opensearch.experimental.feature.search_pipeline.enabled', 'true'
>       }
> ```
> 
> So, you would need to set the flag for versions before 3.0.0 in this PR. Once you backport to 2.x, you need to come back to main and remove it altogether.

It seems like [this commit](https://github.com/opensearch-project/OpenSearch/pull/8513/commits/65c6ee8e407b39d0f547e9f7ddcb18a3539b8b20) doesn't address the [issue ](https://build.ci.opensearch.org/job/gradle-check/19762/console)

```
»  SettingsException[unknown setting [opensearch.experimental.feature.search_pipeline.enabled] did you mean any of [opensearch.experimental.feature.remote_store.enabled, opensearch.experimental.feature.extensions.enabled, opensearch.experimental.feature.identity.enabled, opensearch.experimental.feature.telemetry.enabled]?]
```

**Comment by msfroh** [comment]
Another option might be to make the change across a few steps:
1. Keep the setting, but make it `true` by default.
2. Backport that to 2.x
3. Stop enabling the setting for mixed cluster tests (because it is enabled on main and 2.x).
4. Remove the setting.

**Comment by noCharger** [comment]
> Another option might be to make the change across a few steps:
> 
> 1. Keep the setting, but make it `true` by default.
> 2. Backport that to 2.x
> 3. Stop enabling the setting for mixed cluster tests (because it is enabled on main and 2.x).
> 4. Remove the setting.

Close this PR and track on https://github.com/opensearch-project/OpenSearch/pull/8613

**Comment by macohen** [comment]
@saratvemulapalli just a heads up - there's a new revision of this coming from @noCharger removing the feature flag completely that we need to get merged before the next RC.

**Comment by noCharger** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/20353/
> * **CommitID:** [ac53d93](https://github.com/opensearch-project/OpenSearch/commit/ac53d939918e38930ef7e22af3fd9ece05a6eb1c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test https://build.ci.opensearch.org/job/gradle-check/20353/testReport/org.opensearch.action.admin.cluster.node.tasks/ResourceAwareTasksTests/testBasicTaskResourceTracking/

**Comment by noCharger** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/20359/
> * **CommitID:** [ac53d93](https://github.com/opensearch-project/OpenSearch/commit/ac53d939918e38930ef7e22af3fd9ece05a6eb1c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

```
»  org.opensearch.bootstrap.StartupException: SettingsException[unknown setting [opensearch.experimental.feature.search_pipeline.enabled] did you mean any of [opensearch.experimental.feature.remote_store.enabled, opensearch.experimental.feature.extensions.enabled, opensearch.experimental.feature.identity.enabled, opensearch.experimental.feature.telemetry.enabled]?]
```
This is expected to be addressed after this PR backported. See https://github.com/opensearch-project/OpenSearch/pull/8513#issuecomment-1629852935 for details

**Review by macohen — APPROVED** [review]
I don’t see any flags left over and the backport will fix the 2.x issue.

**Comment by noCharger** [comment]
```
 ./gradlew ':qa:mixed-cluster:v2.10.0#mixedClusterTest'
BUILD SUCCESSFUL in 9m 13s

```
Local test passed after 2.x and 2.9 merged in

**Review by dblock — APPROVED** [review]

**Pull request merged**
