### PR TITLE
Revert to Netty 4.1.79.Final

### PR DESCRIPTION
**Pull request by cwperks**
Signed-off-by: Craig Perkins <cwperx@amazon.com>

### Description

See related issue: https://github.com/opensearch-project/OpenSearch/issues/4427

The last minor version of Netty included a change to eagerly load certificates using BouncyCastle if BouncyCastle is on the classpath: https://github.com/netty/netty/pull/12670

This change has led to errors on startup with the security plugin (See https://github.com/opensearch-project/OpenSearch/issues/4427) because of a bug in checking all required BouncyCastle dependencies (See https://github.com/netty/netty/pull/12743)

There is another bug related to the change that impacts custom bundles for private keys (https://github.com/netty/netty/pull/12746). Both bugs have since been fixed and are targeted for the next 4.1.X release of netty.

This PR reverts netty until the next 4.1.X (4.1.81.Final) release. The full list of changes in netty 4.1.80.Final can be found [here](https://netty.io/news/2022/08/26/4-1-80-Final.html)

### Issues Resolved

https://github.com/opensearch-project/OpenSearch/issues/4427

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]
When this change was added it destabilized the security plugin, lets revert to the last known good version of netty until we know this issue is resolved.

**Review by dreamer-89 — APPROVED** [review]

**Comment by reta** [comment]
@cwperks all backports failed :( I think 1.3 and 2.x would a priority to get it before the release

**Comment by cwperks** [comment]
@reta I created manual backports for 2.x and 1.3.

- 2.x - https://github.com/opensearch-project/OpenSearch/pull/4432
- 1.3 - https://github.com/opensearch-project/OpenSearch/pull/4433

**Comment by cwperks** [comment]
Remaining manual backport PRs have been created:

- https://github.com/opensearch-project/OpenSearch/pull/4438
- https://github.com/opensearch-project/OpenSearch/pull/4439
- https://github.com/opensearch-project/OpenSearch/pull/4440
- https://github.com/opensearch-project/OpenSearch/pull/4441

**Pull request merged**
