### PR TITLE
Remove S3 cooldown period setting

### PR DESCRIPTION
**Pull request by BhumikaSaini-Amazon**
### Description
This PR removes the `COOLDOWN_PERIOD` setting for `S3Repository`. This does not exist in `main` but still exists in `2.x`.

### Related Issues
N/A

### Check List
- [x] ~New functionality includes testing.~
  - [ ] All tests pass
- [x] ~New functionality has been documented.~
  - [x] ~New functionality has javadoc added~
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] ~GitHub issue/PR created in [OpenSearch documentation repo](https://github.com/opensearch-project/documentation-website) for the required public documentation changes (#[Issue/PR number])~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Poojita-Raj** [comment]
User facing change so we'll need to add in a changelog entry.

**Comment by kotwanikunal** [comment]
I think it exists because it will be breaking for `2.x`.
Breaking changes are addressed as a part of major version releases.

**Review by kotwanikunal — CHANGES_REQUESTED** [review]
Change will be breaking for `2.x`

**Comment by BhumikaSaini-Amazon** [comment]
Makes sense @kotwanikunal. Closing this PR. Thanks!

**Pull request closed without merging**
