### PR TITLE
Adding Github action for auto backport PR creation

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha <vachshah@amazon.com>

### Description
This Github action creates backport PR automatically when appropriate labels are added to the PR on main. Once the original PR gets merged to main, this Github action will open backport PR. For example, if we want to backport a PR to 1.x, add label `backport 1.x` to the original PR, once this PR is merged, the Github action will open a backport to 1.x PR from the original PR.

Reference: https://github.com/marketplace/actions/backporting
I tried this on my own repo and was able to create appropriate backport PRs. Example: https://github.com/VachaShah/TestGithubActions/pull/7
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CEHENKLE** [comment]
Thanks for finding this, @VachaShah  Very cool :)

**Review by dblock — APPROVED** [review]
I think it's worth adding a "backports" section to https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md as well.

Once we are happy with this, let's run a campaign for 1.3 to add this to all plugins/components?

**Comment by dblock** [comment]
@VachaShah Feel free to merge! Want to create some backport labels, especially for `1.x` branch, too?

**Comment by VachaShah** [comment]
> @VachaShah Feel free to merge! Want to create some backport labels, especially for `1.x` branch, too?

Thanks @dblock ! I added the details in the `DEVELOPER_GUIDE.md` for auto backports. Will create backport labels as well.

**Comment by VachaShah** [comment]
> > @VachaShah Feel free to merge! Want to create some backport labels, especially for `1.x` branch, too?
> 
> Thanks @dblock ! I added the details in the `DEVELOPER_GUIDE.md` for auto backports. Will create backport labels as well.

Hi @dblock , looks like I don't have permissions to create labels on the repo.

**Comment by VachaShah** [comment]
@dblock Can you merge this PR?

**Review by saratvemulapalli — APPROVED** [review]
Love it!

**Comment by dblock** [comment]
@VachaShah 

1. Did you resolve the labels problem?
2. Should we run a campaign in 1.3 to use this workflow for all plugins? If yes, start by creating a parent issue in https://github.com/opensearch-project/opensearch-plugins/issues similar to https://github.com/opensearch-project/opensearch-plugins/issues/64 and link it from campaigns in https://github.com/opensearch-project/opensearch-build/issues/889

**Comment by saratvemulapalli** [comment]
I believe this would help all the repositories in the opensearch-project. 
Instead of https://github.com/opensearch-project/opensearch-plugins, can we create an issue and document it in https://github.com/opensearch-project/.github?

**Comment by dblock** [comment]
> I believe this would help all the repositories in the opensearch-project. Instead of https://github.com/opensearch-project/opensearch-plugins, can we create an issue and document it in https://github.com/opensearch-project/.github?

That would be in https://github.com/opensearch-project/project-meta maybe? Either way, I want to make sure we can track that campaign for _plugins_ as part of an OpenSearch release, separately, as well.

**Comment by VachaShah** [comment]
> @VachaShah
> 
> 1. Did you resolve the labels problem?
> 2. Should we run a campaign in 1.3 to use this workflow for all plugins? If yes, start by creating a parent issue in https://github.com/opensearch-project/opensearch-plugins/issues similar to [Default CI Java Version to Java 11, run tests on 8, 14 and 17 opensearch-plugins#64](https://github.com/opensearch-project/opensearch-plugins/issues/64) and link it from campaigns in [[RELEASE] Release version 1.3.0 opensearch-build#889](https://github.com/opensearch-project/opensearch-build/issues/889)

@dblock, yes the OpenSearch label was created and I will do the same for other repos. I will create the parent issue shortly for other repos and track one for plugins as well.

**Pull request merged**
