### PR TITLE
Bump com.github.spullara.mustache.java:compiler from 0.9.10 to 0.9.11

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Manually creating a version bump of com.github.spullara.mustache.java:compiler from 0.9.10 to 0.9.11 because the [dependabot PR](https://github.com/opensearch-project/OpenSearch/pull/10636) has been having issues with the gradle check.

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
Looks like changes in modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/20_render_search_template.yml came for the ride.

**Comment by cwperks** [comment]
@dblock The dependabot PR is failing on that test. 

ref: https://build.ci.opensearch.org/job/gradle-check/30414/console

I had to update the test for this dependency update.

**Comment by dblock** [comment]
@cwperks I assume that addition to including the field in the catch is expected?

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Another backport bites the dust @cwperks please.

**Comment by cwperks** [comment]
@dblock Here's the backport: https://github.com/opensearch-project/OpenSearch/pull/13353

Yes there was a change in the error message in the library and the test expected the message in a certain format.  See the change [here](https://github.com/spullara/mustache.java/commit/a05a3ff3cf8675d1225f2e6b7cff2988ee80ad69)

**Pull request merged**
