### PR TITLE
Fix bwc version for concurrent segment search stats

### PR DESCRIPTION
**Pull request by jed326**
### Description
Fix the bwc for concurrent segment search stats. This PR is to be merged alongside 
* https://github.com/opensearch-project/OpenSearch/pull/9653

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
@reta I don't think we need a changelog entry for this PR but let me know if you disagree and would like me to add one. Thanks!

**Comment by reta** [comment]
@jed326 large number of failing BWC tests, seems to be legit and related to this pull request

**Comment by jed326** [comment]
There are bwc tests failing but they don't look related to the concurrent search stats, looks mostly related to snapshots

**Comment by reta** [comment]
@jed326 could you please rebase against latest `main`?

**Comment by reta** [comment]
Here we are https://github.com/opensearch-project/OpenSearch/pull/9745

**Comment by reta** [comment]
@jed326 OK, the snapshots should be fixed, could you rebase please against latest `main`?

**Comment by jed326** [comment]
@reta will do shortly. Thanks!

**Comment by jed326** [comment]
Alright rebased branch https://github.com/jed326/OpenSearch/tree/backport-fix-9653 against `main`, hopefully the tests pass now.

**Comment by reta** [comment]
We have another one here, https://github.com/opensearch-project/OpenSearch/commit/24862c190f4a9d3ed16908d9b6a2ebf7067193f1, the version update was not backported to `main`

**Comment by reta** [comment]
Merging with failing Gradle check since there was another change on `2.x` that has not been backported, https://github.com/opensearch-project/OpenSearch/pull/9736

**Review by reta — APPROVED** [review]

**Comment by jed326** [comment]
> We have another one here, [24862c1](https://github.com/opensearch-project/OpenSearch/commit/24862c190f4a9d3ed16908d9b6a2ebf7067193f1), the version update was not backported to `main`

Good catch, thanks @reta!

**Pull request merged**
