### PR TITLE
Update 2.4.1 release notes

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update 2.4.1 release notes

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dreamer-89 @owaiskazi19 please

**Comment by owaiskazi19** [comment]
@reta should we include https://github.com/opensearch-project/OpenSearch/pull/5546 also here?

**Review by dreamer-89 — APPROVED** [review]

**Comment by dreamer-89** [comment]
> @reta should we include #5546 also here?

Looks like whitesource security scan is failing here. Re-running it will take a lot of time. @reta : Any concerns not including #5546 

https://github.com/opensearch-project/OpenSearch/pull/5546/checks?check_run_id=10070689281

**Comment by reta** [comment]
> Any concerns not including #5546

@dreamer-89 no concerns from me, but indeed whitesource check is failing across many pull requests :(

**Pull request merged**
