### PR TITLE
[Backport] [2.x] Update to Apache Lucene 9.11.0

### PR DESCRIPTION
**Pull request by reta**
### Description
Update to Apache Lucene 9.11.0

### Related Issues
N/A

### Check List
- [X] Functionality includes testing.
- [X] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
The merge should happen once 2.15.0 branch is cut, as we agreed that Apache Lucene 9.11.0 should go to `2.16.0`

**Comment by naveentatikonda** [comment]
@dblock @reta Can we merge this PR as 2.15 branch cut is done

**Comment by reta** [comment]
> @dblock @reta Can we merge this PR as 2.15 branch cut is done

Sure, I just need an approval :-)

**Comment by reta** [comment]
@andrross @dblock @msfroh folks, mind please approving this backport? thank you!

**Review by andrross — APPROVED** [review]

**Pull request merged**
