### PR TITLE
Named queries should return their internal score as well

### PR DESCRIPTION
**Pull request by synhershko**
### Description

While some internal queries may not be scored or not contrbute to the final doc score, in some cases (such as knn queries compbined with other queries) the distance metric is very interesting and should be reported back as part of the response.

This change adds that by default, so named queries always return the score (instead of just the name). It adds no additional cost.

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
  - [ ] Backwards compatibility tests fail - let's have a discussion about what should be expected here since the response format did change when named queries are enabled
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — COMMENTED** [review]
LGTM, do you have an example of before/after response?

**Comment by synhershko** [comment]
> Thanks! LGTM, iterate to green ... do you have an example of before/after response?

Of course. Current behavior of OpenSearch when named queries are enabled, is to return an array like this:

```json
         "hits" : [
           {
              "_index" : "test",
              "_id" : "2",
              "_score" : 1.6207318,
              "_source" : {
                "foo" : "bar",
                "foo2" : "bar2"
              },
              "matched_queries" : ["foo2_query", "foo_query"]
            },
            {
              "_index" : "test",
              "_id" : "1",
              "_score" : 0.18232156,
              "_source" : {
                "foo" : "bar"
              },
              "matched_queries" : ["foo_query"]
            }
          ]
```

This PR changes the behavior so an object (query name -> score) is returned instead:

```json
         "hits" : [
           {
              "_index" : "test",
              "_id" : "2",
              "_score" : 1.6207318,
              "_source" : {
                "foo" : "bar",
                "foo2" : "bar2"
              },
              "matched_queries" : {
                "foo2_query" : 1.4384103,
                "foo_query" : 0.2876821
              }
            },
            {
              "_index" : "test",
              "_id" : "1",
              "_score" : 0.18232156,
              "_source" : {
                "foo" : "bar"
              },
              "matched_queries" : {
                "foo_query" : 0.2876821
              }
            }
          ]
```

As indicated in the PR description,  backwards compatibility tests fail and I'm waiting your guidance as to what should be expected here since the response format did change when named queries are enabled

**Comment by dblock** [comment]
These are the days I wish this was a GraphQL interface :(

1. Should we make this future-compatible with additional fields?

```
"matched_queries" : {
     "foo_query" : {
        "score": 0.2876821
    }
}
```

2. As is it's a breaking change. We can make it in 3.0, but we would rather not in order to be able to backport the change into 2.x and ship it earlier, and to avoid breaking a bunch of clients. Maybe we can supply a new option into the named query, or a query parameter, e.g. `matched_queries: showmeallthecoolinfoyougot`? Is there similar precedent anywhere else? @macohen might know, too.

**Comment by synhershko** [comment]
> Should we make this future-compatible with additional fields?

What additional fields? :)

> As is it's a breaking change. We can make it in 3.0, but we would rather not in order to be able to backport the change into 2.x and ship it earlier, and to avoid breaking a bunch of clients.

I'm all in for releasing early - we have a customer waiting for that to be merged in :) Fixing wire backwards compatibility is easy inter-node, but clients will break because you can't touch older versions.

What I'd recommend then is using a feature flag, only returning score if named queries was requested and a query parameter (or other form of passing this flag) was passed asking for scores too. That'd mean clients will need to be asked to add support for this flag starting at the release version. WDYT?

**Comment by dblock** [comment]
> > Should we make this future-compatible with additional fields?
> 
> What additional fields? :)

So let's do it? It also makes clear what this numeric value is. 

> > As is it's a breaking change. We can make it in 3.0, but we would rather not in order to be able to backport the change into 2.x and ship it earlier, and to avoid breaking a bunch of clients.
> 
> I'm all in for releasing early - we have a customer waiting for that to be merged in :) Fixing wire backwards compatibility is easy inter-node, but clients will break because you can't touch older versions.

I know we all love our customers, but let's not create more work for others.

> What I'd recommend then is using a feature flag, only returning score if named queries was requested and a query parameter (or other form of passing this flag) was passed asking for scores too. That'd mean clients will need to be asked to add support for this flag starting at the release version. WDYT?

The problem with a feature flag is that it's not a permanent solution and we have dozens of clients. Can we try to at least discuss designing something durable and backwards compatible? Want to suggest a query addition and look for other cases where we have something like this?

**Comment by synhershko** [comment]
> Can we try to at least discuss designing something durable and backwards compatible? Want to suggest a query addition and look for other cases where we have something like this?

Sure I'm all ears.

I think if feature flag is not an option, then the next best route here is to support named queries (`_name`) and named with score (`_named_with_score`).

I don't think you can escape the fact all clients will need to be updated with this new feature but at least we don't break them?

**Comment by dblock** [comment]
So what you're suggesting is deprecating `matched_queries` in 2.x and potentially removing it in 3.0? I like it. We could do this:

```
"matched" : {
  "queries" : {
     "foo_query" : {
       "score" : 123
    }
 }
}
```

Curious whether it's an overkill? @andrross @reta wdyt?

**Comment by synhershko** [comment]
> So what you're suggesting is deprecating `matched_queries` in 2.x and potentially removing it in 3.0? I like it.

No, I think we should keep in line with the old response format - named queries are with us for many years and I think we should keep it the same as it was before. I woudln't deprecate, just find a way to add those scores to either the same response format, or by adding another field in the response.

**Comment by synhershko** [comment]
+1 for using a query string parameter as a feature flag, we can support it as a property too

**Comment by reta** [comment]
> +1 for using a query string parameter as a feature flag, we can support it as a property too

@dblock wdyt?

**Comment by andrross** [comment]
> > +1 for using a query string parameter as a feature flag, we can support it as a property too
> 
> @dblock wdyt?

@reta @synhershko I'm not opposed to this, but I would rename the query string parameter to something like `detailed_matched_queries` or `verbose_matched_queries`. `track_matched_query_scores` would be obsolete/confusing if additional details are added.

**Comment by andrross** [comment]
> > > Should we make this future-compatible with additional fields?
> > 
> > 
> > What additional fields? :)
> 
> So let's do it? It also makes clear what this numeric value is.

@dblock @synhershko I'm definitely in favor of the more verbose format simply because it is self-documenting with a score label, even if we never add additional fields.

**Comment by synhershko** [comment]
I'm just wondering what additional details we can provide there in the future? I'm calling YAGNI on it and let's do something simple that works first and worry about the rest later. I just don't see anything else we can possible want to provide other than score.

**Comment by macohen** [comment]
I understand why we would want the query string parameter here, but, to answer @dblock's question for me, I don't know of any precedent for this in OpenSearch. Even the query_string function is all in the body of the request and I really like that about OpenSearch (as a former old-school Solr user). I don't have a better answer for this either that doesn't create a breaking change to push this to 3.0 unfortunately.

**Comment by dblock** [comment]
Let's make a breaking change for 3.0 in this PR?

**Comment by kotwanikunal** [comment]
Apologies. This PR was auto closed without reaching a resolution from the maintainers. 
Re-opening to move it forward.
Thanks for your contributions to OpenSearch!

**Comment by synhershko** [comment]
Thanks @kotwanikunal looking forward to final decision, let's get this in!

**Comment by ticheng-aws** [comment]
Hi @synhershko, the PR is stalled. Is this being worked upon? Feel free to reach out to maintainers for further reviews.

**Comment by synhershko** [comment]
@ticheng-aws I'm well aware this is stalled, see my comment https://github.com/opensearch-project/OpenSearch/pull/7883#issuecomment-1721051791 and previous discussions. When maintainers pick it up and conclude their discussion I'm happy to pick it up again.

**Comment by synhershko** [comment]
cc @dblock @macohen

**Comment by dblock** [comment]
I think https://github.com/opensearch-project/OpenSearch/pull/7883#issuecomment-1599253471 is still accurate? A breaking change for `main`, do we need more maintainers to pitch in? WDYT @msfroh / @andrross?

**Comment by andrross** [comment]
> I think [#7883 (comment)](https://github.com/opensearch-project/OpenSearch/pull/7883#issuecomment-1599253471) is still accurate? A breaking change for `main`, do we need more maintainers to pitch in?

@dblock I agree with your suggestion. I'll ship this PR as a breaking change to main with the structure you proposed. I think we can deliver this in 2.x with some sort of yet-to-be-decided opt-in mechanism as well, but we can work that out once this has landed in main.

**Comment by reta** [comment]
@dblock @andrross I believe the feature is already integrated https://github.com/opensearch-project/OpenSearch/pull/11626

**Comment by dblock** [comment]
@synhershko take a look? what shall we do with this PR?

**Comment by andrross** [comment]
I believe this has been implemented in #11626. I'm going to close this. @synhershko Please do speak up if #11626 doesn't solve your problem.

**Pull request closed without merging**
