### PR TITLE
[Backport 1.x] Bouncycastle upgrade 1.x

### PR DESCRIPTION
**Pull request by saratvemulapalli**
### Description
Backport #1832 to 1.x
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by owaiskazi19 — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Check failure [bc60e30](https://github.com/opensearch-project/OpenSearch/commit/bc60e30079c388bae84b14d8ae75c7294de418aa) [Log 1754](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1754.log)
> 
> [Reports 1754](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1754_reports.zip)

Looks unrelated error to me. I'll give it another shot while reporting this to flaky tests.
```
REPRODUCE WITH: ./gradlew ':plugins:transport-nio:test' --tests "org.opensearch.http.nio.NioHttpServerTransportTests.testLargeCompressedResponse" -Dtests.seed=EA1764D9DE4EEADD -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=no -Dtests.timezone=America/Maceio -Druntime.java=15

org.opensearch.http.nio.NioHttpServerTransportTests > testLargeCompressedResponse FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=183, name=opensearch[transport_worker][T#1], state=RUNNABLE, group=TGRP-NioHttpServerTransportTests]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([EA1764D9DE4EEADD]:0)
            at org.opensearch.http.nio.NioHttpServerTransportTests$3.dispatchRequest(NioHttpServerTransportTests.java:351)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=184, name=opensearch[transport_worker][T#2], state=RUNNABLE, group=TGRP-NioHttpServerTransportTests]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([EA1764D9DE4EEADD]:0)
            at org.opensearch.http.nio.NioHttpServerTransportTests$3.dispatchRequest(NioHttpServerTransportTests.java:351)
```

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Check failure [bc60e30](https://github.com/opensearch-project/OpenSearch/commit/bc60e30079c388bae84b14d8ae75c7294de418aa) [Log 1752](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1752.log)
> 
> [Reports 1752](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1752_reports.zip)

```
REPRODUCE WITH: ./gradlew ':distribution:tools:upgrade-cli:test' --tests "org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution" -Dtests.seed=1F6F70AEA6323361 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms-MY -Dtests.timezone=America/Araguaina -Druntime.java=15

org.opensearch.upgrade.DetectEsInstallationTaskTests > testTaskExecution FAILED
    java.lang.AssertionError: 
    Expected: a collection with size <0>
         but: collection size was <5>
        at __randomizedtesting.SeedInfo.seed([1F6F70AEA6323361:5575542572657CE4]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution(DetectEsInstallationTaskTests.java:53)


Suite: Test class org.opensearch.upgrade.DetectEsInstallationTaskTests
  1> [2022-01-03T14:53:51,848][INFO ][o.o.u.DetectEsInstallationTaskTests] [testTaskExecution] before test
  1> [2022-01-03T14:53:53,132][INFO ][o.o.u.DetectEsInstallationTaskTests] [testTaskExecution] after test
  2> REPRODUCE WITH: ./gradlew ':distribution:tools:upgrade-cli:test' --tests "org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution" -Dtests.seed=1F6F70AEA6323361 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ms-MY -Dtests.timezone=America/Araguaina -Druntime.java=15
  2> java.lang.AssertionError: 
    Expected: a collection with size <0>
         but: collection size was <5>
        at __randomizedtesting.SeedInfo.seed([1F6F70AEA6323361:5575542572657CE4]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.opensearch.upgrade.DetectEsInstallationTaskTests.testTaskExecution(DetectEsInstallationTaskTests.java:53)
  1> [2022-01-03T14:53:53,273][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveDefaultUrlFromConfig] before test
  1> [2022-01-03T14:53:53,281][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveDefaultUrlFromConfig] after test
  1> [2022-01-03T14:53:53,304][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveUrlFromSettings] before test
  1> [2022-01-03T14:53:53,311][INFO ][o.o.u.DetectEsInstallationTaskTests] [testRetrieveUrlFromSettings] after test
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/tools/upgrade-cli/build/testrun/test/temp/org.opensearch.upgrade.DetectEsInstallationTaskTests_1F6F70AEA6323361-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=289, maxMBSortInHeap=6.155808444014184, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ms-MY, timezone=America/Araguaina
  2> NOTE: Linux 5.4.0-1045-aws amd64/AdoptOpenJDK 15.0.1 (64-bit)/cpus=72,threads=1,free=401056352,total=536870912
  2> NOTE: All tests run in this JVM: [DetectEsInstallationTaskTests]
```

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Check failure [bc60e30](https://github.com/opensearch-project/OpenSearch/commit/bc60e30079c388bae84b14d8ae75c7294de418aa) [Log 1766](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1766.log)
> 
> [Reports 1766](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1766_reports.zip)

Another new failure :/

```
REPRODUCE WITH: ./gradlew ':modules:transport-netty4:test' --tests "org.opensearch.http.netty4.Netty4HttpServerTransportTests.testLargeCompressedResponse" -Dtests.seed=49B97FF7A35F7849 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sl -Dtests.timezone=Europe/Uzhgorod -Druntime.java=15

org.opensearch.http.netty4.Netty4HttpServerTransportTests > testLargeCompressedResponse FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=273, name=Thread-5, state=RUNNABLE, group=TGRP-Netty4HttpServerTransportTests]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([49B97FF7A35F7849]:0)
            at org.opensearch.http.netty4.Netty4HttpServerTransportTests$3.dispatchRequest(Netty4HttpServerTransportTests.java:357)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=275, name=Thread-6, state=RUNNABLE, group=TGRP-Netty4HttpServerTransportTests]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([49B97FF7A35F7849]:0)
            at org.opensearch.http.netty4.Netty4HttpServerTransportTests$3.dispatchRequest(Netty4HttpServerTransportTests.java:357)
```

**Comment by saratvemulapalli** [comment]
start gradle check

**Pull request merged**
