### PR TITLE
[Bug] Fix InstallPluginCommand to use proper key signatures

### LINKED ISSUE #996: [BUG] Native Plugin Installation request for .asc and OpenSearch repo has the wrong Public Key
**Describe the bug**

Two issues:

1. When install the native plugin directly, `opensearch-plugin` request to use `.asc` file for validation instead of `.sig` file, which we included in the signing and release process.

```
$ ./opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
[=================================================] 100%
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/releases/plugins/repository-s3/1.0.0/repository-s3-1.0.0.zip.asc
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1167)
	at org.opensearch.plugins.InstallPluginCommand.urlOpenStream(InstallPluginCommand.java:482)
	at org.opensearch.plugins.InstallPluginCommand.verifySignature(InstallPluginCommand.java:622)
	at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:600)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:306)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

```

2. OpenSearch includes the wrong Public Key here:
https://github.com/opensearch-project/OpenSearch/commit/05a6fde676e6436bd1e3d5dfe7de26889a69f0cb

The correct public key is here:
https://opensearch.org/verify-signatures.html
https://artifacts.opensearch.org/publickeys/opensearch.pgp

**To Reproduce**
See Above

**Expected behavior**
Install success

**Plugins**
analysis-icu
analysis-kuromoji
analysis-nori
analysis-phonetic
analysis-smartcn
analysis-stempel
analysis-ukrainian
discovery-azure-classic
discovery-ec2
discovery-gce
ingest-attachment
mapper-annotated-text
mapper-murmur3
mapper-size
repository-azure
repository-gcs
repository-hdfs
repository-s3
store-smb
transport-nio

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by nknize**
The public key has changed since the initial release. This PR fixes the public key and uses the .sig files that are published to the artifacts site.

closes #996

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
Surprise.... more jenkins flakiness...

```
Gradle_Check/search/distribution/bwc/minor/build/bwc/checkout-1.x/distribution/archives/linux-tar/build/install/opensearch-1.1.0-SNAPSHOT, -Dopensearch.path.conf=/var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/qa/rolling-upgrade/build/testclusters/v1.1.0-0/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
» [2021-09-09T21:42:25,447][INFO ][o.o.i.r.ReindexPlugin    ] [v1.1.0-0] ReindexPlugin reloadSPI called
» [2021-09-09T21:42:25,486][INFO ][o.o.i.r.ReindexPlugin    ] [v1.1.0-0] Unable to find any implementation for RemoteReindexExtension
```

restarting

**Comment by nknize** [comment]
start gradle check

**Review by adnapibar — APPROVED** [review]
👍   Are we going to backport this to both 1.x and 1.0 branches?

**Comment by nknize** [comment]
> Are we going to backport this to both 1.x and 1.0 branches?

yes. I'll open backport PRs.

**Pull request merged**
