### PR TITLE
Revert "Add explicit dependency to validatePom and generatePom tasks (#12807)"

### PR DESCRIPTION
**Pull request by reta**
This reverts commit c04dad58bbc941b8d5f18326d5c5cfb7ac312239.

### Description

Revert "Add explicit dependency to validatePom and generatePom tasks (#12807)

### Related Issues
See please https://github.com/opensearch-project/OpenSearch/pull/12807#issuecomment-2015266673

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
> ❌ Gradle check result for [c30d5d9](https://github.com/opensearch-project/OpenSearch/commit/c30d5d903c11910e0358aad2fc563150026c92c2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35714/)

https://github.com/opensearch-project/OpenSearch/issues/12595
https://github.com/opensearch-project/OpenSearch/issues/12306
https://github.com/opensearch-project/OpenSearch/issues/12239

**Comment by cwperks** [comment]
TY for the help here @reta! I will review the initial PR to see if I can provide any insight on how to prevent it from being a breaking change to the plugins.

**Comment by reta** [comment]
> ❌ Gradle check result for [c30d5d9](https://github.com/opensearch-project/OpenSearch/commit/c30d5d903c11910e0358aad2fc563150026c92c2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35717/)

Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by zelinh** [comment]
Would changing back `ConfigureEach` to `all` possibly resolve the incompatible issue with security plugin?

**Comment by reta** [comment]
> Would changing back `ConfigureEach` to `all` possibly resolve the incompatible issue with security plugin?

We need to test that and other plugins

**Comment by andrross** [comment]
> ❌ Gradle check result for [c30d5d9](https://github.com/opensearch-project/OpenSearch/commit/c30d5d903c11910e0358aad2fc563150026c92c2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35733/)

```
> Task :qa:wildfly:composeUp FAILED
Get "https://quay.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by reta** [comment]
> ❌ Gradle check result for [c30d5d9](https://github.com/opensearch-project/OpenSearch/commit/c30d5d903c11910e0358aad2fc563150026c92c2): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35755/)

https://github.com/opensearch-project/OpenSearch/issues/10006

```
java.lang.Exception: Test abandoned because suite timeout was reached.
	at __randomizedtesting.SeedInfo.seed([81B30C60E4925A1F]:0)
```

**Comment by zelinh** [comment]
> > Would changing back `ConfigureEach` to `all` possibly resolve the incompatible issue with security plugin?
> 
> We need to test that and other plugins

I just tested that changing back to `all` can run assemble on security plugin successfully. 
```
☁  ~/workplace/security[main] ./gradlew assemble
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.5
  OS Info               : Mac OS X 14.3 (x86_64)
  JDK Version           : 21 (Oracle JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
  Random Testing Seed   : C82B0FF391C689CE
  In FIPS 140 mode      : false
=======================================

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 44s
11 actionable tasks: 11 executed
```
This might be the issue that the previous compatibility tests failed on security plugin. https://github.com/opensearch-project/OpenSearch/pull/12807#issuecomment-2010933074

**Comment by zelinh** [comment]
@reta I raised a PR to fix the incompatibility for security plugin. You can take a look there. https://github.com/opensearch-project/OpenSearch/pull/12876

**Comment by reta** [comment]
Closing in favor of https://github.com/opensearch-project/OpenSearch/pull/12876

**Pull request closed without merging**
