### PR TITLE
Added a link to the maintainer file in contribution guides

### PR DESCRIPTION
**Pull request by geekygirldawn**
Added a link to the maintainer file in the step where we talk about merging PRs in the contributing and developer guides. This provides a bit more visibility into who could be expected to be merging those changes 

Signed-off-by: Dawn M. Foster <fosterd@vmware.com>

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

**Comment by adnapibar** [comment]
start gradle check

**Comment by geekygirldawn** [comment]
@dblock I think I resolved the merge conflict with your changes to the developer guide.

**Comment by dblock** [comment]
> @dblock I think I resolved the merge conflict with your changes to the developer guide.

The diff looks strange, did you try rebasing this?

```
git checkout main
git pull upstream main
git checkout contrib_maint
git rebase main
```

**Review by dblock — APPROVED** [review]
Looks great, thank you.

Related, we've recently created https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md which should have this change. Want to PR a generic/emtpy MAINTAINERS.md into that? This way new repos inherit all that structure.

**Comment by harold-wang** [comment]
start gradle check

**Comment by dblock** [comment]
Merged, sorry for the delay.

**Pull request merged**
