### PR TITLE
Adding broken links checker

### LINKED ISSUE #873: Check broken links automatically
As we are dynamic and things are fluid, links to other repositories might become broken.

Developers find these problems when they use documentation, but we should have an automated way to check and notify broken links.

This has been done in [opensearch-plugins repo](https://github.com/opensearch-project/opensearch-plugins/pull/54).

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
Adding a broken links checker github action to check for broken links on PRs and push.
 
### Issues Resolved
#873 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
Broken links found in the link checker. I will working on fixing those.

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by dblock** [comment]
It found some real issues! Let's fix them as part of this CR.

**Comment by VachaShah** [comment]
> It found some real issues! Let's fix them as part of this CR.

Yes I have created a Meta issue for all the broken links: #894 and am working on fixing them.

**Comment by saratvemulapalli** [comment]
start gradle check

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
Thanks @VachaShah for taking care of this!

**Pull request merged**
