### PR TITLE
Gradle Check Optimization

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Coming from https://github.com/opensearch-project/OpenSearch/issues/11217#issuecomment-2118322724, this PR will ensure we have the PR number identified by commitID even for `post_merge_action`. This data will be used in gradle metrics dashboard [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083). 

The required jenkinsfile change PR https://github.com/opensearch-project/opensearch-build/pull/4719.
The required library change PR https://github.com/opensearch-project/opensearch-build-libraries/pull/427.

With this change we can get the associated PR for failed tests on `post_merge_action`.

### Related Issues
Part of: https://github.com/opensearch-project/OpenSearch/issues/3713

### Testing
Here is the sample workflow run for `push` action https://github.com/prudhvigodithi/opensearch-build/actions/runs/9163727535/job/25193476071, where the PR number (https://github.com/prudhvigodithi/opensearch-build/pull/110) is displayed for `push` event.
Screenshot 2024-05-22 at 11 38 02 AM

### Check List
- [x] New functionality includes testing.
- [x] All tests pass
- [ ] ~New functionality has been documented.~
- [ ] ~New functionality has javadoc added~
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Tagging @cwperks @peternied @dblock @andrross @peterzhuamazon to please take a look.

**Review by dblock — APPROVED** [review]
LGTM

**Comment by prudhvigodithi** [comment]
@peternied not able to get this Pull Request Checks pass, can you please check ?

**Comment by peternied** [comment]
Seems like the logs on that check spell it out, no?
```
Error: Found 3 errors:
   - Unable to find check list item `New functionality has been documented.` in the pull request description. Check list item that should be checked `[x]` or the item should be 'struck out' with `~` characters on both sides of the text.
   - Unable to find check list item `New functionality has javadoc added` in the pull request description. Check list item that should be checked `[x]` or the item should be 'struck out' with `~` characters on both sides of the text.
   - Unable to find check list item `Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))` in the pull request description. Check list item that should be checked `[x]` or the item should be 'struck out' with `~` characters on both sides of the text.
```

**Comment by prudhvigodithi** [comment]
> Seems like the logs on that check spell it out, no?
> 
> ```
> Error: Found 3 errors:
>    - Unable to find check list item `New functionality has been documented.` in the pull request description. Check list item that should be checked `[x]` or the item should be 'struck out' with `~` characters on both sides of the text.
>    - Unable to find check list item `New functionality has javadoc added` in the pull request description. Check list item that should be checked `[x]` or the item should be 'struck out' with `~` characters on both sides of the text.
>    - Unable to find check list item `Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))` in the pull request description. Check list item that should be checked `[x]` or the item should be 'struck out' with `~` characters on both sides of the text.
> ```

Yes I see that but they dont even exist in my PR description, I guess I have to re-add them back with `~`.

**Review by peternied — APPROVED** [review]

**Comment by andrross** [comment]
@prudhvigodithi FYI looks like you'll need to manually fix some conflicts if you want to backport this to 1.x

**Comment by prudhvigodithi** [comment]
Ya @andrross it should be backported to 1.3 (failed as well, which I will do it manually) as 1.x is reaching EOL and active supported version is 1.3.x, please correct me if I'm wrong.

**Comment by prudhvigodithi** [comment]
Works as expected, here is the gradle check invoked with `push` action https://github.com/opensearch-project/OpenSearch/actions/runs/9202472314/job/25312375443 and I can see its able to identify the PR (https://github.com/opensearch-project/OpenSearch/pull/13787) based on the commit with `post_merge_action` as true. 
Screenshot 2024-05-22 at 10 05 28 PM

**Comment by andrross** [comment]
@prudhvigodithi Yes, you're right! No need to backport 1.x. 1.3 is the only active branch in the 1.x line.

**Pull request merged**
