### PR TITLE
[Backport 2.x] Adds ExtensionsManager.lookupExtensionSettingsById

### PR DESCRIPTION
**Pull request by cwperks**
Backport #7466 to 2.x

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
Thanks @cwperks for the backport. Could you take care of the conflicts?

**Review by saratvemulapalli — APPROVED** [review]

**Comment by cwperks** [comment]
@saratvemulapalli I just resolved the conflicts. Every time I try to follow the steps [here](https://github.com/opensearch-project/OpenSearch/pull/7466#issuecomment-1540837924) and resolve the conflicts locally they still seem to appear when I push the code to github. Do you know why that may be?

**Comment by saratvemulapalli** [comment]
> here

hmmm honestly I just follow natural steps:
- Sync my fork with origin `main` and `2.x`
- Get commit id from main, cherry-pick to `2.x` on fork
- Resolve conflicts and push changes.

**Comment by saratvemulapalli** [comment]
:/
```
[org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.cluster.shards/ClusterShardLimitIT/testCreateIndexWithMaxClusterShardSetting/)
[org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.cluster.shards/ClusterShardLimitIT/testCreateIndexWithMaxClusterShardSetting_2/)
[org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.cluster.shards/ClusterShardLimitIT/testCreateIndexWithMaxClusterShardSetting_3/)
[org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.cluster.shards/ClusterShardLimitIT/testCreateIndexWithMaxClusterShardSetting_4/)
[org.opensearch.indices.replication.SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.indices.replication/SegmentReplicationRelocationIT/testRelocateWhileContinuouslyIndexingAndWaitingForRefresh/)
[org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.search/SearchWeightedRoutingIT/testStrictWeightedRoutingWithCustomString/)
[org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.search/SearchWeightedRoutingIT/testStrictWeightedRoutingWithCustomString_2/)
[org.opensearch.search.SearchWeightedRoutingIT.testStrictWeightedRoutingWithCustomString](https://build.ci.opensearch.org/job/gradle-check/15151/testReport/junit/org.opensearch.search/SearchWeightedRoutingIT/testStrictWeightedRoutingWithCustomString_3/)
```

**Pull request merged**
