### PR TITLE
[Backport 2.0] Revert to Netty 4.1.79.Final

### PR DESCRIPTION
**Pull request by cwperks**
Signed-off-by: Craig Perkins <cwperx@amazon.com>

### Description

See related issue: https://github.com/opensearch-project/OpenSearch/issues/4427

The last minor version of Netty included a change to eagerly load certificates using BouncyCastle if BouncyCastle is on the classpath: https://github.com/netty/netty/pull/12670

This change has led to errors on startup with the security plugin (See https://github.com/opensearch-project/OpenSearch/issues/4427) because of a bug in checking all required BouncyCastle dependencies (See https://github.com/netty/netty/pull/12743)

There is another bug related to the change that impacts custom bundles for private keys (https://github.com/netty/netty/pull/12746). Both bugs have since been fixed and are targeted for the next 4.1.X release of netty.

This PR reverts netty until the next 4.1.X (4.1.81.Final) release. The full list of changes in netty 4.1.80.Final can be found [here](https://netty.io/news/2022/08/26/4-1-80-Final.html)

### Issues Resolved

https://github.com/opensearch-project/OpenSearch/issues/4427

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
@cwperks : Both precommit & gradle check failed due to unused sha file `netty-transport-native-unix-common-4.1.79.Final.jar.sha1`. Can you resolve this issue ?

Pre-commit
```
> Unused sha files found: 
  netty-transport-native-unix-common-4.1.79.Final.jar.sha1
```

Gradle check
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:transport-netty4:dependencyLicenses'.
> Unused sha files found: 
  netty-transport-native-unix-common-4.1.79.Final.jar.sha1
```

**Comment by cwperks** [comment]
@dreamer-89 I removed that license file. That was added in this change (https://github.com/opensearch-project/OpenSearch/pull/3848) which was added in 2.1.

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@dreamer-89 could you merge it please? For some reasons I cannot for `2.0`

**Comment by dreamer-89** [comment]
> @dreamer-89 could you merge it please? For some reasons I cannot for `2.0`

Yes, it is also showing merging is blocked. I don't see any pending approval step. Do you want me to force merge this change @reta ?

**Review by kotwanikunal — APPROVED** [review]

**Comment by kotwanikunal** [comment]
> > @dreamer-89 could you merge it please? For some reasons I cannot for `2.0`
> 
> Yes, it is showing merging is blocked. I don't see any pending approval step. Do you want me to force merge this change @reta ?
> 
> CC @dblock @reta

Merged it in.

**Comment by dreamer-89** [comment]
> > > @dreamer-89 could you merge it please? For some reasons I cannot for `2.0`
> > 
> > 
> > Yes, it is showing merging is blocked. I don't see any pending approval step. Do you want me to force merge this change @reta ?
> > CC @dblock @reta
> 
> Merged it in.

@kotwanikunal : Thanks for the approval. 
Any reasons, it wasn't showing merge option even with approvals ?

**Comment by kotwanikunal** [comment]
@dreamer-89 It looks like the maintainers need to be backported to 2.0 - https://github.com/opensearch-project/OpenSearch/blob/2.0/MAINTAINERS.md
I don't see you here, which might be causing permission issues. 

The PR was still waiting for an approval from [`opensearch-core`](https://github.com/orgs/opensearch-project/teams/opensearch-core), if that helps drill this down further.

**Comment by dreamer-89** [comment]
> @dreamer-89 It looks like the maintainers need to be backported to 2.0 - https://github.com/opensearch-project/OpenSearch/blob/2.0/MAINTAINERS.md I don't see you here, which might be causing permission issues.
> 
> The PR was still waiting for an approval from [`opensearch-core`](https://github.com/orgs/opensearch-project/teams/opensearch-core), if that helps drill this down further.

Thanks @kotwanikunal.

**Comment by reta** [comment]
> @dreamer-89 It looks like the maintainers need to be backported to 2.0 - https://github.com/opensearch-project/OpenSearch/blob/2.0/MAINTAINERS.md I don't see you here, which might be causing permission issues.
> 
> The PR was still waiting for an approval from [`opensearch-core`](https://github.com/orgs/opensearch-project/teams/opensearch-core), if that helps drill this down further.

@kartg that's what I mentioned here https://github.com/opensearch-project/OpenSearch/pull/4342#issuecomment-1232021631

**Comment by kartg** [comment]
@reta I'll try and look into what's going on here. I still don't think it's tied to backporting `MAINTAINERS.md` since both you (https://github.com/opensearch-project/OpenSearch/pull/3598) and @dreamer-89 (https://github.com/opensearch-project/OpenSearch/pull/4149) have previously merged PRs into `2.0` - https://github.com/opensearch-project/OpenSearch/pull/3598 😕 

cc @kotwanikunal

**Comment by kartg** [comment]
Ah, it looks like we didn't backport the [change in Codeowners]() from `2.x` to `2.0`. The reason why @dreamer-89 found the merge blocked was because, as @kotwanikunal pointed out, no one from `opensearch-core` had approved this PR.

I've triggered the backport now - https://github.com/opensearch-project/OpenSearch/pull/4475

Sorry about that @reta ! 😅

**Comment by reta** [comment]
Thanks a mill, @kartg and @kotwanikunal !

**Pull request merged**
