### PR TITLE
Bumping 2.x to 2.2.0

### PR DESCRIPTION
**Pull request by saratvemulapalli**
### Description
Prepping for 2.1.0 release. Bumping 2.x to 2.2.0.

Please note: 2.1 branch will be cut first before this change will be merged. 
 
### Issues Resolved
Part of https://github.com/opensearch-project/OpenSearch/issues/3636
 
### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Check failure [d09c0b9](https://github.com/opensearch-project/OpenSearch/commit/d09c0b9962c39d2dcf5453129e5534c26f38ec5a) [Log 6264](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6264.log)
> 
> [Reports 6264](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6264_reports.zip)

2.1 branch is now out.

**Review by reta — APPROVED** [review]

**Review by mch2 — APPROVED** [review]

**Comment by kotwanikunal** [comment]
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" -Dtests.seed=835FA52215765013 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pl-PL -Dtests.timezone=Asia/Macao -Druntime.java=17

org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT > testHighWatermarkNotExceeded FAILED
    java.lang.AssertionError: Mismatching shard routings: []
    Expected: a collection with size <1>
         but: collection size was <0>
        at __randomizedtesting.SeedInfo.seed([835FA52215765013:6A7E449095B099FD]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.lambda$assertBusyWithDiskUsageRefresh$5(DiskThresholdDeciderIT.java:362)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1049)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.assertBusyWithDiskUsageRefresh(DiskThresholdDeciderIT.java:355)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded(DiskThresholdDeciderIT.java:188)

```

**Comment by kotwanikunal** [comment]
```
REPRODUCE WITH: ./gradlew ':qa:verify-version-constants:v2.1.0#integTest' --tests "org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant" -Dtests.seed=B47B98860A3DE5D6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr-LU -Dtests.timezone=Asia/Omsk -Druntime.java=17

org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT > testLuceneVersionConstant FAILED
    java.lang.AssertionError: 
    Expected: <9.2.0>
         but: was <9.3.0>
        at __randomizedtesting.SeedInfo.seed([B47B98860A3DE5D6:391EA5DA2D35269F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant(VerifyVersionConstantsIT.java:56)
WARNING: A terminally deprecated method in java.lang.System has been called
```

@saratvemulapalli The PR needs an update since https://github.com/opensearch-project/OpenSearch/pull/3676 was merged in.

**Comment by saratvemulapalli** [comment]
> ```
> REPRODUCE WITH: ./gradlew ':qa:verify-version-constants:v2.1.0#integTest' --tests "org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant" -Dtests.seed=B47B98860A3DE5D6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr-LU -Dtests.timezone=Asia/Omsk -Druntime.java=17
> 
> org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT > testLuceneVersionConstant FAILED
>     java.lang.AssertionError: 
>     Expected: <9.2.0>
>          but: was <9.3.0>
>         at __randomizedtesting.SeedInfo.seed([B47B98860A3DE5D6:391EA5DA2D35269F]:0)
>         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
>         at org.junit.Assert.assertThat(Assert.java:964)
>         at org.junit.Assert.assertThat(Assert.java:930)
>         at org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant(VerifyVersionConstantsIT.java:56)
> WARNING: A terminally deprecated method in java.lang.System has been called
> ```
> 
> @saratvemulapalli The PR needs an update since #3676 was merged in.

Thanks @kotwanikunal i've updated it. 
Hopefully it should go through.

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Check failure [6e6453c](https://github.com/opensearch-project/OpenSearch/commit/6e6453ca604e9a2ed43fa515b9630adaf9d0fc8f) [Log 6279](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6279.log)
> 
> [Reports 6279](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6279_reports.zip)

```
Tests with failures:
 - org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded
```

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by tlfeng** [comment]
start gradle check

**Pull request merged**
