### PR TITLE
enables http.custom.headers option in opensearch.yml

### LINKED ISSUE #1069: Enable custom server response headers through opensearch.yml configuration
The objective of this feature is to provide a configuration open in opensearch.yml to enable the server to send custom HTTP response headers.

The option can be defined as shown below:
http.custom.headers: ["Strict-Security-Transport:max-age=31536000; includeSubDomains;"]

Running this "curl -v -u admin:admin http://localhost:9200" command would return the below bold header in the HTTP response. (The below response is coming from Elasticsearch but the same is expected with OpenSearch)
* Rebuilt URL to: http://localhost:9200/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
* Server auth using Basic with user 'admin'
> GET / HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< _**Strict-Security-Transport: max-age=31536000; includeSubDomains;**_
< content-type: application/json; charset=UTF-8
< content-length: 506
<
{
  "name" : "LAPTOP-C0J5I3L2",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "xVUOVOAGR4iaNHA2AEv1pw",
  "version" : {
    "number" : "7.8.0",
    "build_flavor" : "oss",
    "build_type" : "zip",
    "build_hash" : "unknown",
    "build_date" : "2021-02-16T10:30:42.633581400Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

### PR DESCRIPTION
**Pull request by asfoorial**
Signed-off-by: asfoorhm <asfoor.hasan.m@gmail.com>

### Description
Added new configuration option to opensearch.yml to enable sending custom http response headers. The option can be defined as shown below:
http.custom.headers: ["Strict-Security-Transport:max-age=31536000; includeSubDomains;"]
 
### Issues Resolved
#1069
 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Thanks. Let's see what others in https://github.com/opensearch-project/OpenSearch/issues/1069 think about this feature. Either way this PR will need tests to get merged, if you want to get ahead of that.

**Comment by dblock** [comment]
Thanks for the PR. I still feel uneasy allowing custom HTTP headers. Would like someone else's opinion (@nknize?).

**Comment by asfoorial** [comment]
> Thanks for the PR. I still feel uneasy allowing custom HTTP headers. Would like someone else's opinion (@nknize?).

Please note that many web servers give the option to enable custom http response headers, including OpenSearch Dashboards.

So I think enabling it in OpenSearch will make OpenSearch and OpenSearch Dashboards consistent.

**Comment by dblock** [comment]
I want to hear from others whether this a good idea, in the meantime:

1. Get this PR into a mergeable state. Remove commented out code and any println's, make changes, rebase.
2. What's a scenario of setting custom headers on a single node? Why wouldn't this be a cluster-wide setting?
3. Would a syntax like `http.headers.Strict-Security-Transport:max-age=31536000; includeSubDomains;` be better than having to parse header values and keeping a map? 
4. Code as is will fail quietly with anything with more than one ":".
5. Custom headers will conflict with existing settings that set headers, such as cors headers, how do you want to resolve this?

**Comment by dreamer-89** [comment]
@dblock @andrross  : Can you please have a look at it ?

**Comment by asfoorial** [comment]
> @asfoorial: Can you please address the review comments from @dblock ?
> 
> This is pending for a very long time, and would like to bring this to a closure.

You can close this for now. I may resubmit it in the future considering comments from @dblock and others. 

Sorry it took too long.

**Comment by dreamer-89** [comment]
> You can close this for now. I may resubmit it in the future considering comments from @dblock and others.
Sorry it took too long.

Thank you @asfoorial for the quick update. 

I am closing this PR. Please feel free to raise PR and addressing requested changes.

**Pull request closed without merging**
