### PR TITLE
Support Gradle 7. Fixing 'eclipse' plugin dependencies

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
The `eclipse` plugin fails with:

```
...
> Task :test:fixtures:hdfs-fixture:eclipseJdt                                                                                                                                                
Execution optimizations have been disabled for task ':test:fixtures:hdfs-fixture:eclipseJdt' to ensure correctness due to the following reasons:                                             
  - Gradle detected a problem with the following location: '/home/andriy.redko/Workspaces/Experiments/OpenSearch/test/fixtures/hdfs-fixture/.settings/org.eclipse.jdt.core.prefs'. Reason: Ta
sk ':test:fixtures:hdfs-fixture:eclipseJdt' uses this output of task ':test:fixtures:hdfs-fixture:copyEclipseSettings' without declaring an explicit or implicit dependency. This can lead to
 incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#implicit_dependency for mor
e details about this problem.                                                                 
Gradle detected a problem with the following location: '/home/andriy.redko/Workspaces/Experiments/OpenSearch/test/fixtures/hdfs-fixture/.settings/org.eclipse.jdt.core.prefs'. Reason: Task '
:test:fixtures:hdfs-fixture:eclipseJdt' uses this output of task ':test:fixtures:hdfs-fixture:copyEclipseSettings' without declaring an explicit or implicit dependency. This can lead to inc
orrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#implicit_dependency for more de
tails about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradl
e.org/7.3/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
...
```
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock whenever you have time please

**Review by setiah — APPROVED** [review]
LGTM (though i'm not a gradle expert :))!

**Comment by VachaShah** [comment]
Does this need to be backported to 1.x? If so, you can add `backport 1.x` label to this PR and re-run the workflows. Once the backport workflow runs on this PR, this PR can be merged to main and the workflow will create a backport PR automatically.

**Comment by reta** [comment]
@VachaShah the backport PR is here https://github.com/opensearch-project/OpenSearch/pull/1622, it includes this change as well, thank you

**Pull request merged**
