### PR TITLE
Add toString() to MultiSearchRequest, MultiGetRequest and CreateIndex…

### LINKED ISSUE #12144: [BUG] Missing toString() method in many requests classes
### Describe the bug

Whereas SearchRequest has a toString() method, making debugging much easier, it is not present in all other requests.

For instance it is missing in
- MultiSearchRequest
- CreateIndexRequest
- MultiGetRequest

### Related component

Clients

### To Reproduce

1. Create a MultiSearchRequest object
2. Try to log it
3. See something like org.opensearch.action.search.MultiSearchRequest@3eb87ae4

### Expected behavior

1. Create a MultiSearchRequest object
2. Try to log it
3. See something like `{requests=[SearchRequest{...},...]}`

### Additional Details

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - any Java client

**Additional context**
I will try to provide a fix in PR.

### PR DESCRIPTION
**Pull request by guillaume-alvarez**
fix #12144

### Description
Make debugging easier with toString() method in MultiSearchRequest class.

backport of https://github.com/opensearch-project/OpenSearch/pull/12163

### Related Issues
Resolves #12144

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by guillaume-alvarez** [comment]
1 org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing
is covered by https://github.com/opensearch-project/OpenSearch/issues/9191

**Review by kkmr — APPROVED** [review]

**Review by ansjcy — APPROVED** [review]

**Review by andrross — APPROVED** [review]

**Comment by andrross** [comment]
@guillaume-alvarez Do you mind putting together the manual backport PR as described above?

**Comment by kotwanikunal** [comment]
@andrross This was the backport PR :)

**Comment by andrross** [comment]
Lol, sorry @guillaume-alvarez, ignore me please.

**Pull request merged**
