### PR TITLE
Update to Apache Lucene 9.6.0-snapshot-a3ae27f

### PR DESCRIPTION
**Pull request by reta**
### Description
Update to Apache Lucene 9.6.0-snapshot-8a81515

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Poojita-Raj** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> 
>     * **RESULT:** FAILURE ❌
> 
>     * **URL:** https://build.ci.opensearch.org/job/gradle-check/12776/
> 
>     * **CommitID:** [94ffd1f](https://github.com/opensearch-project/OpenSearch/commit/94ffd1fcaae657fceb5ad182d36f1d6be5e81e63)
>       Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>       Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

2 failures (seem related to the change):
org.opensearch.index.mapper.SearchAsYouTypeFieldTypeTests.testPrefixQuery
```
java.lang.AssertionError: 
Expected: <a_field:toolongforourprefixfieldthistermis*>
     but: was <a_field:toolongforourprefixfieldthistermis*>
     
```
     
org.opensearch.join.query.HasChildQueryBuilderTests.testToQueryInnerQueryType
```
java.lang.AssertionError: 
Expected: an instance of org.apache.lucene.search.ConstantScoreQuery
     but: <_id:([ff 69 64])> is a org.apache.lucene.search.MultiTermQueryConstantScoreBlendedWrapper
     
```

**Review by Poojita-Raj — COMMENTED** [review]
Hey @reta, if we're updating to Lucene 9.6, shouldn't we change the default codec being loaded in Codec.java to "Lucene96" from "Lucene95" as well? Additionally CodecService.java still references Lucene95 codecs to create the list of available codecs.

**Comment by reta** [comment]
Thanks @Poojita-Raj , AFAIK the 9.6 snapshot still uses Lucene95 codec [1], where have you seen `Lucene96` usage, I may have missed that, thank you.

[1] https://github.com/apache/lucene/blob/branch_9x/lucene/core/src/java/org/apache/lucene/codecs/Codec.java#L58

**Comment by Poojita-Raj** [comment]
> Thanks @Poojita-Raj , AFAIK the 9.6 snapshot still uses Lucene95 codec [1], where have you seen `Lucene96` usage? I may have missed that, thank you.
> 
> [1] https://github.com/apache/lucene/blob/branch_9x/lucene/core/src/java/org/apache/lucene/codecs/Codec.java#L58

Oh sorry, I misunderstood from the name of the snapshot that it uses a revised codec.

**Review by Poojita-Raj — APPROVED** [review]

**Comment by reta** [comment]
@nknize mind to take a look? thank you

**Comment by reta** [comment]
@nknize @dblock please need your review

**Review by dblock — APPROVED** [review]

**Pull request merged**
