### PR TITLE
 [Backport] [1.3] Discrepancy in result from _validate/query API and actual query validity (#2416) #2466 

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Backport of https://github.com/opensearch-project/OpenSearch/pull/2416 to 1.x
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
I can merge, but I don't think it will make it into 1.3, they are already testing a previous build as an RC.

**Comment by reta** [comment]
@dblock that's sad, but may be for 1.3.1 ?

**Comment by dblock** [comment]
> @dblock that's sad, but may be for 1.3.1 ?

Yes, let's wait a bit till 1.3 does get released to merge, or some automation will pickup the change as 1.3.

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Block this until 1.3.1 is in the pipeline.

**Comment by reta** [comment]
@peterzhuamazon @dblock the 1.3 is on 1.3.1 already, worth merging? thank you!

**Comment by dblock** [comment]
@peterzhuamazon Can you please approve this one now that 1.3.1 has been incremented?

**Comment by dblock** [comment]
Closing, this didn't make it into 1.3, see you in 2.0!

**Pull request closed without merging**
