### PR TITLE
Skip media type parsing for known string values

### LINKED ISSUE #15979: CPU intensive string parsing of MediaType field in binary serialization
### Is your feature request related to a problem? Please describe

I ran some benchmarks of an indexing-only workload and noticed that a surprising large amount of CPU time was being spent on parsing the MediaType as a string on the Netty I/O event loop. This is still a relatively tiny part of the overall CPU time, but there's an obvious optimization here. About half of the CPU cycles spent deserializing the BulkRequest is spent on `parseMediaType`:

image

It turns out that in order to serialize the MediaType, we are writing the string `"application/json; charset=UTF-8"` and then doing complicating string splitting on the read path to parse that string. This change was made as a part of the refactoring to decouple the `XContentType` enum from the generic `StreamInput` and `StreamOutput` framework.

### Describe the solution you'd like

The complicated string parsing logic makes sense when handling HTTP requests that may be coming from arbitrary clients sending different content types and/or different string encodings. However, it's totally overkill (in my opinion) on the binary transport API where the client and server are both OpenSearch processes that are tightly controlled. I think there are 2 ways to fix this:

1. Continue to write `"application/json; charset=UTF-8"` but add a special case on the read path to match that string to constant and return the appropriate MediaType instance. This would bypass the parsing logic and require no changes to the write path.
2. Add a new method called something like `int uniqueId()` to the MediaType interface that can be leveraged by the binary protocol to efficiently serialize any MediaType instance into a single VInt. The MediaTypeRegistry could enforce that there are no conflicts across registered instances. This would be the most efficient way to handle this on both the write path and read path, and it would also avoid tightly coupling any specific MediaType instance to the StreamInput/StreamOutput framework.

I think option 2 is simple enough we should probably do it. I'll send out a PR soon to show that option.

### Related component

Libraries

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andrross**
Less intrusive optimization solving the same problem as #16073

### Related Issues
Resolves #15979

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — COMMENTED** [review]
Any reason not to forward optimize and add the result of `parseMediaType` to this map?

**Comment by reta** [comment]
Love it @andrross ! Thank you!

> Any reason not to forward optimize and add the result of `parseMediaType` to this map?

@dblock I think it would complicate thins a lot: 
a) map is immutable now but it won't be anymore (with all the consequences)
b) map has to be capped since `parseMediaType` could accept myriad of variations 

I believe the `parseMediaType` will be done only once for a whole request, may be it is an acceptable tradeoff?

**Review by reta — APPROVED** [review]
LGTM to me!

**Comment by andrross** [comment]
>> Any reason not to forward optimize and add the result of parseMediaType to this map?
>
> @dblock I think it would complicate things a lot:
> a) map is immutable now but it won't be anymore (with all the consequences)
> b) map has to be capped since parseMediaType could accept myriad of variations

@dblock I agree with @reta about the complexities. Also, in my simple testing I can't even find the `Content-Type` header parsing anywhere in the profile so I think it is negligible. This optimization is targeted at the transport protocol where we've already got a `MediaType` instance and we just want to serialize it across the wire in the binary protocol.

**Pull request merged**
