### PR TITLE
Update version to 2.18.0 for CatShards request and response

### PR DESCRIPTION
**Pull request by gargharsh3134**
### Description
Updating version to 2.18.0 for `CatShardsRequest` and `CatShardsResponse` which were added as 3.0.0 as part of https://github.com/opensearch-project/OpenSearch/pull/14641

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

**Comment by gargharsh3134** [comment]
@dbwiddis @andrross @owaiskazi19 Finally got the build working, had to re-run multiple times owing to flaky tests. Please check whenever you get a chance.
Thanks!

**Review by owaiskazi19 — APPROVED** [review]

**Review by dbwiddis — APPROVED** [review]

**Comment by dbwiddis** [comment]
> @dbwiddis @andrross @owaiskazi19 Finally got the build working, had to re-run multiple times owing to flaky tests. Please check whenever you get a chance. Thanks!

Winter is coming.  (Snow) flakiness is a fact of the season ;)

**Comment by dbwiddis** [comment]
@gargharsh3134 does this need a 2.x backport?

**Comment by gargharsh3134** [comment]
@dbwiddis It was already handled while merging the 2.x backport of source PR (https://github.com/opensearch-project/OpenSearch/pull/16396). We should be good now.
Thanks!

**Comment by dbwiddis** [comment]
> It was already handled while merging the 2.x backport of source PR (#16396). We should be good now. Thanks!

@gargharsh3134 seems one of these was missed.   I manually filed #16590 for 2.18 branch.  I'll trigger the backport from this PR to hopefully fix 2.x as the other changes should be no-op.

**Pull request merged**
