### PR TITLE
CardinalityIT/NestedIT test failures with concurrent search enabled and AssertingCodec

### PR DESCRIPTION
**Pull request by sohami**
### Description
Backport of https://github.com/opensearch-project/OpenSearch/pull/8303

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/8095

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by sohami** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❕
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testPrimaryStopped_ReplicaPromoted
>       1 org.opensearch.indices.replication.SegmentReplicationRelocationIT.testPrimaryRelocation
> ```
> 
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/20145/
> * **CommitID:** [6355800](https://github.com/opensearch-project/OpenSearch/commit/6355800117bb80830fc096baa4251b47640e598e)
>   Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

unrelated failures.

**Comment by kotwanikunal** [comment]
@sohami / @reta Code coverage does not meet the threshold. I think we need more UTs.

**Comment by sohami** [comment]
> @sohami / @reta Code coverage does not meet the threshold. I think we need more UTs.

@kotwanikunal The change is fixing the IT test listed in the title so the coverage is there with ITs and it will also execute for each of the aggregation search path which has extensive coverage

**Comment by kotwanikunal** [comment]
> > @sohami / @reta Code coverage does not meet the threshold. I think we need more UTs.
> 
> @kotwanikunal The change is fixing the IT test listed in the title so the coverage is there with ITs and it will also execute for each of the aggregation search path which has extensive coverage

Ahh. Never realized ITs were not only not covered in codecov but are also considered as code. 💯

**Pull request merged**
