### PR TITLE
Fix LinearRing serialization issue while emitting task description in…

### PR DESCRIPTION
**Pull request by rishabhmaurya**
… a trace log

### Description
[Describe what this change achieves]

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/11688

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
~- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kkmr** [comment]
This is **the** problem to solve.  @dblock  posted a solution for this as well: https://github.com/opensearch-project/OpenSearch/pull/12831

**Comment by reta** [comment]
@rishabhmaurya is it fixed by https://github.com/opensearch-project/OpenSearch/pull/12834

**Comment by andrross** [comment]
I love that there is so much interest in fixing failing tests! Too bad everyone is focused on fixing the same test :)

**Comment by rishabhmaurya** [comment]
I do not like the fact that the search task executes fine, its just when the trace logs are enabled and getDescription() on task is invoked which results in such failures. https://github.com/opensearch-project/OpenSearch/pull/12831 fixes it for linear ring but it could be some other field type tomorrow, originating from core/plugins. 

I will close this one

**Comment by dblock** [comment]
We ended up merging a fix a little closer to what's here in https://github.com/opensearch-project/OpenSearch/pull/12834. Task description will not fail when it cannot be serialized, instead the description will contain the serialization error.

**Comment by dblock** [comment]
> I love that there is so much interest in fixing failing tests! Too bad everyone is focused on fixing the same test :)

This was a well isolated one, and I enjoyed figuring out and debating the best way to fix it! Thanks @shwetathareja @rishabhmaurya @andrross @reta and anyone I forgot to mention.

**Pull request closed without merging**
