### PR TITLE
Add trademark notice

### PR DESCRIPTION
**Pull request by stockholmux**
### Description
Adds trademark notice to README

### Issues Resolved
n/a
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — COMMENTED** [review]
Is this something that will need to be added to all repos?

**Comment by stockholmux** [comment]
@dblock Nope, just this one.

**Review by dblock — APPROVED** [review]

**Comment by stockholmux** [comment]
Thanks @dblock!

**Comment by dblock** [comment]
Didn't notice we have a TOC in this readme, please add in another PR.

**Pull request merged**
