### PR TITLE
Fixing .gitattributes for binary content, removing *.class files

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Specifying binary content in `.gitattributes`, removing accidentally added `.class` files by https://github.com/opensearch-project/OpenSearch/pull/1696
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/1713

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@saratvemulapalli could you give it a try please?

**Comment by saratvemulapalli** [comment]
> @saratvemulapalli could you give it a try please?

Haha you were faster than me. Sure will give it a shot.

**Review by saratvemulapalli — APPROVED** [review]
Thanks @reta for the change.
I did pull it in MacOS and Linux, it works. 
Do you happen to have a windows machine to test?

**Comment by jayaddison** [comment]
(sorry for randomly commenting on this pull request uninvited - I've been reading some recent pull requests given the interest in `log4j` over the past few days)

Is marking these as binary file patterns (using `.gitattributes`) preferable to filtering them out of local unstaged changes (using `.gitignore`)?

**Comment by reta** [comment]
thank @saratvemulapalli 

>  Do you happen to have a windows machine to test?

Yes, I did, the clone is clean

**Comment by reta** [comment]
thanks for looking @jayaddison 

> Is marking these as binary file patterns (using .gitattributes) preferable to filtering them out of local unstaged changes (using .gitignore)?

Those files are part of the codebase (used in tests, fe, etc.), adding them to `.gitignore` would prevent  them from committing.

**Comment by jayaddison** [comment]
> Those files are part of the codebase (used in tests, fe, etc.), adding them to .gitignore would prevent them from committing.

Cool, that makes sense - thank you.  And `*.class` could also be added separately to `.gitignore`?

**Comment by reta** [comment]
> Cool, that makes sense - thank you. And *.class could also be added separately to .gitignore?

That is good point, we probably could add `bin` folder but I am wondering how they appear in first place, they should be in the `build` folder by default unless probably Eclipse is used, @saratvemulapalli is it your case? Thanks!

**Review by dblock — APPROVED** [review]
🚀

**Comment by saratvemulapalli** [comment]
> > Cool, that makes sense - thank you. And *.class could also be added separately to .gitignore?
> 
> That is good point, we probably could add `bin` folder but I am wondering how they appear in first place, they should be in the `build` folder by default unless probably Eclipse is used, @saratvemulapalli is it your case? Thanks!

I believe so, I didnt do post mortem of who generated .class files but across the project they should live under build which is already covered.

**Pull request merged**
