### PR TITLE
[Backport] [2.x] Added missed API visibility annotations for public / experimental APIs (#12864)

### PR DESCRIPTION
**Pull request by reta**
Backport of https://github.com/opensearch-project/OpenSearch/pull/12864 to `2.x`

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [2c8a85a](https://github.com/opensearch-project/OpenSearch/commit/2c8a85aef74dafad49830bad4b5d37ffc4c0e52f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35734/)

https://github.com/opensearch-project/OpenSearch/issues/11310
https://github.com/opensearch-project/OpenSearch/issues/12651

**Comment by reta** [comment]
> ❌ Gradle check result for [2c8a85a](https://github.com/opensearch-project/OpenSearch/commit/2c8a85aef74dafad49830bad4b5d37ffc4c0e52f): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35778/)

https://github.com/opensearch-project/OpenSearch/issues/5329

**Comment by reta** [comment]
> ❌ Gradle check result for [112bc1d](https://github.com/opensearch-project/OpenSearch/commit/112bc1d391bbfcc9320a4e62422b9980f44de908): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35802/)

https://github.com/opensearch-project/OpenSearch/issues/10704

**Comment by reta** [comment]
@peternied if you don't mind reapproving please, finally got a clean build after numerous rebases ... ty

**Review by VachaShah — APPROVED** [review]

**Pull request merged**
