### PR TITLE
Migrate client transports to Apache HttpClient / Core 5.x

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Migrate client transports to Apache HttpClient / Core 5.x

### Issues Resolved
Closes https://github.com/opensearch-project/OpenSearch/issues/4256

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Admire your persistence @reta :) Did a cursory look and it looks all good to me. Are there any actual notable code changes that I may have missed or is it just a rename/moving things around?

**Comment by reta** [comment]
> Admire your persistence @reta :) Did a cursory look and it looks all good to me. Are there any actual notable code changes that I may have missed or is it just a rename/moving things around?

Thanks a mill @dblock ! There are two things I wanted to finish: a) to compare the CPU/memory usage between RestClient based on Apache HttpClient 4 vs 5.1, to make sure we have no leaks anywhere b) try to configure RestClient with HTTP/2. 

Besides that,m  there is only one issue to mention which should be fixed in 5.1.4 release [1], other changes are pretty straightforward, thanks a lot for the review!

[1] https://github.com/opensearch-project/OpenSearch/pull/4459/files#diff-7c27327b9ea112ce87560831ddb6bd267e80837cd51c03796c8e2397f5b8a6a7R908

**Comment by dblock** [comment]
👍 feel free to merge at will

**Comment by dblock** [comment]
Merge?

**Comment by saratvemulapalli** [comment]
@dblock @reta looks like few plugins are failing. 
Are we planing to get these changes to 2.x ?

**Comment by dblock** [comment]
@saratvemulapalli That would be breaking for 2.x, so no?

**Comment by reta** [comment]
> @saratvemulapalli That would be breaking for 2.x, so no?

:+1 to @dblock's answer, sadly will be breaking change

**Comment by saratvemulapalli** [comment]
Thanks @reta @dblock. I've added this to #3351 .

**Pull request merged**
