### PR TITLE
Fix ShardNotFoundException during request cache clean up

### PR DESCRIPTION
**Pull request by sgup432**
### Description
Fixes issue where request cache tries to clean up entries for deleted indexShard and throws ShardNotFoundException. 
The fix is around returning null in case indexShard is not present and handling it accordingly.
Ran the muted IT tests separately.

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/14190

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sgup432** [comment]
@sohami ^^

**Comment by sohami** [comment]
> ❕ Gradle check result for [5d19f76](https://github.com/opensearch-project/OpenSearch/commit/5d19f76847c643b6a0f98c5be7c1a3089ca47e24): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/40794/)
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

https://github.com/opensearch-project/OpenSearch/issues/12708

**Comment by andrross** [comment]
> Ran the muted IT tests separately.

@sgup432 Can you unmute some of those test cases now with this fix?

**Comment by sgup432** [comment]
@andrross I don't think we can unmute them yet. We are still working to fix them permanently so it doesn't reoccur.

**Pull request merged**
