### PR TITLE
Replacing InboundMessage with NativeInboundMessage for deprecation

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
`InboundMessage` was deprecated in #12967 and replaced with `NativeInboundMessage`. Replacing instances in code for the same.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@VachaShah this is for 3.0 only, right? PS: I think we'll have hard time backporting further changes if we take this path now

**Comment by VachaShah** [comment]
> @VachaShah this is for 3.0 only, right? PS: I think we'll have hard time backporting further changes if we take this path now

Yeah this is only for 3.0 since `InboundMessage` is going to be there in the 2.x line. I did this now so that its not forgotten to be done in the future.

**Comment by VachaShah** [comment]
> ❌ Gradle check result for [38e668c](https://github.com/opensearch-project/OpenSearch/commit/38e668c99ab6ba458e228da670c0a22fd9870e27): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36684/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[Test Result](https://build.ci.opensearch.org/job/gradle-check/36684/testReport/) (1 failure / +1)
[org.opensearch.snapshots.InternalSnapshotsInfoServiceTests.testErroneousSnapshotShardSizes](https://build.ci.opensearch.org/job/gradle-check/36684/testReport/junit/org.opensearch.snapshots/InternalSnapshotsInfoServiceTests/testErroneousSnapshotShardSizes/)

**Comment by VachaShah** [comment]
> ❌ Gradle check result for [38e668c](https://github.com/opensearch-project/OpenSearch/commit/38e668c99ab6ba458e228da670c0a22fd9870e27): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36686/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

https://github.com/opensearch-project/OpenSearch/issues/9464

**Comment by VachaShah** [comment]
> ❌ Gradle check result for [38e668c](https://github.com/opensearch-project/OpenSearch/commit/38e668c99ab6ba458e228da670c0a22fd9870e27): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/36690/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[Test Result](https://build.ci.opensearch.org/job/gradle-check/36690/testReport/) (1 failure / ±0)
[org.opensearch.remotestore.RemoteStoreRestoreIT.testMultipleWriters](https://build.ci.opensearch.org/job/gradle-check/36690/testReport/junit/org.opensearch.remotestore/RemoteStoreRestoreIT/testMultipleWriters/)

**Comment by reta** [comment]
`InboundMessage` could be removed, right?

**Review by dblock — APPROVED** [review]
Is there anything public breaking if this gets backported?

**Comment by dblock** [comment]
@reta 👀 pls

**Comment by reta** [comment]
> @reta 👀 pls

https://github.com/opensearch-project/OpenSearch/pull/13126#issuecomment-2045654558 I think we don't need InboundMessage since it is not used anymore, right?

**Comment by reta** [comment]
> Is there anything public breaking if this gets backported?

We basically removing public API from the picture (InboundMessage), it is a breaking change

**Comment by dblock** [comment]
> > Is there anything public breaking if this gets backported?
> 
> We basically removing public API from the picture (InboundMessage), it is a breaking change

So `InboundMessage` was deprecated in 2.x, we should delete it completely in this PR then?

**Comment by VachaShah** [comment]
Hi @reta and @dblock! Thank you for the reviews! I am wondering if we should backport this PR to 2.x and do a separate PR for removing `InboundMessage` from main which is not backported. Or I can remove `InboundMessage` in this same PR and not backport this PR all together. Let me know what you guys think.

**Comment by reta** [comment]
> Or I can remove `InboundMessage` in this same PR and not backport this PR all together. Let me know what you guys think.

The issue as I see it is that all usages  of `InboundMessage` are replaced with `NativeInboundMessage`, this is fine but for anyone relying on  `InboundMessage`  (fe `TcpTransport::inboundMessage(TcpChannel channel, InboundMessage message)`), the methods will never be called.

**Comment by VachaShah** [comment]
> > Or I can remove `InboundMessage` in this same PR and not backport this PR all together. Let me know what you guys think.
> 
> The issue as I see it is that all usages of `InboundMessage` are replaced with `NativeInboundMessage`, this is fine but for anyone relying on `InboundMessage` (fe `TcpTransport::inboundMessage(TcpChannel channel, InboundMessage message)`), the methods will never be called.

Makes sense! I will remove `InboundMessage` in this PR and keep this change only for main.

**Comment by VachaShah** [comment]
Looks like the BWC tests started failing after removing the `InboundMessage` class all together. Will look into the test failures.

**Comment by VachaShah** [comment]
> ❌ Gradle check result for [adccc66](https://github.com/opensearch-project/OpenSearch/commit/adccc6670b30c37431baa7ac174f4f7698eb90b6): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/37228/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[Test Result](https://build.ci.opensearch.org/job/gradle-check/37228/testReport/) (1 failure / +1)
[org.opensearch.index.remote.RemoteSegmentTransferTrackerTests.testComputeTimeLagOnUpdate](https://build.ci.opensearch.org/job/gradle-check/37228/testReport/junit/org.opensearch.index.remote/RemoteSegmentTransferTrackerTests/testComputeTimeLagOnUpdate/)

https://github.com/opensearch-project/OpenSearch/issues/12639

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@reta Good to merge the breaking change?

**Comment by reta** [comment]
> @reta Good to merge the breaking change?

Ah ... @dblock could you please hold on? We've been recently fighting with an issue (along with @peternied ) that merging breaking change in one pull request impacts the checks for other pull requests. There is nothing wrong with breaking change in major release, but we have a flaw in our checks currently.

**Review by dblock — CHANGES_REQUESTED** [review]
Blocking per @reta.

**Comment by reta** [comment]
> Blocking per @reta.

The relevant change is under discussion https://github.com/opensearch-project/OpenSearch/pull/13283

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@dblock we should be cleared out, the check is disabled on `main` now

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
Note on the failing `detect-breaking-change`: the pull request was merged with this check failing, the check itself is disabled on main now (https://github.com/opensearch-project/OpenSearch/pull/13283)

**Pull request merged**
