### PR TITLE
Upgrade netty to 4.1.84.Final

### PR DESCRIPTION
**Pull request by cwperks**
Signed-off-by: Craig Perkins <cwperx@amazon.com>

### Description

Upgrades netty from 4.1.79.Final -> 4.1.84.Final

Netty has released bugfixes for the issues preventing core from upgrading to 4.1.80.Final. See previous revert commit for details: https://github.com/opensearch-project/OpenSearch/pull/4428

### Check List
- [] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Thanks @cwperks !

**Comment by reta** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> 
>     * **RESULT:** FAILURE x
> 
>     * **URL:** https://build.ci.opensearch.org/job/gradle-check/5429/
> 
>     * **CommitID:** [5e68bbc](https://github.com/opensearch-project/OpenSearch/commit/5e68bbc5d3b446dd0f85b6df61f1adfe57093834)
>       Please examine the workflow log, locate, and copy-paste the failure below.
>       [Flakey test?](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flakey-tests)
>       Iterate to green.

```
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: pr_to_clone_url for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:271)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)
```

@peterzhuamazon seems like Jenkins is broken?

**Comment by peterzhuamazon** [comment]
> > ### Gradle Check (Jenkins) Run Completed with:
> > ```
> > * **RESULT:** FAILURE x
> > 
> > * **URL:** https://build.ci.opensearch.org/job/gradle-check/5429/
> > 
> > * **CommitID:** [5e68bbc](https://github.com/opensearch-project/OpenSearch/commit/5e68bbc5d3b446dd0f85b6df61f1adfe57093834)
> >   Please examine the workflow log, locate, and copy-paste the failure below.
> >   [Flakey test?](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flakey-tests)
> >   Iterate to green.
> > ```
> 
> ```
> [Pipeline] // node
> [Pipeline] End of Pipeline
> groovy.lang.MissingPropertyException: No such property: pr_to_clone_url for class: groovy.lang.Binding
> 	at groovy.lang.Binding.getVariable(Binding.java:63)
> 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:271)
> 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)
> ```
> 
> @peterzhuamazon seems like Jenkins is broken?

We were on another deployment tho. Sorry.
Stable now.

**Comment by cwperks** [comment]
I will take care of the manual backports

**Comment by peterzhuamazon** [comment]
@cwperks seems like this part of the documentation also need some updates as well:
https://opensearch.org/docs/latest/security-plugin/configuration/generate-certificates/#generate-an-admin-certificate

See part with pkcs8 let me know if it is accurate.

Thanks.

**Comment by cwperks** [comment]
@peterzhuamazon It is accurate at the moment, but will change if `security` adds a new runtime dependency on [bcpkix-jdk15on](https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on). I'm planning to submit a PR today to add the jar to the security runtime classpath so that it triggers the new netty logic to use bouncycastle to read pem files instead of the built in PEMReader. If the change is accepted I will file and issue and PR against documentation repo to update the docs for generating certificates - thank you for pointing that out!

**Pull request merged**
