### PR TITLE
adding components to DEVELOPER_GUIDE

### PR DESCRIPTION
**Pull request by CEHENKLE**
Signed-off-by: CEHENKLE <henkle@amazon.com>

### Description
Updating DEVELOPER_GUIDE to include component labels.  

 I've recently started adding component labels to issues in the repo.   It's a housekeeping task to group like sets of work together, but I thought it'd be useful to explain what they were some where in case folks were curious and/or had suggestions on how to refine/improve them.  :)

### CODE REVIEW

**Comment by CEHENKLE** [comment]
@dblock Paging Dr. Block for a review.

**Comment by dblock** [comment]
Needs a rebase, please, then LinkChecker should pass.

**Comment by dblock** [comment]
@CEHENKLE you need to amend your commits with `-s`, DCO

**Comment by CEHENKLE** [comment]
start gradle check

**Comment by CEHENKLE** [comment]
@dblock okay, can you take a look now?

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by tlfeng** [comment]
In log 530:
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.ClusterHealthIT.testHealthOnMasterFailover" -Dtests.seed=FD01D1EED12057C3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=ro-RO -Dtests.timezone=EST -Druntime.java=15

org.opensearch.cluster.ClusterHealthIT > testHealthOnMasterFailover FAILED
    java.util.concurrent.ExecutionException: RemoteTransportException[[node_s5][127.0.0.1:46317][cluster:monitor/health]]; nested: MasterNotDiscoveredException[NodeClosedException[node closed {node_s2}{Xg7v9p_mTmGG3SrJF8pkcg}{1Gt9kJ4ZSXOG9s-P1UolvA}{127.0.0.1}{127.0.0.1:34341}{imr}]]; nested: NodeClosedException[node closed {node_s2}{Xg7v9p_mTmGG3SrJF8pkcg}{1Gt9kJ4ZSXOG9s-P1UolvA}{127.0.0.1}{127.0.0.1:34341}{imr}];
```

In log 536:
```
> Task :test:fixtures:minio-fixture:composeUp

ERROR: for 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture-for-snapshot-tool_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture-other_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Creating 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture_1                   ... done

ERROR: for minio-fixture-for-snapshot-tool  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for minio-fixture-other  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Stopping 81df22525be5077429a7afdcff93efee_minio-fixture__minio-fixture_1 ... 
```

**Comment by tlfeng** [comment]
start gradle check

**Pull request merged**
