### PR TITLE
Fix bwcVersions after bumping version 1.3.1

### PR DESCRIPTION
**Pull request by nknize**
This version needed to be added after bumping 1.3 branch to 1.3.1 in #2509

### CODE REVIEW

**Review by setiah — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by reta** [comment]
@nknize we need to add 1.3.1 to `Version.java` as well:

```
public static final Version V_1_3_1 = new Version(1030199, org.apache.lucene.util.Version.LUCENE_8_10_1);
```

**Review by reta — APPROVED** [review]

**Comment by nknize** [comment]
> @nknize we need to add 1.3.1 to `Version.java` as well:
> 
> ```
> public static final Version V_1_3_1 = new Version(1030199, org.apache.lucene.util.Version.LUCENE_8_10_1);
> ```

I just saw that! Pushed the constant. thx!

**Comment by tlfeng** [comment]
Not related to this PR, but a thought regarding the adding BWC versions in `main` branch, after adding version in branches of lower versions. 
The same negligence occurred just 10 days ago, and fixed by PR https://github.com/opensearch-project/OpenSearch/pull/2430. Maybe some documentation needs to be added, and remind people who adding BWC versions in branches other than `main`.

**Comment by dblock** [comment]
> #2430

I think it wouldn't hurt to have a test that runs part of a gradle precommit / check that all these versions are in sync.

**Comment by nknize** [comment]
> I think it wouldn't hurt to have a test that runs part of a gradle precommit / check that all these versions are in sync.

Sounds like a great first issue or something for the Infra / Build team to pick up!

**Comment by dblock** [comment]
> > I think it wouldn't hurt to have a test that runs part of a gradle precommit / check that all these versions are in sync.
> 
> Sounds like a great first issue or something for the Infra / Build team to pick up!

https://github.com/opensearch-project/OpenSearch/issues/2533

**Pull request merged**
