### PR TITLE
Adding Security Reporting Instructions on README.md file

### LINKED ISSUE #1266: [BUG] Include Security Reporting Instructions on README
**Describe the bug**

Most repos include the security reporting warning ('If you discover a potential security issue...') on the README as well as in the issue template. 

**To Reproduce**
Read the README

**Expected behavior**
It has the security reporting warning

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-Off-by- Rishikesh Reddy Pasham rishireddy1159@gmail.com

### Description
Security warnings and issues reporting instructions are added on README.md file.
 
### Issues Resolved
#1266 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
- TOC needs to be updated
- DCO

**Comment by dblock** [comment]
Are you using `git commit with -s`? DCO check still failing. You might need to squash all these commits too.

**Comment by Rishikesh1159** [comment]
> Are you using `git commit with -s`? DCO check still failing. You might need to squash all these commits too.

Yes. I did squash all my commits now, it should work.

**Comment by tlfeng** [comment]
start gradle check

**Comment by tlfeng** [comment]
Hi Rishikesh, please merge or rebase the upstream `main` branch to your dev branch, to let this commit https://github.com/opensearch-project/OpenSearch/commit/82d1d0ec08ae16bf0ca1d74bb320586a8301d3f9 in your branch.
Also don't forget to sign off at this time. 😉

**Comment by tlfeng** [comment]
start gradle check

**Pull request closed without merging**
