### PR TITLE
Add version 1.3.9

### PR DESCRIPTION
**Pull request by andrross**
BWC tests are failing on 2.x due to the release of 1.3.8.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Thanks @andrross , I think this step was automated, or not anymore?

**Comment by andrross** [comment]
> Thanks @andrross , I think this step was automated, or not anymore?

@reta The version increment on the 1.3 branch is automated (#6163), but the change for BWC on the 2.x branch seems not to be automated (#4709 #5564).

**Comment by andrross** [comment]
@reta It is automated for the BWC version on the `.x` branch of the same major version (#6164) but seems to not look ahead to the _next_ major version.

**Comment by reta** [comment]
> @reta It is automated for the BWC version on the `.x` branch of the same major version (#6164) but seems to not look ahead to the _next_ major version.

Oh I see, thanks @andrross

**Comment by andrross** [comment]
Actually, [it is automated for the `main` branch](https://github.com/opensearch-project/OpenSearch/blob/d266a732aea4cf87781acf93e92c56ad3f1d0913/.github/workflows/version.yml#L103) when a 2.x version is added. Seems there's just this one case of patch release for the previous major version that isn't automated.

**Comment by reta** [comment]
@andrross do we need to bring this to `2.5` and `main` as well?

**Comment by andrross** [comment]
`2.5` yes (#6176). `main` no because it doesn't have any support for the 1.x versions.

**Pull request merged**
