### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by sgbasaraner**
### Description
Fixed a typo: "when it doubt" -> "when in doubt".
 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Thanks @sgbasaraner, can you please amend your commit with `-s` for DCO?

**Comment by sgbasaraner** [comment]
Done

**Comment by tlfeng** [comment]
start gradle check

**Comment by dblock** [comment]
start gradle check

**Comment by tlfeng** [comment]
Hi @sgbasaraner, could you please merge or rebase the current upstream `main` branch to your `patch-1` branch? And remember to commit with `-s` after the merge or rebase. 
There was a commit to add version 1.2 for BWC testing https://github.com/opensearch-project/OpenSearch/commit/cbbf967d761d0bfcb4aa783619cdfdf738676371, without it in your developing branch, I'm afraid the check will fail. Thank you!

**Comment by tlfeng** [comment]
start gradle check

**Comment by dblock** [comment]
Rebased into https://github.com/opensearch-project/OpenSearch/pull/1305

**Pull request closed without merging**
