### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Nishanth-thunder**
### Description
Updated code of conduct as the code of conduct was so old and it was updated 2 years ago.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Rishikesh1159** [comment]
@Nishanth-thunder thanks for raising a PR. Looks like DCO check and Change log verifier are failing. Can you please fix those checks. You can find more details about DCO check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) and for changelog verifier more details are present [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin). You can always look into our [CONTRIBUTING.md](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md) and refer any other PR's.

If you are stuck and need any help with this PR please let me know. I can help you out.

**Comment by minalsha** [comment]
@Nishanth-thunder  could you please address @Rishikesh1159  comment above? Please let us know if you need any help. Thanks.

**Comment by dreamer-89** [comment]
@Nishanth-thunder : Are you still working on this ?

**Comment by DarshitChanpura** [comment]
@Nishanth-thunder Closing this PR as it hasn't been worked on in a while. Please let us know if you are still working on it and we can re-open the PR.

**Pull request closed without merging**
