### PR TITLE
[Backport-1.x]Avoid override of routes() in BaseRestHandler to respect the default behavior defined in RestHandler (#889)

### PR DESCRIPTION
**Pull request by cliu123**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
start gradle check

**Comment by cliu123** [comment]
@dblock @saratvemulapalli Could we have anyone review this backport PR? One of the PR on security plugin needs this PR to be merged. Thanks!

**Comment by vrozov** [comment]
@dblock Should not that PR be split into 2 separate PRs the same way how that was done in `main`?

**Review by dblock — APPROVED** [review]
I'm ok with these going together, as long as we're ok squashing them (the only way merges happen here).

**Comment by cliu123** [comment]
> I'm ok with these going together, as long as we're ok squashing them (the only way merges happen here).

@dblock I think we're ok squashing them as long as the finally merged comit message will reflect both of the 2 PRs.

**Comment by cliu123** [comment]
@dblock Are we waiting for anything to merge it?

**Comment by vrozov** [comment]
IMO, those commits should not be squashed as they address two different issues.

**Comment by dblock** [comment]
@vrozov is right, @cliu123 would you please split these into two backport PRs? I thought I could override the merge to be just the commits, but it's disabled by admin on the repo

**Comment by cliu123** [comment]
> I am going to change my mind, I think @vrozov is right, @cliu123 would you please split these into two backport PRs? sorry for the annoyance

@dblock Removed the 2nd commit from this PR. Once this PR get merged, I'll PR the other commit using the same branch.

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
Merged, thx

**Comment by cliu123** [comment]
@dblock Thanks for reviewing and merging! This is the [PR](https://github.com/opensearch-project/OpenSearch/pull/998) for another commit.

**Pull request merged**
