### PR TITLE
Dependabot fix and pr actions

### LINKED ISSUE #1897: Fix Dependabot integrations
We have Dependabot integrated to create PRs for auto updating versions for dependencies. Currently the Dependabot is only able to scan gradle files from the root directory.

Changes needed:

1. Fix the paths in the Dependabot config to scan nested directories.
2. Integrate updateSHAs and spotless with Dependabot PRs since the Dependabot only updates the dependency version. For example https://github.com/VachaShah/OpenSearch/pull/109 - precommit on this PR fails due to new SHA not being present and https://github.com/opensearch-project/OpenSearch/pull/1881 - precommit on this PR fails due to spotless errors.

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
This PR fixes dependabot integrations:
1. Updates the paths for the nested directories so all the `build.gradle` can be scanned.
2. Adds a workflow for running on dependabot PRs to run `./gradlew updateSHAs` and `./gradlew spotlessApply` on dependabot generated PRs since dependabot only updates the version in the `build.gradle`.

Note: I tried these updates on my fork and dependabot successfully opened PRs and the `dependabot_pr` workflow successfully updated them with the updateSHAs and spotless (if required). https://github.com/VachaShah/OpenSearch/pulls

The current open pr limit is being set to 1, once the PRs open correctly with the auto commits (along with CI triggers), I will go and update the limits to 10.

### Issues Resolved
#1897 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
LGTM, needs a rebase

**Comment by VachaShah** [comment]
Hi @dblock, I am keeping this PR in draft since it needs a Github App to trigger workflows on the auto commits. If I merge it without that change, Dependabot will open hundreds of PRs against the repo with the auto commits for updating SHAs not triggering CI runs.

**Comment by VachaShah** [comment]
Known dependabot issue: https://github.com/dependabot/dependabot-core/issues/2804

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Looks like a bunch of PRs failed with `Error: Error: Input required and not supplied: app_id` :(

**Comment by VachaShah** [comment]
> Looks like a bunch of PRs failed with `Error: Error: Input required and not supplied: app_id` :(

Yeah its not able to access the App ID of the Github App :( I am looking through what is causing this.

**Comment by VachaShah** [comment]
> > Looks like a bunch of PRs failed with `Error: Error: Input required and not supplied: app_id` :(
> 
> Yeah its not able to access the App ID of the Github App :( I am looking through what is causing this.

The issue is fixed. I will re-trigger CIs on all the Dependabot PRs (example https://github.com/opensearch-project/OpenSearch/pull/2140) once the currently ongoing gradle check failure on main is fixed so we don't have unnecessary gradle checks running leading to resource consumption.

**Pull request merged**
