### PR TITLE
Update to Gradle 7.5

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Gradle 7.5 update. As always, hitting API incompatibilities.
 
### Issues Resolved
Closes https://github.com/opensearch-project/OpenSearch/issues/3901
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
start gradle check`

**Comment by reta** [comment]
start gradle check

**Comment by reta** [comment]
start gradle check

**Comment by reta** [comment]
start gradle check

**Comment by reta** [comment]
start gradle check

**Comment by reta** [comment]
start gradle check

**Review by adnapibar — APPROVED** [review]
:+1:

**Review by kartg — APPROVED** [review]

**Review by dblock — APPROVED** [review]
Plugins will have to upgrade too I imagine?

**Comment by reta** [comment]
> Plugins will have to upgrade too I imagine?

Yes, desirable (but luckily it is non breaking), I will take plugins + java client one by one

**Pull request merged**
