### PR TITLE
Removed CheckStyle code formatting plugin

### PR DESCRIPTION
**Pull request by owaiskazi19**
Signed-off-by: Owais Kazi <owaiskazi19@gmail.com>

### Description
Currently the project has two formatting tools Spotless and CheckStyle. Spotless itself can format the code and check the standard java code using spotlessApply and spotlessJavaCheck respectively. Both the plugins have different configuration for formatting which restrict us to run Spotless on all the subprojects. Removing CheckStyle will help to run a unified formatting on the codebase.
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/1362
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
> Between the time that we remove checkstyle and add spotless to the entire repo, would the modules excluded from spotless have no formatting standards?

Good question. Few are already formatted with CheckStyle and few are not formatted by any plugins is what I can think of. Once we apply Spotless on all the modules they'll follow https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/formatterConfig.xml

**Comment by tlfeng** [comment]
start gradle check

**Comment by tlfeng** [comment]
start gradle check

**Review by saratvemulapalli — APPROVED** [review]
Changes look good to me!

**Pull request merged**
