### PR TITLE
build no-jdk distributions as part of release build

### PR DESCRIPTION
**Pull request by rursprung**
### Description
with commit e3572464859 the `build.sh` has been moved to this repository and with commit dfa1118eee8 the missing no-jdk builds have been added. with these preliminary works done we can now start building the no-jdk distributions as part of the release build so that they can then be published.

this is part of opensearch-project/opensearch-build#99.

Signed-off-by: Ralph Ursprung <Ralph.Ursprung@avaloq.com>

### Issues Resolved
part of opensearch-project/opensearch-build#99

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rursprung** [comment]
CC @dblock & @peterzhuamazon

**Review by reta — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@rursprung Do you want this in 2.x? Will need a manual backport.

**Comment by rursprung** [comment]
> @rursprung Do you want this in 2.x? Will need a manual backport.

yes, this should land in 2.x if ever possible. i can take care of it next week (i'm off work now)

**Comment by rursprung** [comment]
> > @rursprung Do you want this in 2.x? Will need a manual backport.
> 
> yes, this should land in 2.x if ever possible. i can take care of it next week (i'm off work now)

i've now raised the backport PR: https://github.com/opensearch-project/OpenSearch/pull/4993

**Pull request merged**
