### PR TITLE
[Search Pipeline] Flip SEARCH_PIPELINE feature flag for Search Pipeline GA

### PR DESCRIPTION
**Pull request by noCharger**
### Description
Flip the feature flag as described in https://github.com/opensearch-project/OpenSearch/pull/8513#issuecomment-1630338966

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/8489

### Check List
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@noCharger we need to update the documentation for this feature [1], could you please create an issue there? thank you

[1] https://github.com/opensearch-project/documentation-website/tree/main/_search-plugins/search-pipelines

**Comment by reta** [comment]
Flaky tests failures from https://github.com/opensearch-project/OpenSearch/issues/8131

**Comment by reta** [comment]
Precommit crashes JVM:

```
Exec output and error:
> Task :modules:reindex:jarHell FAILED
| Output for C:\hostedtoolcache\windows\Java_Adopt_jdk\11.0.19-7\x64\bin\java.exe:OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000090000000, 117440512, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 117440512 bytes for Failed to commit area from 0x0000000090000000 to 0x0000000097000000 of length 117440512.
# An error report file with more information is saved as:
# D:\a\OpenSearch\OpenSearch\modules\reindex\hs_err_pid7140.log

 JVM crash log found: file:///D:/a/OpenSearch/OpenSearch/hs_err_pid5260.log
```

**Comment by noCharger** [comment]
> @noCharger we need to update the documentation for this feature [1], could you please create an issue there? thank you
> 
> [1] https://github.com/opensearch-project/documentation-website/tree/main/_search-plugins/search-pipelines

[Issue](https://github.com/opensearch-project/documentation-website/issues/4540) created, thanks!

**Comment by reta** [comment]
@msfroh looks good to you?

**Comment by noCharger** [comment]
@msfroh @andrross need more eyes on this PR. Thanks!

**Review by scrawfor99 — APPROVED** [review]
Looks good. This can be merged.

**Comment by macohen** [comment]
@reta are you able to merge, please? any other concerns or need for @andrross to take a look?

**Pull request merged**
