### PR TITLE
Add perms for remote snapshot cache eviction on scripted query

### LINKED ISSUE #14268: [BUG] java.io.FilePermission error while querying remote restored index with scripted field.
### Describe the bug

We're trying out searchable snapshots. we've taken snapshot and restored as remote searchable index on search nodes.
also we've a scripted field defined.

When querying getting the below exception.

```java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
java.base/java.lang.SecurityManager.checkDelete(SecurityManager.java:875)
java.base/sun.nio.fs.UnixPath.checkDelete(UnixPath.java:794)
java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:226)
java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
org.opensearch.index.store.remote.filecache.FileCacheFactory.lambda$createDefaultBuilder$0(FileCacheFactory.java:58)
org.opensearch.ExceptionsHelper.catchAsRuntimeException(ExceptionsHelper.java:352)
org.opensearch.index.store.remote.filecache.FileCacheFactory.lambda$createDefaultBuilder$1(FileCacheFactory.java:58)
org.opensearch.index.store.remote.utils.cache.LRUCache.evict(LRUCache.java:363)
org.opensearch.index.store.remote.utils.cache.LRUCache.replaceNode(LRUCache.java:330)
org.opensearch.index.store.remote.utils.cache.LRUCache.compute(LRUCache.java:168)
org.opensearch.index.store.remote.utils.cache.SegmentedCache.compute(SegmentedCache.java:96)
org.opensearch.index.store.remote.filecache.FileCache.compute(FileCache.java:91)
org.opensearch.index.store.remote.utils.TransferManager.fetchBlob(TransferManager.java:59)
org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.fetchBlock(OnDemandBlockSnapshotIndexInput.java:148)
org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.demandBlock(OnDemandBlockIndexInput.java:340)
org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.seekInternal(OnDemandBlockIndexInput.java:311)
org.opensearch.index.store.remote.file.OnDemandBlockIndexInput.readInt(OnDemandBlockIndexInput.java:251)
org.opensearch.index.store.remote.file.OnDemandBlockSnapshotIndexInput.readInt(OnDemandBlockSnapshotIndexInput.java:28)
org.apache.lucene.codecs.lucene90.IndexedDISI.advanceBlock(IndexedDISI.java:474)
org.apache.lucene.codecs.lucene90.IndexedDISI.advanceExact(IndexedDISI.java:459)
org.apache.lucene.codecs.lucene90.Lucene90DocValuesProducer$21.advanceExact(Lucene90DocValuesProducer.java:904)
org.apache.lucene.index.SingletonSortedSetDocValues.advanceExact(SingletonSortedSetDocValues.java:85)
org.opensearch.index.fielddata.FieldData$12.advanceExact(FieldData.java:434)
org.opensearch.index.fielddata.ScriptDocValues$BinaryScriptDocValues.setNextDocId(ScriptDocValues.java:508)
org.opensearch.index.fielddata.ScriptDocValues$Strings.setNextDocId(ScriptDocValues.java:547)
org.opensearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:103)
org.opensearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:56)
if (doc.containsKey('tp') && !doc['tp'].empty ) {
  def 
                                  ^---- HERE



access denied ("java.io.FilePermission" "/data/opensearch/data/nodes/0/cache/tIZdR9UlQZqkFyOsaAIycw/0/RemoteLocalStore/_259_Lucene90_0.dvd.15" "delete")
```

but the required file permissions are there `0755`

### Related component

Search:Searchable Snapshots

### To Reproduce

1. Index some data
2. Take snapshot
3. restore snapshot as remote
4. query with a scripted field defined

### Expected behavior

It should not throw any exception and should work like regular search i.e scripted field on a normal index vs remote index(restored from snapshot as remote).

### Additional Details

**Opensearch**
version: 2.13

### PR DESCRIPTION
**Pull request by finnegancarroll**
### Description
Scripted queries require elevated permissions to write to a remote snapshot local file cache. Since accessing the file cache can trigger an eviction the AccessController doPrivileged call needs to move up the call stack so we have permissions to perform file deletions for these evictions.

Reproduced and verified fix with OSB StackOverflow workload:
1. Run OSB StackOverflow workload.
2. Create snapshot from so index.
3. Restore from remote snapshot.
4. Query with a scripted field. 
```
curl -X POST "http://localhost:9200/so/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match": {
      "body": "java"
    }
  },
  "script_fields": {
    "combined_field": {
      "script": {
        "source": "params[\"_source\"][\"user\"] + \" \" + params[\"_source\"][\"body\"]"
      }
    }
  },
  "size": 100
}
'
```

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "failed to parse / load source"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "so",
        "node" : "Q87dFmoFQ4ivpVr0ng82NQ",
        "reason" : {
          "type" : "script_exception",
          "reason" : "runtime error",
          "script_stack" : [
            "org.opensearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:115)",
            "org.opensearch.script.FieldScript.lambda$static$2(FieldScript.java:72)",
            "org.opensearch.script.DynamicMap.get(DynamicMap.java:84)",
            "params[\"_source\"][\"user\"] + \" \" + params[\"_source\"][\"body\"]",
            "       ^---- HERE"
          ],
          "script" : "params[\"_source\"][\"user\"] + \" \" + params[\"_source\"][\"body\"]",
          "lang" : "painless",
          "position" : {
            "offset" : 7,
            "start" : 0,
            "end" : 59
          },
          "caused_by" : {
            "type" : "parse_exception",
            "reason" : "failed to parse / load source",
            "caused_by" : {
              "type" : "access_control_exception",
              "reason" : "access denied (\"java.io.FilePermission\" \"/local/home/carrofin/DEBUG/STORES/DATA/nodes/0/cache/nI-w4Uy5QzeP73xjaqu4SQ/0/RemoteLocalStore/_nd.fdt.87\" \"delete\")"
            }
          }
        }
      }
    ],
    "caused_by" : {
      "type" : "parse_exception",
      "reason" : "failed to parse / load source",
      "caused_by" : {
        "type" : "access_control_exception",
        "reason" : "access denied (\"java.io.FilePermission\" \"/local/home/carrofin/DEBUG/STORES/DATA/nodes/0/cache/nI-w4Uy5QzeP73xjaqu4SQ/0/RemoteLocalStore/_nd.fdt.87\" \"delete\")"
      }
    }
  },
  "status" : 400
}
```
### Related Issues
Resolves #14268

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
Thanks @finnegancarroll! Can you see if you can add a test to SearchableSnapshotIT that fails without this fix?

**Comment by andrross** [comment]
Let's add a changelog entry under "Fixed" as well. Something like "Fix searchable snapshot failure with scripted fields".

**Comment by andrross** [comment]
Sorry for the delay @finnegancarroll. Can you rebase this PR? Also, did you look at adding a test case for this scenario?

**Comment by finnegancarroll** [comment]
> Sorry for the delay @finnegancarroll. Can you rebase this PR? Also, did you look at adding a test case for this scenario?
I'm having trouble reproducing in an integration test. After hacking the cache capacity and block size such that I get evictions I do not see permission issues when running a scripted query. I think the way scripted queries are mocked in the integration tests by overriding `protected Map<String, Function<Map<String, Object>, Object>> pluginScripts()` is not adequately reproducing the permissions.

**Comment by finnegancarroll** [comment]
Flaky tests
https://github.com/opensearch-project/OpenSearch/issues/5329
https://github.com/opensearch-project/OpenSearch/issues/13846

**Comment by finnegancarroll** [comment]
@andrross when you have a moment can you take a look?
Thanks!

**Review by andrross — APPROVED** [review]

**Pull request merged**
