### PR TITLE
fix wlm stats output

### PR DESCRIPTION
**Pull request by kaushalmahi12**
### Description
This change is to disambiguate the wlm stats representation and make it more easily comprehendible

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [X] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kaushalmahi12** [comment]
> @kaushalmahi12 - Failing test looks related to the changes:


Missed this since this was in separate package. fixed it now..

**Review by jainankitk — APPROVED** [review]

**Comment by jainankitk** [comment]
Unrelated failure:

```
[Test Result](https://build.ci.opensearch.org/job/gradle-check/49267/testReport/) (1 failure / +1)

    [org.opensearch.index.translog.RemoteFsTimestampAwareTranslogTests.testMetadataFileDeletionWithPinnedTimestamps](https://build.ci.opensearch.org/job/gradle-check/49267/testReport/junit/org.opensearch.index.translog/RemoteFsTimestampAwareTranslogTests/testMetadataFileDeletionWithPinnedTimestamps/)
```

**Comment by jainankitk** [comment]
Unrelated failures, retrying gradle check:

```
[Test Result](https://build.ci.opensearch.org/job/gradle-check/49270/testReport/) (5 failures / +4)

    [org.opensearch.cluster.MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock](https://build.ci.opensearch.org/job/gradle-check/49270/testReport/junit/org.opensearch.cluster/MinimumClusterManagerNodesIT/testThreeNodesNoClusterManagerBlock/)
    [org.opensearch.cluster.MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock](https://build.ci.opensearch.org/job/gradle-check/49270/testReport/junit/org.opensearch.cluster/MinimumClusterManagerNodesIT/testThreeNodesNoClusterManagerBlock_2/)
    [org.opensearch.cluster.MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock](https://build.ci.opensearch.org/job/gradle-check/49270/testReport/junit/org.opensearch.cluster/MinimumClusterManagerNodesIT/testThreeNodesNoClusterManagerBlock_3/)
    [org.opensearch.cluster.MinimumClusterManagerNodesIT.testThreeNodesNoClusterManagerBlock](https://build.ci.opensearch.org/job/gradle-check/49270/testReport/junit/org.opensearch.cluster/MinimumClusterManagerNodesIT/testThreeNodesNoClusterManagerBlock_4/)
    [org.opensearch.cluster.SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes](https://build.ci.opensearch.org/job/gradle-check/49270/testReport/junit/org.opensearch.cluster/SpecificClusterManagerNodesIT/testElectOnlyBetweenClusterManagerNodes/)
```

**Review by dbwiddis — COMMENTED** [review]
Generally LGTM. Two questions:
 - we're changing output to an existing API. Is this API/backwards compatible or an acceptable change?
 - Is there an update to the documentation (see PR template for check box) or REST API associated here?

**Comment by jainankitk** [comment]
> Generally LGTM. Two questions:
> 
>     * we're changing output to an existing API. Is this API/backwards compatible or an acceptable change?
> 
>     * Is there an update to the documentation (see PR template for check box) or REST API associated here?

@dbwiddis - Thanks for sharing your thoughts. Backward compatibility should not be an issue as the API was recently added and not part of 2.17 release. Good point regarding the documentation update.

@kaushalmahi12 @ruai0511 - Have we added documentation for wlm stats api already? If no, can we link the documentation issue to this PR? If yes, we should create issue to update the documentation

**Comment by kaushalmahi12** [comment]
https://github.com/opensearch-project/documentation-website/issues/8194 - This is the high level issue here. We will be adding the documentation in coming days.

**Pull request merged**
