### PR TITLE
Update `newQueryShardContext()` to fix breaking changes

### PR DESCRIPTION
**Pull request by harshavamsi**
### Description
Fixes BWC for `newQueryShardContext` -- https://github.com/opensearch-project/OpenSearch/actions/runs/10710534586/job/29697453754?pr=15703

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by msfroh — APPROVED** [review]

**Review by jainankitk — APPROVED** [review]
@harshavamsi - Change looks good. I am curious if you noticed some tests failing?

**Comment by harshavamsi** [comment]
> @harshavamsi - Change looks good. I am curious if you noticed some tests failing?

https://github.com/opensearch-project/OpenSearch/pull/15703 -- BWC tests were failing because I did not overload the method enough

**Comment by jainankitk** [comment]
> > @harshavamsi - Change looks good. I am curious if you noticed some tests failing?
> 
> #15703 -- BWC tests were failing because I did not overload the method enough

Thanks @harshavamsi. Interestingly, `detect-breaking-changes` check had not failed for this PR - https://github.com/opensearch-project/OpenSearch/pull/15538, which was also breaking.

@msfroh - Probably a gap we should address in the breaking change detector?

**Comment by harshavamsi** [comment]
```
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 2.17.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-tar/build/distributions/opensearch-min-2.17.0-SNAPSHOT-linux-x64.tar.gz
```

huh how is it running bwc on 2.17?

**Comment by harshavamsi** [comment]
> ```
> Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> > Building 2.17.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-tar/build/distributions/opensearch-min-2.17.0-SNAPSHOT-linux-x64.tar.gz
> ```
> 
> huh how is it running bwc on 2.17?

I think this is failing on 2.17 because the original change has not been backported to 2.x yet. @msfroh what do you think we can do here?

**Comment by msfroh** [comment]
Can you cherry-pick the commit locally, and push it on your branch for the other change?

**Comment by jainankitk** [comment]
> Can you cherry-pick the commit locally, and push it on your branch for the other change?

Seems to be the issue across all PRs - https://github.com/opensearch-project/OpenSearch/pull/15713#issuecomment-2330634143. I think this has probably to do with bwc not setup for 2.17 yet!? Not sure if we need any manual step after bumping up the version to 2.17 in 2.x branch

**Comment by harshavamsi** [comment]
> > Can you cherry-pick the commit locally, and push it on your branch for the other change?
> 
> Seems to be the issue across all PRs - [#15713 (comment)](https://github.com/opensearch-project/OpenSearch/pull/15713#issuecomment-2330634143). I think this has probably to do with bwc not setup for 2.17 yet!? Not sure if we need any manual step after bumping up the version to 2.17 in 2.x branch

https://github.com/opensearch-project/OpenSearch/pull/15712 -- is this because we already cut 2.17 branch and depend on this PR?

**Comment by msfroh** [comment]
We've had 2.17.0 builds all day. They've been coming off the 2.17 branch.

**Comment by jainankitk** [comment]
Do we need to bump up the bwc version in main to 2.18 after bumping to 2.18 for 2.x - https://github.com/opensearch-project/OpenSearch/pull/15680?

**Comment by jainankitk** [comment]
Okay, this PR needs to go in - https://github.com/opensearch-project/OpenSearch/pull/15712/ before builds can start passing again!

**Comment by harshavamsi** [comment]
> Okay, this PR needs to go in - #15712 before builds can start passing again! @bowenlan-amzn resolved similar issue [#15053 (comment)](https://github.com/opensearch-project/OpenSearch/pull/15053#issuecomment-2263758684) when we released 2.16

https://github.com/opensearch-project/OpenSearch/pull/15053#issuecomment-2263798056 -- based on this comment looks like the build manifest needs to be updated?

**Comment by msfroh** [comment]
Ahhh! What changed since I came home is that the 2.18 update on 2.x got merged. (We need to update 2.x before we update main.)

Now we need to update main, which maybe needs the manifest change first? 

Or we need a 2.x Jenkins build to publish 2.18 artifacts. Then we can merge the 2.18 version change for main. Then everyone can rebase their PRs onto that.

**Comment by harshavamsi** [comment]
> Ahhh! What changed since I came home is that the 2.18 update on 2.x got merged. (We need to update 2.x before we update main.)
> 
> Now we need to update main, which maybe needs the manifest change first?
> 
> Or we need a 2.x Jenkins build to publish 2.18 artifacts. Then we can merge the 2.18 version change for main. Then everyone can rebase their PRs onto that.

https://github.com/opensearch-project/opensearch-build/issues/4908#issuecomment-2330707336 -- I added a comment on the 2.17 release issue. Maybe we can automate the manifest update once a version is cut

**Comment by jainankitk** [comment]
@harshavamsi - I believe we don't need to backport this PR to 2.x/2.17, since the original PR never made there?

**Comment by harshavamsi** [comment]
> @harshavamsi - I believe we don't need to backport this PR to 2.x/2.17, since the original PR never made there?

Right, I cherry picked this commit onto 2.x and 2.17 PRs so no need to backport

**Pull request merged**
