### PR TITLE
Add darwin-arm64-tar and no-jdk-darwin-arm64-tar archive distributions.

### LINKED ISSUE #1667: Support for Apple Silicon (arm64) archive distribution build
**Is your feature request related to a problem? Please describe.**
The archive distributions support x86-64 builds but not arm64.

**Describe the solution you'd like**
Add darwin-arm64-tar and no-jdk-darwin-arm64-tar flavors for the archives distribution.

**Describe alternatives you've considered**
Build darwin-tar and use Rosetta 2

**Additional context**
While building on a MacBook Pro 2021 (M1), the default is to try to build arm64 architecture but the targets do not exist.

### PR DESCRIPTION
**Pull request by sharp-pixel**
Signed-off-by: Cédric Pelvet <cedric.pelvet@gmail.com>

### Description
Add darwin-arm64-tar and no-jdk-darwin-arm64-tar flavors for the archives distribution.
 
### Issues Resolved
#1667
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Nice, thanks!

**Comment by dblock** [comment]
start gradle check

**Review by reta — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by sharp-pixel** [comment]
Looking at the build error, looks like an issue with networking.
```
> Task :test:fixtures:s3-fixture:composeUp

ERROR: for 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-session-token_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-repositories-metering_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-other_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-ec2_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Creating 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-ecs_1              ... done
```

Not sure how my changes could impact this. Or maybe an issue on GitHub's side

**Comment by sharp-pixel** [comment]
I had a deeper look at what's happening by running locally and it looks like there is something wrong with tests around BWC:
```
Project :qa:full-cluster-restart declares a dependency from configuration 'opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v1.3.0-1-1.3.0-' to configuration 'expanded-darwin-arm64-tar' which is not declared in the descriptor for project :distribution:bwc:minor.
```
I spent some time in these tests but I cannot understand where this comes from. Can anyone help here? Thanks

**Comment by dblock** [comment]
> I had a deeper look at what's happening by running locally and it looks like there is something wrong with tests around BWC:
> 
> ```
> Project :qa:full-cluster-restart declares a dependency from configuration 'opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v1.3.0-1-1.3.0-' to configuration 'expanded-darwin-arm64-tar' which is not declared in the descriptor for project :distribution:bwc:minor.
> ```
> 
> I spent some time in these tests but I cannot understand where this comes from. Can anyone help here? Thanks

@saratvemulapalli is familiar with this, help?

**Comment by dblock** [comment]
This needs a rebase please.

**Comment by dblock** [comment]
@sharp-pixel Do you want help with this? Want to finish it up?

**Comment by saratvemulapalli** [comment]
> > I had a deeper look at what's happening by running locally and it looks like there is something wrong with tests around BWC:
> > ```
> > Project :qa:full-cluster-restart declares a dependency from configuration 'opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v1.3.0-1-1.3.0-' to configuration 'expanded-darwin-arm64-tar' which is not declared in the descriptor for project :distribution:bwc:minor.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I spent some time in these tests but I cannot understand where this comes from. Can anyone help here? Thanks
> 
> @saratvemulapalli is familiar with this, help?

I somehow missed this. Will take a look.

**Comment by saratvemulapalli** [comment]
@sharp-pixel could you rebase this and merge from main? 
We could run another gradle check and start debugging.

**Comment by sharp-pixel** [comment]
> @sharp-pixel could you rebase this and merge from main? We could run another gradle check and start debugging.

I rebased my changes. I did more debugging on my side from on an Apple Silicon Mac, and it looks like the BWC process is checking compatibility with previous versions (starting from 7.x) with the darwin-arm4 arch. The problem is that these distributions don't exist. I would need to explicitely say that the first darwin-arm64 version is this one for the backward compatibility checks, but couldn't find out how.

**Comment by sharp-pixel** [comment]
> @sharp-pixel Do you want help with this? Want to finish it up?

Yes, sorry for the delay, was checking more things on my side + holidays

**Review by dblock — APPROVED** [review]

**Comment by sharp-pixel** [comment]
Beware that even though all tests pass here, `./gradlew check` is failing on an M1 mac due to BWC (see my previous comment about missing previous versions in this new architecture)

**Comment by dblock** [comment]
> Beware that even though all tests pass here, `./gradlew check` is failing on an M1 mac due to BWC (see my previous comment about missing previous versions in this new architecture)

Yes, this is _a_ step forward, but we have more work to do to CI/CD for Darwin.

**Comment by dblock** [comment]
@sharp-pixel We have a parent item, https://github.com/opensearch-project/opensearch-build/issues/38, so if there's something we can do here next to advance the big picture?

**Comment by saratvemulapalli** [comment]
> > @sharp-pixel could you rebase this and merge from main? We could run another gradle check and start debugging.
> 
> I rebased my changes. I did more debugging on my side from on an Apple Silicon Mac, and it looks like the BWC process is checking compatibility with previous versions (starting from 7.x) with the darwin-arm4 arch. The problem is that these distributions don't exist. I would need to explicitely say that the first darwin-arm64 version is this one for the backward compatibility checks, but couldn't find out how.

Could you open an issue with the failures? 
I believe we have 2 steps here:
1. Run the CI in Darwin Arm64
2. Fix BWC for Darwin Arm64

**Comment by dblock** [comment]
> 1. Run the CI in Darwin Arm64

https://github.com/opensearch-project/OpenSearch/issues/1449

> 2. Fix BWC for Darwin Arm64

I'll let @sharp-pixel do that and describe it nicely ;)

**Comment by radar** [comment]
Hello, I was wondering if this could be applied to the 1.3.x branch as well? I would like to be able to install that version specifically on my Mac.

**Comment by dblock** [comment]
@radar AFAIK there are no more 1.3.x releases except for high sev security patches, https://github.com/orgs/opensearch-project/projects/1

**Comment by radar** [comment]
No problems @dblock, thank you for the headsup.

**Pull request merged**
