### PR TITLE
Add a unit test for MultiTermsAggregator.buildEmptyAggregations (#7089)

### LINKED ISSUE #7089: [BUG] NullPointerException in multi_terms query
Hi all,
we want to use OpenSearch for querying our systems to get aggregated system information like CPU and RAM usage.
Therefore we use date historgram aggregation. Since we want to have those measures for different hosts / containers / processes we need also a kind of grouping mechanism which we tried to realize with the `multi_terms` feature.

Our initial query was looking like this:

```
{
  "aggs": {
    "xLCAggPerTime": {
      "aggs": {
        "MyGroupingAggregate": {
          "aggs": {
            "CPU": {
              "avg": {
                "field": "system.cpu.total.norm.pct"
              }
            },
            "Memory": {
              "avg": {
                "field": "system.memory.actual.used.bytes"
              }
            }
          }, 
          "multi_terms": {
            "terms": [
                {"field": "host.name"},
                {"field": "agent.type"}
              ]
          }
        },
        "xLCAggBucketSort": {
          "bucket_sort": {
            "from": 0,
            "size": 1000
          }
        }
      },
      "date_histogram": {
        "field": "@timestamp",
        "fixed_interval": "1s"
      }
    }
  },
  "from": 0,
  "query": {
    "range": {
      "@timestamp": {
        "gte": "2023-02-09T12:15:47Z",
        "lt": "2023-02-09T12:16:47Z"
      }
    }
  },
  "size": 0,
  "sort": [
    {
      "@timestamp": {
        "unmapped_type": "date",
        "order": "asc"
      }
    }
  ]
}
```
However this query results in the following execption:
`
java.lang.NullPointerException: Cannot invoke \"org.opensearch.common.io.stream.NamedWriteable.getWriteableName()\" because \"namedWriteable\" is null
`

If needed I can also provide the full error response, but for me it seems not to contain much more meaningful information.

The query runs fine if the `multi_terms` part is removed, leaving only 
``` json
            "terms": 
                {"field": "agent.type.keyword"}
              
```
I also tried to minimize the query in order to isolate the issue and it came out that the following query will still produce the error:

``` json
{
  "aggs": {
    "xLCAggPerTime": {
      "aggs": {
        "MyGroupingAggregate": {
          "multi_terms": {
            "terms": [
                {"field": "host.name"},
                {"field": "agent.type"}
              ]
          }
        }
      },
      "date_histogram": {
        "field": "@timestamp",
        "fixed_interval": "60s"
      }
    }
  }
}
```

**Important Note: The queries were tested with ElasticSearch 8.7.0 and they worked as expected. So the queries themsselves can be considered to be correct.**

Thank you already in advance for your help! :slight_smile:

**To Reproduce**
Have an OpenSearch Instance with MetricBeat and run the above query.

**Expected behavior**
The query runs and returns zero or more results, depending on the data in OpenSearch. However, there shall not be a Nullpointer Exception.

**Plugins**
MetricBeat

**Host/Environment (please complete the following information):**
OpenSearch Version used: 2.2.0 & 2.6.0
MetricBeat: 2.7.12.1

### PR DESCRIPTION
**Pull request by austintlee**
### Description
A new unit test for the implementation of buildEmptyAggregation in MultiTermsAggregator

### Issues Resolved
#7089 

### Check List
- [ ] New functionality includes testing.
  - [x ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
@austintlee Thanks! What are your concerns with this UT? The amount of setup you had to do to get to the actual aggreation?

**Comment by austintlee** [comment]
@dblock yeah, the current implementation of MultiTermsAggregator makes it quite difficult to unit test it due to very heavy setup.  Maybe this is generally the case for many classes in OpenSearch?  Is there an issue for that that I can take a look at?  Coming back to this, I think having a unit test is still worth it.

The reason why this PR is failing checks is because this commit needs to be built on top of the other commit that has the actual fix for the NPE which is in another PR.  I can add this commit to #7318

**Comment by dblock** [comment]
> @dblock yeah, the current implementation of MultiTermsAggregator makes it quite difficult to unit test it due to very heavy setup. Maybe this is generally the case for many classes in OpenSearch? Is there an issue for that that I can take a look at? Coming back to this, I think having a unit test is still worth it.

Absolutely. And thank you.

I don't know of an open issue for this, feel free to make one or just do it. Any code deleted will be appreciated!
 
> The reason why this PR is failing checks is because this commit needs to be built on top of the other commit that has the actual fix for the NPE which is in another PR. I can add this commit to #7318

Yep, you should. A failing unit test that demonstrates a problem is a great step 1 for a fix, but you already did the step 2 of fixing the issue, so you're all set 😅 Close this and tack the UT to the other PR and iterate to green.

**Comment by kotwanikunal** [comment]
Apologies. This PR was auto closed without reaching a resolution from the maintainers.
Re-opening to move it forward.
Thanks for your contributions to OpenSearch!

**Comment by ashking94** [comment]
Closing this PR as the marked issue is closed already

**Comment by peternied** [comment]
@reta looks like you closed out the issue related to this change, what do you think of this change?

@austintlee did you still want to see about getting this change merged?

**Comment by austintlee** [comment]
We can close this one.  As I mentioned above, I merged the change in this PR into another PR.

**Pull request closed without merging**
