### PR TITLE
[Backport] Upgrading gson to 2.8.9 (#1541)

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha <vachshah@amazon.com>

### Description
Backport of #1541 
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I don't think we should be backporting this into 1.2, hasn't that ship sailed?

**Comment by VachaShah** [comment]
> I don't think we should be backporting this into 1.2, hasn't that ship sailed?

Backporting this to 1.2 since it is related to https://github.com/google/gson/pull/1991

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [0f1eb21](https://github.com/opensearch-project/OpenSearch/commit/0f1eb2124d871669eeefa4be007703b1aa4793f6) [Log 1087](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1087.log)
> 
> [Reports 1087](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1087_reports.zip)

```
REPRODUCE WITH: ./gradlew ':distribution:tools:plugin-cli:test' --tests "org.opensearch.plugins.InstallPluginCommandTests" -Dtests.method="testOfficialPluginSnapshot {p0=com.google.common.jimfs.JimfsFileSystem@7b5b4f4d p1=org.opensearch.plugins.InstallPluginCommandTests$1Parameter$$Lambda$211/0x0000000800d72208@5ec1bf50}" -Dtests.seed=914519AA9C3BBE1F -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ru-RU -Dtests.timezone=Europe/Vaduz -Druntime.java=15
  2> java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Comment by VachaShah** [comment]
start gradle check

**Review by CEHENKLE — APPROVED** [review]

**Pull request merged**
