### PR TITLE
Update Jackson to 2.12.5

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Although there are no CVEs reported against `2.11.4`, the `2.11.x` release branch is not actively maintained anymore (the last release was in December, 2020). As per [1], `2.12.x` should be backward compatible with `2.11.x`, with no breaking changes expected.

[1] https://github.com/FasterXML/jackson/wiki/Jackson-Releases#general
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Comment by reta** [comment]
Thanks @nknize !

**Review by saratvemulapalli — APPROVED** [review]
Changes look good to me.
Thanks @reta !

**Comment by reta** [comment]
Thank you @saratvemulapalli !

**Comment by reta** [comment]
@dblock @nknize any concerns you have guys? Thank you!

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Let’s back port it to 1.x?

**Comment by reta** [comment]
@dblock sure, will do it shortly, thank you!

**Pull request merged**
