### PR TITLE
Replace exclusionary words whitelist and blacklist in the places that won't impact backwards compatibility

### LINKED ISSUE #1484: Replace "blacklist/whitelist" terminology in code comments, and internal variable, method and class names
**Is your feature request related to a problem? Please describe.**
Replace "blacklist/whitelist" terminology in the code base, but only the places that won't impact the backwards compatibility. 

A part of #1483 

**Describe the solution you'd like**
Replace all the "blacklist/whitelist" terminology with "**denylist/allowlist**" in the following location:
- code comments
- Internal variable, method and class names

Any APIs or configurations will not be impacted.

**Describe alternatives you've considered**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by aponb**
Description

Replacing the exclusionary words whitelist and blacklist that won't impact the compatibility. Changes just in code comments, internal variables, methods and class names.

Issues Resolved

This Pull request replaces Pull request https://github.com/opensearch-project/OpenSearch/pull/1970
Resolve #1484

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Andreas apre@gmx.at

### CODE REVIEW

**Review by tlfeng — APPROVED** [review]
Thanks for the change! 👍

**Comment by nknize** [comment]
Can we rebase and merge this?

**Comment by dblock** [comment]
@aponb Care to rebase and we'll merge? Thanks.

**Comment by tlfeng** [comment]
Hi @aponb, could you please resolve the conflicts, by either manually, or merge/rebase the upstream `main` branch to your feature branch? So that your code change can be merged. We would ship this change in version 1.3.0 release.

**Comment by aponb** [comment]
> Hi @aponb, could you please resolve the conflicts, by either manually, or merge/rebase the upstream `main` branch to your feature branch? So that your code change can be merged. We would ship this change in version 1.3.0 release.

I merged the new changes. I pushed my branch, and tests are running now!

**Comment by dblock** [comment]
```
* What went wrong:
Execution failed for task ':qa:full-cluster-restart:v1.3.0#oldClusterTest'.
> There were failing tests. See the report at: file:///var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/qa/full-cluster-restart/build/reports/tests/v1.3.0%23oldClusterTest/index.html
```

https://github.com/opensearch-project/OpenSearch/issues/1793

**Comment by dblock** [comment]
start gradle check

**Comment by tlfeng** [comment]
In log 3002:
```

REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testOperationBasedRecovery" -Dtests.seed=9E55F733A653B468 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-DZ -Dtests.timezone=Australia/Perth -Druntime.java=17

org.opensearch.upgrades.FullClusterRestartIT > testOperationBasedRecovery FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:46235], URI [/testoperationbasedrecovery], status line [HTTP/1.1 200 OK]
    {"acknowledged":true,"shards_acknowledged":true,"index":"testoperationbasedrecovery"}
        at __randomizedtesting.SeedInfo.seed([9E55F733A653B468:83B9FB16A0D54E1F]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
        at app//org.opensearch.upgrades.FullClusterRestartIT.testOperationBasedRecovery(FullClusterRestartIT.java:1289)

REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testSnapshotRestore" -Dtests.seed=9E55F733A653B468 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-DZ -Dtests.timezone=Australia/Perth -Druntime.java=17

org.opensearch.upgrades.FullClusterRestartIT > testSnapshotRestore FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:46235], URI [/testsnapshotrestore], status line [HTTP/1.1 200 OK]
    {"acknowledged":true,"shards_acknowledged":true,"index":"testsnapshotrestore"}
        at __randomizedtesting.SeedInfo.seed([9E55F733A653B468:A1301DCA6CEEB317]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
        at app//org.opensearch.upgrades.FullClusterRestartIT.testSnapshotRestore(FullClusterRestartIT.java:810)

REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testResize" -Dtests.seed=9E55F733A653B468 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-DZ -Dtests.timezone=Australia/Perth -Druntime.java=17

org.opensearch.upgrades.FullClusterRestartIT > testResize FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:39569], URI [/testresize], status line [HTTP/1.1 200 OK]
    {"acknowledged":true,"shards_acknowledged":true,"index":"testresize"}
        at __randomizedtesting.SeedInfo.seed([9E55F733A653B468:292AEDC7B9152E53]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
        at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
        at app//org.opensearch.upgrades.FullClusterRestartIT.testResize(FullClusterRestartIT.java:1387)

```

**Comment by aponb** [comment]
> In log 3002:
> 
> ```
> 
> REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testOperationBasedRecovery" -Dtests.seed=9E55F733A653B468 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-DZ -Dtests.timezone=Australia/Perth -Druntime.java=17
> 
> org.opensearch.upgrades.FullClusterRestartIT > testOperationBasedRecovery FAILED
>     org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:46235], URI [/testoperationbasedrecovery], status line [HTTP/1.1 200 OK]
>     {"acknowledged":true,"shards_acknowledged":true,"index":"testoperationbasedrecovery"}
>         at __randomizedtesting.SeedInfo.seed([9E55F733A653B468:83B9FB16A0D54E1F]:0)
>         at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
>         at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
>         at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
>         at app//org.opensearch.upgrades.FullClusterRestartIT.testOperationBasedRecovery(FullClusterRestartIT.java:1289)
> 
> REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testSnapshotRestore" -Dtests.seed=9E55F733A653B468 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-DZ -Dtests.timezone=Australia/Perth -Druntime.java=17
> 
> org.opensearch.upgrades.FullClusterRestartIT > testSnapshotRestore FAILED
>     org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:46235], URI [/testsnapshotrestore], status line [HTTP/1.1 200 OK]
>     {"acknowledged":true,"shards_acknowledged":true,"index":"testsnapshotrestore"}
>         at __randomizedtesting.SeedInfo.seed([9E55F733A653B468:A1301DCA6CEEB317]:0)
>         at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
>         at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
>         at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:952)
>         at app//org.opensearch.upgrades.FullClusterRestartIT.testSnapshotRestore(FullClusterRestartIT.java:810)
> 
> REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v1.3.0#oldClusterTest' --tests "org.opensearch.upgrades.FullClusterRestartIT.testResize" -Dtests.seed=9E55F733A653B468 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-DZ -Dtests.timezone=Australia/Perth -Druntime.java=17
> 
> org.opensearch.upgrades.FullClusterRestartIT > testResize FAILED
>     org.opensearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:39569], URI [/testresize], status line [HTTP/1.1 200 OK]
>     {"acknowledged":true,"shards_acknowledged":true,"index":"testresize"}
>         at __randomizedtesting.SeedInfo.seed([9E55F733A653B468:292AEDC7B9152E53]:0)
>         at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
>         at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
>         at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:976)
>         at app//org.opensearch.test.rest.OpenSearchRestTestCase.createIndex(OpenSearchRestTestCase.java:956)
>         at app//org.opensearch.upgrades.FullClusterRestartIT.testResize(FullClusterRestartIT.java:1387)
> ```

I also got this error first. By providing a JAVA11_HOME and a JAVA8_HOME on my local machine the test did pass. Strange, that the check is not working on the server.

**Comment by andrross** [comment]
@aponb that error is unrelated to this change and was fixed in #2334. You may need to rebase the latest changes to get the fix.

**Comment by aponb** [comment]
> @aponb that error is unrelated to this change and was fixed in #2334. You may need to rebase the latest changes to get the fix.

thanks. Looks green now.

**Comment by tlfeng** [comment]
Thanks @aponb for your constant quick response! I will merge it today.

**Comment by aponb** [comment]
> Thanks @aponb for your constant quick response! I will merge it today.

Thanks again to you and also the others for your help!

**Comment by tlfeng** [comment]
Hi @aponb , you are very welcome! 😄
The automatic backport workflow failed, maybe there are some conflicts with your commit and `1.x` branch. 
Would you mind create a PR manually to backport the change into `1.x`? So that the change can be included in version 1.3.0 .
Even if you don't have enough time, we can help you create the backport PR.

**Comment by aponb** [comment]
> Hi @aponb , you are very welcome! smile The automatic backport workflow failed, maybe there are some conflicts with your commit and `1.x` branch. Would you mind create a PR manually to backport the change into `1.x`? So that the change can be included in version 1.3.0 , the code freeze date is Mar.9th (PST) Even if you don't have enough time, we can help you create the backport PR.

ok. I created a backport of the changes. See #2365

**Pull request merged**
