### PR TITLE
Backport of PRs for profile related changes in concurrent search path

### PR DESCRIPTION
**Pull request by sohami**
### Description
This PR backports following PRs from main to 2.x as discussed [here](https://github.com/opensearch-project/OpenSearch/pull/10352#issuecomment-1775603136). There were no new changes needed other than updating the CHANGELOG.md file.

https://github.com/opensearch-project/OpenSearch/pull/9248
https://github.com/opensearch-project/OpenSearch/pull/10111
https://github.com/opensearch-project/OpenSearch/pull/10547
https://github.com/opensearch-project/OpenSearch/pull/10352

### Check List
- [X] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ticheng-aws** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29289/
> * **CommitID:** [1bd7fe1](https://github.com/opensearch-project/OpenSearch/commit/1bd7fe1e836f466d43b2a9b70c85bc5321b2e177)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

This is a known bug https://github.com/opensearch-project/OpenSearch/issues/10798
```
Tests with failures:
 - org.opensearch.search.suggest.CompletionSuggestSearchIT.testSkipDuplicates {p0={"search.concurrent_segment_search.enabled":"false"}}
 - org.opensearch.search.suggest.CompletionSuggestSearchIT.testSkipDuplicates {p0={"search.concurrent_segment_search.enabled":"true"}}

4535 tests completed, 2 failed, 34 skipped
```

**Comment by sohami** [comment]
DCO was failing with below. For some reason it was trying to find `51488860+ticheng-aws@users.noreply.github.com` instead of `ticheng@amazon.com`. From commit I can see Signed-Off message has correct username. So have made DCO to pass manually.

```
Commit sha: [2796681](https://github.com/opensearch-project/OpenSearch/pull/10898/commits/2796681accb95c0b9345473287081171dc031e21), Author: Ticheng Lin, Committer: Sorabh Hamirwasia; Expected "Ticheng Lin [51488860+ticheng-aws@users.noreply.github.com](mailto:51488860+ticheng-aws@users.noreply.github.com)", but got "Ticheng Lin [ticheng@amazon.com](mailto:ticheng@amazon.com)".
Commit sha: [1bd7fe1](https://github.com/opensearch-project/OpenSearch/pull/10898/commits/1bd7fe1e836f466d43b2a9b70c85bc5321b2e177), Author: Ticheng Lin, Committer: Sorabh Hamirwasia; Can not find "Ticheng Lin [51488860+ticheng-aws@users.noreply.github.com](mailto:51488860+ticheng-aws@users.noreply.github.com)", in ["Ticheng Lin [ticheng@amazon.com](mailto:ticheng@amazon.com)", "Ticheng Lin [ticheng@amazon.com](mailto:ticheng@amazon.com)", "Ticheng Lin [ticheng@amazon.com](mailto:ticheng@amazon.com)"].
```

**Comment by sohami** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:**  ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29302/
> * **CommitID:** [1bd7fe1](https://github.com/opensearch-project/OpenSearch/commit/1bd7fe1e836f466d43b2a9b70c85bc5321b2e177)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Created tracking issue for this flaky test: https://github.com/opensearch-project/OpenSearch/issues/11032

**Comment by sohami** [comment]
@reta @ticheng-aws Can you check this PR ? It should be good to merge now.

**Review by ticheng-aws — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
> @reta @ticheng-aws Can you check this PR ? It should be good to merge now.

Thanks @sohami , please get the green Gradle check

**Comment by sohami** [comment]
> > @reta @ticheng-aws Can you check this PR ? It should be good to merge now.
> 
> Thanks @sohami , please get the green Gradle check

@reta  the test failure is due to shrink API. I have created a tracking [issue](https://github.com/opensearch-project/OpenSearch/issues/11032) for the same. Since the changes are in search path I don't see both to be related.

**Comment by reta** [comment]
> @reta the test failure is due to shrink API. I have created a tracking [issue](https://github.com/opensearch-project/OpenSearch/issues/11032) for the same. Since the changes are in search path I don't see both to be related.

We have tons of flaky tests but the checks have to pass before merge

**Pull request merged**
