### PR TITLE
[Backport] [2.10] - Add Tracing Instrumentation at Network and Rest layer

### PR DESCRIPTION
**Pull request by Gaganjuneja**
### Description
backport #9415 to 2.10
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Gaganjuneja** [comment]
@reta, please take a look.

**Review by reta — APPROVED** [review]

**Review by gaiksaya — CHANGES_REQUESTED** [review]
Blocking this PR as it broke security plugin. Waiting on confirmation from @reta

**Comment by gaiksaya** [comment]
Looks like compatibility tool showed the right results:

```
Incompatible components: [https://github.com/opensearch-project/security.git]

**Comment by reta** [comment]
Closing the backport to 2.10, it will break the `security` plugin:

```
  required: Settings,NetworkService,BigArrays,ThreadPool,NamedXContentRegistry,Dispatcher,ClusterSettings,SharedGroupFactory,Tracer                                        
  found: Settings,NetworkService,BigArrays,ThreadPool,NamedXContentRegistry,ValidatingDispatcher,ClusterSettings,SharedGroupFactory                                        
  reason: actual and formal argument lists differ in length
/home/andriy.redko/Workspaces/OpenSearch-plugins/opensearch-security/src/main/java/org/opensearch/security/http/SecurityNonSslHttpServerTransport.java:54: error: constructor Netty4HttpServerTransport in class Netty4HttpServerTransport cannot be applied to given types;
        super(settings, networkService, bigArrays, threadPool, namedXContentRegistry, dispatcher, clusterSettings, sharedGroupFactory);                                    
        ^                                                                            
  required: Settings,NetworkService,BigArrays,ThreadPool,NamedXContentRegistry,Dispatcher,ClusterSettings,SharedGroupFactory,Tracer                                        
  found: Settings,NetworkService,BigArrays,ThreadPool,NamedXContentRegistry,Dispatcher,ClusterSettings,SharedGroupFactory                                                  
  reason: actual and formal argument lists differ in length

```

Retargeting it to 2.11

**Pull request closed without merging**
