### PR TITLE
Fix issue with feature flags where default value may not be honored

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Fixes an issue where FeatureFlags is not honoring the default value of the feature flag setting when calling `isEnabled`. 

The bug exists because the settings object in the FeatureFlags class is not initialized until initializeFeatureFlags is called and will return false from this [line](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L93) instead of honoring the default value. While a feature guarded by a feature flag should not be enabled by default, this is a bug in the way the feature flags logic is implemented. 

### Related Issues

- https://github.com/opensearch-project/OpenSearch/issues/9564

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Add a test for other defaults? (`false`, other types?)

**Comment by cwperks** [comment]
> Add a test for other defaults? (false, other types?)

@dblock I added an additional test for a feature flag where default value is false.

While its not strictly enforced, due to the presence of methods like `isEnabled`, feature flags are exclusively boolean settings.

**Comment by dblock** [comment]
> ❌ Gradle check result for [ea21ee8](https://github.com/opensearch-project/OpenSearch/commit/ea21ee88a0ed5d4e4480c733337ee4ce38808531): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/35720/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

@cwperks looks like [org.opensearch.common.util.FeatureFlagTests.testBooleanFeatureFlagWithDefaultSetToTrue](https://build.ci.opensearch.org/job/gradle-check/35720/testReport/junit/org.opensearch.common.util/FeatureFlagTests/testBooleanFeatureFlagWithDefaultSetToTrue/) failed.

**Comment by cwperks** [comment]
> @cwperks looks like [org.opensearch.common.util.FeatureFlagTests.testBooleanFeatureFlagWithDefaultSetToTrue](https://build.ci.opensearch.org/job/gradle-check/35720/testReport/junit/org.opensearch.common.util/FeatureFlagTests/testBooleanFeatureFlagWithDefaultSetToTrue/) failed.

@dblock I pushed another commit to handle the case when FeatureFlag initialization is called with empty settings where it can disregard defaults. 

There are a lot of static variables and methods in this class which can make it unpredictable during the gradle check.

**Review by dblock — APPROVED** [review]

**Comment by cwperks** [comment]
I will open a backport for this

**Comment by cwperks** [comment]
Opened up a backport here: https://github.com/opensearch-project/OpenSearch/pull/12912

I'm not sure why the automatic backport failed. After cherry-picking, there were no conflicts to resolve.

**Pull request merged**
