### PR TITLE
Upgrading mockito version in OpenSearch

### LINKED ISSUE #1008: Upgrade mockito in OpenSearch
Currently, OpenSearch is using [mockito version 1.9.5 ](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/build.gradle#L125). Opening this issue to upgrade the [mockito](https://github.com/mockito/mockito) version in OpenSearch.

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
Upgrading the `mockito-core` version in OpenSearch from 1.9.5 to 3.11.2.
 
### Issues Resolved
#1008 
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by adnapibar** [comment]
start gradle check

**Comment by dblock** [comment]
I'm amazed that we did two major version bumps for mockito, and everything just worked!?

**Comment by VachaShah** [comment]
> I'm amazed that we did two major version bumps for mockito, and everything just worked!?

Yeah the direct dependencies worked fine for the upgrade.

**Comment by vrozov** [comment]
It does not look that the change updates mockito version globally on the OpenSearch project. The change is local to `build-tools` module. The mocking framework is provided by `org.elasticsearch:securemock:1.2` that is based on the old `1.9.5` `mockito-core` version.

**Comment by VachaShah** [comment]
> It does not look that the change updates mockito version globally on the OpenSearch project. The change is local to `build-tools` module. The mocking framework is provided by `org.elasticsearch:securemock:1.2` that is based on the old `1.9.5` `mockito-core` version.

Yes the securemock update is part of issue #114. This PR is to upgrade the direct dependency for mockito.

**Comment by vrozov** [comment]
IMO, it is confusing to have two different versions (2 major versions apart) in a single project. Will it be better to upgrade both dependencies at the same time or use the same `securemock` dependency in all modules?

**Comment by vrozov** [comment]
The dependency seems to be used only by `PluginBuildPluginTests` where mockito is used simply to mock `BwcVersions` class without mocking any of its methods. It seems that such usage can be replaced with `null`.

**Comment by VachaShah** [comment]
> IMO, it is confusing to have two different versions (2 major versions apart) in a single project. Will it be better to upgrade both dependencies at the same time or use the same `securemock` dependency in all modules?

You are right, we can do this as part of securemock. I will close this PR.

**Pull request closed without merging**
