### PR TITLE
[Backport 2.x] Add indexRandomForConcurrentSearch for tests

### PR DESCRIPTION
**Pull request by jed326**
### Description
Manual backport for the following commits:
- #11181
- #11118 
- #11130
- #11212
- #11184
- #11076

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
> https://build.ci.opensearch.org/job/gradle-check/29979/
- https://github.com/opensearch-project/OpenSearch/issues/7934

**Comment by jed326** [comment]
Will do this manually in #11204

**Comment by jed326** [comment]
https://build.ci.opensearch.org/job/gradle-check/30116/
- https://github.com/opensearch-project/OpenSearch/issues/6090

**Comment by sohami** [comment]
Have manually set DCO to pass since I verified that each commit has the `Signed-off-by` line in it

**Review by sohami — APPROVED** [review]

**Pull request merged**
