### PR TITLE
Bump Apache Lucene to 9.11.0-snapshot-8a555eb (`main` only)

### PR DESCRIPTION
**Pull request by reta**
### Description
Bump Apache Lucene to 9.11.0-snapshot-8a555eb (`main` only)

### Related Issues
N/A

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kotwanikunal — APPROVED** [review]

**Comment by naveentatikonda** [comment]
@reta Are we not backporting this to 2.x ? This PR too https://github.com/opensearch-project/OpenSearch/pull/13195

**Comment by reta** [comment]
> @reta Are we not backporting this to 2.x ? This PR too https://github.com/opensearch-project/OpenSearch/pull/13195

@naveentatikonda we will backport once 9.11 is out (should be quite soon)

**Comment by naveentatikonda** [comment]
> > @reta Are we not backporting this to 2.x ? This PR too #13195
> 
> @naveentatikonda we will backport once 9.11 is out (should be quite soon)

Oh I see...we need some of these changes into 2.x for the lucene byte scalar quantization feature to run some benchmarking tests which needs to be released in opensearch version 2.15

**Comment by reta** [comment]
> It might be late if we wait until 9.11 is released. So, can we backport these 2 PRs to 2.x for now ?

We have to be sure that 9.11 is released before 2.15.0, since this is the branch the 2.15.0 will be cut off (we obviously cannot make any releases with snapshots). There talks about getting 9.11 out (see please https://lists.apache.org/list.html?dev@lucene.apache.org) but no dates yet.

**Comment by naveentatikonda** [comment]
> > It might be late if we wait until 9.11 is released. So, can we backport these 2 PRs to 2.x for now ?
> 
> We have to be sure that 9.11 is released before 2.15.0, since this is the branch the 2.15.0 will be cut off (we obviously cannot make any releases with snapshots). There are talks about getting 9.11 out (see please https://lists.apache.org/thread/wtxslwp3c55j8hv6pk854xnc7pmdn0w0) but no dates yet.

You are right. That makes sense. Thanks!

**Pull request merged**
