### PR TITLE
Add ppc64le architecture

### PR DESCRIPTION
**Pull request by helix-loop**
Add ppc64le architecture for the current architecture check.

### Description
Ability to build OpenSearch on ppc64le architecture
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/1303
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
@helix-loop Thanks! The PR needs `git commit --amend -s` to get DCO to pass.

In the meantime, do we need both `ppc64` and `ppc64le`? And what hardware did you test this on?

**Comment by helix-loop** [comment]
@dblock It would be better to have both, but I can only test and tested this on ppc64le.

**Comment by dblock** [comment]
Is this ready? Unit tests?

**Comment by kartg** [comment]
@helix-loop are you still working on this? What is left to get this from draft to ready-to-merge?

**Comment by helix-loop** [comment]
Currently not. I guess the Unit tests are missing to get this ready. However https://github.com/opensearch-project/OpenSearch/pull/3930 seems to be further.

**Comment by dreamer-89** [comment]
@helix-loop : Are you still working on this ?

**Comment by tlfeng** [comment]
@helix-loop Thank you for your contribution! I'm afraid that I have to close this PR. 
As mentioned in issue #1303, the code change is made by commit https://github.com/opensearch-project/OpenSearch/commit/d76adf3504e3001a84d53177af8ea36af2cc65c1

**Pull request closed without merging**
