### PR TITLE
Adding back [Time series based workload desc order optimization through reverse segment read (#7244)] with fixes

### LINKED ISSUE #7878: [BUG] Reindex is break can not copy all documents from source
**Describe the bug**
Reindex only copy partial of source documents to destination, and seems this is only happened for index `opensearch_dashboards_sample_data_logs` which OSD provided as an example dataset.

**To Reproduce**
1. Usig [docker-compose.yml](https://gist.githubusercontent.com/peterzhuamazon/6718c4fe6db13aa219a64971a61ab6fa/raw/95217de7b229f042b060bd15903de28462c4681d/docker-compose.yml) to spinup OpenSearch and OpenSearch dashboard
2. Import sample web logs data from OpenSearch dashboards 
image

3. perform reindex for index `opensearch_dashboards_sample_data_logs`
```
POST _reindex
{
  "source": {
    "index": "opensearch_dashboards_sample_data_logs"
  },
  "dest": {
    "index": "reindex-logs-20230602"
  }
}
```

4. see the result, total have 14074 records, but reindex only copy 3227 documents.
```
{
  "took": 871,
  "timed_out": false,
  "total": 14074,
  "updated": 0,
  "created": 3227,
  "deleted": 0,
  "batches": 4,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1,
  "throttled_until_millis": 0,
  "failures": []
}
```

**Expected behavior**
Reindex should copy all documents from source index to dest, that say should 14074 documents reindexed.

**Plugins**
using [docker-compose.yml](https://gist.githubusercontent.com/peterzhuamazon/6718c4fe6db13aa219a64971a61ab6fa/raw/95217de7b229f042b060bd15903de28462c4681d/docker-compose.yml)

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Amazon linux
 - Version 2.8, main

**Additional context**

**OpenSearch 2.7 don't have this issue, test the same index, work as expected.**

To see the segments of index 
```
GET _cat/segments/opensearch_dashboards_sample_data_logs?v

index                                  shard prirep ip         segment generation docs.count docs.deleted    size size.memory committed searchable version compound
opensearch_dashboards_sample_data_logs 0     p      172.17.0.3 _9               9       2500            0   1.6mb           0 true      true       9.6.0   true
opensearch_dashboards_sample_data_logs 0     p      172.17.0.3 _b              11        574            0 419.1kb           0 true      true       9.6.0   true
opensearch_dashboards_sample_data_logs 0     p      172.17.0.3 _c              12      11000            0   5.7mb           0 true      true       9.6.0   false
opensearch_dashboards_sample_data_logs 0     r      172.17.0.4 _a              10       2347            0   1.5mb           0 true      true       9.6.0   true
opensearch_dashboards_sample_data_logs 0     r      172.17.0.4 _b              11       3227            0     2mb           0 true      true       9.6.0   true
opensearch_dashboards_sample_data_logs 0     r      172.17.0.4 _c              12       8500            0   4.4mb           0 true      true       9.6.0   false

```

index mapping 
```
{
  "properties": {
    "@timestamp": {
      "path": "timestamp",
      "type": "alias"
    },
    "agent": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "bytes": {
      "type": "long"
    },
    "clientip": {
      "type": "ip"
    },
    "event": {
      "type": "object",
      "properties": {
        "dataset": {
          "type": "keyword"
        }
      }
    },
    "extension": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "geo": {
      "type": "object",
      "properties": {
        "coordinates": {
          "type": "geo_point"
        },
        "dest": {
          "type": "keyword"
        },
        "src": {
          "type": "keyword"
        },
        "srcdest": {
          "type": "keyword"
        }
      }
    },
    "host": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "index": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "ip": {
      "type": "ip"
    },
    "machine": {
      "type": "object",
      "properties": {
        "os": {
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          },
          "type": "text"
        },
        "ram": {
          "type": "long"
        }
      }
    },
    "memory": {
      "type": "double"
    },
    "message": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "phpmemory": {
      "type": "long"
    },
    "referer": {
      "type": "keyword"
    },
    "request": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "response": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "tags": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "timestamp": {
      "type": "date"
    },
    "url": {
      "fields": {
        "keyword": {
          "type": "keyword",
          "ignore_above": 256
        }
      },
      "type": "text"
    },
    "utc_time": {
      "type": "date"
    }
  }
}
```

seems that only segments `172.17.0.4 _b              11       3227` are searched

### PR DESCRIPTION
**Pull request by gashutos**
### Description
This PR adds back reverted PR #7244 due to bug introduced in re-index in this issue #7878.
The issue was, re-index operation on timeseries based workload was only able to re-index documents in its last segment and was skipping all other segments, hence we had data loss.
The reason behind this, we do early terminate the sort queries if lucene index is `indexsorted` or sort field is `_doc`. As per [TopFieldCollector](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/TopFieldCollector.java#L55) code, in case of `IndexSort` or `_doc` field sort, it does earlyTerminate and searches only very first segment. ReIndex plugin queries `scroll` query on `_doc` field in `asc` order. Hence the issue was with Reindex.

In this PR, I am adding check not to enable this optimization in case if sorting is not on @timestamp field as well if it is IndexSorted.

### Related Issues
Resolves #7878 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
> The issue was, re-index operation on timeseries based workload was only able to re-index documents in its last segment and was skipping all other segments, hence we had data loss.

@gashutos would be great if we could somehow add test case(s) for that, what do you think?

**Comment by andrross** [comment]
> would be great if we could somehow add test case(s) for that, what do you think?

Agreed. @gashutos Can you add an integration or unit test to ensure we're not still hitting the early terminate behavior?

**Comment by gashutos** [comment]
> Report



> > would be great if we could somehow add test case(s) for that, what do you think?
> 
> Agreed. @gashutos Can you add an integration or unit test to ensure we're not still hitting the early terminate behavior?

Oops, I missed adding file to commit. Just added now.
Sorry, just got back from short vacation so delay in response. Added integ test to commit now.

**Comment by gashutos** [comment]
>>> would be great if we could somehow add test case(s) for that, what do you think?

>> Agreed. @gashutos Can you add an integration or unit test to ensure we're not still hitting the early terminate behavior?

> Oops, I missed adding file to commit. Just added now.
Sorry, just got back from short vacation so delay in response. Added integ test to commit now.

I was trying a lot about adding unit test to cover `codcov` happy. I think for this scenario, Integ tests are fine but unit tests doesnt add much value even if we end up covering lines. Let me know if you guys think otherwise.

**Comment by reta** [comment]
@gashutos mind please to create a manual backport to `2.x`, thank you

**Pull request merged**
