### PR TITLE
Update runTask to optionally install plugins

### PR DESCRIPTION
**Pull request by mch2**
### Description
Update runTask to optionally install plugins from the command line.

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/6285

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [x] New functionality has been documented.
  - [ ] ~New functionality has javadoc added~
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by dblock — COMMENTED** [review]
Should we just call this property `plugins`? Seems clearer, no?

```
./gradlew run -Pplugins="['plugin1', 'plugin2']"
```

**Comment by mch2** [comment]
> Should we just call this property `plugins`? Seems clearer, no?
> 
> ```
> ./gradlew run -Pplugins="['plugin1', 'plugin2']"
> ```

Yeah thought this too but `plugins` is already a list populated by gradle plugins and will conflict.

```
println plugins
[org.gradle.api.plugins.HelpTasksPlugin$Inject@26650c9b, org.gradle.buildinit.plugins.BuildInitPlugin$Inject@2583c168, org.gradle.buildinit.plugins.WrapperPlugin$Inject@3feadd9c, org.gradle.language.base.plugins.LifecycleBasePlugin$Inject@18ffbf3f, org.opensearch.gradle.docker.DockerSupportPlugin@1e93a4e6, org.opensearch.gradle.info.GlobalBuildInfoPlugin@26ca5145, org.gradle.api.plugins.ReportingBasePlugin$Inject@52398d4c, org.gradle.api.plugins.TestReportAggregationPlugin$Inject@2f5f8baf, org.gradle.api.plugins.JvmEcosystemPlugin$Inject@6c82ca37, org.gradle.testing.jacoco.plugins.JacocoPlugin$Inject@60549e67, org.gradle.testing.jacoco.plugins.JacocoReportAggregationPlugin$Inject@938a4d, org.opensearch.gradle.JdkDownloadPlugin@6233f9a2, org.gradle.plugins.ide.idea.IdeaPlugin$Inject@17a58251, org.opensearch.gradle.DistributionDownloadPlugin@6bd50a8a, org.opensearch.gradle.internal.InternalDistributionDownloadPlugin@51bfcfe8, org.opensearch.gradle.ReaperPlugin@11cd98b5, org.opensearch.gradle.testclusters.TestClustersPlugin$TestClustersHookPlugin@17fb1cfa, org.opensearch.gradle.testclusters.TestClustersPlugin$Inject@3af9321c]
```

**Review by msfroh — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]

**Comment by dblock** [comment]
This resolves https://github.com/opensearch-project/OpenSearch/issues/6285 actually, I'll leave the other issue that asks for `plugins:xyz:run` open, it's a nicer syntax ;)

**Comment by reta** [comment]
@mch2 could you please backport manually to `2.x`?

**Pull request merged**
