### PR TITLE
Fix AwarenessAttributeDecommissionIT flaky tests

### LINKED ISSUE #5220: [BUG] testNodesRemovedAfterZoneDecommission_ClusterManagerNotInToBeDecommissionedZone flaky
org.opensearch.cluster.coordination.AwarenessAttributeDecommissionIT/testNodesRemovedAfterZoneDecommission_ClusterManagerNotInToBeDecommissionedZone

  https://build.ci.opensearch.org/job/gradle-check/6771/
  https://build.ci.opensearch.org/job/gradle-check/6731/

### PR DESCRIPTION
**Pull request by imRishN**
### Description
Few tests in AwarenessAttributeDecommissionIT fails transiently as while making the client request if a `viaNode` is not specified it uses a `RandomizingClient` which can let the request land up on a decommissioned node and then we see exception that cluster manager is not discovered which is not the case. This PR aims to always pick a active node to route the request. 

### Issues Resolved
#5220
#5221 
#5189 

### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Makes sense, merge?

**Comment by imRishN** [comment]
> Makes sense, merge?

Yes, we can merge this now. I'll push another empty commit. It passes again and not flaky anymore

**Comment by dblock** [comment]
Looks like some transient connectivity failures ... let's keep retrying for now.

@imRishN instead of empty commits you can `git commit --amend`, then `git push origin integ-test-fix -f`.

**Comment by imRishN** [comment]
@dblock Thanks for merging it. Can you please also help me add 2.x backport tag so that this commit doesn't get missed in future releases? Thanks!

**Pull request merged**
