### PR TITLE
Add condition that PRs are merged in backport workflow

### PR DESCRIPTION
**Pull request by andrross**
This brings our backport workflow script in line with the script from the [tibdex/backport][1] github action implementation.

[1]: https://github.com/tibdex/backport/blob/b1bb2aaf611d9f2e5d1900c06493769b9f102a45/.github/workflows/backport.yml#L12-L22

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by kotwanikunal — APPROVED** [review]

**Comment by kotwanikunal** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/9847/
> * **CommitID:** [f3d2395](https://github.com/opensearch-project/OpenSearch/commit/f3d23959de29d19ae33a0f1601c81b3a3b9112ec)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

```
fatal: reference is not a tree: f3d23959de29d19ae33a0f1601c81b3a3b9112ec
```

Force push issue

**Comment by kotwanikunal** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/9848/
> * **CommitID:** [016e266](https://github.com/opensearch-project/OpenSearch/commit/016e2660ab7d130871b55e45a4721ab64b29bd3a)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

This will need a merge on #5993

**Comment by kotwanikunal** [comment]
> The backport to `2.x` failed:
> 
> ```
> The process '/usr/bin/git' failed with exit code 128
> ```
> 
> To backport manually, run these commands in your terminal:
> 
> ```shell
> # Fetch latest updates from GitHub
> git fetch
> # Create a new working tree
> git worktree add ../.worktrees/backport-2.x 2.x
> # Navigate to the new working tree
> pushd ../.worktrees/backport-2.x
> # Create a new branch
> git switch --create backport/backport-5997-to-2.x
> # Cherry-pick the merged commit of this pull request and resolve the conflicts
> git cherry-pick -x --mainline 1 715ff72c1bf1ca31e861639faa664f92f6115501
> # Push it to GitHub
> git push --set-upstream origin backport/backport-5997-to-2.x
> # Go back to the original working tree
> popd
> # Delete the working tree
> git worktree remove ../.worktrees/backport-2.x
> ```
> 
> Then, create a pull request where the `base` branch is `2.x` and the `compare`/`head` branch is `backport/backport-5997-to-2.x`.

Might have failed because of #5992

**Comment by andrross** [comment]
Backport PR: #6002

**Pull request merged**
