### PR TITLE
[Port main] update version check as per v2.11.0

### PR DESCRIPTION
**Pull request by r1walz**
port [`94173e3`](https://github.com/opensearch-project/OpenSearch/commit/94173e3f8b343ba29db24e5682d1706bbda9f9a4) from #10267.

### CODE REVIEW

**Review by shwetathareja — APPROVED** [review]

**Comment by msfroh** [comment]
I made the mistake of merging another backport PR before merging this version check fix on `main`. Now we have two version check changes pending on `main`, blocking each other.

I've asked @sgup432 to add the change from this PR (#10271) to https://github.com/opensearch-project/OpenSearch/pull/10280, so they can go in together.

**Comment by msfroh** [comment]
Alternatively, @r1walz, if you can add the change from https://github.com/opensearch-project/OpenSearch/pull/10280 to this PR, that would also fix the build.

**Comment by r1walz** [comment]
I see that my commit is merged in that PR. Feel free to close this one if @sgup432 is comfortable with it :smile:

**Comment by msfroh** [comment]
The other PR was merged with both commits. Closing this one -- sorry for the delay!

**Pull request closed without merging**
