### PR TITLE
Remove macOS from gradle assemble github check

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Remove macOS from gradle assemble github check

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/15743

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Per request, remove the macos from gradle assemble as it is causing issues back and forth. Since we are already building macos snapshot tarball in https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/ running assemble.

cc: @reta @mch2 @getsaurabh02 

Thanks.

**Review by reta — CHANGES_REQUESTED** [review]
@peterzhuamazon I think we fixed all the issues, right?  

> Since we are already building macos snapshot tarball in https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/ running assemble.

We don't build the tarball using different JDKs, the value of this check is that we try to make sure all JDKs we claim to support are supported.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon I think we fixed all the issues, right?
> 
> > Since we are already building macos snapshot tarball in https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/ running assemble.
> 
> We don't build the tarball using different JDKs, the value of this check is that we try to make sure all JDKs we claim to support are supported.

That is a good point so will wait for others to chime in.
Feel free to dismiss this PR if needed.

Thanks!

**Comment by peternied** [comment]
@peterzhuamazon "Per request", could the requester provide more feedback?  I'd like to proactively find issues that will impact our different platform builds.  To this end it looks like `publish-opensearch-min-snapshots` is doing some of this, but its happening post merge and isn't covering the full set of scenarios.

While running these checks on GitHub was easy before we started seeing issues like https://github.com/opensearch-project/OpenSearch/issues/15743 . So long as we have on the scenario it doesn't matter to me if we run it via GHA or Jenkins - however I suspect we'd need to invest in duplicating the workflow and also change our usage profile on those jenkins runner types.

**Comment by peterzhuamazon** [comment]
Close this as after discussion it is good to keep it and test the assemble on multiple JDKs.

Thanks.

**Pull request closed without merging**
