### PR TITLE
Set target and source compatibility to 11, required by Lucene 9.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@dblock.org>

### Description

Set target and source compatibility to 11, required by Lucene 9.
 
### Issues Resolved

Part of https://github.com/opensearch-project/opensearch-plugins/issues/110.

Closes https://github.com/opensearch-project/OpenSearch/issues/1689.

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
@reta CR please?

**Comment by reta** [comment]
@dblock could you please update this guy as well: https://github.com/opensearch-project/OpenSearch/blob/main/distribution/tools/java-version-checker/build.gradle#L14, LGTM otherwise!

**Comment by dblock** [comment]
> @dblock could you please update this guy as well: https://github.com/opensearch-project/OpenSearch/blob/main/distribution/tools/java-version-checker/build.gradle#L14, LGTM otherwise!

Good eyes, thanks! 

Anything else that was done in https://github.com/opensearch-project/OpenSearch/commit/5d020170ff38f58e03c315adcacfb896e9e6f184 need be put back/updated?

**Comment by reta** [comment]
> > @dblock could you please update this guy as well: https://github.com/opensearch-project/OpenSearch/blob/main/distribution/tools/java-version-checker/build.gradle#L14, LGTM otherwise!
> 
> Good eyes, thanks!
> 
> Anything else that was done in [5d02017](https://github.com/opensearch-project/OpenSearch/commit/5d020170ff38f58e03c315adcacfb896e9e6f184) need be put back/updated?

@dblock  ah ... probably we need this one as well: https://github.com/opensearch-project/OpenSearch/commit/5d020170ff38f58e03c315adcacfb896e9e6f184#diff-bc7a42af0a917334e95bb43c1ac3408e14a03a45ef844e044089d4dc233d5b74R235

**Comment by reta** [comment]
@dblock the precommit check should be fixed with https://github.com/opensearch-project/OpenSearch/pull/1109/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R233

```

Note: Recompile with -Xlint:deprecation for details.
> Task :build-tools:compileJava
warning: No processor claimed any of these annotations: java.base/java.lang.Override,java.base/java.lang.SuppressWarnings
error: warnings found and -Werror specified
1 error
1 warning

```

**Comment by dblock** [comment]
> @dblock the precommit check should be fixed with https://github.com/opensearch-project/OpenSearch/pull/1109/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R233
> 
> ```
> 
> Note: Recompile with -Xlint:deprecation for details.
> > Task :build-tools:compileJava
> warning: No processor claimed any of these annotations: java.base/java.lang.Override,java.base/java.lang.SuppressWarnings
> error: warnings found and -Werror specified
> 1 error
> 1 warning
> ```

I'll take it, but that seems like a whack-a-mole. I read https://bugs.openjdk.java.net/browse/JDK-8209058 but I don't understand why this is a problem here, care to explain it to me like a 2yo? :)

**Comment by dblock** [comment]
@reta I used `-Xlint:-processing` to disable just that one, wdyt? probably better than suppressing all warnings as errors.

**Comment by reta** [comment]
> > @dblock the precommit check should be fixed with https://github.com/opensearch-project/OpenSearch/pull/1109/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R233
> > ```
> > 
> > Note: Recompile with -Xlint:deprecation for details.
> > > Task :build-tools:compileJava
> > warning: No processor claimed any of these annotations: java.base/java.lang.Override,java.base/java.lang.SuppressWarnings
> > error: warnings found and -Werror specified
> > 1 error
> > 1 warning
> > ```
> 
> I'll take it, but that seems like a whack-a-mole. I read https://bugs.openjdk.java.net/browse/JDK-8209058 but I don't understand why this is a problem here, care to explain it to me like a 2yo? :)
> 
> Note that I cannot reproduce this locally on my linux setup with JDK11.

Oh this is a new one, I misread it as ` If "-Werror" is used, this fails the compilation, but the warning messages give no clue about what causes them, nor how to resolve them. `, but the cause is different this time, looking now ....

**Review by reta — APPROVED** [review]

**Review by CEHENKLE — APPROVED** [review]

**Pull request merged**
