### PR TITLE
Adding support to run BWC tests for nightly and release builds

### PR DESCRIPTION
**Pull request by saratvemulapalli**
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>

### Description
Adding support to run BWC tests for nightly and release builds via test pipeline.
Refer to: https://github.com/opensearch-project/opensearch-build/issues/90
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/296
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by VachaShah — APPROVED** [review]
LGTM, thank you @saratvemulapalli for the change!

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by tlfeng** [comment]
Hey Sarat, in my PR, the gradle check passed after I merged the current main branch to my branch (https://github.com/opensearch-project/OpenSearch/pull/1153#issuecomment-907492761), so you could try the same.

**Comment by saratvemulapalli** [comment]
> Hey Sarat, in my PR, the gradle check passed after I merged the current main branch to my branch ([#1153 (comment)](https://github.com/opensearch-project/OpenSearch/pull/1153#issuecomment-907492761)), so you could try the same.

Thanks Tianli!
I left the PR open because the runner is not merged yet. But thanks for this.

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by dblock** [comment]
Should this be a default implementation in the calling code?

**Comment by saratvemulapalli** [comment]
> Should this be a default implementation in the calling code, so we wouldn't have to check in a copy of this in all projects?

Good question. Let me know your thoughts.
The thought process is that the bwctest.sh file will define all the bwc tests the repository needs. And each repo/branch could configure it to run with few/all the tests if they need. This file enables that configuration.

That said we have 2 options:
1. Have all repositories define `bwctest.sh`, make it unambiguous for any body to hook up to bwc testing.
2. Define a default mechanism that would be called like (`./gradlew bwctest`) and any repository who wishes to have it custom they could define `bwctest.sh`.

I am leaning towards 1 (for the short term): 
- Its clear for repository owners and no magic involved.
- While repositories are onboarding to bwctest infra, we can update the test_workflow to have a default implementation. 
- Eventually we could move to 2. and add documentation for owners.

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by dblock** [comment]
Why do we need a custom `.sh` script that just calls `gradle`? Shouldn't this be the default for any Gradle project coming from opensearch-build?

**Comment by saratvemulapalli** [comment]
Closing this PR. 
Had a chat with @dblock , It makes sense to have a default bwctest.sh script in opensearch-build.

**Pull request closed without merging**
