### PR TITLE
[Type Removal] Remove TypeFieldMapper usage, remove support of `_type` in searches and from LeafFieldsLookup

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
This change introduces following changes:
1. Remove usages of `TypeFieldMapper` class. In order to keep changes limited, retained `TypeFieldMapper` class which is referred in multiple tests for storing nested paths. Once, https://github.com/opensearch-project/OpenSearch/pull/3004 is merged; this class can be removed completely. 
2. Remove _type support in searches. Bug #2989
3. Remove type handling in LeafFieldsLookup
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/2989
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
Getting issues with gradle on ubuntu machine. Tried stopping/starting gradle but it didn't help. 
```
ubuntu@ip-172-31-33-23:~/OpenSearch$ ./gradlew start

> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Linux 5.13.0-1019-aws (amd64)
  Runtime JDK Version   : 17 (Eclipse Temurin JDK)
  Runtime java.home     : /home/ubuntu/sw/jdk-17.0.1+12
  Gradle JDK Version    : 17 (Eclipse Temurin JDK)
  Gradle java.home      : /home/ubuntu/sw/jdk-17.0.1+12
  Random Testing Seed   : 3B2F9F522B14152D
  In FIPS 140 mode      : false
=======================================

FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Gradle could not start your build.
> Cannot create service of type TaskExecuter using method ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #14 of type ReservedFileSystemLocationRegistry.
   > Cannot create service of type ReservedFileSystemLocationRegistry using method ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.
      > Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
         > Cannot lock execution history cache (/home/ubuntu/OpenSearch/.gradle/7.4.2/executionHistory) as it has already been locked by this process.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

**Comment by dreamer-89** [comment]
start gradle check

**Review by nknize — APPROVED** [review]
This is great! LGTM!

**Comment by CEHENKLE** [comment]
Since we're about to cut rc-1, I'd like to hold on backporting this to 2.0.   But really looking forward to getting it into 2.0!

**Comment by nknize** [comment]
> I'd like to hold on backporting this to 2.0.

++ We'll have the PR auto opened but block the merge to prevent it from going in prematurely.

**Pull request merged**
