### PR TITLE
Upgrading AWS SDK dependency for native plugins

### PR DESCRIPTION
**Pull request by saratvemulapalli**
### Description
Upgrading AWS SDK dependency to 1.12.247 which adds support for IMDSv2. 
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/3690
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Check failure [b086af5](https://github.com/opensearch-project/OpenSearch/commit/b086af593c67884078b641a8dad723c1f24a0f34) [Log 6307](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6307.log)
> 
> [Reports 6307](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6307_reports.zip)

```
Tests with failures:
 - org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded
```

**Comment by saratvemulapalli** [comment]
start gradle check

**Review by VachaShah — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
> ❌   Gradle Check failure [b086af5](https://github.com/opensearch-project/OpenSearch/commit/b086af593c67884078b641a8dad723c1f24a0f34) [Log 6308](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6308.log)
> 
> [Reports 6308](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_6308_reports.zip)

```
Tests with failures:
 - org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks
 ```
:/

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by tlfeng** [comment]
In log 6310:
#1703
```
REPRODUCE WITH: ./gradlew ':qa:remote-clusters:integTest' --tests "org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks" -Dtests.seed=FCB2383D04041213 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-SA -Dtests.timezone=Australia/Victoria -Druntime.java=17

org.opensearch.cluster.remote.test.RemoteClustersIT > testHAProxyModeConnectionWorks FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([FCB2383D04041213:FBC4EDF63F82644E]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.cluster.remote.test.RemoteClustersIT.testHAProxyModeConnectionWorks(RemoteClustersIT.java:125)
```

#3579:
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" -Dtests.seed=FCB2383D04041213 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ko -Dtests.timezone=Australia/Lindeman -Druntime.java=17

org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT > testHighWatermarkNotExceeded FAILED
    java.lang.AssertionError: Mismatching shard routings: []
    Expected: a collection with size <1>
         but: collection size was <0>
        at __randomizedtesting.SeedInfo.seed([FCB2383D04041213:1593D98F84C2DBFD]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.lambda$assertBusyWithDiskUsageRefresh$5(DiskThresholdDeciderIT.java:362)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1049)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.assertBusyWithDiskUsageRefresh(DiskThresholdDeciderIT.java:355)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded(DiskThresholdDeciderIT.java:188)
```

https://github.com/opensearch-project/OpenSearch/issues/1561:
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards" -Dtests.seed=FCB2383D04041213 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-ZA -Dtests.timezone=Poland -Druntime.java=17

org.opensearch.cluster.allocation.ClusterRerouteIT > testDelayWithALargeAmountOfShards FAILED
    java.lang.AssertionError: AcknowledgedResponse failed - not acked
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([FCB2383D04041213:D0C332DC151A38F1]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.opensearch.test.hamcrest.OpenSearchAssertions.assertAcked(OpenSearchAssertions.java:125)
        at org.opensearch.test.hamcrest.OpenSearchAssertions.assertAcked(OpenSearchAssertions.java:129)
...
```

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
```
for i in {1..100}
do
echo "Task $i"
 ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" --rerun-tasks;
response_code=$?
echo "Response code $response_code"
if [[ $response_code = 1 ]]; then
	echo "Test $i failed"
	break
else
	echo "Test $i passed. Sleeping 5 seconds"
	sleep 5
fi
done
```
Still I dont see failures on my local. :/

**Pull request merged**
