### PR TITLE
Revert "Support first and last parameter for missing bucket ordering …

### LINKED ISSUE #2143: [BUG] BWC failures for aggregations in MixedClusterClientYamlTestSuiteIT
Lots of BWC failures for aggregations in MixedClusterClientYamlTestSuiteIT found in #2103.  Here are just a few:

```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.3.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/230_composite/Composite aggregation with unmapped field}" -Dtests.seed=D4386AC6DA14EDFC -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sv-SE -Dtests.timezone=America/Paramaribo -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search.aggregation/230_composite/Composite aggregation with unmapped field} FAILED
    java.lang.AssertionError: Failure at [search.aggregation/230_composite:578]: hits.total didn't match expected value:
                        hits.total: expected Integer [7] but was Integer [6]
  
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.3.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/230_composite/Terms source from part of sorted}" -Dtests.seed=D4386AC6DA14EDFC -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sv-SE -Dtests.timezone=America/Paramaribo -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search.aggregation/230_composite/Terms source from part of sorted} FAILED
    java.lang.AssertionError: Failure at [search.aggregation/230_composite:1017]: expected [2xx] status code but api [search] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"i_o_exception","reason":"Unknown SortOrder ordinal [2]","stack_trace":"[Unknown SortOrder ordinal [2]]; nested: IOException[Unknown SortOrder ordinal [2]];\n\tat 

REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.3.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/230_composite/Composite aggregation with format and calendar_interval}" -Dtests.seed=D4386AC6DA14EDFC -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sv-SE -Dtests.timezone=America/Paramaribo -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search.aggregation/230_composite/Composite aggregation with format and calendar_interval} FAILED
    java.lang.AssertionError: Failure at [search.aggregation/230_composite:365]: expected [2xx] status code but api [search] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"i_o_exception","reason":"Unknown SortOrder ordinal [2]","stack_trace":"[Unknown SortOrder ordinal [2]]; nested: IOException[Unknown SortOrder ordinal [2]];\n\tat 

REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v1.3.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/230_composite/Simple Composite aggregation with GeoTile grid}" -Dtests.seed=D4386AC6DA14EDFC -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sv-SE -Dtests.timezone=America/Paramaribo -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search.aggregation/230_composite/Simple Composite aggregation with GeoTile grid} FAILED
    java.lang.AssertionError: Failure at [search.aggregation/230_composite:694]: expected [2xx] status code but api [search] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"i_o_exception","reason":"Unknown SortOrder ordinal [2]","stack_trace":"[Unknown SortOrder ordinal [2]]; nested: IOException[Unknown SortOrder ordinal [2]];\n\tat 
```

### PR DESCRIPTION
**Pull request by andrross**
…in composite aggregation (#1942) (#2049)"

This reverts commit 5b2713661ea14323754f4083de23888797ab0882.

Signed-off-by: Andrew Ross <andrross@amazon.com>

### Description
Reverts a commit that appears to be breaking backward compatibility tests. Exact cause is not known, but this revert should unblock the builds.
 
### Issues Resolved
closes #2143
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
Error downloading centos caused build failure.

**Comment by andrross** [comment]
start gradle check

**Comment by andrross** [comment]
#2147 should be the fix for this issue on the `main` branch. Assuming that PR works as expected and is merged, then this PR will be closed.

**Comment by nknize** [comment]
> Assuming that PR works as expected and is merged, then this PR will be closed.

agree... it should do the trick. Composite Agg transport failures are triggering bwc failures on multiple PRs so this one is high priority

**Comment by andrross** [comment]
Closing now that #2147 has been merged.

**Pull request closed without merging**
