### PR TITLE
Upgrade to log4j 2.16.0

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Even more hardening has been applied in log4j 2.16.0 (comparing to 2.15.0), see please [1]

[1] https://lists.apache.org/thread/d6v4r6nosxysyq9rvnr779336yf0woz4
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@andrross @dblock fyi :-)

**Review by saratvemulapalli — APPROVED** [review]

**Review by andrross — APPROVED** [review]

**Comment by dblock** [comment]
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.PrimaryAllocationIT.testPrimaryReplicaResyncFailed" -Dtests.seed=6D4D4C998D58C02E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m -Djava.security.manager=allow" -Dtests.locale=es-CR -Dtests.timezone=Africa/Johannesburg -Druntime.java=17

org.opensearch.cluster.routing.PrimaryAllocationIT > testPrimaryReplicaResyncFailed FAILED
    java.lang.AssertionError: 
    Expected: a collection with size <4>
         but: collection size was <3>
        at __randomizedtesting.SeedInfo.seed([6D4D4C998D58C02E:A2886BE2A57855BE]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.opensearch.cluster.routing.PrimaryAllocationIT.lambda$testPrimaryReplicaResyncFailed$14(PrimaryAllocationIT.java:727)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1048)
        at org.opensearch.cluster.routing.PrimaryAllocationIT.testPrimaryReplicaResyncFailed(PrimaryAllocationIT.java:724)
```

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
Backport to 1.x pls.

**Pull request merged**
