### PR TITLE
Moving maintainer kartg to Emeritus

### PR DESCRIPTION
**Pull request by kartg**
### Description
Moving maintainer kartg to Emeritus, and removing from `CODEOWNERS`

### Related Issues
N/A

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
@kartg you might have to remove the alias from [CODEOWNERS](https://github.com/opensearch-project/OpenSearch/blob/main/.github/CODEOWNERS) as well to have a valid CODEOWNER file.

**Comment by owaiskazi19** [comment]
@opensearch-project/admin can you help to remove the permission here?

**Comment by kartg** [comment]
> ❌ Gradle check result for https://github.com/opensearch-project/OpenSearch/commit/6031d386942f89c37bab538617da326d90fa3d92: [FAILURE](https://build.ci.opensearch.org/job/gradle-check/34456/)

#10704 and #5329 , will refire

**Review by andrross — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Comment by dblock** [comment]
> @opensearch-project/admin can you help to remove the permission here?

Done.

**Pull request merged**
