### PR TITLE
fix case insensitive query on wildcard field

### LINKED ISSUE #15855: [BUG] `case_insensitive` wildcard query didn't return expected result
### Describe the bug

When perform wildcard query on wildcard field with `case_insensitive` set to `true`, the expected doc didn't occur.

### Related component

Search

### To Reproduce

1. Create a simple index contains wildcard field
    ```
    PUT case_test
    {
        "mappings": {
            "properties": {
                "wildcard": {
                    "type": "wildcard"
                }
            }
        }
    }
    ```
2. Bulk insert documents contains capital letters
    ```
    PUT _bulk?refresh=true
    {"index": {"_index": "case_test"}}
    {"wildcard": "TtAa"}
    {"index": {"_index": "case_test"}}
    {"wildcard": "ttaa"}
    {"index": {"_index": "case_test"}}
    {"wildcard": "TTAA"}
    ```

3. Search on wildcard field with `case_insensitive` set to `true` and `false` respectly
    **case sensitive:**
    ```
    POST case_test/_search
    {
        "query": {
            "term": {
                "wildcard": {
                    "value": "TtAa",
                    "case_insensitive": false
                }
            }
        }
    }
    ```
    **case insensitive:**
    ```
    POST case_test/_search
    {
        "query": {
            "term": {
                "wildcard": {
                    "value": "TtAa",
                    "case_insensitive": true
                }
            }
        }
    }
    ```
4. Check result

### Expected behavior

case insensitive query should return all three documents, instead of `TtAa` alone

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by HUSTERGS**
### Description
fix case insensitive query on wildcard field

### Related Issues
Resolves #15855

### Check List
- [x] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by msfroh — APPROVED** [review]
Awesome 🎉 

Thanks again @HUSTERGS!

**Comment by HUSTERGS** [comment]
I rebased on the main branch for merge conflict, thus need another approval :D, thanks @msfroh

**Review by msfroh — APPROVED** [review]

**Comment by dblock** [comment]
@msfroh the CHANGELOG check was failing because you need the backport 2.x label on the PR, now added

**Comment by dblock** [comment]
@HUSTERGS update CHANGELOG please?

**Comment by HUSTERGS** [comment]
CHANGELOG added, sorry forgot again :(  need another approval, thanks @dblock

**Review by jainankitk — APPROVED** [review]

**Pull request merged**
