### PR TITLE
Change commit message and PR title to imperative mood

### PR DESCRIPTION
**Pull request by andrross**
Because I'm a pedant.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by saratvemulapalli — APPROVED** [review]
Glad you did this on a Friday 😃

**Review by reta — APPROVED** [review]

**Review by kotwanikunal — APPROVED** [review]

**Comment by dblock** [comment]
Is it "Increment" or "Increments"?

**Comment by andrross** [comment]
> Is it "Increment" or "Increments"?

"Increment", per the guidance here: https://cbea.ms/git-commit/

The way I remember this is by referring to how git itself formulates messages for things like `git revert`:

```
Revert "Andrew's idea that seemed great at the time"

This reverts commit abcd1234
```

**Comment by dblock** [comment]
@andrross I think I am thrown off by dependapot which keeps saying "bumps". We should fix it probably.

**Comment by andrross** [comment]
@dblock https://github.com/dangoslen/dependabot-changelog-helper/pull/131

**Pull request merged**
