### PR TITLE
Increment version to 1.2.3

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Coming from https://github.com/opensearch-project/opensearch-build/issues/1365, increment version to 1.2.3.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
I dont think I've seen this before.
```
> Task :server:test

Tests with failures:
 - org.opensearch.BuildTests.testEqualsAndHashCode
```

**Review by saratvemulapalli — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
> I dont think I've seen this before.
> 
> ```
> > Task :server:test
> 
> Tests with failures:
>  - org.opensearch.BuildTests.testEqualsAndHashCode
> ```

Of course we would use 1.2.3 as an example in a test ...

**Comment by dblock** [comment]
start gradle check

**Pull request merged**
