### PR TITLE
Update single comment for gradle check

### PR DESCRIPTION
**Pull request by andrross**
This is the same change that was applied to the check comptability task by PR #9954 to update a single comment with the latest result of the gradle check workflow.

Relates #9699

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by Poojita-Raj — APPROVED** [review]

**Comment by kotwanikunal** [comment]
I think there was a proposal by @scrawfor99 (You can follow the thread here: https://github.com/opensearch-project/OpenSearch/pull/8488#issuecomment-1623916432)

I still have the same concerns that we have no easy way of tracking the check results otherwise.

**Comment by andrross** [comment]
> I think there was a similar proposal by @scrawfor99 (You can follow the thread here: [#8488 (comment)](https://github.com/opensearch-project/OpenSearch/pull/8488#issuecomment-1623916432))
> 
> I still have the same concerns that we have no easy way of tracking the check results otherwise.

@kotwanikunal Thanks, I had missed #8488. I'm not sure I agree with the concerns about tracking...the GitHub comment will show up as "edited" and allow you to view every revision. Each revision has the commit SHA that was tested as well. This change brings the gradle check in line with how codecov and check compatibility behave.

The point about notifications does stand though because I don't think GitHub will fire off a notification for a comment edit.

**Review by reta — COMMENTED** [review]
@andrross I somewhat missed that this is the change for Gradle check (vs compatibility check), I am 100% with @kotwanikunal on that, the notification is very useful to have for this check at all times.

**Comment by andrross** [comment]
> the notification is very useful to have for this check at all times.

Thanks @reta. That's reasonable so I'll go ahead and close this one. If you don't mind, can you leave your opinion on #9767 to cancel concurrent check workflows to avoid notifications for runs against a commit that has been superseded by a new commit? (I'm on a kick recently to reduce the noise in our PR comment feeds :) ).

**Pull request closed without merging**
