### PR TITLE
Used set to make shell scripts more strict

### PR DESCRIPTION
**Pull request by owaiskazi19**
Signed-off-by: Owais Kazi <owaiskazi19@gmail.com>

### Description
Used `set -e -o pipefail` in shell scripts to generalize and ensure that errors are not silently hidden. 

More on pipefail:
This setting prevents errors in a pipeline from being masked. If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline. By default, the pipeline's return code is that of the last command even if it succeeds.
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/3106
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
I agree that `-e` and `-o pipefail` are best practices, but I'm a little concerned that we might break things by making this change across all scripts. Some of these scripts _could_ have been written assuming the non-strict behavior. Do you think we have adequate test coverage and/or are confident that nothing here will break?

**Comment by owaiskazi19** [comment]
> I agree that `-e` and `-o pipefail` are best practices, but I'm a little concerned that we might break things by making this change across all scripts. Some of these scripts _could_ have been written assuming the non-strict behavior. Do you think we have adequate test coverage and/or are confident that nothing here will break?

That's a great question. I'm not sure if there's a way to test these scripts out. I thought gradle check would do the work for us. Any input you have on the same?

**Comment by owaiskazi19** [comment]
I tried to run these scripts just to see if they will execute and changed `-o pipefail` to `-e`.

**Comment by owaiskazi19** [comment]
https://github.com/opensearch-project/OpenSearch/issues/2064

**Comment by owaiskazi19** [comment]
start gradle check

**Comment by andrross** [comment]
> I tried to run these scripts just to see if they will execute and changed -o pipefail to -e.

Why did you make this change? Did `-o pipefail` cause problems?

**Comment by owaiskazi19** [comment]
> Why did you make this change? Did `-o pipefail` cause problems?

Yes, when executed on my local returned
```
> ./dev-tools/signoff-check.sh 
./dev-tools/signoff-check.sh: 3: set: Illegal option -o pipefail

**Comment by owaiskazi19** [comment]
> what about `-u`? (see the original issue as well)

Hey @rursprung! With `-eu` flag on few scripts I'm getting the error

```
> Task :rest-api-spec:yamlRestTest FAILED
Exec output and error:
| Output for ./bin/opensearch-keystore:./bin/opensearch-env: line 48: OPENSEARCH_JAVA_HOME: unbound variable

**Comment by owaiskazi19** [comment]
@rursprung I have added a generalized way for scripts to set using `-e -o pipefail`.

**Comment by rursprung** [comment]
> @rursprung I have added a generalized way for scripts to set using `-e -o pipefail`. Handled `set: Illegal option -o pipefail` for `./dev-tools/signoff-check.sh` by [changing](https://github.com/opensearch-project/OpenSearch/pull/3278/files#diff-c20c211294982119c9bb74b5147088a14a4cb347f9dd1899c1d3854a1c2b48deR1).

good news, thanks! i missed that some still had `#!/bin/sh` - obviously `#!/usr/bin/env bash` is the correct way of doing things.

what about `-u` (my previous comment which i've now just updated with a better suggestion)?

**Comment by owaiskazi19** [comment]
> what about `-u` (my previous comment which i've now just updated with a better suggestion)?

If we use `set -eu -o pipefail` for the [script](https://github.com/opensearch-project/OpenSearch/blob/main/test/fixtures/krb5kdc-fixture/src/main/resources/provision/addprinc.sh) returns. That's mainly because [of](https://github.com/opensearch-project/OpenSearch/blob/main/test/fixtures/krb5kdc-fixture/src/main/resources/provision/addprinc.sh#L22).  How do you like the current way of having `set -e -o pipefail`?
```
> Task :test:fixtures:krb5kdc-fixture:postProcessFixture FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ubuntu/OpenSearch/test/fixtures/krb5kdc-fixture/build.gradle' line: 52

* What went wrong:
Execution failed for task ':test:fixtures:krb5kdc-fixture:postProcessFixture'.
> Cannot get property 'test.fixtures.peppa.udp.88' on extra properties extension as it does not exist

**Comment by dblock** [comment]
@rursprung looking for your A-OK to merge this, thank you for doing a CR

**Comment by rursprung** [comment]
if possible, i'd like to see `-u` in there as well - i'm not a big fan of silently accepting undefined variables in the code. yes, it works in a lot of scripting languages, but it just adds a (hard to track) source of errors. i'm not sure about the last failure reported by @owaiskazi19 - i don't see anything shell-script related in the error message but also have no clue what this test covers (and don't have time in the next few days to check it out myself, sorry).

if there are corner cases (special scripts) where `-u` isn't possible then i think it should still be added to all others and an explicit comment should be added to the corner cases explaining why/how they rely on undefined variables.

but if this doesn't work for you / you don't want that i think the PR is already a good step in the right direction!

one more thing to consider: maybe it'd make sense to add a small check (GitHub action?) to ensure that the `set` command with the specified minimum of restrictions is present in all `.sh` files? and maybe this should be documented somewhere? otherwise this here is a one-off effort and in new scripts this will be forgotten again.

**Pull request merged**
