### PR TITLE
[Backport 2.x] Mute flaky concurrent segment search tests pending fixes (#10437)

### PR DESCRIPTION
**Pull request by jed326**
### Description
Backport https://github.com/opensearch-project/OpenSearch/commit/9cb4f9dbd44e42269fe573f9592d58d4115cc522 from https://github.com/opensearch-project/OpenSearch/pull/10437.

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
> https://build.ci.opensearch.org/job/gradle-check/29444/
- https://github.com/opensearch-project/OpenSearch/issues/10798

**Comment by peternied** [comment]
- Another failure on https://github.com/opensearch-project/OpenSearch/issues/10798

Good news - PR for review to resolve it #11068 - want to take a look?

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.

#### From https://build.ci.opensearch.org/job/gradle-check/29504/
- https://github.com/opensearch-project/OpenSearch/issues/11085

#### From https://build.ci.opensearch.org/job/gradle-check/29511/
- https://github.com/opensearch-project/OpenSearch/issues/6090
- https://github.com/opensearch-project/OpenSearch/issues/6542

#### From https://build.ci.opensearch.org/job/gradle-check/29504/
- #10798

#### From https://build.ci.opensearch.org/job/gradle-check/29522/
- #10798

**Comment by peternied** [comment]
@jed326 Can you merge or rebase from 2.x I'm seeing unrelated tests failures that were resolved such as https://github.com/opensearch-project/OpenSearch/pull/10955

**Comment by jed326** [comment]
@peternied just rebased. Thanks!

**Comment by jed326** [comment]
Again 😕
> https://build.ci.opensearch.org/job/gradle-check/29527/
- https://github.com/opensearch-project/OpenSearch/issues/10798

**Pull request merged**
