### PR TITLE
Index Level Encryption plugin

### PR DESCRIPTION
**Pull request by asonje**
### Description
This pull request adds index level encryption features to OpenSearch based on the issue #3469. Each OpenSearch index is individually encrypted based on user provided encryption keys. A new cryptofs store type `index.store.type` is introduced which instantiates a CryptoDirectory that encrypts and decrypts files as they are written and read respectively

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]
#3469 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by Bukhtawar — COMMENTED** [review]
As a part of moving security closer to the core should we consider moving CryptoDirectory to core or even better module and crypto providers as plugins instead

**Comment by varun-lodaya** [comment]
+1 to Bukhtawar's comment. Will let @peternied add on this, but generally speaking, does this need a new plugin? Can we provide this functionality in core?

**Comment by andrross** [comment]
> As a part of moving security closer to the core should we consider moving CryptoDirectory to core or even better module and crypto providers as plugins instead

From a software architecture perspective I think it make sense to build on the existing abstractions (e.g. the directory factory/IndexStorePlugin). As to whether it is a module in core, a plugin in the core repo, or a plugin in a separate repo are good questions. However, we shouldn't take any decision here lightly as we'll need to support whatever we release here for multiple major versions since it is essentially writing a new data format. My initial suggestion is that the [sandbox](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#sandbox) is probably a good fit for this feature while it incubates and is proven out.

**Comment by varun-lodaya** [comment]
> From a software architecture perspective I think it make sense to build on the existing abstractions (e.g. the directory factory/IndexStorePlugin). As to whether it is a module in core, a plugin in the core repo, or a plugin in a separate repo are good questions. However, we shouldn't take any decision here lightly as we'll need to support whatever we release here for multiple major versions since it is essentially writing a new data format. My initial suggestion is that the [sandbox in the core repo](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#sandbox) is probably a good fit for this feature while it incubates and is proven out.

Sounds fair to me.

**Comment by Bukhtawar** [comment]
The idea is to decouple abstractions and implementation. The abstraction can be closer to the goal, while the implementations or crypto providers can be plugins.

**Comment by asonje** [comment]
If there are no objections or further comments I will move this to sandbox/plugins per @andrross' suggestion and submit a new PR. Thanks

**Comment by asonje** [comment]
updated PR: #12902

**Pull request closed without merging**
