### PR TITLE
[Backport] Support for translog pruning based on retention leases

### PR DESCRIPTION
**Pull request by saikaranam-amazon**
### Description
Backport of https://github.com/opensearch-project/OpenSearch/pull/1038
 
### Issues Resolved
N/A
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by itiyamas** [comment]
start gradle check

**Review by itiyamas — APPROVED** [review]

**Comment by nknize** [comment]
I've seen these issues before: 

```
* What went wrong:
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 1.0.0 didn't generate expected file /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/bwc/minor/build/bwc/checkout-1.0/distribution/archives/linux-tar/build/distributions/opensearch-1.0.0-SNAPSHOT-linux-x64.tar.gz
```

It usually means the checked out codebase that's being built for bwc testing generated a version artifact that did not match the expected version. In this case, the build expected a 1.0.0 build but got something else (my money is on 1.0.1 since 1.0 branch is now at a staged bugfix release). 

 I haven't had a chance to circle back on this so I'm speculating that the bwc builder is either looking for (or needs to look for) the release tag to check out and build the appropriate bwc version. We inherited that code and release tags upstream always looked like `vM.m.p` until OpenSearch decided to drop the github recommended `v` in favor of just the release number `M.m.p`. Perhaps the Bwc distribution builder is looking for v1.0.0 tag and not finding it so falling back to the 1.0 branch (which is now a staged 1.0.1 and :boom: ).   

@adnapibar is familiar with the BWC builder so perhaps he can take a look?

**Comment by dblock** [comment]
We should re-add the `v` in the tag if this is the case, see https://github.com/opensearch-project/.github/issues/35.

**Comment by nknize** [comment]
Is this feature a blocker for the 1.1 release or can it hold and bake a while for 1.2?

**Comment by saikaranam-amazon** [comment]
> Is this feature a blocker for the 1.1 release or can it hold and bake a while for 1.2?

This is blocker for 1.1 release

**Comment by adnapibar** [comment]
Can you rebase your branch onto OpenSearch/1.x

**Comment by nknize** [comment]
> This is blocker for 1.1 release

What is it blocking?

**Comment by saikaranam-amazon** [comment]
> Can you rebase your branch onto https://github.com/opensearch-project/OpenSearch/tree/1.x

Done. Pushed the change

> What is it blocking?

The changes are needed for the replication plugin releasing with 1.1

**Comment by nknize** [comment]
> The changes are needed for the replication plugin releasing with 1.1

Do you have a merged PR on the replication plugin repo that depends on this logic?

**Comment by saikaranam-amazon** [comment]
> Do you have a merged PR on the replication plugin repo that depends on this logic?

Yes, changes are merged here: [link](https://github.com/opensearch-project/cross-cluster-replication/blob/main/src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt#L709)

**Comment by nknize** [comment]
> Yes, changes are merged here:

That change was merged 2 months ago; and it depends on a setting that has not been in OpenSearch core until today? How is this possible? Release is scheduled for less than a week and we're trying to backport a new setting that has no time to bake.

Huge -1 for this.

**Comment by saikaranam-amazon** [comment]
> That change was merged 2 months ago; and it depends on a setting that has not been in OpenSearch core until today? How is this possible? Release is scheduled for less than a week and we're trying to backport a new setting that has no time to bake.

The changes related to this PR on OpenSearch was raised more than 1 month back after testing from the plugin side

**Comment by nknize** [comment]
> The changes related to this PR on OpenSearch was raised more than 1 month back...

The issue was opened 22 days ago. The PR was opened before the issue. The changes were only recently merged to main, and a backport just now opened against 1.x less than a week before the planned release. This is too late. I'm a fan of the proposed change but this didn't have enough time to bake before the 1.1 release. Huge recommendation to bump to 1.2.



> after thorough testing from our side.

Unfortunately that's not the primary core CI; and we're now playing `gradle check` roulette in hopes that bwc picks a seed that passes all gates in order to wedge it in time for a release. This isn't a good approach as it only leads to knee jerk bugfix releases (which are not the easiest to do atm).

**Comment by nknize** [comment]
If we don't want to hold the feature for a 1.2 release then I recommend we hold the 1.1 release for at least a week to let this settle. I like the change, it's just too late to be wedging these in for a 1.1 release in less than a week. I'm going to mark this as a blocker for 1.1 so we have traceability. Let's hold on removing that blocker label until we're comfortable the changes have had time to bake.

**Comment by adnapibar** [comment]
start gradle check

**Comment by CEHENKLE** [comment]
@saikaranam-amazon  Hi Sai!  Can you tell us more about how your testing was done?  If we're still seeing changes coming in against 1.1, how have you been able to validate the change against the full set?

Thanks!
/C

**Comment by saikaranam-amazon** [comment]
> Can you tell us more about how your testing was done? If we're still seeing changes coming in against 1.1, how have you been able to validate the change against the full set?

These changes are tested on test clusters from our side. I understand that the 1.x branch is active and seeing changes, but the current changes are contained addressing some of the issues identified during replication plugin testing. These shouldn't affect existing OS 1.x code base.

**Review by nknize — CHANGES_REQUESTED** [review]
There are some outstanding concerns on the [issue](https://github.com/opensearch-project/OpenSearch/issues/1100) that look like they still need to be addressed. 

I'm also not seeing any documentation on when it's best to enable this index setting. This isn't good for the community as they could unknowingly enable without understanding any consequences (e.g., retaining unnecessary operations in the tlog). This is 

There also has been movement on this in main up to a few days ago and looks like some [related followup PR(s)](https://github.com/opensearch-project/OpenSearch/pull/1217) (at least one) that further build on top of  this one? 

Given 1.1 is so close to release I think we should hold on this feature until at least 1.2 (at the earliest) and not merge until after the 1.1 branch is cut. There's just too many moving parts here to consider and not enough documentation to educate the user/customer community.

**Comment by nknize** [comment]
I think we can continue to proactively work and merge these incremental improvements in main and let them bake while figuring out a best path to release. That's the nice thing about our branch strategy, no reason to perfect everything before merging, and no reason to jump the gun releasing a feature that needs a little more time and due diligence.

I'm wondering if we can leverage some of the `OverrideablePlugin` mechanisms that @setiah has been working on and implement these tlog settings through an extension in the CCR plugin?  Alternatively we could look at adding a feature flag that only enables this when the flag is set? This would give more guardrails from users unknowingly setting something without fully understanding consequences.

**Comment by nknize** [comment]
Instead of implementing this IndexSetting in the core and baking it into the default TranslogDeletionPolicy can we refactor this PR to make the TranslogDeletionPolicy extendable (protected methods and variables) and implement the retention lease behavior in something like a `CCRTranslogDeletionPolicy extends TranslogDeletionPolicy` within the CCR Replication? I think this would help core not introduce a new IndexSetting that has to be supported long term when we're trying to make translog logic become an extendable feature to support segment level replication.

**Comment by mch2** [comment]
Would we ever wire up CCR without this enabled? I'm wondering if we need to even bother with making this a setting.  We can wire up a subclass of `TranslogDeletionPolicy` inside of `ReplicationEngine`, meaning it would be default behavior if CCR is installed.

**Comment by nknize** [comment]
> Would we ever wire up CCR without this enabled?

That's a great question. I'm not all that familiar with the cross-cluster-replication plugin mechanics. I think you spin up a follower cluster as opposed to a follower index? If that's the case then logically it seems all indexes in the leader cluster are replicated to the follower cluster? And if so does what's the logic in adding index level fidelity to change the deletion policy? It seems a reasonable assertion that retaining uncompressed tlog ops based on retention lease to avoid decompressing lucene stored fields significantly increases translog overhead?

**Comment by mch2** [comment]
@nknize Are we looking at updating https://github.com/opensearch-project/OpenSearch/pull/1227 as well?

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
unrelated failure.. starting gradle check over

**Comment by nknize** [comment]
start gradle check

**Review by nknize — APPROVED** [review]
Tests passing, deprecations in place.. this finally LGTM!

**Pull request merged**
