### PR TITLE
Fix the documentation url of the Create or Update alias API in rest-api-spec

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description

This is a follow-up PR of https://github.com/opensearch-project/OpenSearch/pull/14719, I created a documentation PR for the Create or Update alias API and now the PR is merged, so we need to correct the documentation URL in rest-api-spec.

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/14384

### Check List
<del>- [ ] Functionality includes testing.</del>
<del>- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.</del>
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.</del>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Please do review/fix the related specs in https://github.com/opensearch-project/opensearch-api-specification.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
I wonder where this API spec is still used. We should be replacing it with the one from https://github.com/opensearch-project/opensearch-api-specification.

**Comment by gaobinlong** [comment]
> I wonder where this API spec is still used. We should be replacing it with the one from https://github.com/opensearch-project/opensearch-api-specification.

Do you mean the `rest-api-spec` in core will be deprecated in the future? I think it's a very solid end-to-end test framework which is helpful during the development, but moving the yaml test cases outside the core repo can helps until the PR is merged and new version is built.

**Comment by dblock** [comment]
> > I wonder where this API spec is still used. We should be replacing it with the one from https://github.com/opensearch-project/opensearch-api-specification.
> 
> Do you mean the `rest-api-spec` in core will be deprecated in the future? I think it's a very solid end-to-end test framework which is helpful during the development, but moving the yaml test cases outside the core repo can helps until the PR is merged and new version is built.

Yes, just the spec. It's incomplete, has bugs, doesn't have plugins, etc. I'd like it replaced with a release rom https://github.com/opensearch-project/opensearch-api-specification/releases/tag/main-latest. The YAML test framework though is perfectly fine.

We have https://github.com/opensearch-project/OpenSearch/issues/4027 and https://github.com/opensearch-project/OpenSearch/issues/3090 that are related.

**Pull request merged**
