### PR TITLE
Backporting changes for version workflow

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
Backport https://github.com/opensearch-project/OpenSearch/pull/2157 https://github.com/opensearch-project/OpenSearch/pull/2163 https://github.com/opensearch-project/OpenSearch/pull/2572
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
Looks like a real bwc failure?

```

* What went wrong:
Execution failed for task ':distribution:bwc:bugfix:buildBwcLinuxTar'.
> Building 1.3.1 didn't generate expected file /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/bwc/bugfix/build/bwc/checkout-1.3/distribution/archives/linux-tar/build/distributions/opensearch-min-1.3.1-SNAPSHOT-linux-x64.tar.gz
```

**Comment by VachaShah** [comment]
> distribution:bwc:bugfix:buildBwcLinuxTar

Looks like this was resolved in #2679

**Comment by VachaShah** [comment]
start gradle check

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [9be16db](https://github.com/opensearch-project/OpenSearch/commit/9be16db8bc0a20037a584171e1dd7f6306f455fe) [Log 4141](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_4141.log)
> 
> [Reports 4141](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_4141_reports.zip)

#1846

**Comment by VachaShah** [comment]
start gradle check

**Review by dblock — APPROVED** [review]

**Pull request merged**
