### PR TITLE
Upgrading gson to 2.8.9

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha <vachshah@amazon.com>

### Description
Upgrading `gson` to latest 2.8.9 in direct dependency and via hadoop-common.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [d7b78ba](https://github.com/opensearch-project/OpenSearch/commit/d7b78ba2679435e25aafbbb34acef564ec92d7f3) [Log 1066](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1066.log)
> 
> [Reports 1066](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1066_reports.zip)

```
Tests with failures:
 - org.opensearch.discovery.StableMasterDisruptionIT.testStaleMasterNotHijackingMajority

2632 tests completed, 1 failed, 4 skipped
```

```
1> [2021-11-12T16:43:27,115][WARN ][o.o.c.NodeConnectionsService] [node_t2] failed to connect to {node_t1}{sPuJWTDSQC-Dglo7tjZfog}{6VrTsrXIRcaOHwn8m9dFdw}{127.0.0.1}{127.0.0.1:43109}{dimr}{shard_indexing_pressure_enabled=true} (tried [1] times)
  1> org.opensearch.transport.ConnectTransportException: [node_t1][127.0.0.1:43109] connect_exception
  1> 	at org.opensearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1064) ~[main/:?]
  1> 	at org.opensearch.action.ActionListener.lambda$toBiConsumer$2(ActionListener.java:213) ~[main/:?]
  1> 	at org.opensearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:55) ~[opensearch-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
  1> 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
  1> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
  1> 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
  1> 	at org.opensearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:70) ~[opensearch-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.SocketChannelContext.connect(SocketChannelContext.java:160) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.EventHandler.handleConnect(EventHandler.java:130) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.transport.nio.TestEventHandler.handleConnect(TestEventHandler.java:139) ~[framework-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.NioSelector.attemptConnect(NioSelector.java:446) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.NioSelector.registerChannel(NioSelector.java:469) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.NioSelector.setUpNewChannels(NioSelector.java:458) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.NioSelector.preSelect(NioSelector.java:279) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:172) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at org.opensearch.nio.NioSelector.runLoop(NioSelector.java:148) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	at java.lang.Thread.run(Thread.java:833) [?:?]
  1> Caused by: java.net.ConnectException: Connection refused
  1> 	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
  1> 	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
  1> 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[?:?]
  1> 	at org.opensearch.nio.SocketChannelContext.connect(SocketChannelContext.java:157) ~[opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
  1> 	... 9 more
```

**Comment by VachaShah** [comment]
start gradle check

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [d7b78ba](https://github.com/opensearch-project/OpenSearch/commit/d7b78ba2679435e25aafbbb34acef564ec92d7f3) [Log 1067](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1067.log)
> 
> [Reports 1067](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1067_reports.zip)

```
> Task :test:fixtures:s3-fixture:composeUp

ERROR: for 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-ec2_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Creating 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-repositories-metering_1 ... done
Creating 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-ecs_1              ... done
Creating 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-session-token_1    ... done
Creating 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-other_1                 ... done
Creating 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture_1                       ... done

ERROR: for s3-fixture-with-ec2  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Stopping 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-repositories-metering_1 ... 
Stopping 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-ecs_1              ... 
Stopping 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture_1                       ... 
Stopping 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-other_1                 ... 
Stopping 56aa93ed60e3e11b06e2067e06b0dd8c_s3-fixture__s3-fixture-with-session-token_1    ... 
```

**Comment by VachaShah** [comment]
start gradle check

**Comment by VachaShah** [comment]
> ❌   Gradle Check failure [d7b78ba](https://github.com/opensearch-project/OpenSearch/commit/d7b78ba2679435e25aafbbb34acef564ec92d7f3) [Log 1068](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1068.log)
> 
> [Reports 1068](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1068_reports.zip)

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnHungIOBeyondHealthyTimeout" -Dtests.seed=20C97377870AC21B -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nb -Dtests.timezone=Australia/Sydney -Druntime.java=17

org.opensearch.monitor.fs.FsHealthServiceTests > testFailsHealthOnHungIOBeyondHealthyTimeout FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([20C97377870AC21B:A2BD2D7EF3F6B453]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.opensearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnHungIOBeyondHealthyTimeout(FsHealthServiceTests.java:239)
```

**Comment by tlfeng** [comment]
The test failure from `./gradlew ':server:test' --tests "org.opensearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnHungIOBeyondHealthyTimeout"` has been reported before, in issue #1307 and #1450.

**Comment by VachaShah** [comment]
start gradle check

**Pull request merged**
