### PR TITLE
Manually update Netflix Gradle info from 12.1.5 to 12.1.6 

### PR DESCRIPTION
**Pull request by scrawfor99**
### Description
Manually updates `com.netflix.nebula:gradle-info-plugin` from 12.1.5 to 12.1.6 since #8723 failed. 

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by scrawfor99** [comment]
Should be backported to 2.x and 2.9

**Comment by kotwanikunal** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/20289/
> * **CommitID:** [3d4b2a7](https://github.com/opensearch-project/OpenSearch/commit/3d4b2a709ea57647c01e9a1495915f6fb256adf8)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Seems unrelated
#6287

**Review by kotwanikunal — APPROVED** [review]

**Review by Poojita-Raj — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
Resolve conflicts please ..

**Comment by kotwanikunal** [comment]
Please hold off merging until #8734 has been merged. Backport will fail otherwise.

**Pull request merged**
