### PR TITLE
Add artifacts from benchmarks to .gitignore

### PR DESCRIPTION
**Pull request by peternied**
### Description
Add artifacts from benchmarks to .gitignore, I keep seeing files under the ./benchmarks/bin and ./benchmarks/build-eclipse-default folders which look like they are associated with a pre-processing annotation.

<details><summary>Detailed list of files that were not ignored</summary>
<p>

```
% git status -uall                                                                                                                                                                             ~/git/opensearch
On branch core-identity
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        benchmarks/bin/generated-sources/annotations/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_benchmarkFrom_jmhTest.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType_B1.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType_B2.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType_B3.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType_B1.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType_B2.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType_B3.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/common/jmh_generated/RoundingBenchmark_nextRoundingValue_jmhTest.java
        benchmarks/bin/generated-sources/annotations/org/opensearch/common/jmh_generated/RoundingBenchmark_round_jmhTest.java
        benchmarks/build-eclipse-default/META-INF/BenchmarkList
        benchmarks/build-eclipse-default/META-INF/CompilerHints
        benchmarks/build-eclipse-default/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_benchmarkFrom_jmhTest.class
        benchmarks/build-eclipse-default/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType.class
        benchmarks/build-eclipse-default/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType_B1.class
        benchmarks/build-eclipse-default/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType_B2.class
        benchmarks/build-eclipse-default/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_jmhType_B3.class
        benchmarks/build-eclipse-default/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType.class
        benchmarks/build-eclipse-default/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType_B1.class
        benchmarks/build-eclipse-default/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType_B2.class
        benchmarks/build-eclipse-default/org/opensearch/common/jmh_generated/RoundingBenchmark_jmhType_B3.class
        benchmarks/build-eclipse-default/org/opensearch/common/jmh_generated/RoundingBenchmark_nextRoundingValue_jmhTest.class
        benchmarks/build-eclipse-default/org/opensearch/common/jmh_generated/RoundingBenchmark_round_jmhTest.class
```
</p>
</details>

### Issues Resolved
Makes me stop using `-u` during git add and become more at peace.

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [X] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
I do not think this is worth a changelog entry, but happy to follow the project guidance.

**Comment by andrross** [comment]
Do you know what is generating these files? I use IntelliJ and I have never seen them.

**Comment by peternied** [comment]
> Do you know what is generating these files? I use IntelliJ and I have never seen them.

I'm using VSCode, but I'd suspect if we have eclipse users out there they would see the same thing

**Comment by andrross** [comment]
> > Do you know what is generating these files? I use IntelliJ and I have never seen them.
> 
> I'm using VSCode, but I'd suspect if we have eclipse users out there they would see the same thing

I'm being nit-picky because the file is very neatly organized with explanations of where each of the files come from, and I think the "# These files are generated in the main tree by IntelliJ" heading might not be accurate for these files.

**Review by andrross — APPROVED** [review]

**Pull request merged**
