### PR TITLE
Rename ingest processor supports overriding target field if exists

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description

This PR adds a new parameter `override_target` to the rename ingest processor, when the parameter is true and `target_field` already exists in the document, the processor will override the target field rather than throwing an error `field [] already exists`.

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/12942

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaobinlong** [comment]
@reta, could you help to review this PR, thank you!

**Comment by reta** [comment]
> @reta, could you help to review this PR, thank you!

Thanks @gaobinlong , I have concerns regarding this change, aligned with https://github.com/opensearch-project/OpenSearch/issues/12942#issuecomment-2029093391. It does not look right (to me) and it basically just hides the problem (the field is not expected to be in the document but it is). Semantically, this change would apply to `Copy` processor that would copy from source to target field (and also may add a target field if does not exist with the document). @msfroh any thoughts?

**Review by scrawfor99 — COMMENTED** [review]
Hi @gaobinlong, 

I actually think the implementation of the change looks good. 

I do agree with Peter's comment about this being better named something like `move`. I don't have a problem with the behavior being similar to the `Copy` processor but think that the majority of users may be more familiar with the Unix terminology for move, copy, etc. 

Unless there is another naming pattern we have already committed to, I would generally be in favor of us being consistent with the behavior of Unix if we can. 

This also ties into my opinion on why `Copy` is not where I would expect this behavior. 

https://unix.stackexchange.com/questions/277412/cp-vs-mv-which-operation-is-more-efficient

**Comment by gaobinlong** [comment]
> > @reta, could you help to review this PR, thank you!
> 
> Thanks @gaobinlong , I have concerns regarding this change, aligned with [#12942 (comment)](https://github.com/opensearch-project/OpenSearch/issues/12942#issuecomment-2029093391). It does not look right (to me) and it basically just hides the problem (the field is not expected to be in the document but it is). Semantically, this change would apply to `Copy` processor that would copy from source to target field (and also may add a target field if does not exist with the document). @msfroh any thoughts?

I think `rename` just like `move`, but for now the behavior that always doesn't override the target field is not as expected, so maybe it's more friendly that we provide an option for users to use it as a real `move`. `Copy` processor supports overriding the target field but it doesn't remove the source field, this is different from the `rename` processor which always remove the source field.

**Comment by gaobinlong** [comment]
> Hi @gaobinlong,
> 
> I actually think the implementation of the change looks good.
> 
> I do agree with Peter's comment about this being better named something like `move`. I don't have a problem with the behavior being similar to the `Copy` processor but think that the majority of users may be more familiar with the Unix terminology for move, copy, etc.
> 
> Unless there is another naming pattern we have already committed to, I would generally be in favor of us being consistent with the behavior of Unix if we can.
> 
> This also ties into my opinion on why `Copy` is not where I would expect this behavior.
> 
> https://unix.stackexchange.com/questions/277412/cp-vs-mv-which-operation-is-more-efficient

Thanks, do you mean the `Copy` processor isn't like the `cp` in Linux?  The idea of `Copy` processor comes from the `set` processor which always throws exception if the target field exists, but it supports overriding by specifying `override` to `true`, so the derived `copy` processor also has this behavior.

**Comment by reta** [comment]
> I think `rename` just like `move`, but for now the behavior that always doesn't override the target field is not as expected, so maybe it's more friendly that we provide an option for users to use it as a real `move`. ``

Agree, on the second thought, I think it would make sense to have such an option, thank you @gaobinlong for clarifying.

**Comment by gaobinlong** [comment]
Hi @reta , now all checks have passed yet, could you help to review?

**Comment by reta** [comment]
LGTM, thanks @gaobinlong , it looks like we have no docs for this ingest processor (Rename Processor) [1], could you please create an issue to document it [2]? Thank you

@scrawfor99 LGTY?

[1] https://opensearch.org/docs/latest/ingest-pipelines/processors/index-processors/
[2] https://github.com/opensearch-project/documentation-website/issues

**Review by reta — APPROVED** [review]

**Comment by gaobinlong** [comment]
> LGTM, thanks @gaobinlong , it looks like we have no docs for this ingest processor (Rename Processor) [1], could you please create an issue to document it [2]? Thank you
> 
> @scrawfor99 LGTY?
> 
> [1] https://opensearch.org/docs/latest/ingest-pipelines/processors/index-processors/ [2] https://github.com/opensearch-project/documentation-website/issues

Thank you @reta ,I've opened an issue and a related PR for the missing rename ingest processor, after the PR is merged and backported to old versions, I'll open another PR for the change in this PR.

**Comment by gaobinlong** [comment]
Hi @reta , could this PR be merged now?

**Pull request merged**
