### PR TITLE
Improve breaking change logic for changelog verifier

### LINKED ISSUE #15155: [Feature Request] Changelog verifier should fail if CHANGELOG-3.0.MD is modified and a backport label is applied.
### Is your feature request related to a problem? Please describe

Had an issue earlier where a changelog entry was added to 3.0 and also backported to 2.x: https://github.com/opensearch-project/OpenSearch/pull/15150

This means the changelog for 3.0 was wrong and will probably break auto backport for other PRs. We should be able to add an automated check to the changelog verifier to catch this case.

### Describe the solution you'd like

Suggested by @andrross here: https://github.com/opensearch-project/OpenSearch/pull/15150#issuecomment-2274321630

### Related component

Build

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jed326**
### Description
Improve breaking change logic for changelog verifier

### Related Issues
- Resolves #15155

### Check List
- [x] Functionality includes testing.
~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
For testing see:
https://github.com/opensearch-project/OpenSearch/actions/runs/10360248403/job/28678317869?pr=15214

**Comment by jed326** [comment]
@andrross @sandeshkr419 could you help review? Thanks!

**Comment by peternied** [comment]
@jed326 Can you look into what change wasn't backported and then retrigger this workflow once that's done?

**Comment by jed326** [comment]
Thanks @peternied, I realized that we probably don't want to backport this since changelog-3.0 doesn't exist on 2.x branch

**Pull request merged**
