### PR TITLE
[Bug]: gradle check failing with java heap OutOfMemoryError

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
gradle check failing with java heap OutOfMemoryError
 
### Issues Resolved
Closes https://github.com/opensearch-project/OpenSearch/issues/3973
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CEHENKLE** [comment]
Aaaah!   That's awesome, @reta !!!!!  Nice catch!!!!!!

**Comment by reta** [comment]
> Aaaah! That's awesome, @reta !!!!! Nice catch!!!!!!

Thanks @CEHENKLE , I will keep it as draft for some time, will rerun builds to see if issue is gone

**Comment by bbarani** [comment]
@reta lets merge this fix in soon as I don't see any risk here.

**Comment by reta** [comment]
> @reta lets merge this fix in soon as I don't see any risk here.

@bbarani no objections, have not seen JVM heap issues so far on this pull request

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
@reta @saratvemulapalli this seems like a change that can backport to 2.0/2.1/2.2/2.x/1.3/1.x branches.
Thoughts?

**Comment by saratvemulapalli** [comment]
@peterzhuamazon yeah I agree. This fix probably helps all builds.

**Review by CEHENKLE — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
@reta seems like 1.x/1.3 failed could you manually backport to those branches?
Thanks.

**Pull request merged**
