### PR TITLE
Add Delete Operations to Translog from Engine

### LINKED ISSUE #2926: [Segment Replication] Merge to main tracking - Refactoring of existing classes to support segrep.
This is a tracking task for the refactoring tasks outlined in our meta merging issue.
- [x] Move RecoveryIndex to top level class and move inner classes from RecoveryIndex
- [x] Move RecoveryState.Timer to top level
- [x] Change GatedAutoCloseable to AutoCloseableRefCounted
- [x] Create base class ReplicationTarget and refactor RecoveryTarget to inherit from it.
- [x] Engine interface changes for addIndexOperationToTranslog and addDeleteOperationToTranslog

### PR DESCRIPTION
**Pull request by Rishikesh1159**
Signed-off-by: Rishikesh1159 <rishireddy1159@gmail.com>

### Description
This PR will allow us to decouple adding Delete operations to Lucene and adding Delete operations to Translog. This would be useful for segment replication, as we will need to just add delete operation to replicas translog instead of performing full delete operation. We will only use this method when segment replication is enabled and when we are on a replica node. The logic for checking if segment replication is enabled and is replica node will be added later in a different PR.

This is a part of the process of merging our feature branch - feature/segment-replication - back into main by re-PRing our changes from the feature branch.
The breakdown of the plan to merge to main is detailed here: https://github.com/opensearch-project/OpenSearch/issues/2926
For added context on segment replication - here's the design proposal https://github.com/opensearch-project/OpenSearch/issues/2229
 
### Issues Resolved
#2926 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kartg** [comment]
Same note as https://github.com/opensearch-project/OpenSearch/pull/2977#issuecomment-1102915253 - please add javadocs for the new API

Other than that, LGTM!

**Comment by Rishikesh1159** [comment]
start gradle check

**Comment by kartg** [comment]
Note - we're holding off on pushing this as per https://github.com/opensearch-project/OpenSearch/pull/2977#issuecomment-1103964855

**Review by nknize — CHANGES_REQUESTED** [review]
I figured this is implicit by now but wanted to explicitly mark this to be merged when we have a PR that uses the method.

**Comment by kotwanikunal** [comment]
@Rishikesh1159 Any updates on this? Are you still blocked?

**Comment by Rishikesh1159** [comment]
Closing this PR. Changes necessary are added in a different PR.

**Pull request closed without merging**
