### PR TITLE
[Backport 2.11] Performance Improvement for Datetime formats to 2.11

### PR DESCRIPTION
**Pull request by CaptainDredge**
### Description
Backport changes https://github.com/opensearch-project/OpenSearch/pull/9567 and https://github.com/opensearch-project/OpenSearch/pull/10385

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/4558

Public doc: https://github.com/opensearch-project/documentation-website/pull/5163

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by CaptainDredge** [comment]
Trigerring build for flaky test to pass

**Review by dblock — CHANGES_REQUESTED** [review]
I’m pretty sure 2.11 only takes bug fixes since yesterday, but @CEHENKLE can correct me if I’m wrong

**Comment by CEHENKLE** [comment]
Yeah, the only place it gets weird is when we haven't cut the release branch yet, and by default 2.x is the release branch. So unless it creates problems/more work for the release managers (@bbarani  or @gaiksaya or @rishabh6788 or @peterzhuamazon or anyone else :) ) then it's fine with me :)

**Comment by dblock** [comment]
> That's is correct, this is a backport for `2.x` (2.12)

This one is into a branch called 2.11, so should we not take it here and close this PR?

**Comment by msfroh** [comment]
> This one is into a branch called 2.11, so should we not take it here and close this PR?

Yeah -- I'm going to go ahead and close this one, since it sounds like we're all on the same page about not backporting to 2.11. (2.x is fine.)

Feel free to reopen if I'm wrong.

**Pull request closed without merging**
