### PR TITLE
[Backport 2.x] Implement segment replication event cancellation.

### PR DESCRIPTION
**Pull request by mch2**
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/4225 to 2.x.

### CODE REVIEW

**Comment by dreamer-89** [comment]
Failing due to heap space issue. Tracked in https://github.com/opensearch-project/OpenSearch/issues/3973. 
Refiring!
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':plugins:discovery-azure-classic:compileInternalClusterTestJava'.
> java.lang.OutOfMemoryError: Java heap space
```

**Comment by mch2** [comment]
``` What went wrong:
Execution failed for task ':distribution:bwc:bugfix:buildBwcLinuxTar'.
> Building 2.2.1 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/bugfix/build/bwc/checkout-2.2/distribution/archives/linux-tar/build/distributions/opensearch-min-2.2.1-SNAPSHOT-linux-x64.tar.gz

**Comment by mch2** [comment]
```
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark" -Dtests.seed=2C6090E329EBBFC4 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-HN -Dtests.timezone=Asia/Karachi -Druntime.java=17
  2> java.lang.AssertionError: 
    Expected: an empty collection
         but: <[[qfddaotgwv][1], node[Ak81Pn6GRbeGBUORxWl2bg], [P], s[STARTED], a[id=zu2e5c5bSwyE-ZDsdLv4_g], [qfddaotgwv][5], node[Ak81Pn6GRbeGBUORxWl2bg], [P], s[STARTED], a[id=bO_j9IkxT6Ot4qY8ucWCPg]]>
        at __randomizedtesting.SeedInfo.seed([2C6090E329EBBFC4:3ED836824252A07C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.lambda$testRestoreSnapshotAllocationDoesNotExceedWatermark$2(DiskThresholdDeciderIT.java:260)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1049)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1022)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark(DiskThresholdDeciderIT.java:260)
```

**Review by dreamer-89 — APPROVED** [review]

**Comment by dreamer-89** [comment]
@mch2 : Looks like a conflict, can you rebase and merge ?

**Comment by mch2** [comment]
```

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness" -Dtests.seed=196AC1473FA624F2 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fi-FI -Dtests.timezone=Pacific/Apia -Druntime.java=17

```

**Pull request merged**
