### PR TITLE
[Backport 2.10] Improve performance of rounding dates in date_histogram aggregation

### PR DESCRIPTION
**Pull request by ketanv3**
### Description
Backport of #9727.

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ketanv3** [comment]
Proactively created this backport to start off the checks.

**Comment by msfroh** [comment]
Rerunning the failed precommit jobs. While those are sometimes flaky, they tend to be less flaky than Gradle Check

**Comment by reta** [comment]
> Rerunning the failed precommit jobs. While those are sometimes flaky, they tend to be less flaky than Gradle Check

Yeah, those are sadly the network issues :((((

**Review by msfroh — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Comment by DarshitChanpura** [comment]
@reta @msfroh This is merged after code freeze for 2.10 which was Sept 7. This change should be reverted unless is planned and communicated.

**Comment by reta** [comment]
> @reta @msfroh This is merged after code freeze for 2.10 which was Sept 7. This change should be reverted unless is planned and communicated.

Thanks @DarshitChanpura , for some reasons I have got an impression that the date slipped a bit due to disruptive builds infrastructure

**Comment by msfroh** [comment]
I was under the impression that we didn't have a hard freeze starting with this release, but rather a "window" during which RCs would be built. I'll go back and reread the process to make sure I understand what's going on.

**Pull request merged**
