### PR TITLE
extend `constant_keyword ` field type usage scope

### LINKED ISSUE #14986: [Feature Request] extend `constant_keyword` field type usage scope
### Is your feature request related to a problem? Please describe

Now `constant_keyword` can only support one value, the usage is as follows:
```
PUT romcom_movies
{
  "mappings" : {
    "properties" : {
      "field1" : {
        "type": "constant_keyword",
        "value" : "value1"
      }
    }
  }
}
```
`field1` can only support one value, In fact, we can extend the count of value, such as add a parameter:
```values:[value1, value2,value3]```, the values is multiple fixed.
There are two benefits:
1. encoding the values,  so we can save the storage(`Byte` can encode 128 values). 
2. In some case, it can speed the search.

There are many usage scenarios, such as field name is `age`, `school`, and `city`. It doesn't affect existing functionality.

### Describe the solution you'd like
add a new `values`, support multiple fixed values.
```
PUT romcom_movies
{
  "mappings" : {
    "properties" : {
      "field1" : {
        "type": "constant_keyword",
        "values" : [value1, value2,value3......]
      }
    }
  }
}
```
If needed, I'm pleasure to implement it.

### Related component

Indexing

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kkewwei**
### Description
Add a new parameter `values` in `constant_keyword`, support multiple fixed values.

```
PUT romcom_movies
{
  "mappings" : {
    "properties" : {
      "field1" : {
        "type": "constant_keyword",
        "values" : [value1, value2,value3......]
      }
    }
  }
}
```

It also support `index` and `doc_values`.

### Related Issues
Resolves #14986

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by msfroh** [comment]
While I think the idea of encoding multiple constant values makes sense, concepts like "indexed" or "doc values" don't really make sense for `contstant_keyword` fields, because they aren't actually supposed to be part of the Lucene index.

Part of the beauty of a `constant_keyword` field is that it exists entirely within the mapping.

I noticed that you're delegating to `KeywordFieldType` for some of the query logic, which I don't think works for a constant field that only lives in the mapping. Any query against a `constant_keyword` field should be either a `MatchAllDocsQuery` or a `MatchNoDocsQuery`, because we should be able to directly evaluate the given query against the constant value(s).

Honestly, I think it would be enough to do a for-loop over the existing logic to check each value. Yes, it grows linearly in terms of the number of values, but if we're extending the current logic that handles 1 value to N values, how big is N going to get? Since the mappings are part of the cluster state that gets propagated to every node, you don't want them to get too big.

**Comment by kkewwei** [comment]
@msfroh Thanks for the comment! 

Each document has its own uniq value for `contstant_keyword` fields, We need to store each encoded value on disk for every document. When querying against a `contstant_keyword`, it may not necessarily hit all documents(for example the `sex` field, we only want to get documents containing boys), in this case, it's the same as a keyword query.

for `N`, I think N<128 is enough.

 If we don't use KeywordFieldType, I‘m highly appreciated any additional ideas from you.

**Comment by msfroh** [comment]
Ahh... Okay! If each document has its own value, then it's not a use-case for constant_keyword, which uses one constant value (or possibly list of values, if we want to make that change) for all documents in the index.


If you want documents to have different values, I'm wondering why a regular keyword field wouldn't work. Can you clarify what you're looking for that keyword fields can't do?

**Comment by kkewwei** [comment]
@msfroh, In some cases, we can speed up the query. For example, when the majority documents are hit, we can use the opposite documents, but it seems a limited optimization.

If you think it is useful to support multiple values ​​(with same values ​​in all documents), I will implement it.

**Comment by msfroh** [comment]
> @msfroh, In some cases, we can speed up the query. For example, when the majority documents are hit, we can use the opposite documents, but it seems a limited optimization.

Ahh! I considered something kind of like that for `boolean` fields in https://github.com/opensearch-project/OpenSearch/issues/11143. 

In the end, I haven't done that, since folks could just use a numeric `{0,1}`, field instead. There is an optimization for that on numeric range queries -- if a range query covers more a majority of documents (and the numeric field is present in all documents), it's replaced with "NOT inverse range". You could probably achieve something similar with an "enum" type field where the distinct values get mapped to integers. (It might be nice to do that automatically.)

Anyway -- for the `constant_keyword` field type, I don't know how many people actively want a constant list/set of values across all documents. It's a logical extension of the existing single-valued fields, but I'd also be happy to wait until someone has a use-case that needs it before implementing it. Essentially, I would wait for someone to stand up and say, "Yes, I need that."

**Pull request closed without merging**
