### PR TITLE
Enhance changelog workflow to check for missing labels

### PR DESCRIPTION
**Pull request by kotwanikunal**
### Description
- Hardens the check for `CHANGELOG.md` file and ensures a backport label exists if the entry is BwC

### Related Issues
N/A

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
This workflow is failing in this PR, that's not expected, is it? It should have skipped it?

**Comment by kotwanikunal** [comment]
> This workflow is failing in this PR, that's not expected, is it? It should have re-run it when skip-changelog was added and skipped it?

There was a scenario that was missing. Updated the workflow



> @kotwanikunal Can you link to example workflows of this change that show the new error states in your fork?

Sure. 

Without backport label- https://github.com/kotwanikunal/OpenSearch/pull/164
With backport label - https://github.com/kotwanikunal/OpenSearch/pull/165
With a breaking change - https://github.com/kotwanikunal/OpenSearch/pull/166

**Comment by peternied** [comment]
> Without backport label- [kotwanikunal#164](https://github.com/kotwanikunal/OpenSearch/pull/164)
> With backport label - [kotwanikunal#165](https://github.com/kotwanikunal/OpenSearch/pull/165)
> With a breaking change - [kotwanikunal#166](https://github.com/kotwanikunal/OpenSearch/pull/166)

None of these failed, what should the expected behavior be?

**Comment by kotwanikunal** [comment]
> > Without backport label- [kotwanikunal#164](https://github.com/kotwanikunal/OpenSearch/pull/164)
> > With backport label - [kotwanikunal#165](https://github.com/kotwanikunal/OpenSearch/pull/165)
> > With a breaking change - [kotwanikunal#166](https://github.com/kotwanikunal/OpenSearch/pull/166)
> 
> None of these failed, what should the expected behavior be?

@peternied Looks like a GH bug. Recreated the PR without any changes: https://github.com/kotwanikunal/OpenSearch/pull/167

**Comment by kotwanikunal** [comment]
> ❌ Gradle check result for [6b18aa1](https://github.com/opensearch-project/OpenSearch/commit/6b18aa1fa1d7cedcc4ac7b248dd0f87f8c441842): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/37012/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Looks like I need to rebase. Complaining of a version mismatch

**Comment by peternied** [comment]
@kotwanikunal What is the root cause on the gradle check failures?

**Comment by kotwanikunal** [comment]
> ❌ Gradle check result for [1212672](https://github.com/opensearch-project/OpenSearch/commit/1212672c167533b645e9b1fff5ee60e1bf17ccdf): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/37026/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

#10006

**Comment by kotwanikunal** [comment]
> @kotwanikunal What is the root cause on the gradle check failures?

I was missing a rebase previous - a new change got merged to `2.x` which got compatible with 3.0.
Listed for the other one,

**Pull request merged**
