### PR TITLE
Rename Class ending with Plugin to Module under modules dir 

### PR DESCRIPTION
**Pull request by rockybean**
### Description
Rename Class Name ending with `Plugin` to `Module` under `modules` dir for better classification with `plugins` which is not installed by default.

### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/4034

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nknize — COMMENTED** [review]
Thank you so much for your first contribution @rockybean :tada:!!!  This is a great moment to have more folks like you willing to step up and help grow the project. 

Since there is still some discussion on the best way to draw a logical API distinction between modules and plugins w/o introducing more confusion I'm going to hold on an official approval until we settle on a path forward. Let's continue to discuss on the issue and we'll circle back here on the implementation.

**Comment by rockybean** [comment]
Is there any way to trigger `Gradle Check` task again? 
I rerun the failure task on my local env but all is ok. So I suppose a rerun can fix this check failure.
Anybody can help here?  thanks 

@nknize

**Review by nknize — APPROVED** [review]
Excellent! Thank you for taking care of this @rockybean

**Comment by rockybean** [comment]
Close #4034

**Comment by dblock** [comment]
Why did we go with `ModulePlugin` vs `Module`?

**Comment by reta** [comment]
@dblock check please https://github.com/opensearch-project/OpenSearch/issues/4034#issuecomment-1199786206

**Pull request merged**
