### PR TITLE
Modernize and consolidate JDKs usage across all stages of the build. Update JDK-14 requirement, switch to JDK-17 instead

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update `DEVELOPER_GUIDE.md` and `java-versions.properties`.
 
### Issues Resolved
Part of https://github.com/opensearch-project/OpenSearch/issues/1351
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [X] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tlfeng** [comment]
start gradle check

**Comment by reta** [comment]
Thanks a lot @tlfeng, was checking the tests output, this is unexpected:

```
[2021-10-15T05:27:50,780][WARN ][o.o.t.n.MockNioTransport ] [transport_client_node_s1] Slow execution on network thread [400 milliseconds]
java.lang.RuntimeException: Slow exception on network thread
	at org.opensearch.transport.nio.MockNioTransport$TransportThreadWatchdog.maybeLogElapsedTime(MockNioTransport.java:420) [framework-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.opensearch.transport.nio.MockNioTransport$TransportThreadWatchdog.unregister(MockNioTransport.java:412) [framework-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.opensearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:167) [framework-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.opensearch.nio.NioSelector.handleRead(NioSelector.java:433) [opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.opensearch.nio.NioSelector.processKey(NioSelector.java:259) [opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.opensearch.nio.NioSelector.singleLoop(NioSelector.java:187) [opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.opensearch.nio.NioSelector.runLoop(NioSelector.java:144) [opensearch-nio-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

AFAIK, this repository plugin tests don't simulate network issues, but I will recheck tomorrow morning. 
Thanks again!

**Comment by tlfeng** [comment]
Thanks for your explanation for the repository plugin test 😄. I sometime saw some kinds of network issues with those tests, but didn't investigate more.
The above failure is not reproducible in my host, so I will trigger the check again. start gradle check

**Comment by dblock** [comment]
The gradle check is still using Java 14.

```
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 6.6.1
  OS Info               : Linux 5.4.0-1045-aws (amd64)
  JDK Version           : 14 (AdoptOpenJDK)
  JAVA_HOME             : /var/CITOOL/tools/hudson.model.JDK/JDK14
  Random Testing Seed   : 61237CACA4283E2D
  In FIPS 140 mode      : false
=======================================
```

I imagine this comes hardcoded from the infrastructure that runs gradle checks. We need it to start picking up Java version from https://github.com/opensearch-project/OpenSearch/blob/main/.ci/java-versions.properties#L16.
 
@peternied @peterzhuamazon where/how do we make this happen?

**Comment by reta** [comment]
@dblock the JDK-14 is coming from the CI build image, it has JAVA_HOME set to AdoptJDK-14 distribution, the pull request is being finalized (testing it right), should fix that.

**Pull request merged**
