### PR TITLE
Fix fs info reporting negative available size

### PR DESCRIPTION
**Pull request by bugmakerrrrrr**
### Description
Today, the fs info may report a negative available size, which happens when the following conditions are met:
1. A node has both `data` and `search` roles.
2. Some space is reserved for file cache.
3. The file cache space is being used by other files, primarily local indices files.

Related exception:
```
java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -1781760b
	at org.opensearch.core.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:78) ~[classes/:?]
	at org.opensearch.core.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:73) ~[classes/:?]
	at org.opensearch.monitor.fs.FsInfo$Path.getAvailable(FsInfo.java:141) ~[classes/:?]
	at org.opensearch.cluster.InternalClusterInfoService.fillDiskUsagePerNode(InternalClusterInfoService.java:452) ~[classes/:?]
	at org.opensearch.cluster.InternalClusterInfoService$1.onResponse(InternalClusterInfoService.java:265) ~[classes/:?]
	at org.opensearch.cluster.InternalClusterInfoService$1.onResponse(InternalClusterInfoService.java:260) [classes/:?]
	at org.opensearch.action.LatchedActionListener.onResponse(LatchedActionListener.java:58) [classes/:?]
	at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:113) ~[classes/:?]
	at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:107) [classes/:?]
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74) [classes/:?]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89) ~[classes/:?]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [classes/:?]
	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:341) [classes/:?]
	at org.opensearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:315) [classes/:?]
```

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kotwanikunal** [comment]
Thanks for the changes @bugmakerrrrrr. Can you please add in a changelog entry in the 2.x section?

**Comment by bugmakerrrrrr** [comment]
Update: `Path.free` includes both bytes that are available for allocation and bytes that are reserved for privileged processes, so we cannot make a direct comparison between the `free`, `available`, and `fileCacheReserved` values.

**Comment by kotwanikunal** [comment]
@bugmakerrrrrr Looks like the test is still failing: https://build.ci.opensearch.org/job/gradle-check/31254/testReport/org.opensearch.monitor.fs/FsProbeTests/testFsInfoWhenFileCacheOccupied/

**Comment by bugmakerrrrrr** [comment]
@kotwanikunal Fixed. 1. We cannot rely on the `available` value because the available space will change as the test progresses. 2. free space includes both bytes that are available for allocation and bytes that are reserved for privileged processes, so we cannot make a direct comparison between the free, available, and fileCacheReserved values.

**Comment by bugmakerrrrrr** [comment]
@kotwanikunal hi, can we merge this pr?

**Comment by kotwanikunal** [comment]
> @kotwanikunal hi, can we merge this pr?

Sure. Let me try to get it to green. Current failures seem to be unrelated.

**Review by kotwanikunal — APPROVED** [review]

**Comment by kotwanikunal** [comment]
Take 2: looks like the failure is related

```
* What went wrong:
Execution failed for task ':server:spotlessJavaCheck'.
> The following files had format violations:
      src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
          @@ -45,12 +45,9 @@
           import·org.opensearch.index.store.remote.filecache.FileCacheFactory;
           import·org.opensearch.test.OpenSearchTestCase;
           
          -import·java.io.BufferedWriter;
           import·java.io.IOException;
           import·java.nio.file.FileStore;
          -import·java.nio.file.Files;
           import·java.nio.file.Path;
          -import·java.nio.file.StandardOpenOption;
           import·java.nio.file.attribute.FileAttributeView;
           import·java.nio.file.attribute.FileStoreAttributeView;
           import·java.util.Arrays;
  Run './gradlew :server:spotlessApply' to fix these violations.
  ```

@bugmakerrrrrr can you please run `./gradlew spotlessApply`? And while you are at it, do you mind rebasing as well? 
Thanks :)

**Comment by bugmakerrrrrr** [comment]
> Take 2: looks like the failure is related
> 
> ```
> * What went wrong:
> Execution failed for task ':server:spotlessJavaCheck'.
> > The following files had format violations:
>       src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
>           @@ -45,12 +45,9 @@
>            import·org.opensearch.index.store.remote.filecache.FileCacheFactory;
>            import·org.opensearch.test.OpenSearchTestCase;
>            
>           -import·java.io.BufferedWriter;
>            import·java.io.IOException;
>            import·java.nio.file.FileStore;
>           -import·java.nio.file.Files;
>            import·java.nio.file.Path;
>           -import·java.nio.file.StandardOpenOption;
>            import·java.nio.file.attribute.FileAttributeView;
>            import·java.nio.file.attribute.FileStoreAttributeView;
>            import·java.util.Arrays;
>   Run './gradlew :server:spotlessApply' to fix these violations.
> ```
> 
> @bugmakerrrrrr can you please run `./gradlew spotlessApply`? And while you are at it, do you mind rebasing as well? Thanks :)

@kotwanikunal done.

**Comment by mgodwan** [comment]
@bugmakerrrrrr Are you planning to continue on this PR and targeting any upcoming release? 
 This has been stalled now, and if this is not planned to be continued, lets close this.

**Comment by bugmakerrrrrr** [comment]
@kotwanikunal Is there anything else I can do for this PR? or should I close this?

**Comment by jed326** [comment]
@bugmakerrrrrr We need to get the Gradle Check step to pass in order to merge PRs. Sometimes the Gradle Check will fail due to flaky tests, you can refer to: https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests

Specifically here it looks like you need to rebase your branch and fix the merge conflicts and then see if there are any more test failures. Thank you!

**Comment by andrross** [comment]
@bugmakerrrrrr Sorry for the delay here. I've pushed a rebase and fixed up the changelog conflicts.

**Comment by bugmakerrrrrr** [comment]
hi @andrross, can we merge this

**Review by andrross — APPROVED** [review]

**Review by andrross — APPROVED** [review]

**Review by andrross — APPROVED** [review]

**Review by andrross — APPROVED** [review]

**Pull request merged**
