### PR TITLE
Add release notes for 2.11

### PR DESCRIPTION
**Pull request by noCharger**
### Description

- Updated CHANGELOG.md
  - `Bump org.apache.commons:commons-compress from 1.22 to 1.23.0` had been released in 2.8 https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.8.0.md?plain=1#L46
  - `Bump netty from 4.1.99.Final to 4.1.100.Final (#10564)` is released in 2.11
- Added other changes from CHANGELOG.md to the new 2.11 release notes

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by noCharger** [comment]
https://github.com/opensearch-project/OpenSearch/actions/runs/6499797235/job/17653890753?pr=10594

```
> Task :distribution:docker:docker-ppc64le-export:exportDockerImage FAILED
Output for docker:
write /home/runner/work/OpenSearch/OpenSearch/distribution/docker/build/.docker_temp_1123310373: no space left on device
```

Can someone help with rerun failed GH actions? Thanks!

**Comment by noCharger** [comment]
https://build.ci.opensearch.org/job/gradle-check/27758/console

```
Tests with failures:
 - org.opensearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT.testRequestBreaker {p0={"search.concurrent_segment_search.enabled":"true"}}
 - org.opensearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT.testRequestBreaker {p0={"search.concurrent_segment_search.enabled":"false"}}

4496 tests completed, 2 failed, 42 skipped
```

Known issue https://github.com/opensearch-project/OpenSearch/issues/10154

**Comment by noCharger** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/27771/
> * **CommitID:** [eb648e2](https://github.com/opensearch-project/OpenSearch/commit/eb648e22d81097334e1057baeecb4b737f1ada2d)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test

```
> Task :server:internalClusterTest

Tests with failures:
 - org.opensearch.remotestore.RemoteStoreRestoreIT.testRTSRestoreWithRefreshedDataPrimaryReplicaDown

4496 tests completed, 1 failed, 42 skipped

> Task :server:internalClusterTest FAILED
build complete, generating: /var/jenkins/workspace/gradle-check/search/build/27771.tar.bz2

FAILURE: Build failed with an exception.
```
which should have been fixed by https://github.com/opensearch-project/OpenSearch/issues/9408

**Comment by kotwanikunal** [comment]
Pushing this in since there are no code changes.

**Comment by kotwanikunal** [comment]
@noCharger Can you please manually backport to `2.11` and `2.x` using the listed process?

**Comment by msfroh** [comment]
There are a bunch of changes in this changelog that aren't in 2.11.

Lots of changes have been backported to 2.x but not to the 2.11 branch. 

For example, this changelog says that we updated to Lucene 9.8 in 2.11, which we did not.

**Pull request merged**
