### PR TITLE
Set ingest processor supports copying from one field to another

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description
When using template snippets like `{}`, the rendered result is always string, not the original field type, in order to implement copying from one field to another, this PR adds a new parameter named `copy_from` for set processor which can be set to one of the field in the incoming document, and the value of that field will be copied deeply and assigned to the specified field.

`copy_from` and `value` are mutually exclusive, either of them can be set.

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/10134

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaobinlong** [comment]
The failed test is a flaky test, there's an [issue](https://github.com/opensearch-project/OpenSearch/issues/10542) tracking it.

**Comment by gaobinlong** [comment]
Flaky test : https://github.com/opensearch-project/OpenSearch/issues/2775.

**Comment by dblock** [comment]
@gaobinlong I restarted gradle check and checked the boxes in the description for you, but please do go through the checklist

**Comment by gaobinlong** [comment]
@dblock thanks, now all checks have passed yet, could you help to review this PR?

**Comment by dblock** [comment]
Not very familiar with this part of the code, maybe another maintainer can take a look?

**Comment by gaobinlong** [comment]
Could anyone help to review this PR? It's been opened for months.

**Comment by msfroh** [comment]
> Why we are not introducing dedicated `CopyProcessor` (or `CopyFromProcessor`)?

While I get that the `set` processor is often used for "simple" copying cases (e.g. as a way of "flattening" an input document), I'm inclined to agree with @reta that this behavior is distinct enough that it probably warrants its own processor.

As a bonus, since you know that the source is definitely going to be another field, you could (for example) add a `remove_original` parameter to the new processor to let it behave like a "field move", rather than a field copy.

**Comment by gaobinlong** [comment]
> > Why we are not introducing dedicated `CopyProcessor` (or `CopyFromProcessor`)?
> 
> While I get that the `set` processor is often used for "simple" copying cases (e.g. as a way of "flattening" an input document), I'm inclined to agree with @reta that this behavior is distinct enough that it probably warrants its own processor.
> 
> As a bonus, since you know that the source is definitely going to be another field, you could (for example) add a `remove_original` parameter to the new processor to let it behave like a "field move", rather than a field copy.

OK, implementing a new processor makes things simpler, and will not confuse users, I'll open another PR to implement `CopyProcessor`, thanks!

**Comment by gaobinlong** [comment]
Close this PR because https://github.com/opensearch-project/OpenSearch/pull/11870 has been merged.

**Pull request closed without merging**
