### PR TITLE
alt bash path support

### PR DESCRIPTION
**Pull request by hackacad**
Signed-off-by: hackacad <admin@hackacad.net>

### Description
Be more liberal about the location of bash

### Issues Resolved
required for upstream FreeBSD support

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
So what could go wrong when changing `#!/bin/bash` to `#!/usr/bin/env bash`? Is there anything written about what the shebang is _supposed_ to be across *nix'es?

**Comment by hackacad** [comment]
Using env is the recommended way in POSIX.
https://www.google.com/search?tbm=bks&q=linux+unix+shell+script+usr+bin+env

Using hard coded path to bash is a common issue (of course, there's a built-in shebang_fix in FreeBSD Makefile/built system, but using a env should make it more portable for every *nix* OS)

(env should always be available on every UNIX/Linux at /usr/bin/env)

**Review by dblock — APPROVED** [review]
cc: @nknize for a quick look, but this makes sense to me

**Comment by hackacad** [comment]
> cc: @nknize for a quick second look, but this makes sense to me

just ftr:
this is already used in some OpenSearch scripts like
`/dev-tools/atomic_push.sh`
`/gradlew`

**Comment by dblock** [comment]
> > cc: @nknize for a quick second look, but this makes sense to me
> 
> just ftr:
> this is already used in some OpenSearch scripts like
> `/dev-tools/atomic_push.sh`
> `/gradlew`

Let's fix anywhere we're not doing this in this PR?

**Comment by hackacad** [comment]
> 
> Let's then also fix anywhere we're not doing this in this PR?

These are the tools that are necessary during/for runtime. 
I’m not sure if the other ones have any dependencies or checksums which might be effected then. 
I’ll have a look at it.

**Comment by hackacad** [comment]
I rethought the idea of using env for start-up scripts. In most cases, this should work, but I'm not aware of every use-case, especially in custom build Linux/Unix systems. 
Is there a way of fixing that during build and create a separate FreeBSD version?  I created a ticket on FreeBSD side with all necessary fixes. 
I'd agree if you refuse that PR, which compensates for the shebang (that could be resolved during package building).

**Pull request merged**
