### PR TITLE
Fix get task API does not refresh resource stats

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description
List tasks API will refresh the resource stats for the tasks which support resource tracking, but get task API does not refresh the resource stats, this PR fix the bug and add some tests for it.

### Related Issues
https://github.com/opensearch-project/OpenSearch/issues/8655

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaobinlong** [comment]
Could anyone help to review this PR? I think it's pretty straightforward.

**Comment by gaobinlong** [comment]
@jed326 , could you help to review this PR, thanks!

**Review by jed326 — APPROVED** [review]
LGTM, Thanks for opening this bug fix! @reta could you help provide a maintainer review here?

**Comment by reta** [comment]
> LGTM, Thanks for opening this bug fix! @reta could you help provide a maintainer review here?

Somehow lost this change, @gaobinlong it looks good, could you rebase + resolve conflicts? thank you

**Comment by gaobinlong** [comment]
> > LGTM, Thanks for opening this bug fix! @reta could you help provide a maintainer review here?
> 
> Somehow lost this change, @gaobinlong it looks good, could you rebase + resolve conflicts? thank you

Thanks @reta, I've done that and now all gradle checks have passed yet.

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@gaobinlong mind please backporting to `2.x` manually? thank you

**Pull request merged**
