### PR TITLE
Fixing thread leak errors in tests

### PR DESCRIPTION
**Pull request by kartg**
### Description
Fixing thread leak errors in tests - this was occurring due to unused NoOpClient instances that were leftover from refactoring. Since the client was never closed, this caused multiple tests to fail incorrectly.

Signed-off-by: Kartik Ganesh <gkart@amazon.com>
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by mch2 — APPROVED** [review]

**Comment by kartg** [comment]
```
* What went wrong:
Execution failed for task ':distribution:bwc:bugfix:buildBwcLinuxTar'.
> Building 1.3.1 didn't generate expected file /var/jenkins/workspace/OpenSearch_CI/PR_Checks/Gradle_Check/search/distribution/bwc/bugfix/build/bwc/checkout-1.3/distribution/archives/linux-tar/build/distributions/opensearch-min-1.3.1-SNAPSHOT-linux-x64.tar.gz
```

Looks similar to #1958 and #1801

WIll refire Gradle check

**Comment by kartg** [comment]
start gradle check

**Comment by tlfeng** [comment]
Hey, seems the above test failure is caused by this commit missing in the feature branch https://github.com/opensearch-project/OpenSearch/commit/e051a426d2d0b7e986bd81feb82ec7cb1baf674f, adding 1.3.2 into BWC versions.

**Comment by kartg** [comment]
Thanks @tlfeng ! I'll cherry pick that over to the feature branch 😄

**Comment by kartg** [comment]
Two test failures - one in the seg-rep IT tests:

```
java.lang.AssertionError: Count is 58 hits but 110 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

This should be fixed once #2637 is pushed.

The other is in IndexStatsIT.testFilterCacheStats

```
2> java.lang.AssertionError: expected:<0> but was:<1>
        at __randomizedtesting.SeedInfo.seed([F7ED452E643248E7:92D2B86BD43A4F9E]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.indices.stats.IndexStatsIT.testFilterCacheStats(IndexStatsIT.java:1225)
```

This is flaky test failure captured in #2501

**Comment by kartg** [comment]
start gradle check

**Comment by kartg** [comment]
Failed because of another count assertion error. I'll go ahead and merge.

**Pull request merged**
