### PR TITLE
Upgrade aws-sdk-java version to 2.20.86

### PR DESCRIPTION
**Pull request by sachinpkale**
### Description
- There are a couple of issues with existing aws-sdk-java version that we use.
- https://github.com/aws/aws-sdk-java-v2/pull/4066
- https://github.com/aws/aws-sdk-java-v2/issues/3652#issuecomment-1659206900

### Check List
- ~[ ] New functionality includes testing.~
  - ~[ ] All tests pass~
- ~[ ] New functionality has been documented.~
  - ~[ ] New functionality has javadoc added~
- ~[ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@sachinpkale could we go to the latest one? Or there are some quirks?

**Review by kotwanikunal — APPROVED** [review]

**Comment by kotwanikunal** [comment]
@sachinpkale Can you please add a changelog entry in the dependency section? (`Unreleased 2.x` if this will be backported)

**Comment by sachinpkale** [comment]
> @sachinpkale could we go to the latest one? Or there are some quirks?

Ideally, yes. We should go with latest version but being a bit defensive here. `2.20.86` fixes both the mentioned issues and I verified the same in my testing as well.

**Review by Bukhtawar — COMMENTED** [review]
Thanks Sachin,
Can we look at what set of issues between this version (2.20.86) and latest could potentially impact us from the change log

**Comment by sachinpkale** [comment]
> Thanks Sachin, Can we look at what set of issues between this version (2.20.86) and latest could potentially impact us from the change log

Between 2.20.86 and latest version (2.25.6), there are 2292 commits. 
https://github.com/aws/aws-sdk-java-v2/compare/2.20.86...2.25.6

It would not be possible to understand how many of these are impacting OpenSearch interaction with the SDK but they could be significant. For example, 2.25.5 has a fix for S3 multipart client (https://github.com/aws/aws-sdk-java-v2/releases/tag/2.25.5)

We can also setup dependabot to upgrade the version to latest (not changing the major version) one but not sure what kind of tests we need to add to make sure the new version does not break anything.

**Review by Bukhtawar — APPROVED** [review]
looks good to me. we can decouple this PR and follow it up for latest version update espl  with stream upload support on S3SDK

**Review by gbbafna — APPROVED** [review]

**Pull request merged**
