### PR TITLE
Add codecov status badge

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
Add readme code cov status badge
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/1323

### Related
https://github.com/opensearch-project/OpenSearch/issues/850

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by saratvemulapalli — APPROVED** [review]

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
image

Hi @dreamer-89 the badge placement needs to be tweaked.

Thanks.

**Comment by dreamer-89** [comment]
> image
> 
> Hi @dreamer-89 the badge placement needs to be tweaked.
> 
> Thanks.

Thanks @peterzhuamazon for pointing this out. Added a newline to segregate badge and logo.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Since I setup each branch have its own coverage I think we can backport this.
Tho @dreamer-89 you might want to change each backport to have different links.

Example 1.x: https://app.codecov.io/gh/opensearch-project/opensearch/branch/1.x

**Comment by dreamer-89** [comment]
> Since I setup each branch have its own coverage I think we can backport this. Tho @dreamer-89 you might want to change each backport to have different links.
> 
> Example 1.x: https://app.codecov.io/gh/opensearch-project/opensearch/branch/1.x

That's a good point. We should have branch specific links. 

Though, I am thinking if there is a more generic fix which handles future branches as well.

**Comment by dblock** [comment]
Dup of #1323? Can we close?

**Comment by dreamer-89** [comment]
Closed in favour of 

> Dup of #1596? Can we close?

Closed

**Pull request closed without merging**
