### PR TITLE
[Backport] [1.x] Modernize and consolidate JDKs usage across all stages of the build. Use JDK-17 as bundled JDK distribution to run tests

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Backport of https://github.com/opensearch-project/OpenSearch/pull/1358 and https://github.com/opensearch-project/OpenSearch/pull/1368 to 1.x
 
### Issues Resolved
Closes https://github.com/opensearch-project/OpenSearch/issues/1910
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock interestingly, we updated the DEVELOPER_GUIDE.md with JDK-17 notes (from `main`) already :-) so things should be right in order now

**Review by saratvemulapalli — APPROVED** [review]
I would like @dblock to also take a look at this.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Good work, thanks!

**Comment by dblock** [comment]
I think we need to talk about this whole JDK version business, I opened https://github.com/opensearch-project/project-website/issues/628

**Pull request merged**
