### PR TITLE
[Backport 2.x]Support of GeoJson Point for GeoPoint field (#4597)

### PR DESCRIPTION
**Pull request by heemin32**
* Support of GeoJson Point for GeoPoint field

See https://github.com/opensearch-project/geospatial/issues/152

Signed-off-by: Heemin Kim <heemin@amazon.com>
(cherry picked from commit a282d399225247226d5abc3e3cd903462c973877)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
> @dblock Please take a look and merge it.

Please take a look at these unrelated failures, and for each locate whether it's intermittent and whether there's an issue already opened, and link the PR to it - we keep count so we can address issues in priority order. Please open new issues for any new intermittent failures. You can then force push on your branch to retry CI till it's green. Unfortunately flakey tests are what we live with rn :(

**Comment by heemin32** [comment]
Failure of `org.opensearch.search.PitMultiNodeTests.testCreatePitWhileNodeDropWithAllowPartialCreationFalse` is from https://github.com/opensearch-project/OpenSearch/issues/4259

**Comment by heemin32** [comment]
Failing test is from https://github.com/opensearch-project/OpenSearch/issues/4859

**Comment by heemin32** [comment]
https://github.com/opensearch-project/OpenSearch/issues/4831 & https://github.com/opensearch-project/OpenSearch/issues/4861

**Comment by dblock** [comment]
```
Tests with failures:
 - org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests.testSortMissingLast
 - org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests.testSortMissingLastReverse
 - ```

**Comment by heemin32** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** UNSTABLE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/5114/
> * **CommitID:** [a8ec925](https://github.com/opensearch-project/OpenSearch/commit/a8ec925b2541cb524fcebb15bf27c9925770cf5c)

Those are flaky tests I believe.

**Comment by heemin32** [comment]
> ```
> Tests with failures:
>  - org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests.testSortMissingLast
>  - org.opensearch.index.fielddata.SortedSetDVStringFieldDataTests.testSortMissingLastReverse
>  - 
> ```
> 
> @heemin32 This is not a fluke isn't it? I didn't try

Those are flaky tests I believe.

**Comment by heemin32** [comment]
I should merge this PR to 2.x branch. https://github.com/opensearch-project/OpenSearch/pull/4270

**Comment by dblock** [comment]
I backported https://github.com/opensearch-project/OpenSearch/pull/4270 in https://github.com/opensearch-project/OpenSearch/pull/4867, rebase?

**Comment by dblock** [comment]
I added a section in dev guide on what to do with failed tests, care to try it out for me @heemin32?
https://github.com/opensearch-project/OpenSearch/pull/4868

**Comment by heemin32** [comment]
> I added a section in dev guide on what to do with flakey tests, care to try it out for me @heemin32? #4868
```
3. Search through [issues](https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22Flakey+Random+Test+Failure%22) using the name of the failed test for whether this is a known flakey test. 
-> Why not just search issue using failed test name as keyword? Some issue might not have been tagged properly yet.
5. If an existing issue is found, paste a link to the known issue in a comment to your PR.
6. If no existing issue is found, open one.
-> If no existing issue is found, open one and paste a link to the issue in a comment to your PR.
8. Retry CI via the GitHub UX or by pushing an update to your PR.
-> Retry CI via the GitHub UX is not only available to maintainer.
```

**Comment by andrross** [comment]
@heemin32 can you rebase to pull in #4869?

**Comment by andrross** [comment]
@heemin32 can you fix the changelog conflicts?

**Comment by heemin32** [comment]
```
[Test Result](https://build.ci.opensearch.org/job/gradle-check/5263/testReport/) (4 failures / +4)
[org.opensearch.search.PitMultiNodeTests.testCreatePitWhileNodeDropWithAllowPartialCreationFalse](https://build.ci.opensearch.org/job/gradle-check/5263/testReport/junit/org.opensearch.search/PitMultiNodeTests/testCreatePitWhileNodeDropWithAllowPartialCreationFalse/)
[org.opensearch.search.PitMultiNodeTests.testCreatePitWhileNodeDropWithAllowPartialCreationFalse](https://build.ci.opensearch.org/job/gradle-check/5263/testReport/junit/org.opensearch.search/PitMultiNodeTests/testCreatePitWhileNodeDropWithAllowPartialCreationFalse_2/)
[org.opensearch.search.PitMultiNodeTests.testCreatePitWhileNodeDropWithAllowPartialCreationFalse](https://build.ci.opensearch.org/job/gradle-check/5263/testReport/junit/org.opensearch.search/PitMultiNodeTests/testCreatePitWhileNodeDropWithAllowPartialCreationFalse_3/)
[org.opensearch.search.PitMultiNodeTests.testCreatePitWhileNodeDropWithAllowPartialCreationFalse](https://build.ci.opensearch.org/job/gradle-check/5263/testReport/junit/org.opensearch.search/PitMultiNodeTests/testCreatePitWhileNodeDropWithAllowPartialCreationFalse_4/)
```
Flaky test: https://github.com/opensearch-project/OpenSearch/issues/4259

**Review by andrross — APPROVED** [review]

**Pull request merged**
