### PR TITLE
[Backport 2.10] Fix broken backward compatibility from 2.7 for IndexSorted field indi…

### PR DESCRIPTION
**Pull request by gashutos**
Backport of https://github.com/opensearch-project/OpenSearch/pull/10075

### CODE REVIEW

**Comment by gashutos** [comment]
@reta ^^

**Review by reta — CHANGES_REQUESTED** [review]
Holding the merge till we get green light from release team

**Review by andrross — APPROVED** [review]

**Review by reta — APPROVED** [review]
2.10 is cleared out

**Comment by reta** [comment]
There is an issue with the fix, https://github.com/opensearch-project/OpenSearch/pull/10075#issuecomment-1721860925 for the reference, @gashutos is looking

**Comment by reta** [comment]
> There is an issue with the fix, [#10075 (comment)](https://github.com/opensearch-project/OpenSearch/pull/10075#issuecomment-1721860925) for the reference, @gashutos is looking

Cleared out

**Pull request merged**
