### PR TITLE
Add support to run SegRep integ tests using remote store settings (#7361)

### PR DESCRIPTION
**Pull request by sachinpkale**
Backport https://github.com/opensearch-project/OpenSearch/commit/9bf99b4a63de0e14811c0aeab0e9f854591f72ed from https://github.com/opensearch-project/OpenSearch/pull/7361.

### CODE REVIEW

**Review by gbbafna — APPROVED** [review]

**Comment by kotwanikunal** [comment]
Apologies. This PR was auto closed without reaching a resolution from the maintainers.
Re-opening to move it forward.
Thanks for your contributions to OpenSearch!

**Comment by ashking94** [comment]
Closing this as this has been backported in a different PR already

**Comment by peternied** [comment]
@ashking94 could you please link to the back port where this was done?

**Comment by ashking94** [comment]
https://github.com/opensearch-project/OpenSearch/pull/7692

**Pull request closed without merging**
