### PR TITLE
Change JNA to upstream version from elastic JNA build

### LINKED ISSUE #114: Fork or replace elasticsearch dependencies
The elasticsearch build relies on the following libraries independently built by elastic.co:

* [JNA](https://github.com/elastic/jna-build)
* [SecureMock](https://github.com/elastic/securemock)
* [MockSocket](https://github.com/elastic/mocksocket)
* Geolite2DB - Being tracked in a dedicated issue: https://github.com/opensearch-project/OpenSearch/issues/404

This issue is to track the tasks needed to fork into the following repos:

* [search-jna-build](https://github.com/opendistro-for-elasticsearch/search-jna-build)
* [search-securemock](https://github.com/opendistro-for-elasticsearch/search-securemock)
* [search-mocksocket](https://github.com/opendistro-for-elasticsearch/search-mocksocket)

- [x] Mirror fork JNA
- [x] Mirror fork Secure Mock
- [x] Mirror fork MockSocket

**Update the OpenSearch build files for these dependencies**
- [ ] server/build.gradle
- [x] client/rest/build.gradle
- [x] client/sniffer/build.gradle
- [ ] gradle/local-distribution.gradle
- [ ] test/framework/build.gradle

**Remove the exclusions for thirdPartyAudit task**
- [ ] https://github.com/opensearch-project/OpenSearch/issues/420

### PR DESCRIPTION
**Pull request by xuezhou25**
### Description
This PR is to change the JNA dependency from Elasticsearch JNA Build to a GA version.
Elasticsearch rebuild JNA dependency to support platforms that supported by Elastic. It ignores several native libraries  for 
 platforms they do not support. Opensearch replace the rebuild version with a GA version, which is more suitable for OSS. 
 
### Issues Resolved
#114 
 
### Check List
  - [x] All tests pass
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Xue Zhou xuezhou@amazon.com

### CODE REVIEW

**Comment by tlfeng** [comment]
start gradle check

**Review by dblock — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
Great. A few thoughts:

1. The commit needs a better description (please amend).
2. Your DCO sign off should be your e-mail, right now it's some Amazon machine name. See the commit description, you will need to configure your email address on the machine making this PR. 
3. Looking at [org-wide search](https://github.com/search?q=org%3Aopensearch-project+org.elasticsearch%3Ajna&type=code) I think we have a similar dependency in plugins. Please take a look at those and let's make sure we don't break them by merging this here (maybe we need PRs into the plugins at the "same time").
4. I want to make sure that the Elasticsearch JNA version wasn't building native bits for a platform _not_ supported by upstream JNA or used some flags that produced a different kind of distribution that was, for example, optimized differently. I don't think so, but please confirm that we didn't break anything?

**Comment by dblock** [comment]
LGTM, but the commit still doesn't have a clean humanly readable description. Please update.

**Comment by xuezhou25** [comment]
> LGTM, but the commit still doesn't have a clean humanly readable description. Please update.

Description changed.
Elasticsearch JNA version did not build native libraries for a platform not supported by upstream JNA. It only removes native libs for platforms Elastic do not support. So I think we won't break anything.

**Comment by dblock** [comment]
> > LGTM, but the commit still doesn't have a clean humanly readable description. Please update.
> 
> Description changed.
> Elasticsearch JNA version did not build native libraries for a platform not supported by upstream JNA. It only removes native libs for platforms Elastic do not support. So I think we won't break anything.

I am still seeing this:

Screen Shot 2021-08-03 at 9 38 10 AM

```
git commit --amend -s -m "Replaced custom built JNA by official JNA distribution."
git push origin jna -f
```

**Comment by xuezhou25** [comment]
> > > LGTM, but the commit still doesn't have a clean humanly readable description. Please update.
> > 
> > 
> > Description changed.
> > Elasticsearch JNA version did not build native libraries for a platform not supported by upstream JNA. It only removes native libs for platforms Elastic do not support. So I think we won't break anything.
> 
> I am still seeing "change_jna_GA" in the commit description:
> 
> Screen Shot 2021-08-03 at 9 38 10 AM
> 
> ```
> git commit --amend -s -m "Replaced custom built JNA by official JNA distribution."
> git push origin jna -f
> ```

Done. I will pay attention to the commit description next time. Thanks for the reminder.

**Comment by dblock** [comment]
start gradle check

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Merged, thank you. I think we don't need to backport this to 1.1, but someone please speak up if you think otherwise.

**Pull request merged**
