### PR TITLE
Remove usages of MultiTermQuery.setRewriteMethodsetRewriteMethod

### LINKED ISSUE #2896: Remove usages of MultiTermQuery.setRewriteMethod
`query.setRewriteMethod` is [removed in Lucene 9.2](https://github.com/apache/lucene/pull/726) so we will need to refactor all references to this method. In it's place we should use [MultiTermQuery.CONSTANT_SCORE_REWRITE](https://github.com/apache/lucene/blob/e6fb74f9090db2bc274af94c17d80739697bdc01/lucene/core/src/java/org/apache/lucene/search/MultiTermQuery.java#L81) as the default `method` parameter [whenever `null` is used](https://github.com/opensearch-project/OpenSearch/blob/c4b684d3ae0f56786f0b2c40b48d4329bd595a24/server/src/test/java/org/opensearch/index/mapper/TextFieldTypeTests.java#L175).  

Related #2879

### PR DESCRIPTION
**Pull request by ruanwenjun**
### Issues Resolved
Close #2896
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nknize — APPROVED** [review]
:tada: Thanks so much @ruanwenjun! This LGTM! Super helpful

**Review by reta — APPROVED** [review]

**Comment by owaiskazi19** [comment]
Looks like a legit failure 

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.query.MultiMatchQueryBuilderTests.testToFuzzyQuery" -Dtests.seed=483DC00A51C4031E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-SG -Dtests.timezone=Africa/Gaborone -Druntime.java=17

org.opensearch.index.query.MultiMatchQueryBuilderTests > testToFuzzyQuery FAILED
    java.lang.AssertionError: expected: org.apache.lucene.search.FuzzyQuery<mapped_string:text~2> but was: org.apache.lucene.search.FuzzyQuery<mapped_string:text~2>
        at __randomizedtesting.SeedInfo.seed([483DC00A51C4031E:36FCE1C4C85FA31A]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.index.query.MultiMatchQueryBuilderTests.testToFuzzyQuery(MultiMatchQueryBuilderTests.java:415)

**Review by VachaShah — APPROVED** [review]
Thank you @ruanwenjun for picking this up!

**Comment by ruanwenjun** [comment]
> 

Thanks for your review, this is caused by an error change, I have changed this.

**Comment by ruanwenjun** [comment]
> Looks like a legit failure
> 
> ```
> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.query.MultiMatchQueryBuilderTests.testToFuzzyQuery" -Dtests.seed=483DC00A51C4031E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-SG -Dtests.timezone=Africa/Gaborone -Druntime.java=17
> 
> org.opensearch.index.query.MultiMatchQueryBuilderTests > testToFuzzyQuery FAILED
>     java.lang.AssertionError: expected: org.apache.lucene.search.FuzzyQuery<mapped_string:text~2> but was: org.apache.lucene.search.FuzzyQuery<mapped_string:text~2>
>         at __randomizedtesting.SeedInfo.seed([483DC00A51C4031E:36FCE1C4C85FA31A]:0)
>         at org.junit.Assert.fail(Assert.java:89)
>         at org.junit.Assert.failNotEquals(Assert.java:835)
>         at org.junit.Assert.assertEquals(Assert.java:120)
>         at org.junit.Assert.assertEquals(Assert.java:146)
>         at org.opensearch.index.query.MultiMatchQueryBuilderTests.testToFuzzyQuery(MultiMatchQueryBuilderTests.java:415)
> ```



> > 
 Thanks for your review, this is caused by an error change, I have changed this.

**Pull request merged**
