### PR TITLE
Update TRIAGING instructions for closed issues

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

During triage, some issues are closed due to insufficient information or other reasons.

The current [TRIAGING](https://github.com/opensearch-project/OpenSearch/blob/main/TRIAGING.md) document instructs Issue submitters to re-open a closed issue after addressing problems.  However, only project committers have the permission to re-open a closed issue.  

This PR updates the "canned response" to reflect this reality.

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [X] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dbwiddis** [comment]
I can't figure out how to get the description checker action to pass.  @peternied please merge https://github.com/peternied/check-pull-request-description-checklist/pull/1 to make my life easier.

The documentation on the action could be more helpful in telling me how to handle indented bullets as well.

**Review by peternied — APPROVED** [review]
Thanks for this update, looks good to me

**Review by kotwanikunal — APPROVED** [review]

**Comment by peternied** [comment]
@dbwiddis When you get a chance please report all the test failures, gradle check is on its 5x try - this is kinda of ridiculous.

**Review by reta — APPROVED** [review]

**Comment by peternied** [comment]
@dbwiddis I've followed all the failures, and created [1] to follow up.

- [1] https://github.com/opensearch-project/OpenSearch/issues/12410

### Flaky test round up
#### [Batch 1](https://build.ci.opensearch.org/job/gradle-check/33943/)
- https://github.com/opensearch-project/OpenSearch/issues/12197
#### [Batch 2](https://build.ci.opensearch.org/job/gradle-check/33963/testReport/)
- https://github.com/opensearch-project/OpenSearch/issues/10006
- https://github.com/opensearch-project/OpenSearch/issues/9191
#### [Batch 3](https://build.ci.opensearch.org/job/gradle-check/33967/testReport/)
- https://github.com/opensearch-project/OpenSearch/issues/9191
- https://github.com/opensearch-project/OpenSearch/issues/9208
#### [Batch 4](https://build.ci.opensearch.org/job/gradle-check/33973/)
- https://github.com/opensearch-project/OpenSearch/issues/12408
#### [Batch 5](https://build.ci.opensearch.org/job/gradle-check/33979/testReport/)
- https://github.com/opensearch-project/OpenSearch/issues/12197
- https://github.com/opensearch-project/OpenSearch/issues/9191
- https://github.com/opensearch-project/OpenSearch/issues/11979
- https://github.com/opensearch-project/OpenSearch/issues/9208
#### [Batch 6](https://build.ci.opensearch.org/job/gradle-check/33984/)
- https://github.com/opensearch-project/OpenSearch/issues/9191
- https://github.com/opensearch-project/OpenSearch/issues/12409
#### [Batch 7](https://build.ci.opensearch.org/job/gradle-check/33994/)
- https://github.com/opensearch-project/OpenSearch/issues/9191

**Pull request merged**
