### PR TITLE
Rename translog pruning setting to CCR specific setting and addressed Bug in the test case

### PR DESCRIPTION
**Pull request by saikaranam-amazon**
### Description
- Rename translog pruning setting to CCR specific setting
  - From `index.translog.retention_lease.pruning.enabled` to `index.plugins.replication.translog.retention_lease.pruning.enabled`
- [Bug] Fix test case issue for translog deletion policy and translog tests
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/1100
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Comment by krishna-ggk** [comment]
start gradle check

**Comment by itiyamas** [comment]
start gradle check

**Comment by saikaranam-amazon** [comment]
1.x branch is generating 1.2 build and build is expecting 1.1 artifacts 

> Building 1.1.0 didn't generate expected file /Volumes/Unix/OpenSearch/OpenSearch/distribution/bwc/minor/build/bwc/checkout-1.x/distribution/archives/linux-tar/build/distributions/opensearch-1.1.0-SNAPSHOT-linux-x64.tar.gz

Actual file generated - opensearch-1.2.0-SNAPSHOT-linux-x64.tar.gz

**Comment by CEHENKLE** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Review by nknize — APPROVED** [review]
LGTM

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
The build was broke by #1251 where `min` was added to the artifact and bwc tests are still expecting a file w/o the min label.

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
unrelated test failure. I [opened an issue](https://github.com/opensearch-project/OpenSearch/issues/1292)  Kicking off gradle check again (this is really bad practice; we need better random testing to catch these failures quicker).

**Comment by nknize** [comment]
start gradle check

**Pull request merged**
