### PR TITLE
Fix fail open stats in case the only healthy shard copy reside in weighed away az

### LINKED ISSUE #7599: [BUG][Weighted Shard Routing] Fail open count is not updated for one healthy shard copy in weighed away az
**Describe the bug**
[Fail Open stats](https://github.com/opensearch-project/OpenSearch/issues/5037) added as part of [PR](https://github.com/opensearch-project/OpenSearch/pull/6041) does not update fail open count if there is a fail open executed due to single healthy shard copy and that copy resides in weighed away az data node. 

**To Reproduce**
1. Create a domain with 3 azs (3 shard copies) and set shard routing weight to 0 for one of the azs. 
2. Inject faults(fail all copies of a shard except the one in weighed away az) so that fail open is executed for shard search request. 
3. Make node stats api call ```GET /_nodes/<node_id>/stats/weighted-routing```
4. Fail open count is not updated 

**Expected behavior**
Fail open count should increase on fail open execution.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by anshu1106**
### Description

This PR fixes fail open stats in case the only healthy shard copy reside in weighed away az data nodes

### Related Issues
Resolves #7599

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Let's get this to green?

**Comment by anshu1106** [comment]
> Let's get this to green?

addressed

**Comment by kotwanikunal** [comment]
Apologies. This PR was auto closed without reaching a resolution from the maintainers.
Re-opening to move it forward.
Thanks for your contributions to OpenSearch!

**Comment by ashking94** [comment]
@anshu1106  Is this being worked upon? You can tag the maintainers to get traction on this.

**Comment by ticheng-aws** [comment]
Hi @anshu1106, do we have any updates?

**Comment by kotwanikunal** [comment]
Closing this PR due to inactivity. @anshu1106 Please re-open if needed.

**Pull request closed without merging**
