### PR TITLE
Upgrade lucene version

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
Upgrades the lucene snapshot to `9.5.0-snapshot-d5cef1c`

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dreamer-89 @nknize do we want to merge that to `2.x`? It implies that Lucene 9.5 is released before 2.5.0 (January 17th, 2023), is it realistic?

**Comment by dreamer-89** [comment]
> @dreamer-89 @nknize do we want to merge that to `2.x`? It implies that Lucene 9.5 is released before 2.5.0 (January 17th, 2023), is it realistic?

Thanks @reta for catching and bringing this up. This is a valid point.
I will convert this to draft state to gather more feedback for now.

**Comment by saratvemulapalli** [comment]
@reta @dreamer-89 I would prefer holding off the change looking at our release schedule[1]. Code freeze for 2.5 is Jan 10th and release is on 17th. Ideally we'd want to get some bake time and would be perfect for 2.6.

[1] https://opensearch.org/releases.html

**Comment by kotwanikunal** [comment]
@dreamer-89 Looks like this is tagged for 2.6.0. Should we get this in?

**Comment by reta** [comment]
We should close this one I this one, the `2.x` is on 9.5.0 release

**Comment by dreamer-89** [comment]
Closing this as 2.x is on 9.5 version of Lucene added in https://github.com/opensearch-project/OpenSearch/pull/6078

**Pull request closed without merging**
