### PR TITLE
OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
In some circumstances, when running a search operation, if the client TCP connection is closed before the search operation is completed, opensearch crashes with:

```
[2022-07-20T17:51:36,145][ERROR][org.opensearch.bootstrap.OpenSearchUncaughtExceptionHandler] fatal error in thread [opensearch[mycluster-elasticsearch-3][search][T#8]], exiting
java.lang.AssertionError: unexpected higher total ops [15] compared to expected [14]
	at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:465) ~[opensearch-1.3.4.jar:1.3.4]
	at org.opensearch.action.search.AbstractSearchAsyncAction.lambda$performPhaseOnShard$2(AbstractSearchAsyncAction.java:303) ~[opensearch-1.3.4.jar:1.3.4]
```
 
### Issues Resolved
Closes https://github.com/opensearch-project/OpenSearch/issues/3962
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by andrross — APPROVED** [review]

**Comment by dbonf** [comment]
will this backported to 1.3 please?

**Comment by reta** [comment]
> will this be backported to 1.3 please?

Yes, on it

**Comment by reta** [comment]
@dbonf would you be able to give it a try on 1.3.5-SNAPSHOT? thank you!

**Comment by dbonf** [comment]
@reta sure, do I need to compile it or is it already available somewhere?

**Comment by reta** [comment]
> @reta sure, do I need to compile it or is it already available somewhere?

Good question, I think if you could compile (once https://github.com/opensearch-project/OpenSearch/pull/4148 is in), would be awesome, I am not 100% sure we publish snapshots

**Comment by dbonf** [comment]
@reta I managed to build from reta:backport/backport-4143-to-1.3` and first tests are promising, no crashes

**Pull request merged**
