### PR TITLE
Remove unused classes

### PR DESCRIPTION
**Pull request by adnapibar**
### Description
These internal classes are not used anymore and can be safely removed.

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Rabi Panda <adnapibar@gmail.com>

### CODE REVIEW

**Comment by adnapibar** [comment]
#4881

**Comment by kotwanikunal** [comment]
I can see that some of the classes are public and are not marked as `opensearch.internal`. Should we call this out within the breaking changes?

**Comment by adnapibar** [comment]
> 



> I can see that some of the classes are public and are not marked as `opensearch.internal`. Should we call this out within the breaking changes?

Sure, which one is not marked as `opensearch.internal` ?

**Comment by kotwanikunal** [comment]
> > 
> 
> > I can see that some of the classes are public and are not marked as `opensearch.internal`. Should we call this out within the breaking changes?
> 
> Sure, which one is not marked as `opensearch.internal` ?

My bad. I was looking at the header docs instead of class documentation.

**Review by kotwanikunal — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Pull request merged**
