### PR TITLE
[WIP] Developer guide updates

### PR DESCRIPTION
**Pull request by dblock**
### Description

Ongoing changes to DEVELOPER_GUIDE.md
 
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by harold-wang — APPROVED** [review]
This is good, thanks for the update!

**Comment by dblock** [comment]
start gradle check

**Comment by dblock** [comment]
Why do we not allow merge commits anymore? These are 3 separate changes, I'd prefer to keep them as such.

**Comment by nknize** [comment]
> Why do we not allow merge commits anymore? These are 3 separate changes, I'd prefer to keep them as such.

The history behind that is because [some PRs](https://github.com/opensearch-project/OpenSearch/pull/557) have many iterations and merging the separate commits makes the fidelity and churn of the git log too high to track for tagging purposes. The general guidance is "one commit per change". So three distinct changes should have three separate PRs. Otherwise individual commits working up to one change (bugfix,enhancement,feature) should be squashed into one commit for that one change.

**Comment by dblock** [comment]
Thanks @nknize. I've rarely seen this in OSS projects. Part of the problem is that squashed commits don't match the branch from which they came from, therefore it's difficult to tell whether all the changes on that branch were merged. As a contributor I can click "delete branch" on GitHub after the merge (if I remember), but [scripts that prune branches](https://github.com/dblock/dotfiles/blob/master/bash/bin/git-delete-merged) don't work at all. So developers typically end up with hundreds of useless branches that are impossible to keep track of.

**Review by aekewu1111 — COMMENTED** [review]
The

**Comment by nknize** [comment]
I'm open to majority preference. Personally I've worked in both settings starting w/ merge commits and then switching to squash merging. I prefer the simplicity and upstream cleanliness of disallowing merge commits. IMHO I'm willing to spend the time cleaning up my less important local / forked branches and forgo keeping them in sync than dig through a long tail of commits on the upstream repo (which can get very long for impactful deprecation changes). For me, this way also makes it easier to backport features from main to next release branch by cherry-picking instead of merging. But I can see merit in both workflows.

**Comment by nknize** [comment]
@dblock would you mind backporting to 1.x? It's Developer Guide updates so I don't think a PR is necessary unless you prefer?

**Comment by dblock** [comment]
> @dblock would you mind backporting to 1.x? It's Developer Guide updates so I don't think a PR is necessary unless you prefer?

Done. I cherry-picked it and pushed. LMK if I did it wrong.

**Comment by dblock** [comment]
> > @dblock would you mind backporting to 1.x? It's Developer Guide updates so I don't think a PR is necessary unless you prefer?
> 
> Done. I cherry-picked it and pushed. LMK if I did it wrong.

Also I realize "[WIP]" slid into the commit description on squash merge, sorry about that.

**Pull request merged**
