### PR TITLE
Compare strings with equals() instead of ==

### PR DESCRIPTION
**Pull request by dk2k**
Compare strings with equals() instead of ==

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dbwiddis** [comment]
@dk2k this will be mergeable after you respond to the suggested change.

**Comment by dk2k** [comment]
I accepted the suggested change

**Comment by dbwiddis** [comment]
> I accepted the suggested change

Well, apparently I shouldn't have suggested that.  It's failing precommit and gradle check because of ForbiddenAPIs:

```
Forbidden method invocation: java.lang.Boolean#getBoolean(java.lang.String) [use org.opensearch.common.Booleans#parseBoolean(java.lang.String)]
```
Looks like we want to enforce either "true" or "false".

So can you please update to that method?  Sorry for the incorrect suggestion here.    (Note you can run `./gradlew precommit` locally to catch these before pushing.)

**Comment by dk2k** [comment]
Sorry, I spoiled the rebase

**Pull request closed without merging**
