### PR TITLE
Removed suspicious getClass() call on Class

### PR DESCRIPTION
**Pull request by dk2k**
Removed suspicious getClass() call on Class

### CODE REVIEW

**Comment by dblock** [comment]
Is there a test covering this path?

**Review by dblock — CHANGES_REQUESTED** [review]
Reading the code seems like the .getClass() was intentional. I could be wrong.

**Comment by dk2k** [comment]
@dbwiddis 
Code snippet for illustration:

    public static void main(String[] args) {
        StringBuilder stringBuilder = new StringBuilder();
        Class classInstance = stringBuilder.getClass();
        System.out.println(classInstance);
        System.out.println(classInstance.getClass());
    }
    
output:
class java.lang.StringBuilder
class java.lang.Class

Which of the lines from this output do you expect to see as part of exception's message?

**Comment by dblock** [comment]
The log entry says "streamable custom class XYZ already registered", we expect to see XYZ

**Pull request closed without merging**
