### PR TITLE
Max scroll limit breach to throw a OpenSearchRejectedExecutionException

### PR DESCRIPTION
**Pull request by Bukhtawar**
… on max scroll limit breach

Signed-off-by: Bukhtawar Khan bukhtawa@amazon.com

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
#1053 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
LGTM. Is there a story to this?

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by Bukhtawar** [comment]
It's trying to address a bug #1054 to ensure we throw a 429 instead of a 503

**Comment by Bukhtawar** [comment]
Guess the gradle checkstyle issue is already addressed?

**Comment by dblock** [comment]
I think this is yours actually

```
> Task :server:checkstyleTest
[ant:checkstyle] [ERROR] /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/server/src/test/java/org/opensearch/search/SearchServiceTests.java:40:8: Unused import - org.opensearch.ExceptionsHelper. [UnusedImports]
[ant:checkstyle] [ERROR] /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/server/src/test/java/org/opensearch/search/SearchServiceTests.java:41:8: Unused import - org.opensearch.OpenSearchException. [UnusedImports]
```

**Comment by Bukhtawar** [comment]
Addressed already as a part of https://github.com/opensearch-project/OpenSearch/pull/1054/commits/07edd93c98b25b234fea34849e2aa567094e8a77

**Comment by dblock** [comment]
start gradle check

**Comment by Bukhtawar** [comment]
Pinging @dblock @adnapibar for help with approval and merge

**Comment by dblock** [comment]
Merged. Will you please backport PR into 1.1?

**Pull request merged**
