### PR TITLE
[Remote Store] Fix stuck segments upload issue

### LINKED ISSUE #11020: [BUG] Stuck segments upload leads to high refresh lag
**Describe the bug**
There is a use case where when segments are getting uploaded to remote store and a flush/force merge happens, there is a possibility that the segment tracker's data can get erased while there is async refresh retry is happening. This leads to latch not getting counted down.

https://github.com/opensearch-project/OpenSearch/blob/a2febe956defae25417a84bca3646efc2bafb7a5/server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java#L388-L403

**To Reproduce**
Run indexing for a long time. 

**Expected behavior**
Refreshes should never get stuck.

### PR DESCRIPTION
**Pull request by ashking94**
### Description
There is a use case where when segments are getting uploaded to remote store and a flush/force merge happens, there is a possibility that the segment tracker's data can get erased while there is async refresh retry is happening. This leads to latch not getting counted down.

https://github.com/opensearch-project/OpenSearch/blob/a2febe956defae25417a84bca3646efc2bafb7a5/server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java#L388-L403

### Related Issues
Resolves #11020

### Check List
- [ ] ~New functionality includes testing.~
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ashking94** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29439/
> * **CommitID:** [ee651e7](https://github.com/opensearch-project/OpenSearch/commit/ee651e73f4f58679e026c4a3b657a6a1c0d3353a)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Known flaky tests - https://github.com/opensearch-project/OpenSearch/issues/10193, https://github.com/opensearch-project/OpenSearch/issues/9499

**Review by kkmr — APPROVED** [review]

**Comment by dblock** [comment]
@ashking94 Please see through gradle check failures above?

**Review by dblock — CHANGES_REQUESTED** [review]
There should be a test that reproduces the bug as described and fails without the fix, please.

**Comment by ticheng-aws** [comment]
Hi @ashking94, the PR is stalled. Do we have any updates?

**Comment by ashking94** [comment]
> Hi @ashking94, the PR is stalled. Do we have any updates?

I plan to take it up real soon.

**Comment by ashking94** [comment]
Part problem that this PR is solving has been fixed with https://github.com/opensearch-project/OpenSearch/pull/11896 already. Will rebase the PR and get only relevant code.

**Pull request closed without merging**
