### PR TITLE
Serialize MediaType as an integer to avoid string parsing

### LINKED ISSUE #15979: CPU intensive string parsing of MediaType field in binary serialization
### Is your feature request related to a problem? Please describe

I ran some benchmarks of an indexing-only workload and noticed that a surprising large amount of CPU time was being spent on parsing the MediaType as a string on the Netty I/O event loop. This is still a relatively tiny part of the overall CPU time, but there's an obvious optimization here. About half of the CPU cycles spent deserializing the BulkRequest is spent on `parseMediaType`:

image

It turns out that in order to serialize the MediaType, we are writing the string `"application/json; charset=UTF-8"` and then doing complicating string splitting on the read path to parse that string. This change was made as a part of the refactoring to decouple the `XContentType` enum from the generic `StreamInput` and `StreamOutput` framework.

### Describe the solution you'd like

The complicated string parsing logic makes sense when handling HTTP requests that may be coming from arbitrary clients sending different content types and/or different string encodings. However, it's totally overkill (in my opinion) on the binary transport API where the client and server are both OpenSearch processes that are tightly controlled. I think there are 2 ways to fix this:

1. Continue to write `"application/json; charset=UTF-8"` but add a special case on the read path to match that string to constant and return the appropriate MediaType instance. This would bypass the parsing logic and require no changes to the write path.
2. Add a new method called something like `int uniqueId()` to the MediaType interface that can be leveraged by the binary protocol to efficiently serialize any MediaType instance into a single VInt. The MediaTypeRegistry could enforce that there are no conflicts across registered instances. This would be the most efficient way to handle this on both the write path and read path, and it would also avoid tightly coupling any specific MediaType instance to the StreamInput/StreamOutput framework.

I think option 2 is simple enough we should probably do it. I'll send out a PR soon to show that option.

### Related component

Libraries

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andrross**
### Related Issues
Resolves #15979

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — COMMENTED** [review]
Help me understand where these `uniqueId`'s come from? For `XContentType` I see it uses `index`? Do those change? What happens when a new media type is inserted into the list of possible media types in a minor version?

**Comment by reta** [comment]
Adding to @dblock concerns, the media type has variable part. Fe "application/json; charset=UTF-8" or "application/json; charset=UTF-16", all of those are  "application/json" but have `charset` deviation, the `MediaRegistry` knows only about "application/json" (if I am not mistaken). The unique id concept will not cover it since media type is also coming from client requests.

May be what we could do, in order to simplify things, is to cache media types on each node? Fe using hash or something? How would it work (in the nutshell):

- write side:
```
out.write(mediaType.hash());
out.write(mediaType);
```

- read side:
```
hash = out.read();
mediaTypeStr =  out.readString();
if (cache.contains(hash)) {
   // use from cache
} else {
   MediaType.fromMediaType(mediaTypeStr);
}

```

**Comment by andrross** [comment]
> the media type has variable part. Fe "application/json; charset=UTF-8" or "application/json; charset=UTF-16", all of those are "application/json" but have charset deviation, the MediaRegistry knows only about "application/json" (if I am not mistaken). The unique id concept will not cover it since media type is also coming from client requests.

@reta @dblock This is a fair point, but the code that exists today can only model the variable part of the media type as a [`ParsedMediaType`](https://github.com/opensearch-project/OpenSearch/blob/301c766075a4a91870439482cab4cfb09d9299bd/libs/core/src/main/java/org/opensearch/core/xcontent/MediaTypeRegistry.java#L374) type. Once we're down to a `MediaType` instance, then the variable part has been discarded and (for the JSON case) it is going to say "application/json; charset=UTF-8" in all cases because that is [hardcoded](https://github.com/opensearch-project/OpenSearch/blob/301c766075a4a91870439482cab4cfb09d9299bd/libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java#L66).

I think there may be a disconnect in the object modelling in that the MediaType interface is quite generic, but in practice the only implementation is as the XContentType enum. This interface was only relatively recently introduced to decouple the specific XContentType enum out of the `opensearch-core` library. Prior to that the enum ordinal was being serialized over the transport layer. The refactoring in this PR gets us back to that behavior, but retains the decoupling by adding this new `uniqueId` concept to the interface.

One alternative, which I mentioned in the [issue](#15979), is to simply add in a short-circuit optimization in the `parseMediaType()` method where if the string matches one of the hardcoded values it will return without actually doing any parsing. We'd still be paying the penalty of writing the whole (hardcoded) "application/json; charset=UTF-8" string instead of just a single byte though. @reta what do you think?

**Comment by reta** [comment]
> Once we're down to a `MediaType` instance, then the variable part has been discarded and (for the JSON case) it is going to say "application/json; charset=UTF-8" in all cases because that is [hardcoded](https://github.com/opensearch-project/OpenSearch/blob/301c766075a4a91870439482cab4cfb09d9299bd/libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java#L66).

I did some debugging and you are very right, the whatever the content type request had is narrowed down to the respective XContent's media type.

> I think there may be a disconnect in the object modelling in that the MediaType interface is quite generic, but in practice the only implementation is as the XContentType enum. 

This is actually an important point - the media type at least designed to be extensible. 

> One alternative, which I mentioned in the [issue](https://github.com/opensearch-project/OpenSearch/pull/16073#15979), is to simply add in a short-circuit optimization in the parseMediaType() method where if the string matches one of the hardcoded values it will return without actually doing any parsing.

I think that would be a best option, that we could generalize in `MediaTypeRegistry` by checking `XContentType::mediaType` first (since this ones are known and hardcoded).

**Comment by andrross** [comment]
Closing in favor of #16358

**Pull request closed without merging**
