### PR TITLE
Fix LocalTranslogTests.testWithRandomException test scenario

### LINKED ISSUE #6625: Test failure: LocalTranslogTests.testWithRandomException
This is reproducible with the seed below.

https://build.ci.opensearch.org/job/gradle-check/12272/consoleFull

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.translog.LocalTranslogTests.testWithRandomException" -Dtests.seed=4736E0CC7306EBDA -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-DO -Dtests.timezone=GMT -Druntime.java=19

org.opensearch.index.translog.LocalTranslogTests > testWithRandomException FAILED
    java.lang.AssertionError: expected:<null> but was:<java.lang.RuntimeException: simulated>
        at __randomizedtesting.SeedInfo.seed([4736E0CC7306EBDA:21EE8BD308E265CB]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.index.translog.LocalTranslogTests.testWithRandomException(LocalTranslogTests.java:3235)
```

### PR DESCRIPTION
**Pull request by mitrofmep**
### Description
Set TragicException in case of simulated Runtime Exception for asserting and passing test `LocalTranslogTests.testWithRandomException`

### Issues Resolved
Resolves #6625  

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

### CODE REVIEW

**Comment by dblock** [comment]
Please sign DCO/iterate to green. Thanks!

**Comment by mitrofmep** [comment]
> Please sign DCO/iterate to green. Thanks!

Done)

**Comment by dblock** [comment]
@mitrofmep Do you think you could add a test that always hits this code?

**Comment by mitrofmep** [comment]
> @mitrofmep Do you think you could add a test that always hits this code?

Sure! Proceeding from this case, is it ok if I'll create a copy of this test `LocalTranslogTests.testWithRandomException`, but change random values to exact values, that are passed to test in case of "problem" seed?

**Comment by dbwiddis** [comment]
> @mitrofmep Do you think you could add a test that always hits this code?

Hey @dblock I independently tracked this one down, and the existing random tests do trigger this; it's 100% reproducible with the seed given in the failed log builds.  I don't think an additional test is needed, and I think the fix is correct here (the test expects the failure tracked in "tragic" but it's just a plain exception.

**Comment by dbwiddis** [comment]
I might note that the "expected" and "actual" fields in the `assertEquals()` associated with this failure (and all in this test method) are reversed, which makes debugging slightly confusing. I wouldn't mind if those were switched to their correct order in this PR.

**Comment by dblock** [comment]
@mitrofmep LMK if you want me to merge as is or fix the order of the check that @dbwiddis suggests (and write a test that always fails without this fix as I do? :))

**Comment by mitrofmep** [comment]
> @mitrofmep LMK if you want me to merge as is or fix the order of the check that @dbwiddis suggests (and write a test that always fails without this fix as I do? :))

Hello! Could you merge it as is for now, and we can add this always falling test later. I also reversed "actual" and "expected" fields, as @dbwiddis mentioned.

**Comment by mitrofmep** [comment]
@dblock, is it okay for merging now, or should I add something else?

**Pull request merged**
