### PR TITLE
[Backport 2.x] [Remote Store] Change behaviour in replica recovery for remote translog enabled indices (#4318)

### PR DESCRIPTION
**Pull request by ashking94**
Signed-off-by: Ashish Singh <ssashish@amazon.com>

### Description
PR link to main: https://github.com/opensearch-project/OpenSearch/pull/4318

### Issues Resolved
NA

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by andrross** [comment]
I believe this depends on #4857

**Comment by andrross** [comment]
@ashking94 I believe the test failures have been fixed and the dependent PR merged. Please rebase this the 2.x branch and it should pass the tests.

**Comment by ashking94** [comment]
@andrross - done.

**Comment by andrross** [comment]
@ashking94 Can you fix the DCO on your latest commit?

**Comment by ashking94** [comment]
@andrross - My bad. It's done now.

**Review by andrross — APPROVED** [review]

**Pull request merged**
