### PR TITLE
Removing hard coded value of max concurrent shard requests

### LINKED ISSUE #3363: [BUG] Max concurrent requests per node changed from default 5 to 1 in Elasticsearch 7.10/Opensearch 1.0
**Describe the bug**
Max concurrent search requests per node was changed from default value of 5 earlier to 1 in Elasticsearch 7.10/Opensearch 1.0 as part of [this commit](https://github.com/elastic/elasticsearch/commit/3d69b5c41e235d7962b6dc315aba8b2f4cbe0ef9). This can lead to ShardNotFoundException if the single node has multiple shards for an index, and shards relocate while the coordinator executes single request batches on data nodes, especially during B/G in Amazon Opensearch service

**To Reproduce**
1. Create node with multiple shards
2. Relocate shards to another node during search request
3. Search request should fail with ShardNotFoundException

**Expected behavior**
The default behavior should keep 5 concurrent requests per node to avoid this regression.

**Screenshots**
```
RemoteTransportException[[76bbf5b90a0e3fe668805d61884db93d][172.16.70.171:9300][indices:data/read/search[phase/query]]]; nested: ShardNotFoundException[no such shard];
Caused by: [users/GK-cv0TRRPO_1ag32E7NKA][[users][224]] ShardNotFoundException[no such shard]
        at org.opensearch.index.IndexService.getShard(IndexService.java:301)
        at org.opensearch.search.SearchService.getShard(SearchService.java:429)
        at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:394)
        at org.opensearch.action.search.SearchTransportService.lambda$registerRequestHandler$6(SearchTransportService.java:333)
        at com.amazonaws.elasticsearch.iam.IamTransportRequestHandler.messageReceived(IamTransportRequestHandler.java:68)
        at com.amazonaws.elasticsearch.ccs.CrossClusterRequestInterceptor$CrossClusterRequestHandler.messageReceived(CrossClusterRequestInterceptor.java:155)
        at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:138)
        at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:64)
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:85)
        at org.opensearch.transport.InboundHandler.handleRequest(InboundHandler.java:220)
        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:120)
        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102)
        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:713)
        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:155)
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:130)
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:95)
```

### PR DESCRIPTION
**Pull request by jainankitk**
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>

### Description
Removes the hard coding for max concurrent shard requests
 
### Issues Resolved
#3363 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by Bukhtawar — COMMENTED** [review]
Thanks @jainankitk should we also add a test to ensure that we catch it if it accidentally gets reset to 1

**Comment by jainankitk** [comment]
@nknize @Bukhtawar - Yeah, I could not think of good way to add test. Maybe we can merge the PR, to fix the regression asap and I will keep the issue open to add test whenever I have time?

**Comment by nknize** [comment]
> Maybe we can merge the PR, to fix the regression asap and I will keep the issue open to add test whenever I have time?

+1 So we don't miss (and in case another contributor wants to pick it up) go ahead and open an issue and throw a **TODO** in the code w/ a link to the issue.

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@nknize backport to 2.0, wdyt?

**Comment by nknize** [comment]
> backport to 2.0, wdyt?

yes

**Comment by jainankitk** [comment]
> don't worry about the TODO in the code (they're often overlooked and rarely taken out).. let's just open a low hanging fruit issue to track the test.

@nknize Thank you for promptly merging this fix. Created separate issue for adding test https://github.com/opensearch-project/OpenSearch/issues/3384

**Comment by dblock** [comment]
> It's up to you if you want to add a test to make sure the `maxConcurrentRequestsPerNode` member variable keeps the value. I don't think it's necessary and will likely require you to add a getter method just for the test.

FWIW, I don't agree, it's a bug, the value here isn't propagating properly in some scenario, so we should have a test. Otherwise I'll accidentally change it back to 1 and nothing will break.

**Comment by jainankitk** [comment]
> FWIW, I don't agree, it's a bug, the value here isn't propagating properly in some scenario, so we should have a test. Otherwise I'll accidentally change it back to 1 and nothing will break.

I agree with @dblock that we must have test (not optional) for preventing this regression from happening again. Though, I agree with @nknize to not hold the check-in back for test if it takes few days to get the tests in. This code is not new, but rather artifact of regression due to other commit.

**Comment by nknize** [comment]
> I'll accidentally change it back to 1 and nothing will break.

Nothing should break. `1` is a valid value. 

> the value here isn't propagating properly in some scenario

 The value was straight hard coded to `1`.

While the test should be as simple as ensuring the value matches the input, we need to avoid relaxing modifiers just for tests. So that needs a little more thought. It can wait to not hold up the fix and addressed in a follow up.

**Comment by Bukhtawar** [comment]
@nknize Totally agree. Sure 1 is a valid value however we cannot allow the change to be reverted by a future commit for the same reason that it was tagged as a BUG. 
I am glad we have a follow up issue but what I am afraid is if it doesn't get picked up now unlikely we would see that getting picked up in near future

**Comment by nknize** [comment]
> if it doesn't get picked up now unlikely we would see that getting picked up in near future

That's a fair concern. Label as a good first issue and high severity and it shouldn't linger. @jainankitk do you also want to assign it to yourself to prioritize it now that the fix is merged?

**Comment by jainankitk** [comment]
I took first stab at it and after spending some time came up with below assertion. I liked this approach as we are not adding relaxing modifiers just for testing. Unfortunately, none of our tests trigger this code path at all! :( So, I guess this is going to take more time than expected.

```
diff --git a/server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java b/server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
index 1d6d3f284d5..40070827082 100644
--- a/server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
+++ b/server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
@@ -152,6 +152,7 @@ abstract class AbstractSearchAsyncAction<Result extends SearchPhaseResult> exten
         // on a per shards level we use shardIt.remaining() to increment the totalOps pointer but add 1 for the current shard result
         // we process hence we add one for the non active partition here.
         this.expectedTotalOps = shardsIts.totalSizeWith1ForEmpty();
+        assert maxConcurrentRequestsPerNode == request.getMaxConcurrentShardRequests() || maxConcurrentRequestsPerNode == shardsIts.size();
         this.maxConcurrentRequestsPerNode = maxConcurrentRequestsPerNode;
         // in the case were we have less shards than maxConcurrentRequestsPerNode we don't need to throttle
         this.throttleConcurrentRequests = maxConcurrentRequestsPerNode < shardsIts.size();
```

**Pull request merged**
