### PR TITLE
Upgrading Joda version

### PR DESCRIPTION
**Pull request by saratvemulapalli**
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>

### Description
Joda was a standard implementation for versions < Java 8. 
Since Java 8, we use `Java.time` but we still use Joda for BWC to talk to old nodes. 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kartg — APPROVED** [review]
Looks straightforward 😄 You're good to go once Gradle check passes

**Comment by saratvemulapalli** [comment]
@reta you've made a PR to remove deprecated methods. [1]
I see we introduced Joda for BWC, but its been a while since we've supported Java 8. 
Is it safe to remove this compatibility wrapper since we are with JDK 17 on 3.0 which at the most should be compatible with OpenSearch 2.0.  

[1] https://github.com/opensearch-project/OpenSearch/pull/3346

**Comment by saratvemulapalli** [comment]
> * https://build.ci.opensearch.org/job/gradle-check/741/

```
Tests with failures:
 - org.opensearch.common.time.DateUtilsTests.testTimezoneIds
```
Looks very related. Will take a look.

**Review by dreamer-89 — APPROVED** [review]

**Comment by reta** [comment]
> @reta you've made a PR to remove deprecated methods. [1] I see we introduced Joda for BWC, but its been a while since we've supported Java 8.
> 
> Is it safe to remove this compatibility wrapper since we are with JDK 17 on 3.0 which at the most should be compatible with OpenSearch 2.0 ? Are there any reasons why we shouldn't?
> 
> [1] #3346

@saratvemulapalli apologies for the delay (was off this week), I think we could consider removing Joda compatibility wrapper. I don't see any reasons to keep it.

**Comment by saratvemulapalli** [comment]
> > @reta you've made a PR to remove deprecated methods. [1] I see we introduced Joda for BWC, but its been a while since we've supported Java 8.
> > Is it safe to remove this compatibility wrapper since we are with JDK 17 on 3.0 which at the most should be compatible with OpenSearch 2.0 ? Are there any reasons why we shouldn't?
> > [1] #3346
> 
> @saratvemulapalli apologies for the delay (was off this week), I think we could consider removing Joda compatibility wrapper. I don't see any reasons to keep it.

No worries. Thanks @reta. I would like to pick this up. 
I'll open an issue.

**Pull request merged**
