### PR TITLE
backport 1.2.5 to main branch

### PR DESCRIPTION
**Pull request by abhinavGupta16**
Signed-off-by: Abhinav Gupta <abhng@amazon.com>

### Description
Backport `1.2.5` to main branch - https://github.com/opensearch-project/OpenSearch/pull/2052
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nknize — CHANGES_REQUESTED** [review]
Both changes were already pushed to the main branch. Odd that it's showing these as valid changes?

**Comment by abhinavGupta16** [comment]
> Both changes were already pushed to the main branch. Odd that it's showing these as valid changes?

@nknize - I think you pushed changes were pushed minutes before I raised the PR! o_O 

Even I don't know why it's not showing a conflict here. 

Closing this PR

**Comment by dblock** [comment]
> Even I don't know why it's not showing a conflict here.

Probably PR made off a non-rebased branch?

**Comment by abhinavGupta16** [comment]
> > Even I don't know why it's not showing a conflict here.
> 
> Probably PR made off a non-rebased branch?

The source branch is not up to date with `main`, but it does make the change on the same line number.

**Pull request closed without merging**
