### PR TITLE
Bump forbiddenapis from 3.0 to 3.2 in /buildSrc (#2113)

### PR DESCRIPTION
**Pull request by VachaShah**
Backport https://github.com/opensearch-project/OpenSearch/commit/3faeec8c53058a5f8cc9d7a2e645fe7c9a1d48da from https://github.com/opensearch-project/OpenSearch/pull/2113

### CODE REVIEW

**Comment by VachaShah** [comment]
start gradle check

**Comment by VachaShah** [comment]
start gradle check

**Comment by dblock** [comment]
This one is known:

```
> Task :server:test

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.cluster.routing.allocation.IndexShardHotSpotTests.testSkewedClusterScaleOut" -Dtests.seed=BFA446B37EA49C28 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=zh-HK -Dtests.timezone=Asia/Sakhalin -Druntime.java=17

org.opensearch.cluster.routing.allocation.IndexShardHotSpotTests > testSkewedClusterScaleOut FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([BFA446B37EA49C28:6BC0F8D096CF37CD]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.cluster.routing.allocation.IndexShardHotSpotTests.testSkewedClusterScaleOut(IndexShardHotSpotTests.java:66)

```

https://github.com/opensearch-project/OpenSearch/issues/2091

**Comment by dblock** [comment]
start gradle check

**Comment by VachaShah** [comment]
> 

```
* What went wrong:
Execution failed for task ':distribution:docker:buildDockerImage'.
> A failure occurred while executing org.opensearch.gradle.docker.DockerBuildTask$DockerBuildAction
   > Process 'command 'docker'' finished with non-zero exit value 1
```

#2023

**Comment by VachaShah** [comment]
start gradle check

**Review by dblock — APPROVED** [review]

**Pull request merged**
