### PR TITLE
Disable seg-rep for fuzzy filter postings upgrade IT

### PR DESCRIPTION
**Pull request by mgodwan**
### Description
Test is flaky as seg-rep is causing issues during lucene codec upgrade. There is a separate test for seg-rep and upgrade. Disabling seg-rep in the fuzzy filter tests

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by shwetathareja** [comment]
@mgodwan with your change also, the integ test is failing.

**Comment by mgodwan** [comment]
> @mgodwan with your change also, the integ test is failing.

Yes, I hadn't removed the assertion which verified all nodes have same segments in seg-rep mode. Verifying the doc count now only similar to other indexing tests with doc-rep mode.
Tests passed locally over 50 times.
Will monitor the ongoing checks on the PR

**Comment by mgodwan** [comment]
Failing test:

```
Tests with failures:
 - org.opensearch.remotestore.RemoteIndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing

```

This is marked flaky here: https://github.com/opensearch-project/OpenSearch/issues/9191

**Comment by mgodwan** [comment]
Test modified in this PR has passed: https://build.ci.opensearch.org/job/gradle-check/33366/testReport/org.opensearch.upgrades/IndexingIT/

**Review by shwetathareja — APPROVED** [review]

**Comment by mch2** [comment]
@mgodwan am not opposed to this change but would like to understand more on the failure and where this differs with the segrep specific test. Do you have a link to a failed check due to codec upgrade with segrep? I would expect the segrep test to have similar flakiness then as the test is not currently setting the shard movement strategy to ensure primary shards move last.

**Comment by mgodwan** [comment]
@mch2 you can use this gradle check run to see the failure: https://build.ci.opensearch.org/job/gradle-check/33349/console

Essentially, the failure was due to primary shard writing segments with Lucene99Codec and replica on the older OS version node being unable to read the same

```
»  Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene99' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene95, Lucene80, Lucene84, Lucene86, Lucene87, Lucene70, Lucene90, Lucene91, Lucene92, Lucene94]
```

**Pull request merged**
