### PR TITLE
[Feature/Identity] Merge remote-tracking branch 'origin/main' into feature/identity

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Merges latest changes from main into feature/identity.

CHANGELOG check should be ignored.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwperks** [comment]
Any idea why `Execution failed for task ':test:fixtures:azure-fixture:composeUp'` is failing?

**Comment by peternied** [comment]
```
> Exit-code 1 when calling /usr/bin/docker-compose, stdout: Step 1/5 : FROM ubuntu:18.04
  18.04: Pulling from library/ubuntu
  Digest: sha256:a3765b4d74747b5e9bdd03205b3fbc4fa19a02781c185f97f24c8f4f84ed7bbf
  Status: Downloaded newer image for ubuntu:18.04
   ---> 5d2df19066ac
  Step 2/5 : RUN apt-get update -qqy
   ---> Running in 9239f3a00055
  [91mW: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Connection failed [IP: 185.125.190.39 80]
  W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.36), connection timed out Could not connect to security.ubuntu.com:80 (185.125.190.39), connection timed out
  W: Some index files failed to download. They have been ignored, or old ones used instead.
  [0mRemoving intermediate container 9239f3a00055
   ---> b0f9217eac76
  Step 3/5 : RUN apt-get install -qqy openjdk-11-jre-headless
   ---> Running in 29a6455fa26b
  [91mE: Unable to correct problems, you have held broken packages.
  [0m

```

Network issue :(

**Comment by peternied** [comment]
I've restarted the job - @cwperks let me know if you've got a successful check locally and you'd like me to merge into the feature branch even if we don't have a passing run here.

**Comment by peternied** [comment]
@cwperks This looks like a failure that should be addressed:

```
2> REPRODUCE WITH: ./gradlew ':sandbox:modules:identity:internalClusterTest' --tests "org.opensearch.identity.BasicAuthIT.testBasicAuthSuccess" -Dtests.seed=B5EC5026418ADE05 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ja -Dtests.timezone=Asia/Ulaanbaatar -Druntime.java=19
  2> org.opensearch.client.ResponseException: method [GET], host [http://127.0.0.1:46871/], URI [/_cluster/health], status line [HTTP/1.1 401 Unauthorized]
    {"error":{"root_cause":[{"type":"exception","reason":"Authentication failed"}],"type":"exception","reason":"Authentication failed"},"status":401}
        at __randomizedtesting.SeedInfo.seed([B5EC5026418ADE05:3CCCAD60723EE246]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:384)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:354)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:329)
        at app//org.opensearch.identity.BasicAuthIT.testBasicAuthSuccess(BasicAuthIT.java:35)
```

**Comment by cwperks** [comment]
Thank you @peternied. Looking into the failure now.

**Comment by cwperks** [comment]
@peternied The test passes for me locally. @DarshitChanpura filed an issue to look into optimizing node bootstrap for identity which will make the test more stable: https://github.com/opensearch-project/OpenSearch/issues/6175

**Pull request merged**
