### PR TITLE
Rename package 'o.o.action.support.master' to 'o.o.action.support.clustermanager'

### PR DESCRIPTION
**Pull request by tlfeng**
### Description
Replace `master` terminology by `cluster manager` in the public Java APIs to support inclusive language.
The PR deal with the only package name in the repository.

- Rename package `org.opensearch.action.support.master` to `org.opensearch.action.support.clustermanager`.
- Replace `Master` to  `ClusterManager` for all the classes in the package, including all the references to the classes.

The above changes are done by the [Rename refactoring](https://www.jetbrains.com/help/idea/rename-refactorings.html) feature of IntelliJ IDEA, so that both the definition and reference can be renamed.

For an easier review, the rename of class names in the package is located at https://github.com/opensearch-project/OpenSearch/pull/3556/files#diff-2cc8ed7ea18e1fe657578d25badfb9b858659971c84c5f4f6e74f481098b82a1 in the file change list, starting with the class `AcknowledgedRequest`.

To keep the git history of the files with name `master` in the new files with name `cluster manager`, I have to put renaming and deprecating classes in 2 separate Pull Requests, and then the 2 PRs will result 2 separate git commits after PR merged.

The next PR will be like: https://github.com/tlfeng/OpenSearch/commit/e484e0f5225ae337cc0521f3427d5ace413ee1ec
Add the old `master` usage back, and deprecate them.

### Issues Resolved
The first PR for issue https://github.com/opensearch-project/opensearch/issues/3542 .
The issue will be resolved by following 2 PRs: deprecate the classes with and deprecate methods/variables that contains "master" in the names.
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tlfeng** [comment]
In log 5958:
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" -Dtests.seed=8717BDA4121AAE4E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-CA -Dtests.timezone=Africa/Addis_Ababa -Druntime.java=17

org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT > testHighWatermarkNotExceeded FAILED
    java.lang.AssertionError: Mismatching shard routings: []
    Expected: a collection with size <1>
         but: collection size was <0>
        at __randomizedtesting.SeedInfo.seed([8717BDA4121AAE4E:6E365C1692DC67A0]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.lambda$assertBusyWithDiskUsageRefresh$5(DiskThresholdDeciderIT.java:362)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1049)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.assertBusyWithDiskUsageRefresh(DiskThresholdDeciderIT.java:355)
        at org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded(DiskThresholdDeciderIT.java:188)
```

In log 5959:
The same test failure
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" -Dtests.seed=3D6C62AF22C0F847 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sr-RS -Dtests.timezone=Pacific/Majuro -Druntime.java=17
...
```

**Comment by tlfeng** [comment]
In log 5972:
```

**Comment by reta** [comment]
@tlfeng this is good but breaking change, we probably should not target 2.1.0 but 3.0.0 only, wdyt?

**Comment by tlfeng** [comment]
In log 5994:
```
org.opensearch.lucene.index.ShuffleForcedMergePolicyTests > testDiagnostics FAILED
    java.lang.AssertionError: 
    Expected: a value greater than <2>
         but: <2> was equal to <2>
        at __randomizedtesting.SeedInfo.seed([1161A2BF9C23F5EE:241F7C459E731AC7]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.lucene.index.ShuffleForcedMergePolicyTests.testDiagnostics(ShuffleForcedMergePolicyTests.java:81)

  2> NOTE: reproduce with: gradlew test --tests ShuffleForcedMergePolicyTests.testDiagnostics -Dtests.seed=1161A2BF9C23F5EE -Dtests.badapples=true -Dtests.locale=sk -Dtests.timezone=America/Lower_Princes -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

**Comment by tlfeng** [comment]
@reta Thank your for the review.
My plan is to support the public Java classes/method in both new name "cluster manager" and old name "master" in version 2.1 . Finally the change is backwards compatible, not a traditional breaking change.
However there will be 2 Pull Requests to achieve the compatibility:
1. Rename the definition and all reference to the public classes or methods, from "master" to "cluster manager"
2. Add the "master" usages back, let the "master" class extends "cluster manager" class, and mark it deprecated.

To keep the git history of the files with name master in the new files with name cluster manager, I have to put renaming and deprecating classes in 2 separate Pull Requests, and then the 2 PRs will result 2 separate git commits after PR merged.

Having 2 PRs will have a sense of separation, but this is the only way to keep the git history in the class with new name, while deprecating the class with old name. I will try to merge the 2 PRs in one day, so that won't affect the compatibility in any snapshot builds.

The next PR will be like: https://github.com/tlfeng/OpenSearch/commit/e484e0f5225ae337cc0521f3427d5ace413ee1ec
Add the old master usage back, and deprecate them.

**Comment by tlfeng** [comment]
Haven't seen any test failure in my local `./gradlew check` run, so re-trigger the check.

**Comment by reta** [comment]
> The next PR will be like: [tlfeng@e484e0f](https://github.com/tlfeng/OpenSearch/commit/e484e0f5225ae337cc0521f3427d5ace413ee1ec)
> Add the old master usage back, and deprecate them.

Got it, thanks @tlfeng, it makes sense !

**Review by reta — APPROVED** [review]

**Comment by tlfeng** [comment]
@reta Thank you so much for reviewing the huge code change! I planned to rely on my colleagues to review it, but you gave me a big surprise!

**Pull request merged**
