### PR TITLE
Integrate with https://jitpack.io/

### PR DESCRIPTION
**Pull request by vrozov**
### Description
Integrate with jitpack.io for publishing maven artifacts
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [+] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I'm A-OK with this. Sign your PR?

**Comment by vrozov** [comment]
The commit is GPG signed, does it require additional signoff?

**Comment by dblock** [comment]
> The commit is GPG signed, does it require additional signoff?

Yeah the DCO check above is failing because it also wants `-s`. IANAL for why.

**Comment by dblock** [comment]
Also, I am looking at https://jitpack.io/#vrozov/opensearch/, but doesn't look like it ran. Does this actually work?

**Comment by vrozov** [comment]
Please see https://jitpack.io/com/github/vrozov/OpenSearch/beea913193/build.log

**Pull request closed without merging**
