### PR TITLE
OpenJDK Update (April 2023 Patch releases)

### PR DESCRIPTION
**Pull request by reta**
### Description
OpenJDK Update (April 2023 Patch releases): OpenJDK 20.0.1 /  17.0.7+7 / 11.0.19+7

### Related Issues
Resolves #[7252], depends on https://github.com/opensearch-project/opensearch-build/pull/3457

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
Keeping a draft for now, Linux/ppc64le is not yet released

**Comment by reta** [comment]
Linux/ppc64le is available now, no blockers anymore except CI

**Review by scrawfor99 — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
This is ready to be merged now.
* https://github.com/opensearch-project/opensearch-build/issues/3425 completed now.
Thanks.

**Comment by peterzhuamazon** [comment]
Jenkins is failing on 3.x build due to this PR not merged yet 😄 
https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/7871/pipeline/129

**Comment by reta** [comment]
> Jenkins is failing on 3.x build due to this PR not merged yet 😄 https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/7871/pipeline/129

@peterzhuamazon I will revert the 3.0.0 to JDK-19, we are still blocked by `ppc64le` distributions not being available

**Comment by peterzhuamazon** [comment]
Still waiting: https://adoptium.net/temurin/releases/?version=20

**Comment by reta** [comment]
@dblock @peterzhuamazon not so good news [1], the  Linux/ppc64le, Linux/s390x, Linux/arm32 and AIX/ppc64 won't be released for 20.0.1+9, I will try to preserve the older one for those while moving everything else to JDK-20.0.1+9

[1] https://github.com/adoptium/temurin-build/issues/3371

**Comment by peterzhuamazon** [comment]
So @reta how do we move forward at this point?
Switch back to nightly builds of 20?
Thanks.

**Comment by reta** [comment]
> Switch back to nightly builds of 20?

@peterzhuamazon yes, when it is merged, we could use JDK-20 in 3.0.0 manifest

**Comment by reta** [comment]
@dblock @andrross mind taking a look? thank you

**Review by dblock — APPROVED** [review]

**Review by scrawfor99 — APPROVED** [review]

**Comment by dhrubo-os** [comment]
Just curious to know why are we updating to Java 20, when most updated gradle version 8.1.1 doesn't have support for it?

https://docs.gradle.org/current/userguide/compatibility.html

**Comment by reta** [comment]
> Just curious to know why are we updating to Java 20, when most updated gradle version 8.1.1 doesn't have support for it yet?

@dhrubo-os 8.1.x supports JDK-20, there are issues with Kotlin DSL (afaik, [1]) which we are not affecting us anyhow

[1] https://github.com/gradle/gradle/issues/23488

**Pull request merged**
