### PR TITLE
Change the "Master" nomenclature

### PR DESCRIPTION
**Pull request by sharp-pixel**
### Description
Replace `master` by `leader` in the context of master node and by `main` in the context of master git branch when applicable.

**Warning:** Causes breaking changes in the API `_cat/master` => `_cat/leader` and cluster configuration parameters

Needs discussion and validation for these breaking changes.
 
### Issues Resolved
Solves #472
 
### Check List
- [ x ] New functionality includes testing.
  - [ x ] All tests pass
- [ x ] New functionality has been documented.
  - [ x ] New functionality has javadoc added
- [ x ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by stockholmux** [comment]
I am 100% behind this PR. I know this issue was discussed prior to being made public - I thought there was even an associated issue although I can't find it.

**Comment by dansimpson** [comment]
The only concern I have with this change is that is breaks some APIs. In a perfect world, this would be a deprecation warning first, and then at a later date, after all the libraries are caught up, the change is made.

If 1.0.0 has API compatibility with Elasticsearch, it lowers the barrier of adoption for folks coming from Elasticsearch and Elasticsearch libraries. These APIs are probably not involved in many of the customers hot paths, but Elasticsearch was really good about backwards compatibility, deprecation, and I think that improves the developer experience.

Maybe there is a way to rewrite the parameter names from old to new, with deprecation warnings, and for the rest handlers, perhaps adding support for both paths, with the intent of removing in a future version.

**Comment by dblock** [comment]
+1 on the spirit of this PR, but I do think we should preserve backward compatibility, what's involved in doing that here?

**Comment by stockholmux** [comment]
I think a middle ground might be to have two user facing APIs: one with new terminology and the other as a deprecated terminology similar to what @dansimpson is saying. By, say, 2.0 the 'm' word is gone fully from APIs.

We document the new terminology so anyone starting off with OpenSearch never starts using the 'm' word.

Mark internal facing uses of the 'm' as a future change and no new code should contain the old terminology. Attack internal changes as the code modified.

(These are my views as a white dude in Canada - other voices are welcome to disagree and tell me I'm flat out wrong)

**Comment by sharp-pixel** [comment]
I agree, breaking things directly is not a good idea, Java class and variable renaming is not a problem, but we should handle both configuration options and APIs.
What's involved is duplicating the API endpoints and adding more tests to check both terminologies, and adding some warning for deprecation in the server logs when a deprecated configuration parameter is used.
So you see anything else?

**Comment by morsik** [comment]
Apart from my personal opinions about this very stupid policically-correct change which I already wrote [here](https://github.com/opensearch-project/OpenSearch/issues/472) - `leader` is **totally wrong** here. ES master is not "leader" of anything. Master is meant do to some job, not lead other nodes to do something.

> The master node is responsible for lightweight cluster-wide actions such as creating or deleting an index, tracking which nodes are part of the cluster, and deciding which shards to allocate to which nodes. It is important for cluster health to have a stable master node.

Please read documentation first (and context that it's used in!)  before even trying to do such stupid changes.

**Comment by stockholmux** [comment]
@sharp-pixel The configuration options are a good point. I imagine the will need to be a startup deprecation notice. My understanding that providing an alternate route for external facing APIs is not a heavy lift.

**Comment by dblock** [comment]
<strike>stupid</strike> -> unnecessary or incorrect or something else

I am sympathetic to @morsik saying that leader/follower may not be the right nomenclature for OpenSearch; do we have any thoughts on `primary` and `secondary`?

**Comment by peternied** [comment]
To me the existing nomenclature and technical utility have the following characteristics:
1) Authoritative decision maker
2) Allocation of data storage
3) System meta-state storage

> I am sympathetic to @morsik saying that leader/follower may not be the right nomenclature for OpenSearch; do we have any thoughts on `primary` and `secondary`?

Primary comes close (1, 2) - but I have trouble separating its ties to systems where the data storage is on the primary.  It can mislead the underlying architecture since all data is on the nodes.

* `Leader`, `Governor`, `Delegator`, `Controller`, `Manager` - All function highly on (1, 2)
* `Allocator`, `Assigner`, `Router` - Good performance around (2), with some (3)

The problem I run into with all of these terms is that they are often used so they become suffixes to the name, {Domain}{Suffix} e.g. "HttpRequestRouter", "ThreadDelegator", "ScenarioTestLeader"

`ClusterManager` lands the best for me on all (1,2,3).  I think the term works for single node clusters, as a bonus.

**Comment by dblock** [comment]
> Primary comes close (1, 2) - but I have trouble separating its ties to systems where the data storage is on the primary. It can mislead the underlying architecture since all data is on the nodes.

That's a very good point.

**Comment by muralikpbhat** [comment]
Technically, there is a leader election (so it is definitely 'leading' the leader eligible nodes) and it may be ok to call it leader. However, I agree the functionality of master is not well represented in that and also if we have different approach in future to decide the leader rather than election, the name leader will become inappropriate. Internally, java classes and docs around master responsibilities are named as 'cluster coordination'. So it might be best to call it 'ClusterCoordinator'? I would have preferred it to be one word, but calling it just 'Coordinator' is conflicting with coordinator nodes which is responsible for fanout.

**Comment by tlfeng** [comment]
Hi @sharp-pixel, we have got a plan to replace the non-inclusive term "master" (https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995), could you please take a look at the plan and modify your PR?
To sum up,
1. Could you use `clustermanager` to replace `master`? We think it describes the responsibility for the "master" node.
2. We would like to resolve the issue #1548 as the first step, so please split your PR to have one that only replacing the "master" where the backwards compatibility won't be impacted, and those without touching APIs or settings.
3. Then resolving the issue #1549 as the next step to make duplicate APIs to keep the backwards compatibility.

Look forward to hearing from you soon. Thank you! 👍

**Comment by sharp-pixel** [comment]
Hi, I will start working on proposed changes. Thanks for constructive
input!

**Comment by tlfeng** [comment]
Hi @sharp-pixel. could you please share any plan or progress on this issue?

**Pull request closed without merging**
