### PR TITLE
Restore support for Java 8 for RestClient

### PR DESCRIPTION
**Pull request by reta**
### Description
Restore support for Java 8 for RestClient. There are still community asks for 2.x clients compatible with Java 8 baseline. The issue has worsen recently due to breaking changes in 2.x baseline (https://github.com/opensearch-project/OpenSearch/pull/5902, https://github.com/opensearch-project/OpenSearch/pull/9082), runtime replacement 1.x vs 2.x is not transparent anymore (causes compile time issues). 

### Related Issues
Part of https://github.com/opensearch-project/opensearch-java/issues/156

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Amazing! Is this enough to ensure that we don't break it in the future?

**Comment by dblock** [comment]
👏

**Comment by praveenchandna** [comment]
Hello 
Java 8 support is getting added in the OpenSearch "Java Client" or "Java high-level REST client" ?
In which release it will be available ? Any timelines ?

Thanks !!

**Comment by reta** [comment]
> Java 8 support is getting added in the OpenSearch "Java Client" or "Java high-level REST client" ?

It is added to OpenSearch Rest Client (not "Java high-level REST client" ), for the OpenSearch "Java Client" - the change in under review https://github.com/opensearch-project/opensearch-java/pull/767

**Comment by praveenchandna** [comment]
Hello 
Here in the above reply you mentioned "OpenSearch Rest Client", to which client you are referring it to ? As per the list of clients in the below webpage I didn't found that. 
https://opensearch.org/docs/latest/clients/

Java 8 support is restored in all which clients ?

Thanks !!

**Comment by reta** [comment]
> Here in the above reply you mentioned "OpenSearch Rest Client", to which client you are referring it to ?

Hello @praveenchandna, this is the Rest Client from the OpenSearch core [1], which is one of the transports used by OpenSearch Java Client [2]. Thank you.

[1] https://github.com/opensearch-project/OpenSearch/tree/main/client/rest
[2] https://opensearch.org/docs/latest/clients/java/#installing-the-client-using-restclient-transport

**Comment by Hrvojeee** [comment]
Hi @reta , please some help since I see your name all over the place so must probably know; with the newly released opensearch-java 2.9.0 I was under the impression that I would be able to use the client in a Java 8 project. When I include the newly deployed artifact https://central.sonatype.com/artifact/org.opensearch.client/opensearch-java and try to instantiate either the Rest Client transport or the AwsSdk2Transport per docs https://opensearch.org/docs/latest/clients/java/#installing-the-client-using-restclient-transport , my project compiles fine against Java 8 but when I run the app with Java8 I get this:
`nested exception is java.lang.UnsupportedClassVersionError: org/opensearch/client/util/ObjectBuilder has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
Was the opensearch-java compiled with JDK11 or I'm doing something wrong or I missed the whole point of the Java8 support feature?

**Comment by reta** [comment]
> Was the opensearch-java compiled with JDK11 or I'm doing something wrong or I missed the whole point of the Java8 support feature?

Hi @Hrvojeee , no you should not be missing the point here - your JDK-8 project should be working fine with `opensearch-java`  as of `2.9.0`. Do you mind sharing your dependencies tree? From the  `opensearch-java`  side, the JVM bytecode is JDK-8 (class file versions is 52.0), as `javap` shows:

```
$ javap  -v -classpath  ~/.m2/repository/org/opensearch/client/opensearch-java/2.9.0/opensearch-java-2.9.0.jar org/opensearch/client/util/ObjectBuilder
```

```
  Last modified Feb 22, 2024; size 252 bytes
  SHA-256 checksum 53575abaabe221f3ecaad3363e74a8090048ca517590a716cb09df9894811e12                                                                                                                                                                                                                                                                   
  Compiled from "ObjectBuilder.java"
public interface org.opensearch.client.util.ObjectBuilder<T extends java.lang.Object> 
  minor version: 0
  major version: 52
  flags: (0x0601) ACC_PUBLIC, ACC_INTERFACE, ACC_ABSTRACT
  this_class: #1                          // org/opensearch/client/util/ObjectBuilder 
  super_class: #2                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 1, attributes: 2
```

**Comment by Hrvojeee** [comment]
Ok this is embarrassing, did not try javap to confirm. I must have had some older version of the opensearch-java lib on my classpath. When i did some mvn cleans its working fine. Sorry, stupid question, and thanks for the response!

**Pull request merged**
