### PR TITLE
Revert "Optimize remote state stale file deletion (#13131)"

### PR DESCRIPTION
**Pull request by reta**
This reverts commit b9befaa12524744ffe71d3f12699cb27cb8fca5e.

### Description
Introduces new flaky tests https://github.com/opensearch-project/OpenSearch/issues/13968

### Related Issues
Reverting #13131

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@andrross @dblock reverting due to new flaky tests, @sachinpkale  @shiv0408 please resubmit when flakyness is understood and eliminated.

**Review by andrross — APPROVED** [review]

**Review by kotwanikunal — APPROVED** [review]

**Comment by shiv0408** [comment]
@reta rather than reverting the whole change, can we disable the test instead? I [found the reason](https://github.com/opensearch-project/OpenSearch/issues/13968#issuecomment-2148307668) for flakiness and we can discuss how we can modify the test to accommodate that. Does necessarily need to revert the whole change.

**Comment by reta** [comment]
> @reta rather than reverting the whole change, can we disable the test instead? I [found the reason](https://github.com/opensearch-project/OpenSearch/issues/13968#issuecomment-2148307668) for flakiness and we can discuss how we can modify the test to accommodate that. Does necessarily need to revert the whole change.

@shiv0408 the nature of the failure is unknown - either impl is not stable or test is not stable, please spend more time on the change and resubmit it.

**Comment by reta** [comment]
> Reverting this commit will just bring another flaky test #12798, which was removed as part of this.
> If we can wait for a day to merge this, I would rather want to raise a fix for the test.

I will reopen the issue than, thanks for heads up

**Comment by reta** [comment]
> ❌ Gradle check result for [4bdac24](https://github.com/opensearch-project/OpenSearch/commit/4bdac246f380e478cd28cd3b9e59b00c2e521967): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/39736/)

https://github.com/opensearch-project/OpenSearch/issues/10314

**Review by andrross — APPROVED** [review]

**Pull request merged**
