### PR TITLE
Remove type mapping from document index API

### PR DESCRIPTION
**Pull request by dreamer-89**
### Description
This commit removes type mapping from Index Rest API end-point. 
 
### Issues Resolved
[2010](https://github.com/opensearch-project/OpenSearch/issues/2010)
Parent: [1940](https://github.com/opensearch-project/opensearch/issues/1940)

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dreamer-89** [comment]
Build docker image failure which seems to be impacting all recent Gradle check runs.

Failure message
```
> Task :distribution:docker:buildDockerImage FAILED
Exec output and error:
| Output for docker:Sending build context to Docker daemon  223.8MB

| Step 1/27 : FROM centos:8 AS builder
|  ---> 5d0da3dc9764
| Step 2/27 : RUN set -eux ;     tini_bin="" ;     case "$(arch)" in         aarch64) tini_bin='tini-arm64' ;;         x86_64)  tini_bin='tini-amd64' ;;         *) echo >&2 ; echo >&2 "Unsupported architecture $(arch)" ; echo >&2 ; exit 1 ;;     esac ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin} ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin}.sha256sum ;     sha256sum -c ${tini_bin}.sha256sum ;     rm ${tini_bin}.sha256sum ;     mv ${tini_bin} /tini ;     chmod +x /tini
|  ---> Running in 47fa6fd08ea9
| [91m+ tini_bin=
| + case "$(arch)" in
| [0m[91m++ arch
| [0m[91m+ tini_bin=tini-amd64
| + curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64

```

**Comment by owaiskazi19** [comment]
> Build docker image failure which seems to be impacting all recent Gradle check runs.
> 
> Failure message
> 
> ```
> > Task :distribution:docker:buildDockerImage FAILED
> Exec output and error:
> | Output for docker:Sending build context to Docker daemon  223.8MB
> 
> | Step 1/27 : FROM centos:8 AS builder
> |  ---> 5d0da3dc9764
> | Step 2/27 : RUN set -eux ;     tini_bin="" ;     case "$(arch)" in         aarch64) tini_bin='tini-arm64' ;;         x86_64)  tini_bin='tini-amd64' ;;         *) echo >&2 ; echo >&2 "Unsupported architecture $(arch)" ; echo >&2 ; exit 1 ;;     esac ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin} ;     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/${tini_bin}.sha256sum ;     sha256sum -c ${tini_bin}.sha256sum ;     rm ${tini_bin}.sha256sum ;     mv ${tini_bin} /tini ;     chmod +x /tini
> |  ---> Running in 47fa6fd08ea9
> | �[91m+ tini_bin=
> | + case "$(arch)" in
> | �[0m�[91m++ arch
> | �[0m�[91m+ tini_bin=tini-amd64
> | + curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64
> ```

The above issue is fixed in https://github.com/opensearch-project/OpenSearch/pull/2024. Can you rebase with latest main and try again? Thanks.

**Comment by dreamer-89** [comment]
Another flaky test failure.
[Log](https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Checks/job/Gradle_Check/2300/artifact/gradle_check_2300.log)

```
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.cluster.routing.MovePrimaryFirstTests.testClusterGreenAfterPartialRelocation" -Dtests.seed=C3DD9E18AA9C799E -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=id-ID -Dtests.timezone=Asia/Barnaul -Druntime.java=17
  2> java.lang.AssertionError: timed out waiting for green state
        at __randomizedtesting.SeedInfo.seed([C3DD9E18AA9C799E:9017FA7D81D8068A]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureColor(OpenSearchIntegTestCase.java:985)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:924)
        at org.opensearch.test.OpenSearchIntegTestCase.ensureGreen(OpenSearchIntegTestCase.java:913)
        at org.opensearch.cluster.routing.MovePrimaryFirstTests.testClusterGreenAfterPartialRelocation(MovePrimaryFirstTests.java:124)
  2> NOTE: leaving temporary files on disk at: /var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/server/build/testrun/test/temp/org.opensearch.cluster.routing.MovePrimaryFirstTests_C3DD9E18AA9C799E-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {index_uuid=Lucene84, type=Lucene84}, docValues:{}, maxPointsInLeafNode=2007, maxMBSortInHeap=6.26240016618465, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=id-ID, timezone=Asia/Barnaul
  2> NOTE: Linux 5.4.0-1045-aws amd64/Eclipse Adoptium 17.0.2 (64-bit)/cpus=72,threads=1,free=404328640,total=536870912
  2> NOTE: All tests run in this JVM: [BinaryDocValuesRangeQueryTests, AddVotingConfigExclusionsResponseTests, SnapshotStatusTests, GetDataStreamsRequestTests, GetComposableIndexTemplateRequestTests, MultiGetResponseTests, SearchPhaseControllerTests, TransportReplicationAllPermitsAcquisitionTests, ShardStartedClusterStateTaskExecutorTests, DataStreamMetadataTests, MovePrimaryFirstTests]
```

**Review by andrross — APPROVED** [review]

**Comment by dblock** [comment]
start gradle check

**Comment by dreamer-89** [comment]
Another transient failure `RecoveryFromGatewayIT.testReuseInFileBasedPeerRecovery`
```
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.gateway.RecoveryFromGatewayIT.testReuseInFileBasedPeerRecovery" -Dtests.seed=A154F46F2F012504 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=it-IT -Dtests.timezone=Asia/Chongqing -Druntime.java=17
  2> java.lang.AssertionError: shard [test][0] on node [node_t1] has pending operations:
     --> RetentionLeaseBackgroundSyncAction.Request{retentionLeases=RetentionLeases{primaryTerm=1, version=1501, leases={peer_recovery/onm_qT7fR0eVZIivwO1xDw=RetentionLease{id='peer_recovery/onm_qT7fR0eVZIivwO1xDw', retainingSequenceNumber=939, timestamp=1644413489370, source='peer recovery'}, peer_recovery/4jOrhJ6BST2DAZ4OOOV5vw=RetentionLease{id='peer_recovery/4jOrhJ6BST2DAZ4OOOV5vw', retainingSequenceNumber=939, timestamp=1644413489370, source='peer recovery'}}}, shardId=[test][0], timeout=1m, index='test', waitForActiveShards=0}
    	at org.opensearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:248)
    	at org.opensearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:3232)
    	at org.opensearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:1116)
    	at org.opensearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:433)
    	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
    	at org.opensearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:377)
```

**Review by reta — APPROVED** [review]

**Pull request merged**
