### PR TITLE
Fix issue that deprecated setting 'cluster.initial_master_nodes' is not identified in node bootstrap check

### LINKED ISSUE #2769: [BUG] Cluster bootstrap fails due to `cluster.initial_master_nodes` -> `cluster.initial_cluster_manager_nodes` renaming
**Describe the bug**
https://github.com/opensearch-project/opensearch-build/issues/1624#issuecomment-1088861343

**To Reproduce**
1. Checkout [this branch](https://github.com/cliu123/security/tree/upgrade_to_opensearch_2.0.0_alpha1)
2. Run `./gradlew clean assemble` to build security plugin
3. Security plugin artifact gets generated in `build/distributions` folder.
4. Install security plugin on [OpenSearch 2.0.0-alpha1](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.0-alpha1/latest/linux/x64/builds/opensearch/dist/opensearch-min-2.0.0-alpha1-linux-x64.tar.gz)
5. Start cluster

**Expected behavior**
Cluster starts successfully.

**Plugins**
security plugin

**Error log**
```
opensearch-2.0.0-alpha1 % bin/opensearch
[2022-04-05T08:14:46,609][INFO ][o.o.n.Node               ] [smoketestnode] version[2.0.0-alpha1], pid[65264], build[tar/8b4d8797dd99c4cd1d9ebb4d4a189b2603ee9b62/2022-04-04T19:55:10.117456775Z], OS[Mac OS X/10.15.7/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/14.0.2/14.0.2+12-46]
[2022-04-05T08:14:46,611][INFO ][o.o.n.Node               ] [smoketestnode] JVM home [/Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home], using bundled JDK [false]
[2022-04-05T08:14:46,611][INFO ][o.o.n.Node               ] [smoketestnode] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/var/folders/7w/pf_kzhln0f17f4mv1_79nrjhzkss_b/T/opensearch-3856531273804745298, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/Users/cgliu/git/opensearch-2.0.0-alpha1, -Dopensearch.path.conf=/Users/cgliu/git/opensearch-2.0.0-alpha1/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2022-04-05T08:14:46,612][WARN ][o.o.n.Node               ] [smoketestnode] version [2.0.0-alpha1] is a pre-release version of OpenSearch and is not suitable for production
[2022-04-05T08:14:47,377][WARN ][stderr                   ] [smoketestnode] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2022-04-05T08:14:47,378][WARN ][stderr                   ] [smoketestnode] SLF4J: Defaulting to no-operation (NOP) logger implementation
[2022-04-05T08:14:47,378][WARN ][stderr                   ] [smoketestnode] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2022-04-05T08:14:48,205][INFO ][o.o.i.r.ReindexPlugin    ] [smoketestnode] ReindexPlugin reloadSPI called
[2022-04-05T08:14:48,207][INFO ][o.o.i.r.ReindexPlugin    ] [smoketestnode] Unable to find any implementation for RemoteReindexExtension
[2022-04-05T08:14:48,217][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [aggs-matrix-stats]
[2022-04-05T08:14:48,218][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [analysis-common]
[2022-04-05T08:14:48,218][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [geo]
[2022-04-05T08:14:48,218][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [ingest-common]
[2022-04-05T08:14:48,218][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [ingest-geoip]
[2022-04-05T08:14:48,218][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [ingest-user-agent]
[2022-04-05T08:14:48,218][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [lang-expression]
[2022-04-05T08:14:48,219][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [lang-mustache]
[2022-04-05T08:14:48,219][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [lang-painless]
[2022-04-05T08:14:48,219][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [mapper-extras]
[2022-04-05T08:14:48,219][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [opensearch-dashboards]
[2022-04-05T08:14:48,219][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [parent-join]
[2022-04-05T08:14:48,219][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [percolator]
[2022-04-05T08:14:48,219][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [rank-eval]
[2022-04-05T08:14:48,220][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [reindex]
[2022-04-05T08:14:48,220][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [repository-url]
[2022-04-05T08:14:48,220][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded module [transport-netty4]
[2022-04-05T08:14:48,220][INFO ][o.o.p.PluginsService     ] [smoketestnode] loaded plugin [opensearch-security]
[2022-04-05T08:14:48,263][INFO ][o.o.e.NodeEnvironment    ] [smoketestnode] using [1] data paths, mounts [[/System/Volumes/Data (/dev/disk1s1)]], net usable_space [242.8gb], net total_space [465.6gb], types [apfs]
[2022-04-05T08:14:48,263][INFO ][o.o.e.NodeEnvironment    ] [smoketestnode] heap size [1gb], compressed ordinary object pointers [true]
[2022-04-05T08:14:48,306][INFO ][o.o.n.Node               ] [smoketestnode] node name [smoketestnode], node ID [Gva382quT6OyioZIY4Palw], cluster name [opensearch], roles [cluster_manager, remote_cluster_client, data, ingest]
[2022-04-05T08:14:50,865][INFO ][o.o.t.NettyAllocator     ] [smoketestnode] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=256kb, factors={opensearch.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=1mb, heap_size=1gb}]
[2022-04-05T08:14:50,935][INFO ][o.o.d.DiscoveryModule    ] [smoketestnode] using discovery type [zen] and seed hosts providers [settings]
[2022-04-05T08:14:51,167][WARN ][o.o.g.DanglingIndicesState] [smoketestnode] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
[2022-04-05T08:14:51,327][INFO ][o.o.n.Node               ] [smoketestnode] initialized
[2022-04-05T08:14:51,327][INFO ][o.o.n.Node               ] [smoketestnode] starting ...
[2022-04-05T08:14:51,435][INFO ][o.o.t.TransportService   ] [smoketestnode] publish_address {192.168.1.70:9300}, bound_addresses {[::]:9300}
[2022-04-05T08:14:51,739][INFO ][o.o.b.BootstrapChecks    ] [smoketestnode] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_cluster_manager_nodes / cluster.initial_master_nodes] must be configured
ERROR: OpenSearch did not exit normally - check the logs at /Users/cgliu/git/opensearch-2.0.0-alpha1/logs/opensearch.log
[2022-04-05T08:14:51,746][INFO ][o.o.n.Node               ] [smoketestnode] stopping ...
[2022-04-05T08:14:51,758][INFO ][o.o.n.Node               ] [smoketestnode] stopped
[2022-04-05T08:14:51,758][INFO ][o.o.n.Node               ] [smoketestnode] closing ...
[2022-04-05T08:14:51,766][INFO ][o.o.n.Node               ] [smoketestnode] closed
```

### PR DESCRIPTION
**Pull request by tlfeng**
### Description

Problem:
The deprecated setting `cluster.initial_master_nodes` is not identified in the node bootstrap check.
Although the setting is configured in `opensearch.yml`, the node bootstrap check still fails with message `the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_cluster_manager_nodes / cluster.initial_master_nodes] must be configured`.

Change:
- Add `INITIAL_MASTER_NODES_SETTING` back to accepted discovery settings in `discoveryIsConfigured()`, which used in node bootstrap check.
- Add unit tests back about the setting `cluster.initial_master_nodes` to test it's an accepted discovery setting.
- Make an exception message more accurate to show the configured setting name of the 2 setting.

Reason:
The PR https://github.com/opensearch-project/OpenSearch/pull/2463 deprecated the setting `cluster.initial_master_nodes`, and added alternative setting `cluster.initial_cluster_manager_nodes`.
The bug is caused by the the setting `INITIAL_MASTER_NODES_SETTING` was replaced by `INITIAL_CLUSTER_MANAGER_NODES_SETTING` directly in the [code](https://github.com/opensearch-project/OpenSearch/blob/e9bd78c59c5be94e90f6b154f8f2d8f27215b5e3/server/src/main/java/org/opensearch/cluster/coordination/ClusterBootstrapService.java#L160), while they should both exist. The method `discoveryIsConfigured()` is used [in this place](https://github.com/opensearch-project/OpenSearch/blob/e9bd78c59c5be94e90f6b154f8f2d8f27215b5e3/server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java#L770).

Background:
Bootstrapping a cluster is required when an OpenSearch cluster starts up for the very first time. In development mode (single node without joining a cluster), with no discovery settings configured, this is automatically performed by the nodes themselves.

### Issues Resolved
Resolve #2769 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tlfeng** [comment]
In log 4229:
```
> Task :plugins:repository-azure:internalClusterTest

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:internalClusterTest' --tests "org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles" -Dtests.seed=3F29D4B383D73056 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=el -Dtests.timezone=Europe/Skopje -Druntime.java=17

org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests > testSnapshotWithLargeSegmentFiles FAILED
    java.lang.AssertionError: 
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.repositories.blobstore.OpenSearchBlobStoreRepositoryIntegTestCase.assertSuccessfulRestore(OpenSearchBlobStoreRepositoryIntegTestCase.java:532)
        at org.opensearch.repositories.blobstore.OpenSearchBlobStoreRepositoryIntegTestCase.assertSuccessfulRestore(OpenSearchBlobStoreRepositoryIntegTestCase.java:528)
```
```
> Task :plugins:repository-azure:internalClusterTest

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:internalClusterTest' --tests "org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests.testRequestStats" -Dtests.seed=3F29D4B383D73056 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=el -Dtests.timezone=Europe/Skopje -Druntime.java=17

org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests > testRequestStats FAILED
    java.lang.AssertionError: 
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.repositories.blobstore.OpenSearchBlobStoreRepositoryIntegTestCase.assertSuccessfulRestore(OpenSearchBlobStoreRepositoryIntegTestCase.java:532)
        at org.opensearch.repositories.blobstore.OpenSearchBlobStoreRepositoryIntegTestCase.assertSuccessfulRestore(OpenSearchBlobStoreRepositoryIntegTestCase.java:528)
```

**Comment by tlfeng** [comment]
start gradle check

**Comment by tlfeng** [comment]
In log 4234:
Same as above
```
> Task :plugins:repository-azure:internalClusterTest

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:internalClusterTest' --tests "org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles" -Dtests.seed=822244C1A3DDD3CD -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-IQ -Dtests.timezone=Europe/Monaco -Druntime.java=17
```
```
REPRODUCE WITH: ./gradlew ':plugins:repository-azure:internalClusterTest' --tests "org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests.testRequestStats" -Dtests.seed=822244C1A3DDD3CD -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-IQ -Dtests.timezone=Europe/Monaco -Druntime.java=17
```

**Comment by tlfeng** [comment]
start gradle check

**Review by dblock — APPROVED** [review]
Good enough for now, but I worry that this "setting exists?" may not work correctly in a distributed scenario. Thus this whole business of "what's the name of the actual setting, the new `INITIAL_CLUSTER_MANAGER_NODES_SETTING` vs. the deprecated `INITIAL_MASTER_NODES_SETTING` should be implemented as a method on Setting itself, e.g. `setting.getActualNameOfSettingInConfigurationOrSomethingLikeThat()`, and return the name of the setting used as fallback in the case that it has a fallback, and its own name otherwise. Possible?

**Comment by tlfeng** [comment]
Hi @dblock Thanks for your suggestion! I take it into account, and will discuss with the team to find a solution to prevent such issue happens in other recent deprecated settings.

**Comment by dblock** [comment]
> Hi @dblock Thanks for your suggestion! I will take it into account, and will discuss with the team to find a solution to prevent such issue happens in other recent deprecated settings.

To be clear, I am suggesting the following:

### current

```
String initialClusterManagerSettingName = INITIAL_CLUSTER_MANAGER_NODES_SETTING.exists(settings)
            ? INITIAL_CLUSTER_MANAGER_NODES_SETTING.getKey()
            : INITIAL_MASTER_NODES_SETTING.getKey();
```

### new

```
String initialClusterManagerSettingName = INITIAL_CLUSTER_MANAGER_NODES_SETTING.getName(settings)
```

**Pull request merged**
