### PR TITLE
[WIP] Adds automation script to add issue labels to PR

### LINKED ISSUE #8199: Pull requests to inherit labels from parent issues
**Is your feature request related to a problem? Please describe.**
Currently, we have 100+ open PRs and they are increasing week over week. It could be much easier for people to review PRs if they have clear component labels. For example if the PR has `indexing` label, then maintainers and contributors who have indexing experience can pick those related PRs and review/merge them easily.

**Describe the solution you'd like**
PR can automatically inherit labels from the associated issues. Once contributor connect PR to an issues, an automatic workflow will be triggered to copy labels from the issue to the PR.

There should be a logic to exclude some labels like `untriaged`

cc: @andrross @dblock

### PR DESCRIPTION
**Pull request by DarshitChanpura**
### Related Issues
Resolves #8199

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
This is pretty cool! What do you think about implementing this as a marketplace GitHub Action instead so we can reuse it across opensearch-project?

**Comment by DarshitChanpura** [comment]
> This is pretty cool! What do you think about implementing this as a marketplace GitHub Action instead so we can reuse it across opensearch-project?

I've forked it out of a pre-exisiting workflow: https://github.com/michalvankodev/copy-issue-labels
I'm still trying to figure out how to make sure it can be used across forks. I have it running on my own repo: https://github.com/DarshitChanpura/security/pull/8 but having trouble getting it working for this PR and related one in security: https://github.com/opensearch-project/security/pull/3331

**Comment by DarshitChanpura** [comment]
@dblock I'm getting this error:
```
Run DarshitChanpura/copy-issue-labels@v1.0.0
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/DarshitChanpura/copy-issue-labels/v1.0.0/webpack:/copy-issue-labels/node_modules/@octokit/request/dist-node/index.js:66:1
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/opensearch-project/OpenSearch/actions/runs/6125060737/job/16626278354?pr=9914#step:2:10)6:5)
```
which tells me that the GITHUB token I'm using doesn't have enough access rights. Possible solution would be to create a token specific to this PR so it can be used across forks

**Comment by kotwanikunal** [comment]
This was resolved with #10010

**Pull request closed without merging**
