### PR TITLE
Bump min java version to 11

### PR DESCRIPTION
**Pull request by nknize**
To support upgrading to lucene 9.x the minimum java version is bumped to java 11.

### CODE REVIEW

**Comment by reta** [comment]
I expected that :D, @nknize, the other thoughts, do you think we could follow Elasticsearch (and many other projects) lead and go full speed on JDK-17? I have crunched JDK vendors for support timelines, JDK-11 is set for EOL in 2023 / 2024, wdyt?

**Review by reta — APPROVED** [review]

**Review by reta — CHANGES_REQUESTED** [review]
Please update https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md

**Comment by nknize** [comment]
> go full speed on JDK-17

I'm fine w/ that. I think it'll be more involved than bumping the minimum compatibility variables? Since lucene 9 requires a minimum of 11 we can merge this PR and tackle the bump to min 17 in a separate PR?

**Comment by reta** [comment]
> > go full speed on JDK-17
> 
> I'm fine w/ that. I think it'll be more involved than bumping the minimum compatibility variables? Since lucene 9 requires a minimum of 11 we can merge this PR and tackle the bump to min 17 in a separate PR?

:+1: No objections, do you want me to open an issue for discussion? 
Than you!

**Comment by andrross** [comment]
> go full speed on JDK-17

Maybe continue this discussion in #1689?

**Comment by reta** [comment]
@dblock afaik we need to merge it to unblock Lucene 9 migration.

**Review by andrross — APPROVED** [review]
This seems right to me. We can merge this into main to unblock the Lucene 9 work while continuing the discussion of whether to go all the way to 17.

We probably want to backport this (11 being minimum supported version) to the 1.x as well given that Java 8 is going end of life.

**Comment by reta** [comment]
> We probably want to backport this (11 being minimum supported version) to the 1.x as well given that Java 8 is going end of life.

This one I wish but not sure, by all means it will be a breaking change for some users, from operations perspective (there are still compelling cases for CMS GC apparently), but out commitment to 1.x - no breaking changes.

**Comment by dblock** [comment]
I'd like this PR to include changes to the developer guide and other READMEs purging mentions of Java 8.

**Comment by reta** [comment]
> I'd like this PR to include changes to the developer guide and other READMEs purging mentions of Java 8.

@dblock already asked in here https://github.com/opensearch-project/OpenSearch/pull/1977#pullrequestreview-864016539

**Comment by dblock** [comment]
> > I'd like this PR to include changes to the developer guide and other READMEs purging mentions of Java 8.
> 
> @dblock already asked in here [#1977 (review)](https://github.com/opensearch-project/OpenSearch/pull/1977#pullrequestreview-864016539)

I have no original ideas, just repeating what other smart people say hoping no one notices :)

**Comment by reta** [comment]
> > > I'd like this PR to include changes to the developer guide and other READMEs purging mentions of Java 8.
> > 
> > 
> > @dblock already asked in here [#1977 (review)](https://github.com/opensearch-project/OpenSearch/pull/1977#pullrequestreview-864016539)
> 
> I have no original ideas, just repeating what other smart people say hoping no one notices :)

Oops sorry :+1: , emphasizing the importance of keeping docs in sync :bow:

**Comment by dblock** [comment]
Superseded with https://github.com/opensearch-project/OpenSearch/pull/2025

**Pull request closed without merging**
