### PR TITLE
[Backport 2.x] Support batch ingestion in bulk API (#12457) (#13306)

### PR DESCRIPTION
**Pull request by chishui**
### Description

Backport https://github.com/opensearch-project/OpenSearch/commit/1219c568248fafa479d67a1eaa6e3e2d9748701e from https://github.com/opensearch-project/OpenSearch/pull/13306.

This PR is to enable batch ingestion in _bulk API. Please refer to https://github.com/opensearch-project/OpenSearch/issues/12457 for proposal and discussion.

### Related Issues

Closes https://github.com/opensearch-project/OpenSearch/issues/12457.

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by chishui** [comment]
@dblock please help merge this backport

**Comment by dblock** [comment]
> ❌ Gradle check result for [587aed7](https://github.com/opensearch-project/OpenSearch/commit/587aed77f9c093236597c6d9a4ded4668fe8bb00): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38065/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.gateway.RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction](https://build.ci.opensearch.org/job/gradle-check/38065/testReport/junit/org.opensearch.gateway/RecoveryFromGatewayIT/testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction/)

https://github.com/opensearch-project/OpenSearch/issues/13307


[org.opensearch.remotemigration.RemoteReplicaRecoveryIT.testReplicaRecovery](https://build.ci.opensearch.org/job/gradle-check/38065/testReport/junit/org.opensearch.remotemigration/RemoteReplicaRecoveryIT/testReplicaRecovery/)

https://github.com/opensearch-project/OpenSearch/issues/8919

**Comment by dblock** [comment]
> ❌ Gradle check result for [587aed7](https://github.com/opensearch-project/OpenSearch/commit/587aed77f9c093236597c6d9a4ded4668fe8bb00): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38066/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.indices.CacheStatsAPIIndicesRequestCacheIT.testNullLevels {p0={"opensearch.experimental.feature.pluggable.caching.enabled":"true"}}](https://build.ci.opensearch.org/job/gradle-check/38066/testReport/junit/org.opensearch.indices/CacheStatsAPIIndicesRequestCacheIT/testNullLevels__p0___opensearch_experimental_feature_pluggable_caching_enabled___true___/)

https://github.com/opensearch-project/OpenSearch/issues/13458

**Comment by dblock** [comment]
> ❌ Gradle check result for [587aed7](https://github.com/opensearch-project/OpenSearch/commit/587aed77f9c093236597c6d9a4ded4668fe8bb00): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38070/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards](https://build.ci.opensearch.org/job/gradle-check/38070/testReport/junit/org.opensearch.cluster.allocation/ClusterRerouteIT/testDelayWithALargeAmountOfShards/)

https://github.com/opensearch-project/OpenSearch/issues/10558

**Comment by chishui** [comment]
> [org.opensearch.ratelimitting.admissioncontrol.AdmissionForClusterManagerIT.testAdmissionControlResponseStatus](https://build.ci.opensearch.org/job/gradle-check/38077/testReport/junit/org.opensearch.ratelimitting.admissioncontrol/AdmissionForClusterManagerIT/testAdmissionControlResponseStatus/)

https://github.com/opensearch-project/OpenSearch/issues/13045

> [org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testIndexReopenClose](https://build.ci.opensearch.org/job/gradle-check/38077/testReport/junit/org.opensearch.remotestore/SegmentReplicationUsingRemoteStoreIT/testIndexReopenClose/)

https://github.com/opensearch-project/OpenSearch/issues/13084

**Comment by chishui** [comment]
> ❌ Gradle check result for https://github.com/opensearch-project/OpenSearch/commit/587aed77f9c093236597c6d9a4ded4668fe8bb00: [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38085/)

[org.opensearch.ratelimitting.admissioncontrol.AdmissionForClusterManagerIT.testAdmissionControlResponseStatus](https://build.ci.opensearch.org/job/gradle-check/38077/testReport/junit/org.opensearch.ratelimitting.admissioncontrol/AdmissionForClusterManagerIT/testAdmissionControlResponseStatus/)

https://github.com/opensearch-project/OpenSearch/issues/13045

[org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testIndexReopenClose](https://build.ci.opensearch.org/job/gradle-check/38077/testReport/junit/org.opensearch.remotestore/SegmentReplicationUsingRemoteStoreIT/testIndexReopenClose/)

https://github.com/opensearch-project/OpenSearch/issues/13084

**Pull request merged**
