### PR TITLE
Initial draft on slow task execution

### LINKED ISSUE #985: Log slow bulk and search task execution across various node interactions
## Problem
If there are problems in the system occurring due to slow IO or Network on a particular node the rest of the nodes also get impacted waiting on the response. There is no easy way to know from logs if a particular node has gone slow, either while doing a live DEBUG or figuring out the root cause of the incident. The current slow logs serves into providing shard-level details on slow query or index. At present there is no way to know the coordinator view

## Proposal
We can attach a listener to the `TransportAction` corresponding to bulk and search and log warning of the execution time of the bulk task eg shard bulk/primary/replication tasks if they take beyond a reasonable threshold with the below details. 

From the below details we could atleast make out there is a slow replication action(time in queue + time spent in the replica indexing) on the problematic node. Since we know the task id and the parent id we should be able to get a break down of the entire bulk request. 

Note since the replica action took longer the primary and the coordinator action will have a corresponding log line. Looking at all of them holistically we should be able to reason and pin point about the slow action 

```
[2021-06-17T01:19:48,596][INFO ][c.a.c.e.logger           ] [dcdce07c4314957e5cc0e43d5cd60511] Action [indices:data/write/bulk[s][r]] on node [dcdce07c4314957e5cc0e43d5cd60511], 
task id : [26786394294], parent task id : [26795282749] took longer than the threshold of [60]s
```

### PR DESCRIPTION
**Pull request by Bukhtawar**
### Description
Initial draft on slow task execution
 
### Issues Resolved
#985 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Bukhtawar Khan <bukhtawa@amazon.com>

### CODE REVIEW

**Comment by dblock** [comment]
@Bukhtawar what shall we do with this?

**Comment by Bukhtawar** [comment]
I'll find sometime to wrap this up. Sorry for the delay.

**Comment by dreamer-89** [comment]
@Bukhtawar : Are you still working on this ?

**Comment by kotwanikunal** [comment]
> @Bukhtawar : Are you still working on this ?
> 
> Please let us know if any help is needed. This is pending for a very long time, and would like to bring this to a closure.

@Bukhtawar Any updates on this?

**Comment by CEHENKLE** [comment]
@Bukhtawar Poke on this...

**Comment by Bukhtawar** [comment]
Sorry folks, I will get to this in a couple of weeks.

**Comment by CEHENKLE** [comment]
@Bukhtawar How goes?  Is this still an active PR for you?

Thanks!

**Comment by Bukhtawar** [comment]
Resolving this for now. Will reopen when I get back to it

**Pull request closed without merging**
