### PR TITLE
Add a link to the flakey test dev guide.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>

### Description

Added some text to help the contributor with next steps on CI failures.

### Issues Resolved

Closes https://github.com/opensearch-project/OpenSearch/issues/4871.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by owaiskazi19 — APPROVED** [review]

**Comment by dblock** [comment]
```
org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT > test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials} FAILED
    java.lang.AssertionError: Failure at [repository_s3/20_repository_permanent_credentials:152]: expected [2xx] status code but api [snapshot.create] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"invalid_snapshot_name_exception","reason":"[repository_permanent:snapshot-one] Invalid snapshot name [snapshot-one], snapshot with the same name already exists","stack_trace":"InvalidSnapshotNameException[[rep
```

https://github.com/opensearch-project/OpenSearch/issues/2064

**Comment by dblock** [comment]
Again

```
 - org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT.test {yaml=repository_s3/20_repository_permanent_credentials/Try to create repository with broken endpoint override and named client}
 ```

**Comment by peterzhuamazon** [comment]
@dblock please add this to 1.x and 1.3 as well.

Thanks.

**Comment by dblock** [comment]
> @dblock please add this to 1.x and 1.3 as well.
> 
> Thanks.

Will do. I think I want to edit this a bit on main first.

**Pull request merged**
