### PR TITLE
[Backport 2.x] Segment Replication - Update /_cat/segment_replication API with backpressure metrics. (#6674)

### PR DESCRIPTION
**Pull request by mch2**
Manual backport of #6674

### CODE REVIEW

**Review by Rishikesh1159 — APPROVED** [review]

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12555/
> * **CommitID:** [e6f5c91](https://github.com/opensearch-project/OpenSearch/commit/e6f5c9112aba0b481437b90ea9eb47cf27b21a9c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting" -Dtests.seed=89B60E8FE0F69067 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=da -Dtests.timezone=Asia/Kashgar -Druntime.java=17

org.opensearch.cluster.shards.ClusterShardLimitIT > testCreateIndexWithMaxClusterShardSetting FAILED
    java.lang.AssertionError: MaxShardPerCluster 3 should be greater than or equal to MaxShardPerNode 1000
        at __randomizedtesting.SeedInfo.seed([89B60E8FE0F69067:C350FF314DA856DF]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.cluster.shards.ClusterShardLimitIT.setMaxShardLimit(ClusterShardLimitIT.java:750)
        at org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting(ClusterShardLimitIT.java:259)
```

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12551/
> * **CommitID:** [e6f5c91](https://github.com/opensearch-project/OpenSearch/commit/e6f5c9112aba0b481437b90ea9eb47cf27b21a9c)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.opensearch.index.translog.RemoteFSTranslogTests.testConcurrentWriteViewsAndSnapshot" -Dtests.seed=C95CCC85159CEF44 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=pl -Dtests.timezone=Africa/Asmera -Druntime.java=17

org.opensearch.index.translog.RemoteFSTranslogTests > testConcurrentWriteViewsAndSnapshot FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=241, name=writer_1, state=RUNNABLE, group=TGRP-RemoteFSTranslogTests]
        at __randomizedtesting.SeedInfo.seed([C95CCC85159CEF44:ED8535A8CE0B1CC7]:0)

        Caused by:
        java.lang.AssertionError: Expected non-empty readers
            at __randomizedtesting.SeedInfo.seed([C95CCC85159CEF44]:0)
            at org.opensearch.index.translog.RemoteFsTranslog.deleteStaleRemotePrimaryTermsAndMetadataFiles(RemoteFsTranslog.java:398)
            at org.opensearch.index.translog.RemoteFsTranslog.trimUnreferencedReaders(RemoteFsTranslog.java:368)
            at org.opensearch.index.translog.RemoteFSTranslogTests$2.doRun(RemoteFSTranslogTests.java:863)
```

**Comment by Rishikesh1159** [comment]
Looks like test causing gradle check to fail `shards.ClusterShardLimitIT > testCreateIndexWithMaxClusterShardSetting` is not related to this PR. I can reproduce the test failing on opensearch 2.x branch also with seeds: `-Dtests.seed=C95CCC85159CEF44, -Dtests.seed=89B60E8FE0F69067`

**Comment by Rishikesh1159** [comment]
Closing this PR. Another PR:https://github.com/opensearch-project/OpenSearch/pull/6741 manually backported this changes

**Pull request closed without merging**
