### PR TITLE
[Backport 2.x] Allow customization of netty channel handles before and during decompression

### PR DESCRIPTION
**Pull request by cwperks**
Manual backport of #10261 to 2.x.

There are differences in the netty pipeline between main and 2.x (mainly around http2). This PR updates the test to accommodate for the differences.

### CODE REVIEW

**Comment by cwperks** [comment]
@peternied Can you re-run the CI on this PR and get it merged to the 2.x line?

**Comment by peternied** [comment]
@cwperks Could you '+1' existing or create issues for the random failures associated with the first CI run [1]? I've re-trigged the CI run

| Test | Params|
|-|-|
| org.opensearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test | {yaml=pit/10_basic/Delete all}|
| org.opensearch.remotestore.RemoteStoreRefreshListenerIT.testRemoteRefreshRetryOnFailure| |
| org.opensearch.search.scroll.SearchScrollWithFailingNodesIT.testScanScrollWithShardExceptions | {p0={"search.concurrent_segment_search.enabled":"true"}}|
| org.opensearch.search.scroll.SearchScrollWithFailingNodesIT.testScanScrollWithShardExceptions | {p0={"search.concurrent_segment_search.enabled":"false"}}|


- [1] https://build.ci.opensearch.org/job/gradle-check/27244/testReport/

**Comment by peternied** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 2.10.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.10/distribution/archives/linux-tar/build/distributions/opensearch-min-2.10.0-SNAPSHOT-linux-x64.tar.gz

```

**Comment by DarshitChanpura** [comment]
This is blocking 2.12 version bump: https://github.com/opensearch-project/security/pull/3498 which in turn is blocking build on main due to backward-compatibility test expecting 2.12

**Comment by peternied** [comment]
@DarshitChanpura I'm be monitoring this

**Review by peternied — APPROVED** [review]

**Pull request merged**
