### PR TITLE
Manually backport #11060 (Simple regex normalization refactor)

### PR DESCRIPTION
**Pull request by scrawfor99**
### Description
[Describe what this change achieves]

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [ ] ~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by scrawfor99** [comment]
@reta can you mark this 2.11 backport please?

**Comment by reta** [comment]
> @reta can you mark this 2.11 backport please?

@scrawfor99 we need to align with the release team, @bbarani @CEHENKLE please signoff if we are OK bringing this one into 2.11.1, thank you

**Review by bbarani — APPROVED** [review]

**Comment by bbarani** [comment]
I am good with backporting this fix to 2.11 branch to release in 2.11.1 patch version.

**Comment by reta** [comment]
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29786/

https://github.com/opensearch-project/OpenSearch/issues/10154
https://github.com/opensearch-project/OpenSearch/issues/10558

**Comment by reta** [comment]
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/29792/

https://github.com/opensearch-project/OpenSearch/issues/8932
https://github.com/opensearch-project/OpenSearch/issues/11155

**Comment by reta** [comment]
@scrawfor99 `2.11` backport failed :(

**Comment by cwperks** [comment]
@reta @scrawfor99 I opened up a manual backport to 2.11: https://github.com/opensearch-project/OpenSearch/pull/11185

**Pull request merged**
