### PR TITLE
Replaced "master" terminology in Log message

### PR DESCRIPTION
**Pull request by owaiskazi19**
### Description
Replace "master" terminology in Log messages.
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/2539
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
https://github.com/opensearch-project/OpenSearch/issues/1561

**Comment by owaiskazi19** [comment]
start gradle check

**Comment by owaiskazi19** [comment]
https://github.com/opensearch-project/OpenSearch/issues/1703

**Comment by owaiskazi19** [comment]
start gradle check

**Review by nknize — CHANGES_REQUESTED** [review]
Are we skipping the comments as well? I'm seeing the use of `master-eligible` terminology in comments in [AddVotingConfigExclusionsRequest.java](https://github.com/opensearch-project/OpenSearch/pull/2575/files#diff-4001d5f31251773b1eab2cd73efd3b0cc94ed1f822452aacc710b67bf8a32f53), for example (line 57, 69, 78)

Maybe we can clean that here as well?

**Review by nknize — APPROVED** [review]
LGTM

**Pull request merged**
