### PR TITLE
configurable new-line handling in OpenSearchJsonLayout

### LINKED ISSUE #4673: OpenSearchJsonLayout logs newlines in json
**Describe the bug**
Using the OpenSearchJsonLayout for logging out of a docker container adds newlines in the generated json-string when a stack-trace is appended. This makes it unnecessarily hard to process the logs by a line based log-agent.

**To Reproduce**
Use the following log4j2 config: 
```status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = OpenSearchJsonLayout
appender.console.layout.type_name = server

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
```
which generates logs like this:
```
{ ... "cluster.uuid": "KK8EloHiQGCbVCUO3RPkmg", "node.id": "HTVcLMDtRLSgVqq2w5l0UA" ,
"stacktrace": ["java.lang.NullPointerException: Cannot invoke \"String.length()\" because \"other\" is null",
"at org.apache.lucene.search.spell.LevenshteinDistance.getDistance(LevenshteinDistance.java:62)"
...
"at java.lang.Thread.run(Thread.java:833) [?:?]"] }
```

**Expected behavior**
Not adding unnecessary newlines.

The newlines are injected here:
https://github.com/opensearch-project/OpenSearch/blob/10bff0c9f5b9ca78b3dc50f5c704dabf41b9d535/server/src/main/java/org/opensearch/common/logging/JsonThrowablePatternConverter.java

Is there any reason for those or can they get removed?

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04 (docker)

### PR DESCRIPTION
**Pull request by svenso**
### Description
The OpenSearchJsonLayout got some new properties. Primarily to emit compact, linebased json.

### Issues Resolved
#4673 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I like it.

**Comment by dblock** [comment]
Rebase this PR and mark it ready when you're satisfied with it? Fix any CI failures. If the failures are not related to this PR, check whether there's already an issue for those failure, and call it out in a comment.

**Comment by minalsha** [comment]
Thanks @dblock  for the inputs.  @svenso  are you still working on this? do you need any help?

**Comment by dreamer-89** [comment]
@svenso: Are you still working on this PR ?

**Comment by svenso** [comment]
the forbidden api issue & DCO should now be solved.

**Comment by dreamer-89** [comment]
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/12959/
> * **CommitID:** [c5245c1](https://github.com/opensearch-project/OpenSearch/commit/c5245c1a57f8839aa163b276eea3a7aedc0c6ca3)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Is this expected failure, @svenso ? 
```
> Task :qa:logging-config:test

REPRODUCE WITH: ./gradlew ':qa:logging-config:test' --tests "org.opensearch.common.logging.OpenSearchJsonLayoutTests.testEmptyType" -Dtests.seed=A6E8E1607DC1009E -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-NI -Dtests.timezone=Asia/Singapore -Druntime.java=19

org.opensearch.common.logging.OpenSearchJsonLayoutTests > testEmptyType FAILED
    junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([A6E8E1607DC1009E:2F6D8CCF138BC8E9]:0)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2864)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2850)
        at org.opensearch.common.logging.OpenSearchJsonLayoutTests.testEmptyType(OpenSearchJsonLayoutTests.java:48)
```

**Comment by tlfeng** [comment]
The following test failure that occurred in the build No.12999 seems related to the change.
```
REPRODUCE WITH: ./gradlew ':qa:logging-config:integTest' --tests "org.opensearch.qa.custom_logging.CustomLoggingConfigIT.testSuccessfulStartupWithCustomConfig" -Dtests.seed=956E2547DB08797 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=he-IL -Dtests.timezone=Antarctica/Davis -Druntime.java=19

org.opensearch.qa.custom_logging.CustomLoggingConfigIT > testSuccessfulStartupWithCustomConfig FAILED
    java.lang.AssertionError: 
    Expected: a collection containing .*integTest-0.*cluster.uuid.*node.id.*recovered.*cluster_state.*
         but: mismatches were: [was "integTest-0   version[3.0.0-SNAPSHOT], pid[197926], build[tar/1d1de6e20bacdf7e16e18d038c58ab5eba246541/2023-03-28T17:52:20.694180032Z], OS[Linux/5.15.0-1028-aws/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/19.0.2/19.0.2+7]", was "integTest-0   JVM home [/usr/lib/jvm/temurin-19-jdk-amd64], using bundled JDK [false]", was "integTest-0   JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.security.manager=allow, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/var/jenkins/workspace/gradle-check/search/qa/logging-config/build/testclusters/integTest-0/tmp, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=logs, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.security.manager=allow, -Xms512m, -Xmx512m, -ea, -esa, -XX:TieredStopAtLevel=1, -XX:ReservedCodeCacheSize=64m, -XX:MaxDirectMemorySize=268435456, -Dopensearch.path.home=/var/jenkins/workspace/gradle-check/search/distribution/archives/linux-tar/build/install/opensearch-3.0.0-SNAPSHOT, -Dopensearch.path.conf=/var/jenkins/workspace/gradle-check/search/qa/logging-config/build/testclusters/integTest-0/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]", was "integTest-0   version [3.0.0-SNAPSHOT] is a pre-release version of OpenSearch and is not suitable for production", was "integTest-0   ReindexPlugin reloadSPI called", was "integTest-0   Unable to find any implementation for RemoteReindexExtension", was "integTest-0   loaded module [aggs-matrix-stats]", was "integTest-0   loaded module [analysis-common]", was "integTest-0   loaded module [geo]", was "integTest-0   loaded module [ingest-common]", was "integTest-0   loaded module [ingest-geoip]", was "integTest-0   loaded module [ingest-user-agent]", was "integTest-0   loaded module [lang-expression]", was "integTest-0   loaded module [lang-mustache]", was "integTest-0   loaded module [lang-painless]", was "integTest-0   loaded module [mapper-extras]", was "integTest-0   loaded module [opensearch-dashboards]", was "integTest-0   loaded module [parent-join]", was "integTest-0   loaded module [percolator]", was "integTest-0   loaded module [rank-eval]", was "integTest-0   loaded module [reindex]", was "integTest-0   loaded module [repository-url]", was "integTest-0   loaded module [systemd]", was "integTest-0   loaded module [test-delayed-aggs]", was "integTest-0   loaded module [transport-netty4]", was "integTest-0   no plugins loaded", was "integTest-0   Using MemorySegmentIndexInput with Java 19; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false", was "integTest-0   using [1] data paths, mounts [[/ (/dev/root)]], net usable_space [78gb], net total_space [96.7gb], types [ext4]", was "integTest-0   heap size [512mb], compressed ordinary object pointers [true]", was "integTest-0   node name [integTest-0], node ID [4JqEHFjJRzWzVgxMeBbERg], cluster name [integTest], roles [ingest, remote_cluster_client, data, cluster_manager]", was "integTest-0   creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=256kb, factors={opensearch.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=1mb, heap_size=512mb}]", was "integTest-0   using discovery type [zen] and seed hosts providers [settings, file]", was "integTest-0   gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually", was "integTest-0   initialized", was "integTest-0   starting ...", was "integTest-0   publish_address {127.0.0.1:46413}, bound_addresses {[::1]:33177}, {127.0.0.1:46413}", was "integTest-0   max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]", was "integTest-0   startInitialJoin: coordinator becoming CANDIDATE in term 0 (was null, lastKnownLeader was [Optional.empty])", was "integTest-0   expected, but did not find, a dynamic hosts list at [/var/jenkins/workspace/gradle-check/search/qa/logging-config/build/testclusters/integTest-0/config/unicast_hosts.txt]", was "integTest-0   setting initial configuration to VotingConfiguration{4JqEHFjJRzWzVgxMeBbERg}", was "integTest-0   scheduling scheduleNextElection{gracePeriod=0s, thisAttempt=0, maxDelayMillis=100, delayMillis=95, ElectionScheduler{attempt=1, ElectionSchedulerFactory{initialTimeout=100ms, backoffTime=100ms, maxTimeout=10s}}}", was "integTest-0   publish_address {127.0.0.1:34561}, bound_addresses {[::1]:38943}, {127.0.0.1:34561}", was "integTest-0   started", was "integTest-0   scheduleNextElection{gracePeriod=0s, thisAttempt=0, maxDelayMillis=100, delayMillis=95, ElectionScheduler{attempt=1, ElectionSchedulerFactory{initialTimeout=100ms, backoffTime=100ms, maxTimeout=10s}}} starting election", was "integTest-0   scheduling scheduleNextElection{gracePeriod=500ms, thisAttempt=1, maxDelayMillis=200, delayMillis=555, ElectionScheduler{attempt=2, ElectionSchedulerFactory{initialTimeout=100ms, backoffTime=100ms, maxTimeout=10s}}}", was "integTest-0   PreVotingRound{preVotesReceived={}, electionStarted=false, preVoteRequest=PreVoteRequest{sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, currentTerm=0}, isClosed=false} requesting pre-votes from [{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}]", was "integTest-0   PreVotingRound{preVotesReceived={{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}=PreVoteResponse{currentTerm=0, lastAcceptedTerm=0, lastAcceptedVersion=0}}, electionStarted=true, preVoteRequest=PreVoteRequest{sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, currentTerm=0}, isClosed=false} added PreVoteResponse{currentTerm=0, lastAcceptedTerm=0, lastAcceptedVersion=0} from {integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, starting election", was "integTest-0   starting election with StartJoinRequest{term=1,node={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}", was "integTest-0   joinLeaderInTerm: for [{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}] with term 1", was "integTest-0   handleStartJoin: leaving term [0] due to StartJoinRequest{term=1,node={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}", was "integTest-0   attempting to join {integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, minimumTerm=0, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, targetNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}]}", was "integTest-0   successful response to StartJoinRequest{term=1,node={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}} from {integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}", was "integTest-0   handleJoin: added join Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, targetNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}} from [{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}] for election, electionWon=true lastAcceptedTerm=0 lastAcceptedVersion=0", was "integTest-0   handleJoin: election won in term [1] with VoteCollection{votes=[4JqEHFjJRzWzVgxMeBbERg], joins=[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, targetNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}]}", was "integTest-0   handleJoinRequest: coordinator becoming LEADER in term 1 (was CANDIDATE, lastKnownLeader was [Optional.empty])", was "integTest-0   received a join request for an existing node [{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}]", was "integTest-0   elected-as-cluster-manager ([1] nodes joined)[{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true} elect leader, _BECOME_CLUSTER_MANAGER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: cluster-manager node changed {previous [], current [{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}]}", was "integTest-0   received full cluster state version [1] with size [335]", was "integTest-0   no known cluster-manager node, scheduling a retry", was "integTest-0   scheduleNextElection{gracePeriod=500ms, thisAttempt=1, maxDelayMillis=200, delayMillis=555, ElectionScheduler{attempt=2, ElectionSchedulerFactory{initialTimeout=100ms, backoffTime=100ms, maxTimeout=10s}}} not starting election", was "integTest-0   cluster UUID set to [DQSK-4kLQUKgR97ho5GprA]", was "integTest-0   cluster-manager node changed {previous [], current [{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}]}, term: 1, version: 1, reason: Publication{term=1, version=1}", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  publication ended successfully: Publication{term=1, version=1}", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  successfully joined {integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, minimumTerm=0, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}, targetNode={integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}}]}", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  setting findPeersInterval to [1s] as node commission status = [true] for local node [{integTest-0}{4JqEHFjJRzWzVgxMeBbERg}{x9HwXtcITlqbMfKhtQsuJg}{127.0.0.1}{127.0.0.1:46413}{dimr}{testattr=test, shard_indexing_pressure_enabled=true}]", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  received full cluster state version [2] with size [288]", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  publication ended successfully: Publication{term=1, version=2}", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  recovered [0] indices into cluster_state", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  received diff cluster state version [3] with uuid [qgtxMduqRF6Y3kPUZ7FuPw], diff size [139]", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  publication ended successfully: Publication{term=1, version=3}", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  received diff cluster state version [4] with uuid [Y9UI1GWoRcSOUqG6B6KwvA], diff size [139]", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  publication ended successfully: Publication{term=1, version=4}", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  received diff cluster state version [5] with uuid [NtucF1HKSBSc68cYjA1uRg], diff size [139]", was "integTest-0 DQSK-4kLQUKgR97ho5GprA  publication ended successfully: Publication{term=1, version=5}"]
        at __randomizedtesting.SeedInfo.seed([956E2547DB08797:96DD3721CBF83233]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:964)
        at org.junit.Assert.assertThat(Assert.java:930)
        at org.opensearch.qa.custom_logging.CustomLoggingConfigIT.lambda$testSuccessfulStartupWithCustomConfig$0(CustomLoggingConfigIT.java:61)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1060)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1033)
        at org.opensearch.qa.custom_logging.CustomLoggingConfigIT.testSuccessfulStartupWithCustomConfig(CustomLoggingConfigIT.java:59)

**Comment by DarshitChanpura** [comment]
@svenso Would you need any help with this PR to get it across the finish line?

**Pull request closed without merging**
