### PR TITLE
Added support of copying remote directory without specifying whether …

### PR DESCRIPTION
**Pull request by vikasvb90**
### Description
Fixes invalid red flag raised by https://github.com/opensearch-project/OpenSearch/pull/13663

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] ~~New functionality includes testing.~~
  - [x] All tests pass
- [ ] ~~New functionality has been documented.~~
  - [ ] ~~New functionality has javadoc added~~
- [ ] ~~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] ~~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~~
- [ ] ~~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
> ❌ Gradle check result for [9aa2458](https://github.com/opensearch-project/OpenSearch/commit/9aa24587345c19ccc9e7f7f7546eb94ff5cb24c0): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38684/)

https://github.com/opensearch-project/OpenSearch/issues/13667

**Comment by vikasvb90** [comment]
Flaky test failure
```
> Task :server:test

Tests with failures:
 - org.opensearch.search.query.QueryPhaseTests.testQueryTimeoutChecker {p0=0 p1=org.opensearch.search.query.QueryPhase$DefaultQueryPhaseSearcher@652e345}

12999 tests completed, 1 failed, 37 skipped
```
https://github.com/opensearch-project/OpenSearch/issues/9464

**Comment by reta** [comment]
> ❌ Gradle check result for [9aa2458](https://github.com/opensearch-project/OpenSearch/commit/9aa24587345c19ccc9e7f7f7546eb94ff5cb24c0): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38693/)

https://github.com/opensearch-project/OpenSearch/issues/13046

**Comment by reta** [comment]
> ❌ Gradle check result for [2d74206](https://github.com/opensearch-project/OpenSearch/commit/2d74206e7d319ea6a419bca422543bd193e04419): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/38696/)

https://github.com/opensearch-project/OpenSearch/issues/13473
https://github.com/opensearch-project/OpenSearch/issues/11997

**Comment by reta** [comment]
@vikasvb90 we cannot get this pull request passing all the check, the change was reverted, please resubmit the proper backport, thank you

**Pull request closed without merging**
