### PR TITLE
Adding slf4j license header to LoggerMessageFormat.java

### LINKED ISSUE #9879: Licensing of org.opensearch.core.common.logging.LoggerMessageFormat.java
While documenting code i noticed that : 
```libs/core/src/main/java/org/opensearch/core/common/logging/LoggerMessageFormat.java```

 is an almost identical copy of : 
https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java/org/slf4j/helpers/MessageFormatter.java
which is under the MIT License.

It's pretty much a non-issue since, as far as i know, it's not forbidden by the MIT License. But i'm not a licensing expert.

This code have both elasticsearch and opensearch license header (both Apache 2.0)

I wanted to add this in the javadoc :
```
/**
 * Format string for OpenSearch log messages.
 * <p>
 * This class is almost a copy of {@code org.slf4j.helpers.MessageFormatter}<p>
 * The original code is licensed under the MIT License and is available at :
 * <a href="https://github.com/qos-ch/slf4j/blob/7c164fab8d54f823dd55c01a5a839c153f578297/slf4j-api/src/main/java/org/slf4j/helpers/MessageFormatter.java">MessageFormatter.java</a>
 *
 * @opensearch.internal
 */
``` 
 but it's a little bit weird to have this in the javadoc and i'd appreciate some feedback.

Thank you.

### PR DESCRIPTION
**Pull request by hyandell**
### Description
Per #9879, I've added my suggested source header. I've only eyeballed the code (it's a comment being added) and haven't run any compiling/testing. No concerns if folk want to do a different PR for this, but I'm only a brief visitor to these shores.

### Related Issues
- Resolves #9879

### Check List
- [ ] ~New functionality includes testing.~
  - [ ] ~All tests pass~
- [ ] ~New functionality has been documented.~
  - [ ] ~New functionality has javadoc added~
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peternied** [comment]
Thanks for digging into this @hyandell - changes look good to me, I'll see about getting this merged.

**Review by peternied — APPROVED** [review]

**Comment by dblock** [comment]
I presume we need to backport it to active branches, I would do 2.x and 1.x. 
@hyandell looks like you may need to do this by hand

**Comment by hyandell** [comment]
Definitely looking for y'all to manage your backports :) But +1 to applying this on the active branches.

**Comment by dblock** [comment]
@hyandell You'll have to manually backport to 2.x and 1.x, these are active trees.

**Pull request merged**
