### PR TITLE
Adding workflow to auto delete backport merged branches from backport workflow

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
Workflow to automatically delete the branches created by the [backport action ](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/backport.yml) of type `backport/*`.

I will backport this PR to release branches so that the auto delete runs on backport PRs created for those branches.
 
### Issues Resolved
Part 2 of #1962 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Is it possible to put both workflows for backports into backport.yml?

**Comment by VachaShah** [comment]
> Is it possible to put both workflows for backports into backport.yml?

I kept them separate since the backport workflow will run on PRs on the main branch while the delete branch workflow needs to run on backport PRs created on the release branches. WDYT?

**Comment by dblock** [comment]
> > Is it possible to put both workflows for backports into backport.yml?
> 
> I kept them separate since the backport workflow will run on PRs on the main branch while the delete branch workflow needs to run on backport PRs created on the release branches. WDYT?

No strong feelings. My only argument to combine is that when other projects want to introduce the backport process they would need to copy 2 workflows instead of 1.

**Comment by VachaShah** [comment]
> No strong feelings. My only argument to combine is that when other projects want to introduce the backport process they would need to copy 2 workflows instead of 1.

Thats true. This just came to my mind, combining them might not be possible since both the workflows have different `on` to define what kind of events trigger the workflow.

**Review by saratvemulapalli — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]
This works for new backport PRs. 
How about the ones which already exist?

**Comment by dblock** [comment]
@VachaShah Feel free to merge if you're happy with this as is.

**Comment by VachaShah** [comment]
> This works for new backport PRs. How about the ones which already exist?

For the ones that already exist, I will delete them from the PRs. We just updated the setting to allow deletes such branches.

**Comment by VachaShah** [comment]
Auto-backported this PR to 1.x #2065 and the backport branch is auto-deleted after merge.

**Pull request merged**
