### PR TITLE
[Backport 2.x] Add capability to disable source recovery_source for an index (#13590)

### PR DESCRIPTION
**Pull request by navneet1v**
### Description
Backport of the PR: https://github.com/opensearch-project/OpenSearch/pull/13590

### Related Issues
NA

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by navneet1v** [comment]
@reta , @msfroh can I get a review on this backport PR. The automated backport failed.

**Comment by reta** [comment]
> @reta , @msfroh can I get a review on this backport PR. The automated backport failed.

@navneet1v sure, needs https://github.com/opensearch-project/OpenSearch/pull/14072 :(

**Comment by navneet1v** [comment]
> > @reta , @msfroh can I get a review on this backport PR. The automated backport failed.
> 
> @navneet1v sure, needs #14072 :(

Oh. will wait for your PR to be merged and will trigger gradle check again.

**Comment by navneet1v** [comment]
> > Oh. will wait for your PR to be merged and will trigger gradle check again.
> 
> Just went in, please rebase

done

**Comment by navneet1v** [comment]
> ❌ Gradle check result for [628682b](https://github.com/opensearch-project/OpenSearch/commit/628682bfa8292c6558cba94864a0e9854a2c8246): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40208/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

trying 1 more time.

**Comment by navneet1v** [comment]
> ❌ Gradle check result for [7dbc163](https://github.com/opensearch-project/OpenSearch/commit/7dbc1636e566cf928557966a12f4f46ad9c5f35b): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40238/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

trying again.

**Comment by navneet1v** [comment]
> ❌ Gradle check result for [c91a26a](https://github.com/opensearch-project/OpenSearch/commit/c91a26af4e5c33c340999ba93b6d12dc16dccfc9): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40308/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

Flaky test: https://github.com/opensearch-project/OpenSearch/issues/13828

**Comment by andrross** [comment]
> ❌ Gradle check result for [d152e4a](https://github.com/opensearch-project/OpenSearch/commit/d152e4a1f9775f3753092ee583322250bf3b9050): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/40581/)

#12197

**Comment by navneet1v** [comment]
@andrross should I do a force push again to re-run gradle check.. :(

**Comment by navneet1v** [comment]
@andrross, @reta , @msfroh  I can see a successful gradle check. can we merge this PR?

**Review by reta — APPROVED** [review]

**Pull request merged**
