### PR TITLE
[BUG] Fix versioning issues discovered through version bump

### PR DESCRIPTION
**Pull request by nknize**
This PR fixes up the version framework to ensure a smooth version bump across releases.

### CODE REVIEW

**Comment by nknize** [comment]
start gradle check

**Comment by nknize** [comment]
start gradle check

**Review by saratvemulapalli — APPROVED** [review]
Changes look good to me, Thanks @nknize !

**Comment by saratvemulapalli** [comment]
As we discussed this, lets open an issue for having a cleaner way of bumping up versioning in OpenSearch.
Hopefully one day we will not have a hack :)

**Pull request merged**
