### PR TITLE
Support allow_duplicate_keys for json processor

### PR DESCRIPTION
**Pull request by MunifTanjim**
### Description

This is to support creating an ingest pipeline for ECS JSON logs.
Due to how some logging frameworks work, ECS JSON logs may contain duplicate keys. Instead of failing, the JSON parser should be more lenient and prefer the last value.

Ported from https://github.com/elastic/elasticsearch/pull/74956

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by MunifTanjim** [comment]
This is still relevant! @opensearch-ci-bot

**Review by dblock — COMMENTED** [review]
Thanks, not sure how we missed the PR. Please iterate to green.

I don't know much about the xcontent business, maybe @reta can review this? Who else?

**Comment by reta** [comment]
> I don't know much about the xcontent business, maybe @reta can review this? Who else?

Thanks for the pull request @MunifTanjim but we cannot port features from elasticsearch "as-is" without violating license

**Comment by dblock** [comment]
Oh I didn't notice the port from Elastic. That PR is from Jul 6, 2021 which is after 7.10.2 I believe, closing this PR.

Anyone wanting this feature in OpenSearch: please ensure that you're not copying any non-APLv2 code.

**Pull request closed without merging**
