### PR TITLE
[feature/sandboxing branch]Add initial doc for plugin sandboxing

### PR DESCRIPTION
**Pull request by saratvemulapalli**
### Description
Adding initial doc for plugin sandboxing.
 
### Issues Resolved
Part of #1422 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
Looks like its because of changes missing in feature branch vs main.
I'll merge the changes first from main.

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
start gradle check

**Comment by saratvemulapalli** [comment]
@owaiskazi19 DCO is failing because the number of commits is high and out of bounds for the check. 
Once you review it, i'll merge it. Sequential commits should be fine.

**Comment by saratvemulapalli** [comment]
Cancelling this and creating a new feature branch.

**Pull request closed without merging**
