### PR TITLE
[Backport to 2.x] [Segment Replication] - Update replicas to commit SegmentInfos instead of relying on segments_N from primary shards.

### PR DESCRIPTION
**Pull request by dreamer-89**
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/4402 to 2.x

### CODE REVIEW

**Comment by dreamer-89** [comment]
Looks like something is missing. There is only one file change in this backport PR.

**Comment by dreamer-89** [comment]
Java compilation error :(
```
> Task :rest-api-spec:validatePom

        TranslogManager translogManager = engine.translogManager();
> Task :test:framework:compileJava
                                                ^
  symbol:   method translogManager()
  location: variable engine of type Engine

> Task :server:processTestResources
> Task :server:dependencyLicenses
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :test:framework:compileJava

> Task :test:framework:compileJava FAILED
> Task :server:filepermissions
```

**Comment by dreamer-89** [comment]
Java spotless failure.

**Comment by dreamer-89** [comment]
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':distribution:bwc:maintenance:buildBwcLinuxTar'.
> Building 1.3.5 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/maintenance/build/bwc/checkout-1.3/distribution/archives/linux-tar/build/distributions/opensearch-min-1.3.5-SNAPSHOT-linux-x64.tar.gz

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
org.gradle.api.GradleException: Reaper process failed. Check log at /var/jenkins/workspace/gradle-check/search/.gradle/reaper/build-13277/error.log for details
> Reaper process failed. Check log at /var/jenkins/workspace/gradle-check/search/.gradle/reaper/build-13277/error.log for details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org/

BUILD FAILED in 16m 29s
2432 actionable tasks: 2418 executed, 2 from cache, 12 up-to-date
Gradle Check Failed!
```

**Review by mch2 — APPROVED** [review]
thanks for the backport @dreamer-89

**Pull request merged**
