### PR TITLE
[Backport-1.x] Upgrade dependency (#1571)

### PR DESCRIPTION
**Pull request by VachaShah**
* Upgrading guava, commons-io and apache-ant dependencies

Signed-off-by: Vacha <vachshah@amazon.com>

* Adding failureaccess since guava needs it

Signed-off-by: Vacha <vachshah@amazon.com>

### Description
Backport of #1571 
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
start gradle check

**Review by saratvemulapalli — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
@VachaShah/ @zelinh  do we have an update on whitesource?

**Comment by zelinh** [comment]
> @VachaShah / @zelinh do we have an update on whitesource?

No, we haven't heard from them regarding of the update of this issue yet. @bbarani Can we ignore the whitesource check at this time?

**Comment by VachaShah** [comment]
start gradle check

**Comment by VachaShah** [comment]
@zelinh As discussed, I tried to run the WhiteSource scan again but it still fails after 375m each time.

**Comment by zelinh** [comment]
I updated the issue regarding our WhiteSource integration. Please refer to #1593.

**Comment by VachaShah** [comment]
The WhiteSource issue is being tracked in #1593 with the team related to a bigger problem on their end. Can we merge this PR @saratvemulapalli ?

**Pull request merged**
