### PR TITLE
[Backport-1.x] Run Spotless and exclude Checkstyle on server module

### PR DESCRIPTION
**Pull request by owaiskazi19**
Signed-off-by: Owais Kazi <owaiskazi19@gmail.com>

### Description
Backport of https://github.com/opensearch-project/OpenSearch/pull/1380
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by saratvemulapalli** [comment]
> Can one of the admins verify this patch?

@peterzhuamazon not sure whats going with this..

**Comment by owaiskazi19** [comment]
> The original PR has 4085 files while this one has 4080 files, anything missing here?

The main branch has more commits than 1.x branch and 5 more files are added as a part of those commits. I had to remove those files to sync it with the current 1.x branch.

**Comment by tlfeng** [comment]
start gradle check

**Comment by owaiskazi19** [comment]
@nknize we can merge this PR.

**Comment by owaiskazi19** [comment]
> #1397 was merged so this will need a rebase. It's a large change that's likely to impact some pending backport PRs so lets get this one in ASAP.

@nknize we can merge this PR.

**Pull request merged**
