### PR TITLE
Removing unused method from TransportSearchAction

### LINKED ISSUE #3384: [TEST] Missing unit/integration test for validating max concurrent search requests per node
**Describe the bug**
There is no unit/integration test for validating correct value of max concurrent search requests per node. Recent regression was reported for that #3363 

**Expected behavior**
There should be test to validate that the behavior is as expected

**Related PR**
#3364

### PR DESCRIPTION
**Pull request by jainankitk**
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>

### Description
Realized that method itself is unused and the value of max concurrent shards does not matter
 
### Issues Resolved
#3384 #3363 
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by Bukhtawar — COMMENTED** [review]
wow that's interesting, wondering how do we better detect dead code. Do we need a better integration with gradle lint

**Review by nknize — APPROVED** [review]

**Review by Bukhtawar — APPROVED** [review]

**Comment by reta** [comment]
@Bukhtawar @nknize I think we should revert it back folks, this overloaded method `TransportSearchAction::executeRequest` is used by PIT implementation [1] (it is still in feature branch so not straightforward to trace).

[1] https://github.com/opensearch-project/OpenSearch/blob/feature/point_in_time/server/src/main/java/org/opensearch/action/search/CreatePitController.java#L118

**Comment by dblock** [comment]
@reta Does this still need to happen?

**Comment by reta** [comment]
> @reta Does this still need to happen?

It looks like yes, the method is still in use in PIT branch

**Comment by Bukhtawar** [comment]
Thanks for pointing out @reta will revert as needed.

**Pull request merged**
