### PR TITLE
Add 2.18.0 version

### PR DESCRIPTION
**Pull request by reta**
### Description
Add 2.18.0 version

### Related Issues
Needs https://github.com/opensearch-project/OpenSearch/pull/15680 first

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by mch2 — APPROVED** [review]

**Comment by harshavamsi** [comment]
Gradle bwc checks are failing without this since 2.17 is already cut, can we merge this for bwc?

**Comment by harshavamsi** [comment]
@sachinpkale can we merge this?

> ❌ Gradle check result for [36b344c](https://github.com/opensearch-project/OpenSearch/commit/36b344ca0cfc9bc3000b2b2f0e5c1122f41fd7ab): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47049/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

[org.opensearch.index.engine.NRTReplicationEngineTests.testGetSegmentInfosSnapshotPreservesFilesUntilRelease](https://build.ci.opensearch.org/job/gradle-check/47049/testReport/junit/org.opensearch.index.engine/NRTReplicationEngineTests/testGetSegmentInfosSnapshotPreservesFilesUntilRelease/) -- flaky test

**Comment by msfroh** [comment]
If there's a flaky test, we need to fix the flaky tests.

**Review by jainankitk — APPROVED** [review]

**Comment by shiv0408** [comment]
Build failed again
```
* What went wrong:
Execution failed for task ':distribution:bwc:minor:buildBwcLinuxTar'.
> Building 2.18.0 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/minor/build/bwc/checkout-2.x/distribution/archives/linux-tar/build/distributions/opensearch-min-2.18.0-SNAPSHOT-linux-x64.tar.gz

```

**Comment by shiv0408** [comment]
@jainankitk  @mch2 Can someone help in retriggering the gradle check?

**Comment by harshavamsi** [comment]
> @jainankitk @mch2 Can someone help in retriggering the gradle check?

gradle check I think will keep failing until build manifest is updated

**Comment by jainankitk** [comment]
> > @jainankitk @mch2 Can someone help in retriggering the gradle check?
> 
> gradle check I think will keep failing until build manifest is updated

Does anyone know how to trigger manifest update? @peterzhuamazon did it last time for 2.17 release - https://github.com/opensearch-project/OpenSearch/pull/15712#issuecomment-2330687134

**Comment by shiv0408** [comment]
> > > > @jainankitk @mch2 Can someone help in retriggering the gradle check?
> > > 
> > > 
> > > gradle check I think will keep failing until build manifest is updated
> > 
> > 
> > Does anyone know how to trigger manifest update? @peterzhuamazon did it last time for 2.17 release - [#15712 (comment)](https://github.com/opensearch-project/OpenSearch/pull/15712#issuecomment-2330687134)
> 
> [opensearch-project/opensearch-build@0d951c5](https://github.com/opensearch-project/opensearch-build/commit/0d951c563a9283d51387eb09c70df39c05d12b9d) -- I think this is what happens, its triggered by the CI

We need to trigger this CI then, all my PRs are failing because of this bwc failure.

**Comment by Bukhtawar** [comment]
I think we should avoid bumping up versions on the last day of code freeze. Is there a way we could revert earlier commits to unblock?

**Comment by harshavamsi** [comment]
> I think we should avoid bumping up versions on the last day of code freeze. Is there a way we could revert earlier commits to unblock?

https://github.com/opensearch-project/OpenSearch/pull/15680 -- this is the problem right now. 2.18 is in 2.x

**Comment by shiv0408** [comment]
> I think we should avoid bumping up versions on the last day of code freeze. Is there a way we could revert earlier commits to unblock?

Reverting #15680 will unblock mp

**Comment by msfroh** [comment]
> Reverting https://github.com/opensearch-project/OpenSearch/pull/15680 will unblock mp

Reverting will mean that we'll go back to two different branches linked to the same version, despite being in different states.

There should be a **very** quick series of steps:
1. Cut the release branch.
2. Update the 2.x branch
3. Update the main branch.

It's hard to do that when everyone is cramming changes into the main, 2.x, and release branches, though.

**Comment by shiv0408** [comment]
> > Reverting #15680 will unblock mp
> 
> Reverting will mean that we'll go back to two different branches linked to the same version, despite being in different states.
> 
> There should be a **very** quick series of steps:
> 
>     1. Cut the release branch.
> 
>     2. Update the 2.x branch
> 
>     3. Update the main branch.
> 
> 
> It's hard to do that when everyone is cramming changes into the main, 2.x, and release branches, though.
> 
> (See [opensearch-project/opensearch-build#4909 (comment)](https://github.com/opensearch-project/opensearch-build/issues/4909#issuecomment-2330754390))

All our lives would have been easier if the release branch cut was post code freeze. Build failing because of this version bump or jenkins hosts choking on sheer number of build requests. So, +1 for branch cut post "freeze" from next release.

**Comment by sohami** [comment]
> ❌ Gradle check result for [36b344c](https://github.com/opensearch-project/OpenSearch/commit/36b344ca0cfc9bc3000b2b2f0e5c1122f41fd7ab): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47188/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
 
It seems like it is taking wrong commit on 2.x: ?
```
> Task :distribution:bwc:minor:checkoutBwcBranch
Commit date of current: 'Wed, 4 Sep 2024 21:30:23 -0400'
Performing checkout of opensearch-project/2.x...
Checkout hash for :distribution:bwc:minor is b44242d47ee70ddc9a22932befda65ba739cd189
```

**Comment by shiv0408** [comment]
> > ❌ Gradle check result for [36b344c](https://github.com/opensearch-project/OpenSearch/commit/36b344ca0cfc9bc3000b2b2f0e5c1122f41fd7ab): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47188/)
> > Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
> 
> It seems like it is taking wrong commit on 2.x: ?
> 
> ```
> > Task :distribution:bwc:minor:checkoutBwcBranch
> Commit date of current: 'Wed, 4 Sep 2024 21:30:23 -0400'
> Performing checkout of opensearch-project/2.x...
> Checkout hash for :distribution:bwc:minor is b44242d47ee70ddc9a22932befda65ba739cd189
> ```

Happened last time also. https://github.com/opensearch-project/OpenSearch/pull/15053#issuecomment-2264113147

Seems like can't do anything apart from retrying.

**Comment by shiv0408** [comment]
Closed by mistake, Sorry.

**Comment by shiv0408** [comment]
> ❌ Gradle check result for https://github.com/opensearch-project/OpenSearch/commit/36b344ca0cfc9bc3000b2b2f0e5c1122f41fd7ab: [FAILURE](https://build.ci.opensearch.org/job/gradle-check/47206/)

Flaky: #14012 

Which is closed:

> Closing for now since it does not yet manifests in any merged code

Originally posted by @reta in https://github.com/opensearch-project/OpenSearch/issues/14012#issuecomment-2151002217

**Review by jed326 — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Looks like MacOS builds are stuck. Do you know why @reta? Not sure I understand what's going on.

**Comment by reta** [comment]
> Looks like MacOS builds are stuck. Do you know why @reta? Not sure I understand what's going on.

https://github.com/opensearch-project/OpenSearch/pull/15741

**Comment by reta** [comment]
The MacOS assemble checks should be "fixed" now: https://github.com/opensearch-project/OpenSearch/pull/15741

**Review by jed326 — APPROVED** [review]

**Pull request merged**
