### PR TITLE
Upgraded to t-digest 3.3.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@dblock.org>

### Description

The upgrade to t-digest 3.3 fixes a number of bugs in calculating percentiles. 

Looking at sample output, the old version 3.2 was interpolating data (see https://github.com/opensearch-project/OpenSearch/pull/3634#issuecomment-1162666812 for an explanation) and producing different (wrong) results, especially in the small sample size. For example, given input of [1, 51, 101, 151] the 25th, 50th and 75th percentiles changed from [26,76,126] to [51,101,151] with this upgrade. 

The tests in this PR have been adjusted to reflect the new expected percentiles, and I added both a 2.x mixed cluster test, and made all the other tests select a 3.x node to preserve a trail of this change. I also corrected the assumption that the number of centroids is `<=` that the number of data points, not `=`. 

Because results change significantly I think this is a 3.x change and should not be back-ported, but open to other considerations.

There are many changes between t-digest 3.2 and 3.3, see https://github.com/tdunning/t-digest/pull/194. 

### Issues Resolved

Closes https://github.com/opensearch-project/OpenSearch/issues/1756.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Ok, doesn't look so simple...

```
org.opensearch.search.aggregations.metrics.InternalTDigestPercentilesRanksTests > testEqualsAndHashcode FAILED
    java.lang.AssertionError: expected:<64> but was:<81>
        at __randomizedtesting.SeedInfo.seed([DF508FEF9F0E8839:AE5FF72250E9C116]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.search.aggregations.metrics.InternalTDigestPercentilesRanksTests.createTestInstance(InternalTDigestPercentilesRanksTests.java:56)
        at org.opensearch.search.aggregations.metrics.InternalTDigestPercentilesRanksTests.createTestInstance(InternalTDigestPercentilesRanksTests.java:42)
```

**Comment by dblock** [comment]
```
java.lang.AssertionError: aggregations.percentiles_int.values.25\.0 didn't match expected value:
        aggregations.percentiles_int.values.25\.0: expected Double [26.0] but was Double [51.0]
            at org.opensearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:115)
            at org.opensearch.test.rest.yaml.section.Assertion.execute(Assertion.java:89)
            at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:447)
```

**Comment by dblock** [comment]
@tdunning Would you mind assisting here a bit please?

The upgrade from 3.2 to 3.3 produces different percentiles in some scenarios given very simple data. You can see raw data in https://github.com/opensearch-project/OpenSearch/blob/37651e9b5fe914a99f0abe0a36e10bd46d958691/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/180_percentiles_tdigest_metric.yml and the diff in this PR for how those changed. The data is just 4 values: 1, 51, 101 and 151. 

I didn't expect such a big difference in a dot release. At the very least I'd like to understand whether this is expected, and whether this is going to have to be released as a major breaking change for OpenSearch users.

**Comment by tdunning** [comment]
I am not entirely clear about how to read the difference here.

I think that what you are saying is that given samples [1, 51, 101, 151]
the 25th, 50th and 75th percentiles changed from [26,76,126] to
[51,101,151].

Is that correct?

If so, this was a bug fix involved in cleaning up the behavior of the
system in small count cases. The problem is that with just four data
points, we don't need to summarize the data at all. As such, any quantiles
that involve interpolation between observed values are simply wrong.

**Comment by tdunning** [comment]
Sorry... I missed your very fine explanation.

I understand now that you were doing a regression test against previous behavior and were surprised at a change in this behavior.

The fact is, however, this old behavior was a bug. That bug was fixed.

If we look at the quantile curve for your data, we see this:

image


The circles indicate an open boundary and the filled dots indicate a closed one. Because we retain all of the data, we can't in good faith interpolate. The only question is whether the quantile at exactly 0.25 should be 1 or 51. In t-digest, I settled on the lower value. The old code was interpolating and was just wrong.


> The upgrade from 3.2 to 3.3 produces different percentiles in some scenarios given very simple data. Neither the old data nor the new data is "correct", but that is expected I imagine given that we use t-digest. You can see raw data in https://github.com/opensearch-project/OpenSearch/blob/37651e9b5fe914a99f0abe0a36e10bd46d958691/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/180_percentiles_tdigest_metric.yml and the diff in this PR for how those changed. The data is just 4 values: 1, 51, 101 and 151.
> 
> Data	Percentile	Result
> 1	1	2.5
> 51	5	8.5
> 101	25	38.5
> 151	50	76
> 75	113.5
> 95	143.5
> 99	149.5
> 100	151
> I didn't expect such a big difference in a dot release. At the very least I'd like to understand whether this is expected, and whether this is going to have to be released as a major breaking change for OpenSearch users.

**Comment by tdunning** [comment]
In case you are curious, a similar issue arises with the cdf function. There, the graph for you data looks like this:

image

Here, what I have chosen is to use the mid point when you ask for the CDF at exactly a sample point. This gets a bit fancier when there are multiple samples at just the same point. In general, I take the CDF to be the 

image

**Review by kotwanikunal — APPROVED** [review]

**Review by kartg — APPROVED** [review]
Just one question for my understanding:

> I also corrected the assumption that the number of centroids is <= that the number of data points, not =.

@dblock is this an expected change with the minor version bump? Or has the old assertion been passing serendipitously?

**Comment by tdunning** [comment]
This is an expected change if the number of data points is a significant
fraction of the compression factor. Exactly when equality fails depends on
the minor version, the scale function and a tiny bit on the data itself.

If you don't compress the digest before examining it, more samples will be
retained than the so-called public compression, but less than or equal to
the private compression. The guarantee is that when you serialize the
digest, it will respect the compression factor you set, but until then
there can be more data in memory than allowed by the factor you set.

**Comment by dblock** [comment]
> Just one question for my understanding:
> 
> > I also corrected the assumption that the number of centroids is <= that the number of data points, not =.
> 
> @dblock is this an expected change with the minor version bump? Or has the old assertion been passing serendipitously?

Thanks @tdunning for your thorough explanation, I've learned a bunch! Either way the assertion was testing an internal assumption to t-digest.

**Comment by dblock** [comment]
Does anyone think we should consider this a bug fix and backport it to 2.x (queries will start returning different, more correct results)? @kartg @kotwanikunal ?

**Comment by kartg** [comment]
I'm inclined towards backporting since any future 2.x backports that modify these files would result in conflicts (see https://github.com/opensearch-project/OpenSearch/pull/3248#issuecomment-1122871590 for another such instance)

**Comment by dblock** [comment]
@kartg I do care about users more than merge conflicts, but I hear you. Any feelings about user impact?

**Comment by kavilla** [comment]
One of the functional tests from OpenSearch Dashboards displayed the incorrect value [[link it issue]](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1821). We will update the value on `main` but keep the `2.x` branches untouched.

**Comment by sharp-pixel** [comment]
> I settled on the lower value.

Then shouldn't the result be [1, 51, 101]?

[1, 51, 101] is the result I get from Mathematica as well:

```
vec = {1, 51, 101, 151};
Quantile[vec, #] & /@ {1/4, 1/2, 3/4}
```
```
{1, 51, 101}
```

**Comment by dblock** [comment]
@tdunning ^

**Comment by kavilla** [comment]
So when updated the values for this test it seemed to get inconsistent values for the 50th, 75th, and 95th percentile for example: https://github.com/opensearch-project/OpenSearch-Dashboards/runs/7120932868?check_suite_focus=true

and 

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1822#issuecomment-1170573139

**Comment by dblock** [comment]
@kavilla Are you sure? I felt like I was getting something similar, but turned out the tests were seeded with some random value. 

In any case if you *are* sure, open a new issue?

**Comment by tdunning** [comment]
I am happy to comment on the t-digest side of things if somebody can say what the test is actually doing.

**Comment by dblock** [comment]
> > I settled on the lower value.
> 
> Then shouldn't the result be [1, 51, 101]?
> 
> [1, 51, 101] is the result I get from Mathematica as well:
> 
> ```
> vec = {1, 51, 101, 151};
> Quantile[vec, #] & /@ {1/4, 1/2, 3/4}
> ```
> 
> ```
> {1, 51, 101}
> ```

@tdunning Could you check out the above, please?

**Comment by dblock** [comment]
@kavilla Want to open an issue in t-digest re: ^ ?

**Comment by tdunning** [comment]
The problem here is that the inverse CDF (aka quantile) is not a function.

For the example you give with observations at [1, 51, 101, 151], the CDF is
well behaved and looks like this:

[image: image.png]
This does have discontinuities at each observed value, of course, and we
could adopt a variety of conventions to define the value of the CDF exactly
at each sampled value. One convention defines the CDF as segments that are
open on the left, but closed on the right. This would make the value of
CDF(1) be 0. The opposite convention has all segments closed on the left
and open on the right so CDF(1) would be 0.25. These conventions are
asymmetric, however, which can lead to surprising results if, for instance,
you negate all sampled values. I would prefer that CDF(samples, x) ==
CDF(-samples, -x) so t-digest uses the convention that the CDF is midway
between these alternative conventions so that CDF(1) = 0.125 instead of
either 0 or 0.25.

Resolving the value at these discontinuities does not solve the problem you
are talking about. As you can see, the value of the CDF is constant for all
values in the open interval (51, 101). This means that there is no unique
value for the inverse CDF at 0.5. Any value in (51, 101) could be used.
Mathematic uses 51. Julia and R use 76. T-digest uses 101.

**Comment by dblock** [comment]
@tdunning The images didn't make it to GitHub, if you care to edit, but thanks for your explanation!

**Comment by sharp-pixel** [comment]
From https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile and https://mathworld.wolfram.com/Quantile.html, we could choose between 9 standardized definitions.

To make sure we are comparing the same things - especially in unit tests - we probably should decide on a default one, and optionally enable the choice of the others types.

Mathematica uses type 1 by default, R uses type 7 by default, but both provide the option to choose.

**Comment by tdunning** [comment]
> @tdunning The images didn't make it to GitHub, if you care to edit, but thanks for your explanation!

Sorry about that. The image is very similar to what I posted in an earlier comment. I have edited my reply but in editing the response, I had difficulty getting the image to show up.

image

**Comment by tdunning** [comment]
So I have been experimenting a fair bit with the Julia implementation (easier than playing with the Java version because interactive).

I have changed the problem in question a tiny bit to make it more clear what is happening. I am using points at `[1,11,15,30]`. 

My first experiment was to verify that the `cdf` function performs as expected. It does. In particular, the `cdf` at exactly the sample points shows the desired interpolation behavior. Here is a picture produced by scanning x in small increments to get the blue line and then plotting points at exactly the sample points:

image

The point of real interest, however, was to determine how the `quantile` function behaves. The following plot shows that the `quantile` (wider blue line) and `cdf` (thin gray line) functions lay right on top of each other. Further, evaluating `quantile` just before and just after `q=[0.25,0.5,0.75]` (green and purple dots) we see the desired boundary behavior.

image

I would contend that it is hard to do better than this due to inevitable floating point limits.

@dblock , @kavilla , @sharp-pixel what do you think?

Also, I looked into the R and Julia implementations of the quantile function. In fact, they are trying to estimate the theoretical distribution rather than the empirical inverse cdf. This is a different problem entirely. Adding the Julia `quantile` to the graph shows what I mean

image

The result is far from the empirical inverse cdf function.

**Comment by sharp-pixel** [comment]
Thanks @tdunning.

It seems Julia uses type 7 (from https://docs.julialang.org/en/v1/stdlib/Statistics/), so we just need to pick one quantile function type as the default, document it, and optionally have the choice to override the type.

**Comment by dblock** [comment]
I opened https://github.com/opensearch-project/OpenSearch/issues/5115 to discuss the user-facing aspects of this. Because there's no one correct result at the edges, I think we could support multiple strategies to everybody's satisfaction.

**Pull request merged**
