### PR TITLE
[Backport 2.x] Update AggregatorFactory to provide a method to indicate if it supports concurrent search

### PR DESCRIPTION
**Pull request by jed326**
### Description
Backport PR for #9469

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jed326** [comment]
@sohami @reta Here is the backport for #9469. Thanks!

**Comment by kotwanikunal** [comment]
@jed326 DCO is failing. Can you please fix it?

**Comment by jed326** [comment]
@kotwanikunal I'm trying to figure out why it's failing...the commit is signed off but the [details](https://github.com/opensearch-project/OpenSearch/pull/9550/checks?check_run_id=16215878025) for the DCO say there are 70 commits with problems

**Review by reta — APPROVED** [review]

**Review by sohami — APPROVED** [review]

**Comment by jed326** [comment]
@reta @sohami could you help merge in this PR? A changelog conflict came up and I just resolved it.

**Comment by reta** [comment]
> @reta @sohami could you help merge in this PR? A changelog conflict came up and I just resolved it.

Sure, once checks are done, should be good to go

**Pull request merged**
